### ISSUE TITLE
ActionBar behind StatusBar

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/NativeScript#2669] opened 2016-09-02 13:53 UTC
On Android my ActionBar seems to be either behind the status bar or has no top padding. I'm not sure which.

![screenshot_2016-09-02-14-43-24](https://cloud.githubusercontent.com/assets/1102402/18205818/fb0959b4-711b-11e6-9bed-be42ea688f00.jpg)

This is the template for the page:

```
<Page> 
    <Page.actionBar>
      <ActionBar title="History" />
    </Page.actionBar>
    <TabView>
        <TabView.items>
            <TabViewItem title="Journey" xmlns:JourneyTab="pages/tabView/journeyTab">
            <TabViewItem.view>
                <JourneyTab:journeyTab />
            </TabViewItem.view>
            </TabViewItem>
            <TabViewItem title="History" xmlns:HistoryTab="pages/tabView/historyTab">
            <TabViewItem.view>
                <HistoryTab:historyTab />
            </TabViewItem.view>
            </TabViewItem>
        </TabView.items>
    </TabView>
</Page>
```

I'm experiencing this on every page. They all contain similar code. There is no CSS related to the ActionBar.

This is my first time using NativeScript so please excuse my ignorance. This is also a project that I didn't build myself from scratch.

I can't seem to find anything in the project related to the actionbar or status bar and the internet hasn't thrown up any similar reports.

Any idea what could be causing this?

And also, how do I remove the shadow behind the status bar?

│ Component           │ Current version │ Latest version │ Information │
│ nativescript           │ 2.2.1                   │ 2.2.1                │ Up to date  │
│ tns-core-modules │ 2.2.1                  │ 2.2.1                 │ Up to date  │
│ tns-android            │ 2.2.0                 │ 2.2.0                 │ Up to date  │
│ tns-ios                    │ 2.2.1                  │ 2.2.1                 │ Up to date  │

**Comment by tsonevn** [comment] 2016-09-02 14:51
Hi @3rror404,
I was unable to reproduce such an issue. Could you verify , if there are some global style set for the ActionBar in `app.css` file. It will also help if you could give us some more info about the problem or to send us sample project where this issue has been reproduced. 
About your second question you could use [nativescript-statusbar](https://www.npmjs.com/package/nativescript-statusbar) plugin to style the StatusBar.

**Comment by jiwonyune** [comment] 2016-09-02 17:18
I have the same problem. It would be nice if this problem could be fixed.

**Comment by kazemihabib** [comment] 2016-09-03 08:20
It seems that your status bar is transparent you can disable it by removing 
 open APP_Resources/values/styles.xml and remove 
`<item name="android:windowTranslucentStatus">true</item>`
from 
`<style name="AppThemeBase" parent="Theme.AppCompat.Light.NoActionBar"> </style> `
section.

but if you want to keep this transparent and fix your problem: 
```
  private getStatusBarHeight() {
      let result:number = 0;
      let resourceId:number = application.android.context.getResources().getIdentifier("status_bar_height", "dimen", "android");
      if (resourceId > 0) {

          result = application.android.context.getResources().getDimensionPixelSize(resourceId);
      }
      return result;
    } 

     this.statusBarHeight= this.getStatusBarHeight(); 
``` 
and  then you can set marginTop or paddingTop:
```
 <ActionBar   [style.marginTop]="statusBarHeight" ></ActionBar> 
```

**Comment by 3rror404** [comment] 2016-09-05 09:25
@kazemihabib Thank you. My `styles.xml` had the following:

```
<!-- theme to use FOR launch screen-->
<style name="LaunchScreenThemeBase" parent="Theme.AppCompat.Light.NoActionBar">

    ...

    <item name="android:windowTranslucentStatus">true</item>

</style>
```

Removing the `android:windowTranslucentStatus` key fixed it for the entire app.

**Comment by PanayotCankov** [comment] 2016-09-12 09:20
If the translucency causes problems, we should consider removing it from the launch screen for good.
This is provided by the template-hello-world.

**Comment by PanayotCankov** [comment] 2016-09-12 09:41
Also we should investigate if there is a problem with the code that restores the original theme.

**Comment by nmongiya** [comment] 2017-10-17 03:16
I don't have `<item name="android:windowTranslucentStatus">true</item>` in my styles.xml but if I lock the screen and wakes it back, it is messed up. I mean after unlocking the screen 'Action Bar' is going behind the status bar.

**Comment by NickIliev** [comment] 2018-12-11 09:12
Closing as the issue does not seem to be reproducible with NativeScript 5.1

**Closed by NickIliev** 2018-12-11 09:12 UTC
Labels: os: android
