### ISSUE TITLE
Repeater.itemTemplate cannot use XML elements from plugins

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#2721] opened 2016-09-14 15:52 UTC
**Platform:** iOS
**TNS:** 2.2.1

Trying to make a Repeater using JS (this is needed), but I cannot use any external plugins that I normally can when writing the Repeater from the XML. I'm trying to use [nativescript-web-image-cache](https://github.com/VideoSpike/nativescript-web-image-cache) inside the itemTemplate. See scenario below:

**XML**

``` xml
<Page navigatedTo="navigatedTo" xmlns:IC="nativescript-web-image-cache">
  <StackLayout id="container" />
</Page>
```

**JS**

``` js
var Repeater = require("ui/repeater").Repeater;
var StackLayout = require("ui/layouts/stack-layout").StackLayout;
var ObservableArray = require("data/observable-array").ObservableArray;

var items = new ObservableArray(
  "http://example.com/image1.png",
  "http://example.com/image2.png",
  "http://example.com/image3.png"
);

var page, pageData = new Observable({
  items: items
});

exports.navigatedTo = function(args) {
  page = args.object;
  page.bindingContext = pageData;

  var itemsLayout = new StackLayout();
  itemsLayout.orientation = "horizontal";

  var repeater = new Repeater();
  repeater.items = items;
  repeater.itemsLayout = itemsLayout;
  repeater.itemTemplate = '<IC:WebImage src="{{ $value }}" />';
};
```

The error I get:

```
file:///app/tns_modules/ui/builder/builder.js:162:56: JS ERROR Error: Parsing XML at 1:13
     ↳Module 'ui/web-image' not found for element 'WebImage'.
       ↳Could not find module 'ui/web-image'. Computed path ...
```

It works (of course) when doing it through XML only:

``` xml
<Page navigatedTo="navigatedTo" xmlns:IC="nativescript-web-image-cache">
  <StackLayout id="container">
    <Repeater items="{{ items }}">
      <Repeater.itemsLayout>
        <StackLayout orientation="horizontal" />
      </Repeater.itemsLayout>
      <Repeater.itemTemplate>
        <IC:WebImage src="{{ $value }}" />
      </Repeater.itemTemplate>
    </Repeater>
  </StackLayout>
</Page>
```

**Comment by tsonevn** [comment] 2016-09-15 07:03
Hi @NordlingArt,
Thank you for reporting this issue.

I tested the given scenario and confirm that at the moment it is not possible to create `Repeater` while using javascript and  `itemTemplate` to be created from view from external  NativeScrtipt plugin.

Regards,
@tsonevn

**Comment by NordlingArt** [comment] 2016-09-15 13:17
@tsonevn - Thanks for confirming!

**Comment by hamorphis** [comment] 2016-10-31 14:53
By the way, the `itemTemplate` property is of type `itemTemplate: string | view.Template;`, which means that it accepts a `view.Template` as well. `view.Template` is defined as:
```
    interface Template {
        /**
         * Call signature of the factory function.
         * Returns a new View instance.
         */
        (): View;
    }
```
which is a function that returns an instance of a view. So if you can instantiate your custom component from code-behind, you could do something like this:

```
repeater.itemTemplate = function(){
   let myCustomComponent = new MyComponent();
   //...
   return myCustomComponent;
}

**Comment by NordlingArt** [comment] 2016-10-31 16:48
@hamorphis - That's something to look into yes, had no idea about that. Thanks!

**Comment by hamorphis** [comment] 2016-11-01 09:27
The problem is that when you assign the item template as a string from code-behind, no one knows what the 'IC' stands for and this partial XML cannot be parsed.

**Comment by hamorphis** [comment] 2016-11-01 09:33
@NordlingArt If you still want to assign the item template as a string, you will need to add the namespace somewhere inside it like this:
```
<IC:WebImage xmlns:IC="nativescript-web-image-cache" src="{{ $value }}"/>
```

**Comment by hamorphis** [comment] 2016-11-01 09:34
@NordlingArt Let me know if this fixes the issue for you so we can close this issue.

**Comment by NordlingArt** [comment] 2016-11-01 10:23
@hamorphis - I worked around this issue a while ago, so I have no use for it as of now. You can close the issue. But thanks a lot for clarifying!

**Closed** 2016-11-01 10:23 UTC
Labels: Android, iOS, T:Bug

**Comment by hamorphis** [comment] 2016-11-01 12:15
Try either this: 

```
repeater.itemTemplate = '<IC:WebImage xmlns:IC="nativescript-web-image-cache" src="{{ $value }}" />';
```

or this: 

```
    repeater.itemTemplate = function () {
        var webImage = new imageCache.WebImage();
        webImage.bind({
            targetProperty: "src",
            sourceProperty: "$value"
        });
        return webImage;
    };
```

**Comment by sushant-j** [comment] 2017-12-12 13:41
Thank you for this thread!
Was trying to get nativescript-cardview to get inside a repeater and it was throwing errors.
This helped me :)
