### ISSUE TITLE
Android native method is not callable on a singleton

### ISSUE THREAD

**Issue by NCenerar** [NativeScript/NativeScript#9771] opened 2022-02-13 22:06 UTC
### Issue Description

When running my project, I get an `JS: [Vue warn]: Error in mounted hook: "TypeError: theProblem.isOk is not a function"` but it exists.
The problem seems to occur because the underlying native code uses a singleton pattern.

`PublicInterface` is a public interface providing a method to get the singleton and defining a public method `boolean isOk()`.
The `get()`method calls a static method in `PublicClass` that implements the singleton pattern with an inner private class.
This inner private class implements the `PublicInterface`.
The resulted object seems to be good but calling the method `boolean isOk()` gives an error.

# Quick setup
Clone my example project:
```
git clone git@github.com:NCenerar/nativescript-issue-01.git
```

Enter the project and run it on android:
```
tns debug android
```

# The bug

When the code reach a method call on an android object `mypackage.PublicInterface.get().isOk()`, you will get a runtime error:

```
The build result is located at: xxx/platforms/android/app/build/outputs/apk/debug/app-debug.apk
Installing on device XXXX...
Successfully installed on device with identifier 'XXXX'.
Restarting application on device XXXX...
JS: {NSVue (Vue: 2.6.12 | NSVue: 2.9.0)} -> CreateElement(Frame)
JS: {NSVue (Vue: 2.6.12 | NSVue: 2.9.0)} -> CreateElement(Page)
JS: {NSVue (Vue: 2.6.12 | NSVue: 2.9.0)} -> CreateElement(ActionBar)
JS: {NSVue (Vue: 2.6.12 | NSVue: 2.9.0)} -> CreateElement(label)
JS: {NSVue (Vue: 2.6.12 | NSVue: 2.9.0)} -> AppendChild(ActionBar(4), Label(5))
JS: {NSVue (Vue: 2.6.12 | NSVue: 2.9.0)} -> AppendChild(Page(3), ActionBar(4))
JS: {NSVue (Vue: 2.6.12 | NSVue: 2.9.0)} -> CreateElement(gridlayout)
JS: {NSVue (Vue: 2.6.12 | NSVue: 2.9.0)} -> CreateElement(label)
JS: {NSVue (Vue: 2.6.12 | NSVue: 2.9.0)} -> CreateElement(formattedstring)
JS: {NSVue (Vue: 2.6.12 | NSVue: 2.9.0)} -> CreateElement(span)
JS: {NSVue (Vue: 2.6.12 | NSVue: 2.9.0)} -> AppendChild(, Span(9))
JS: {NSVue (Vue: 2.6.12 | NSVue: 2.9.0)} -> CreateElement(span)
JS: {NSVue (Vue: 2.6.12 | NSVue: 2.9.0)} -> AppendChild( , Span(10))
JS: {NSVue (Vue: 2.6.12 | NSVue: 2.9.0)} -> AppendChild(Label(7),  Blank {N}-Vue app)
JS: {NSVue (Vue: 2.6.12 | NSVue: 2.9.0)} -> AppendChild(GridLayout(6), Label(7))
JS: {NSVue (Vue: 2.6.12 | NSVue: 2.9.0)} -> AppendChild(Page(3), GridLayout(6))
JS: {NSVue (Vue: 2.6.12 | NSVue: 2.9.0)} -> AppendChild(Frame(2), Page(3))
JS: Before bug:
JS:   theProblem seems good                     : mypackage.PublicClass$PrivateInnerClass@12abed3
JS:   theProblem.isOk is undefined but shouldn't: undefined
JS: And this is obviously giving an error:
JS: [Vue warn]: Error in mounted hook: "TypeError: theProblem.isOk is not a function"
JS: 
JS: found in
JS: 
JS: ---> <Home> at app/components/Home.vue
JS:        <Frame>
JS:          <Root>
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{org.nativescript.issuenativeandroid/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: TypeError: theProblem.isOk is not a function
System.err: 
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.issuenativeandroid/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: TypeError: theProblem.isOk is not a function
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3271)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
System.err:     at android.os.Looper.loop(Looper.java:214)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7397)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: TypeError: theProblem.isOk is not a function
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:29)
System.err:     at android.app.Activity.performCreate(Activity.java:7802)
System.err:     at android.app.Activity.performCreate(Activity.java:7791)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1300)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
System.err:     ... 11 more
Unable to apply changes on device: XXXX. Error is: The application org.nativescript.issuenativeandroid does not appear to be running on XXXX or is not built with debugging enabled. Try starting the application manually..
```

# Long setup

Initialize the project:
```
tns create issue-native-android --vue --ts
cd issue-native-android
```

Create a java interface `./App_Resources/Android/src/main/java/mypackage/PublicInterface.java`:
```java
package mypackage;

public interface PublicInterface {
    public static PublicInterface get() {
        return PublicClass.get();
    }
    public boolean isOk();
}
```

Update the types `./types/references.d.ts`:
```typescript
/// <reference path="../node_modules/@nativescript/types/index.d.ts" />

declare namespace mypackage {
    export class PublicInterface {
        public static get(): mypackage.PublicInterface;
        public isOk(): boolean;
    }
}
```

Create a java class implementing the interface with a singleton pattern based on a private inner class `App_Resources/Android/src/main/java/mypackage/PublicClass.java`:
```java
package mypackage;

public final class PublicClass {
    private static class PrivateInnerClass implements PublicInterface {
        @Override
        public boolean isOk() {
            return true;
        }
    }

    private static PrivateInnerClass singleton;
    public static PrivateInnerClass get() {
        if (PublicClass.singleton == null ) {
            PublicClass.singleton = new PrivateInnerClass();
        }
        return PublicClass.singleton;
    }
}
```

Update the main Component and add a mounted function `./app/Components/Home.vue`:
```typescript
    mounted() {
      const theProblem = mypackage.PublicInterface.get();
      console.log("Before bug:");
      console.log("  theProblem seems good                     :", theProblem);
      console.log("  theProblem.isOk is undefined but shouldn't:", theProblem.isOk);
      console.log("And this is obviously giving an error:");
      console.log("  theProblem.isOk()                         :", theProblem.isOk());
    }
```

Run on android:
```
tns debug android
```

### Reproduction

https://github.com/NCenerar/nativescript-issue-01

1. `git clone https://github.com/NCenerar/nativescript-issue-01`
2. `cd nativescript-issue-01`
3. `tns debug android`

See the error in the file `Home.vue` on the line `L33`

### Relevant log output (if applicable)

```shell
JS: [Vue warn]: Error in mounted hook: "TypeError: theProblem.isOk is not a function"
JS: 
JS: found in
JS: 
JS: ---> <Home> at app/components/Home.vue
JS:        <Frame>
JS:          <Root>
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{org.nativescript.issuenativeandroid/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: TypeError: theProblem.isOk is not a function
System.err: 
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.issuenativeandroid/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: TypeError: theProblem.isOk is not a function
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3271)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
System.err:     at android.os.Looper.loop(Looper.java:214)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7397)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: TypeError: theProblem.isOk is not a function
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:29)
System.err:     at android.app.Activity.performCreate(Activity.java:7802)
System.err:     at android.app.Activity.performCreate(Activity.java:7791)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1300)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
System.err:     ... 11 more
```

### Environment

```yaml
OS: macOS 12.2
CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
Shell: /bin/zsh
node: 17.3.1
npm: 8.3.0
nativescript: 8.1.5

# android
java: 11.0.11
ndk: 22.1.7171670
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 13.2.1/13C100
cocoapods: 1.11.2
python: 2.7.18
python3: 3.8.9
ruby: 2.7.5
platforms: 
  - DriverKit 21.2
  - iOS 15.2
  - macOS 12.1
  - tvOS 15.2
  - watchOS 8.3
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "~8.1.1",
  "@nativescript/theme": "~3.0.1",
  "nativescript-vue": "~2.9.0"
},
"devDependencies": {
  "@nativescript/android": "8.1.1",
  "@nativescript/types": "~8.1.1",
  "@nativescript/webpack": "~5.0.0",
  "@types/node": "~14.6.2",
  "nativescript-vue-template-compiler": "~2.9.0",
  "typescript": "~4.3.5",
  "vue": "~2.6.12"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by triniwiz** [comment] 2022-02-13 22:24
If you extended the class as `PublicClass` should you not access it using the same class  instead of PublicInterface which just an interface?

**Comment by NCenerar** [comment] 2022-02-13 22:54
In my actual case, the java code comes from an external librarie so I can't change it and it is far more complex. There are multiple implementations of the interface and it conditionnaly choose the implementation to use.
I must access the instance from the `PublicInterface`.

Event if I "could" (in this particular example), it should be working the way I wrote it.
I can't figure what is wrong and why I get the `JS: [Vue warn]: Error in mounted hook: "TypeError: theProblem.isOk is not a function"`

I really think it is a bug from NativeScript 😢

**Comment by triniwiz** [comment] 2022-02-13 23:52
You can try console.dir(PublicInterface) it should list what’s available 


Sent from Yahoo Mail for iPhone


On Sunday, February 13, 2022, 6:54 PM, Nicolas Cenerario ***@***.***> wrote:




In my actual case, the java code comes from an external librarie so I can't change it and it is far more complex. There are multiple implementations of the interface and it conditionnaly choose the implementation to use.
I must access the instance from the PublicInterface.

Event if I "could" (in this particular example), it should be working the way I wrote it.
I can't figure what is wrong and why I get the JS: [Vue warn]: Error in mounted hook: "TypeError: theProblem.isOk is not a function"

I really think it is a bug from NativeScript 😢

**Comment by NCenerar** [comment] 2022-02-14 07:09
`console.dir` does not provide any interesting informations. I could not get it to provide anything for any object / classes, even the working ones.

I did some testing with a even simpler example:

`App_Resources/Android/src/main/java/mypackage/PublicClass.java`
```java
package mypackage;

import android.util.Log;

class PackageProtectedClass implements Runnable {
    @Override
    public void run() {
        Log.d("JS", String.format("Run:  I am %s %s", this.getClass(), this));
    }
}

public class PublicClass {
    public PackageProtectedClass getIt() {
        return new PackageProtectedClass();
    }
}
```

`./types/references.d.ts`
```typescript
/// <reference path="../node_modules/@nativescript/types/index.d.ts" />

declare namespace mypackage {
    export class PackageProtectedClass extends java.lang.Object implements java.lang.Runnable {
        public constructor(): PackageProtectedClass;
        public run(): void;
    }
    export class PublicClass extends java.lang.Object {
        public constructor(): PublicClass;
        public getIt(): mypackage.PackageProtectedClass;
    }
}
```

Script part of `./app/Components/Home.vue`
```typescript
  import Vue from "nativescript-vue";

  function logObject(name: string, obj: any, indent: number = 0) {
      const prefix = ''.padStart(indent, ' ');
      const proto = Object.getPrototypeOf(obj);
      if (name) console.log(prefix, name, obj);
      console.log(prefix, " >", Object.entries(obj));
      console.log(prefix, " >", Object.getOwnPropertyNames(obj));
      if (obj && proto && obj !== Object.prototype) {
        logObject('', proto, indent + 2);
      }
  }

  export default Vue.extend({
    computed: {
      message() {
        return "Blank {N}-Vue app";
      }
    },
    mounted() {
      logObject("mypackage", mypackage);
      logObject("PublicClass", mypackage.PublicClass);
      logObject("PackageProtectedClass", mypackage.PackageProtectedClass);
      const theFactory = new mypackage.PublicClass();
      const theProblem = theFactory.getIt();
      logObject("theFactory", theFactory);
      logObject("theProblem", theProblem);
      console.log("theProblem.run :", theProblem.run);
      const theClass = theProblem.getClass();
      const theInterfaces = theClass.getInterfaces();
      const theDeclaredMethods = theClass.getDeclaredMethods()
      console.log("theProblem.getClass() :", theClass);
      console.log("theClass.getInterfaces() :", theInterfaces);
      for (let i=0; i<theInterfaces.length; i++) {
        console.log(" > ", i, theInterfaces[i]);
      }
      console.log("theClass.getDeclaredMethods() :", theDeclaredMethods);
      for (let i=0; i<theDeclaredMethods.length; i++) {
        console.log(" > ", i, theDeclaredMethods[i]);
      }
      try {
        theProblem.run();
      } catch (e) {
        console.error(e, (e as Error).stack);
      }
    }
  });
```

The output is interesting:
```log
JS:  mypackage {}
JS:   > [[PublicClass, function () { [native code] }], [PackageProtectedClass, function () { [native code] }]]
JS:   > [PublicClass, PackageProtectedClass]
JS:     > []
JS:     > [constructor, __defineGetter__, __defineSetter__, hasOwnProperty, __lookupGetter__, __lookupSetter__, isPrototypeOf, propertyIsEnumerable, toString, valueOf, __proto__, toLocaleString]
JS:  PublicClass function () { [native code] }
JS:   > [[extend, function () { [native code] }], [null, function () { [native code] }], [class, class mypackage.PublicClass]]
JS:   > [length, name, arguments, caller, prototype, extend, null, class, valueOf]
JS:     > [[extend, function () { [native code] }], [null, function () { [native code] }], [class, class java.lang.Object]]
JS:     > [length, name, arguments, caller, prototype, extend, null, class, valueOf]
JS:       > []
JS:       > [length, name, arguments, caller, constructor, apply, bind, call, toString]
JS:         > []
JS:         > [constructor, __defineGetter__, __defineSetter__, hasOwnProperty, __lookupGetter__, __lookupSetter__, isPrototypeOf, propertyIsEnumerable, toString, valueOf, __proto__, toLocaleString]
JS:  PackageProtectedClass function () { [native code] }
JS:   > [[extend, function () { [native code] }], [null, function () { [native code] }], [class, class mypackage.PackageProtectedClass]]
JS:   > [length, name, arguments, caller, prototype, extend, null, class, valueOf]
JS:     > [[extend, function () { [native code] }], [null, function () { [native code] }], [class, class java.lang.Object], [valueOf, function () { [native code] }]]
JS:     > [length, name, arguments, caller, prototype, extend, null, class, valueOf]
JS:       > []
JS:       > [length, name, arguments, caller, constructor, apply, bind, call, toString]
JS:         > []
JS:         > [constructor, __defineGetter__, __defineSetter__, hasOwnProperty, __lookupGetter__, __lookupSetter__, isPrototypeOf, propertyIsEnumerable, toString, valueOf, __proto__, toLocaleString]
JS:  theFactory mypackage.PublicClass@b67070e
JS:   > []
JS:   > []
JS:     > [[<init>, function <init>() { [native code] }], [getIt, function getIt() { [native code] }]]
JS:     > [<init>, getIt, constructor]
JS:       > [[<init>, function <init>() { [native code] }], [clone, function clone() { [native code] }], [equals, function equals() { [native code] }], [finalize, function finalize() { [native code] }], [getClass, function getClass() { [native code] }], [hashCode, function hashCode() { [native code] }], [notify, function notify() { [native code] }], [notifyAll, function notifyAll() { [native code] }], [toString, function toString() { [native code] }], [wait, function wait() { [native code] }]]
JS:       > [<init>, clone, equals, finalize, getClass, hashCode, notify, notifyAll, toString, wait, constructor]
JS:         > []
JS:         > [constructor, __defineGetter__, __defineSetter__, hasOwnProperty, __lookupGetter__, __lookupSetter__, isPrototypeOf, propertyIsEnumerable, toString, valueOf, __proto__, toLocaleString]
JS:  theProblem mypackage.PackageProtectedClass@1d8752f
JS:   > [[constructor, function () { [native code] }]]
JS:   > [constructor]
JS:     > []
JS:     > [constructor]
JS:       > [[<init>, function <init>() { [native code] }], [clone, function clone() { [native code] }], [equals, function equals() { [native code] }], [finalize, function finalize() { [native code] }], [getClass, function getClass() { [native code] }], [hashCode, function hashCode() { [native code] }], [notify, function notify() { [native code] }], [notifyAll, function notifyAll() { [native code] }], [toString, function toString() { [native code] }], [wait, function wait() { [native code] }]]
JS:       > [<init>, clone, equals, finalize, getClass, hashCode, notify, notifyAll, toString, wait, constructor]
JS:         > []
JS:         > [constructor, __defineGetter__, __defineSetter__, hasOwnProperty, __lookupGetter__, __lookupSetter__, isPrototypeOf, propertyIsEnumerable, toString, valueOf, __proto__, toLocaleString]
JS: theProblem.run : undefined
JS: theProblem.getClass() : class mypackage.PackageProtectedClass
JS: theClass.getInterfaces() : [Ljava.lang.Class;@e38673c
JS:  >  0 interface java.lang.Runnable
JS: theClass.getDeclaredMethods() : [Ljava.lang.reflect.Method;@1e06cc5
JS:  >  0 public void mypackage.PackageProtectedClass.run()
JS: TypeError: theProblem.run is not a function TypeError: theProblem.run is not a function
JS:     at VueComponent.mounted (file: app/webpack:/issue-native-android/app/components/Home.vue?3a7c:60:17)
JS:     at invokeWithErrorHandling (file: app/webpack:/issue-native-android/node_modules/nativescript-vue/dist/index.js:1862:0)
JS:     at callHook$1 (file: app/webpack:/issue-native-android/node_modules/nativescript-vue/dist/index.js:5097:0)
JS:     at Object.insert (file: app/webpack:/issue-native-android/node_modules/nativescript-vue/dist/index.js:4019:0)
JS:     at invokeInsertHook (file: app/webpack:/issue-native-android/node_modules/nativescript-vue/dist/index.js:5680:0)
JS:     at Vue.patch [as __patch__] (file: app/webpack:/issue-native-android/node_modules/nativescript-vue/dist/index.js:5899:0)
JS:     at Vue._update (file: app/webpack:/issue-native-android/node_modules/nativescript-vue/dist/index.js:4823:0)
JS:     at Vue.updateComponent (file: app/webpack:/issue-native-android/node_modules/nativescript-vue/dist/index.js:4944:0)
JS:     at Watcher.get (file:///data/data/org.nativescript.issuen...
```

What bother me is the difference between the working object `theFactory` and the non working object `theProblem`:
```
JS:  theFactory mypackage.PublicClass@b67070e
JS:   > []
JS:   > []
JS:     > [[<init>, function <init>() { [native code] }], [getIt, function getIt() { [native code] }]]
JS:     > [<init>, getIt, constructor]

JS:  theProblem mypackage.PackageProtectedClass@1d8752f
JS:   > [[constructor, function () { [native code] }]]
JS:   > [constructor]
JS:     > []
JS:     > [constructor]
```

Each of them seems to have a correct reference but `theProblem` does not seems to be correctly binded.

It is a very simple factory pattern and I wonder how NativeScript is supposed to handle object instance coming from a native librarie.

I'm probably missing something. Is there something that I'm supposed to provide?

**Comment by farfromrefug** [comment] 2022-02-14 07:27
@NCenerar it might be because `PackageProtectedClass` is private and thus the sbg does not "read" it and thus cant know about the run method. does it work if you make it public ?

**Comment by NCenerar** [comment] 2022-02-14 08:28
@farfromrefug It works if I use a public class but this is the responsibility (or choice) of the underlying library. Java allows to return an instance of a private class and use it as its publicly available interfaces. NativeScript should be able to detect such interfaces.
Another "fix" is to make `getIt()` returns a `Runnable` instead of a `PackageProtectedClass ` but again, it is not a valid fix because it would mean that NativeScript is forbidding valid native code. Since the code comes from an external library (which is working), I have to comply with it.

**Comment by farfromrefug** [comment] 2022-02-14 09:05
@NCenerar i understand your point. I am almost sure the issue lies in the sbg. We can try it! did you generate typings for your lib using  https://github.com/NativeScript/android-dts-generator ? 
If not can you try. What i want is to see if the generated typings contain the private Impl class.

**Comment by NCenerar** [comment] 2022-02-14 13:00
@farfromrefug 

```typescript
/// <reference path="android-declarations.d.ts"/>

declare module com {
	export module activelook {
		export module mylibrary {
			export class BuildConfig {
				public static class: java.lang.Class<com.activelook.mylibrary.BuildConfig>;
				public static DEBUG: boolean;
				public static LIBRARY_PACKAGE_NAME: string;
				public static BUILD_TYPE: string;
				public constructor();
			}
		}
	}
}

declare module mypackage {
	export class PackageProtectedClass {
		public static class: java.lang.Class<mypackage.PackageProtectedClass>;
		public run(): void;
	}
}

declare module mypackage {
	export class PublicClass {
		public static class: java.lang.Class<mypackage.PublicClass>;
		public constructor();
		public getIt(): mypackage.PackageProtectedClass;
	}
}

//Generics information:


```

I don't really know how to interpret it. There is no reference to the `implements Runnable` part.

**Comment by farfromrefug** [comment] 2022-02-14 13:54
@NCenerar what you see is what you can use. If it does not appear you wont be able to use it from JS.
If you expect more to be seen you need to create an issue in the android runtime repo. There you need to share a `jar` showing the issue so that we can reproduce and see why the methods are not "seen"

**Comment by NCenerar** [comment] 2022-02-14 15:00
@farfromrefug Well, the method `public run(): void` is indeed in the `PackageProtectedClass` declaration and this is the method triggering the error so, in a sense, I can't use what I see. 🤔

**Comment by farfromrefug** [comment] 2022-02-14 15:01
@NCenerar ok i wasnt sure as you talked about `isOK` in the beginning. Can you please create an issue in the android runtime and share your example?

**Comment by NCenerar** [comment] 2022-02-15 10:48
@farfromrefug Issue created ✔️

**Comment by rigor789** [comment] 2022-03-06 14:07
Closing in favor of the issue in the runtime (https://github.com/NativeScript/android-runtime/issues/1698)

**Closed by rigor789** 2022-03-06 14:07 UTC
