### ISSUE TITLE
Error: nullinjectorerror no provider for baseurl 

### ISSUE THREAD

**Issue by sabrineayadi** [NativeScript/NativeScript#7720] opened 2019-08-22 20:14 UTC
### Any help please 
![aa](https://user-images.githubusercontent.com/44321003/63546260-ad19f000-c529-11e9-8437-62d845a59c53.PNG)
**My package.json**
{
  "nativescript": {
    "id": "org.nativescript.conFusion",
    "tns-ios": {
      "version": "6.0.1"
    },
    "tns-android": {
      "version": "6.0.1"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~8.0.0",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/http": "~8.0.0-beta.10",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "@nebular/security": "^4.2.0",
    "angular-local-storage": "^0.7.1",
    "nativescript-angular": "~8.0.0",
    "nativescript-localstorage": "^2.0.1",
    "nativescript-theme-core": "~1.0.6",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.5.0",
    "rxjs-compat": "^6.5.2",
    "tns-core-modules": "~6.0.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.0.0",
    "@ngtools/webpack": "~8.0.0",
    "nativescript-dev-webpack": "~1.0.0",
    "typescript": "~3.4.0"
  },
  "gitHead": "f28dbc60d74dd2cef4b645afd8fdd63bbb12c73e",
  "readme": "NativeScript Application"
}

**Comment by NickIliev** [comment] 2019-08-23 11:18
@sabrineayadi the issue is most likely related to an issue with the code within some of your Angular components. - for example, check your HTTP providers. 

Still, there is not enough information to be able to investigate further. Consider providing a sample Playground or demo app that are reproducing this one.

**Comment by sabrineayadi** [comment] 2019-08-24 17:54
@NickIliev  this my code
**app.module.ts** 


Any help please 

My package.json

{
  "nativescript": {
    "id": "org.nativescript.conFusion",
    "tns-ios": {
      "version": "6.0.1"
    },
    "tns-android": {
      "version": "6.0.1"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN ",
  "repository": "",
  "dependencies": {
    "@angular/animations": "~8.0.0",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/http": "~8.0.0-beta.10",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "@nebular/security": "^4.2.0",
    "angular-local-storage": "^0.7.1",
    "nativescript-angular": "~8.0.0",
    "nativescript-localstorage": "^2.0.1",
    "nativescript-theme-core": "~1.0.6",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.5.0",
    "rxjs-compat": "^6.5.2",
    "tns-core-modules": "~6.0.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.0.0",
    "@ngtools/webpack": "~8.0.0",
    "nativescript-dev-webpack": "~1.0.0",
    "typescript": "~3.4.0"
  },
  "gitHead": "f28dbc60d74dd2cef4b645afd8fdd63bbb12c73e",
  "readme": "NativeScript Application"
}
app.module.ts import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";

import { NativeScriptModule } from "nativescript-angular/nativescript.module";

import { NativeScriptHttpModule } from "nativescript-angular/http";

import { HttpClientModule} from "@angular/common/http";

import { AppRoutingModule } from "./app-routing.module";

import { AppComponent } from "./app.component";

import { MenuComponent } from "./menu/menu.component";

import { DishService } from "./services/dish.service";

import { ProcessHTTPMsgService } from "./services/process-httpmsg.service";

//import { LocalStorageService } from "nativescript-localstorage";

import { InjectionToken } from '@angular/core';

import {baseURL} from './shared/baseurl';

import { from } from "rxjs";

import { NativeScriptHttpClientModule } from "nativescript-angular/http-client";

@NgModule({ bootstrap: [

    AppComponent

],


imports: [

    HttpClientModule,

    NativeScriptModule,

    AppRoutingModule,

    NativeScriptHttpModule

],

declarations: [


    AppComponent,

    MenuComponent 

],

providers: [

    DishService,

    ProcessHTTPMsgService,

    HttpClientModule,

    {provide: 'BaseURL', useValue: baseURL}

],

schemas: [

    NO_ERRORS_SCHEMA

]
})
**ProcessHTTPMsgService**
import { Injectable } from '@angular/core';

import { Observable } from 'rxjs';

import {Response} from '@angular/http';

import { HttpClientModule} from "@angular/common/http";

import { throwError } from 'rxjs';

import { HttpErrorResponse } from '@angular/common/http';

import 'rxjs/add/observable/throw';

@Injectable({

providedIn: 'root',

})

export class ProcessHTTPMsgService {

constructor() { }

public extractData(res:Response)

{ let body = res.json();

   return body || {} ;
}

public handleError(error: Response | any) {

let errMsg: string;

if (error instanceof Response) {

  const body = error.json();

  const err =body.error || JSON.stringify(body);

  errMsg = `${error.status} - ${error.statusText || ''} ${err}`;

} else {

  errMsg = error.message ? error.message : error.toString();

}

return Observable.throw(errMsg);
}
}

**dish service**
import {Injectable} from '@angular/core';

import { Dish } from '../shared/dish';

import { Observable } from 'rxjs';

import { Http, Response } from '@angular/http';

import { baseURL } from '../shared/baseurl';

import { ProcessHTTPMsgService } from './process-httpmsg.service';

import 'rxjs';

import 'rxjs/add/operator/map';

import 'rxjs/add/operator/delay';

import 'rxjs/add/operator/catch';

@Injectable({

providedIn: 'root',
})

export class DishService {

constructor(public http:Http, private ProcessHTTPMsgService: ProcessHTTPMsgService ) {}

getDishes(): Observable

{

return this.http.get(baseURL + 'dishes')

.map(res => {return this.ProcessHTTPMsgService.extractData(res);})

.catch(error => {return this.ProcessHTTPMsgService.handleError(error)});

}

getDish(id: number): Observable

{

return this.http.get(baseURL + 'dishes/' + id)

.map(res => {return this.ProcessHTTPMsgService.extractData(res);})

.catch(error => {return this.ProcessHTTPMsgService.handleError(error)});
}

getFeaturedDish(): Observable

{ return this.http.get(baseURL + 'dishes?featured=true')

.map(res => {return this.ProcessHTTPMsgService.extractData(res)[0];})

.catch(error => {return this.ProcessHTTPMsgService.handleError(error)});
}

}
**baseurl.ts** 
export const baseURL = "my@IP:3000/";
**menu.component.ts**

import { Component, OnInit, Inject} from '@angular/core';

import { Dish } from '../shared/dish';

import { DishService } from '../services/dish.service';

import { HttpClientModule} from "@angular/common/http";

@Component({

selector: 'app-menu',

moduleId: module.id,

templateUrl: './menu.component.html'
})

export class MenuComponent implements OnInit

{

dishes: Dish[];

errMess: string;

constructor(private http: HttpClientModule, private DishService: DishService,

@Inject('baseURL') private baseURL)

{}

ngOnInit()

{
    this.DishService.getDishes()

    .subscribe(dishes => this.dishes = dishes, 

        errmess => this.errMess = <any>errmess)
}
}

**Comment by NickIliev** [comment] 2019-08-30 05:46
@sabrineayadi the above code is hardly readable ... better use [Playground](https://play.nativescript.org/)

Closing the issue as how-to related  but do let me know if you have test project or Playground demo and I will take a look

**Closed by NickIliev** 2019-08-30 05:46 UTC
Labels: needs more info
