### ISSUE TITLE
[Android] - Button does not follow GridLayout layering behavior

### ISSUE THREAD

**Issue by shiv19** [NativeScript/NativeScript#6613] opened 2018-11-26 00:14 UTC
**Environment**

 - CLI: latest 5.x
 - Cross-platform modules: latest 5.x
 - Android Runtime: latest 5.x
 - iOS Runtime: latest 5.x

**Describe the bug**
In grid layout, the items at the bottom are expected to come on top. This behavior is commonly used to layer items in NativeScript. The Android button doesn't obey this behavior, whereas the iOS button does.

**To Reproduce**
https://play.nativescript.org/?template=play-js&id=9LFxKc
Visit this on Android, then visit on iOS. On iOS, the button stays behind the layered layout.
I've included a possible workaround.

**Expected behavior**
Expect the button to obey layering on Android, without having to set `style="z-index: 0"`

**Sample project**
https://play.nativescript.org/?template=play-js&id=9LFxKc

**Comment by tsonevn** [comment] 2018-11-26 06:38
Duplicate of https://github.com/NativeScript/NativeScript/issues/6184

**Closed by tsonevn** 2018-11-26 06:38 UTC
