### ISSUE TITLE
The Preview service has been disabled until further notice. Configure local builds and use "ns run " instead

### ISSUE THREAD

**Issue by zeddrix** [NativeScript/NativeScript#9571] opened 2021-09-24 05:36 UTC
### I posted this question too [here on stackoverflow](https://stackoverflow.com/questions/69309987/the-preview-service-has-been-disabled-until-further-notice-configure-local-buil) for more details (with screenshots of error logs).

All I was doing was following the [docs here](https://svelte-native.technology/docs#quick-start). But it just gave me this error:  

#### `The Preview service has been disabled until further notice. Configure local builds and use "ns run " instead.`

**Comment by janoshrubos** [comment] 2021-09-24 11:09
Thank you for your issue!

  The Playground and the Preview app has been disabled until further notice, the implementation is in progress for a better user experience.

With `ns run` you can deploy your app to your iOS/Android device or simulator. To configure your local builds you should install Xcode or install Android Studio. 
You can read more info on the [Environment Setup](https://docs.nativescript.org/environment-setup.html).

Duplicate of https://github.com/NativeScript/NativeScript/issues/9512

**Comment by jms-1005** [comment] 2022-08-17 16:52
<img width="564" alt="Screen Shot 2022-08-17 at 9 51 07 AM" src="https://user-images.githubusercontent.com/96402058/185197501-c90729f5-2dc5-4234-adb0-88f67962e11b.png">

I keep getting this error when I run `ns run`. Not sure if everyone else is facing the same issue.

**Comment by zeddrix** [comment] 2022-08-17 22:21
View the solution on a post I made [here on stackoverflow](https://stackoverflow.com/questions/69309987/the-preview-service-has-been-disabled-until-further-notice-configure-local-buil).

**Closed** 2022-08-17 22:22 UTC
Labels: known-issue, playground
