### ISSUE TITLE
Sequential Animation with instruction to the default state is ignored

### ISSUE THREAD

**Issue by Fatme** [NativeScript/NativeScript#834] opened 2015-09-28 12:50 UTC
_From @sebawita on September 28, 2015 11:52_

The bellow animation sequence is expected to fade out and in 2 times, however the actual result is that the component fades once that is it.
This is because the instructions that tell the component to set opacity to 1 are ignored, as this is the opacity when the animation begins.

```
var animationModule = require("ui/animation");
var animationChain = [
                        { target: view1, opacity: 0.2 },
                        { target: view1, opacity: 1 },
                        { target: view1, opacity: 0.2 },
                        { target: view1, opacity: 1 }
                    ];
var animation = new animationModule.Animation(animationChain, true);
animation.play();
```

The below sequence works fine the first time, but the second time I execute it, opacity: 0.99 becomes the initial value, so all instructions that set the opacity to 0.99 are ignored.
```
var animationChain = [
                        { target: view1, opacity: 0.2 },
                        { target: view1, opacity: 0.99 },
                        { target: view1, opacity: 0.2 },
                        { target: view1, opacity: 0.99 }
                    ];
```

I tried this with other animation instructions (see below) and all seem to ignore instructions that are equal to the initial state of the component:

This should make the component smaller and then back to normal. The component doesn't go back to normal.
```
animationChain = [
                        { target: view1, scale: { x: 0.8, y: 0.8 } },
                        { target: view1, scale: { x: 1, y: 1 } }
                    ];
```

This should move the component to the right 5 times and then move it back to its original position, but it doesn't come back to the original position.
```
animationChain = [
                        { target: view1, translate: { x: 10, y: 0 }, duration: 70, iterations: 5 },
                        { target: view1, translate: { x: 0, y: 0 }, duration: 50 }
                    ];
```

This should swing the component a bit to one side then the other and finally put it back to its original position, but the last instruction is ignored.
```
animationChain = [
                        { target: view1, rotate: 10, duration: 150 },
                        { target: view1, rotate: -10, duration: 300 },
                        { target: view1, rotate: 0, duration: 150 }
                    ];
```

I have only tried it on Android, so not sure how it behaves on iOS.

_Copied from original issue: NativeScript/nativescript-cli#971_

**Comment by Fatme** [comment] 2015-09-28 12:50
_From @sebawita on September 28, 2015 12:9_

In animation.android.js I found _createAnimators function where I commented out all if statements that compare the current state of the animation to the original value.
After doing that the animations seem to work fine.

Is there a major reason why this should work this way?
I would vote to remove all the if statements in that switch.

**Comment by hamorphis** [comment] 2015-10-14 06:23
Duplicate of https://github.com/NativeScript/NativeScript/issues/759

**Closed** 2015-10-14 06:24 UTC
