### ISSUE TITLE
Error: TypeError: javaObj.entrySet is not a function

### ISSUE THREAD

**Issue by torvicv** [NativeScript/NativeScript#6069] opened 2018-07-13 20:09 UTC
In my console appear this message:

Tried to serialize an unsupported type: javaObj.getClass().getName(), error: TypeError: javaObj.entrySet is not a function.

Despite of this Error, my application works fine. In the console say that Report this error so I have done it.

**Comment by NickIliev** [comment] 2018-07-16 05:44
@torvicv the issue is more likely related [to this one](https://github.com/NativeScript/NativeScript/issues/5990) - closing as duplicate to the linked issue.

If your issue is not related to using nativescript-plugin-firebase please post all the needed information requested in the "open a new issue" section  so we could investigate the problem.

**Closed by NickIliev** 2018-07-16 05:44 UTC
Labels: needs more info, os: android
