### ISSUE TITLE
Backspace button event on TextField

### ISSUE THREAD

**Issue by mehulcs** [NativeScript/NativeScript#7346] opened 2019-06-12 12:03 UTC
**Is your feature request related to a problem? Please describe.**
Event for backspace button to create OTP screen, Where each TextField holds one number. Backspacing on an empty field should jump to previous TextField.

**Additional context**
Listening to data change events do not solve this issue as pressing backspace button on empty TextField won't fire data change event.

**Comment by tsonevn** [comment] 2019-06-13 09:57
Duplicate of https://github.com/NativeScript/NativeScript/issues/7349.
Check out the provided solution in the comment [here](https://github.com/NativeScript/NativeScript/issues/7349#issuecomment-501635567).

**Closed by tsonevn** 2019-06-13 09:57 UTC
