### ISSUE TITLE
Multiple HTTP response headers set incorrectly

### ISSUE THREAD

**Issue by erkanarslan** [NativeScript/NativeScript#1833] opened 2016-03-23 14:11 UTC
Let say server application sends these headers in response:

````
Header-A : value1
Header-A : value2
````

The `headers` field of http response contains this object:

````js
{
    'Header-A' : ['value1', 'value1']
}
````

As you see, the first value is duplicated.

**Comment by enchev** [comment] 2016-03-24 13:52
Hey @erkanarslan,

I've made pull request with possible fix for this issue. Unfortunately it will be very hard to test it locally and that why I'm asking you if you can test it in your case and let me know about the result.

**Comment by erkanarslan** [comment] 2016-03-24 14:37
@enchev The problem is on Android. I'm not sure if that change you made on iOS will work on Android too.

**Comment by enchev** [comment] 2016-03-24 14:57
Do you have the same problem in iOS or you've got this only in Android?

**Comment by erkanarslan** [comment] 2016-03-24 15:05
I don't own a MacBook, cannot test on iOS. Maybe it has the same problem too.

**Comment by enchev** [comment] 2016-03-24 15:06
Do you know reliable echo or whatever service where we can test this?

**Comment by erkanarslan** [comment] 2016-03-24 15:07
No, I work on my own localhost.

**Comment by enchev** [comment] 2016-03-24 15:11
Can you experiment with [the code here](https://github.com/NativeScript/NativeScript/blob/master/http/http-request.android.ts#L62-L72) to check if there is a way to read properly headers in your case?

**Comment by erkanarslan** [comment] 2016-03-24 15:24
In `tns-core-modules/http/http-request.android.js`, I found the part you showed and added these console log functions:

````js
var jHeaders = result.headers;
var length = jHeaders.size();
var i;
var pair;
for (i = 0; i < length; i++) {
    pair = jHeaders.get(i);
    console.log(pair.key);
    console.log(pair.value);
    http.addHeader(headers, pair.key, pair.value);
}
````

The result is this:
````
JS: Date
JS: Thu, 24 Mar 2016 15:19:33 GMT
JS: Server
JS: Apache/2.4.7 (Ubuntu)
JS: X-Powered-By
JS: PHP/5.5.9-1ubuntu4.14
JS: Cache-Control
JS: no-cache
JS: Set-Cookie
JS: laravel_session=eyJpdiI6ImR2XC9UeEhWXC82UWpLXC9WZ2FDTFVLbUE9PSIsInZhbHVlIjoiT3JYNFpqejlDaXRcL1N6dngxR0RSMXRHVllPenQ2VDhBXC9vcHZHSnlVa0pEcDkyTFcwY1JhVG1GMFFMUlNXdDg1c0EwOE9YMkJqN2g0blJNWHROMzZlZz09IiwibWFjIjoiNTIyYzA0ZjA5Nzg0MWNkYjhkNjI1YWE5NTllZDUyMmZiODAyYzA0ZTVkMDcwYjkzNWEyNTczOTBhYTU0Y2RjNCJ9; expires=Thu, 31-Mar-2016 15:19:33 GMT; Max-Age=604800; path=/; httponly
JS: Set-Cookie
JS: laravel_session=eyJpdiI6ImR2XC9UeEhWXC82UWpLXC9WZ2FDTFVLbUE9PSIsInZhbHVlIjoiT3JYNFpqejlDaXRcL1N6dngxR0RSMXRHVllPenQ2VDhBXC9vcHZHSnlVa0pEcDkyTFcwY1JhVG1GMFFMUlNXdDg1c0EwOE9YMkJqN2g0blJNWHROMzZlZz09IiwibWFjIjoiNTIyYzA0ZjA5Nzg0MWNkYjhkNjI1YWE5NTllZDUyMmZiODAyYzA0ZTVkMDcwYjkzNWEyNTczOTBhYTU0Y2RjNCJ9; expires=Thu, 31-Mar-2016 15:19:33 GMT; Max-Age=604800; path=/; httponly
JS: Content-Length
JS: 32
JS: Keep-Alive
JS: timeout=5, max=100
JS: Connection
JS: Keep-Alive
JS: Content-Type
JS: application/json
JS: X-Android-Sent-Millis
JS: 1458832750757
````

The server application is an existing application that works without problem. Still, I tested if it sends the cookies wrong but there is no problem. Cookies are repeated.

**Comment by sitefinitysteve** [comment] 2016-03-31 15:49
I think I have this issue as well

http://www.screencast.com/t/JmPuRbZTN

On iOS the result is JSON, but on Android I get the ServiceStack Html page as if I never set the Content-Type header at all.

The workaround for me is super ugly, needing to put the format in the querystring (checking for ?, etc etc)

**Comment by devna13** [comment] 2016-06-22 22:03
I get double cookies making http request

**Comment by hdeshev** [comment] 2016-07-07 11:41
Duplicate of #2413, Fixed on master.

**Closed by hdeshev** 2016-07-07 11:41 UTC
