### ISSUE TITLE
Button highlighting stay pressed inside Listview

### ISSUE THREAD

**Issue by markomiljkovic** [NativeScript/NativeScript#5438] opened 2018-02-19 15:26 UTC
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes 

### Tell us about the problem
Hello guys Im having issue with highlighted psedo element on Buttons
When I have listview and Inside I have Button 

```
 <lv:RadListView id="songs" items="{{ playlist }}">
                    <lv:RadListView.itemTemplate>
                       Button  class="play"
                                    text="Play Song"  tap="playRecord"/>
    </lv:RadListView.itemTemplate>
</lv:RadListView>
```

and In my app.css 
```
.play:highlighted {
    background-color: #8D9FA6;
    color: #fff;
}
```

When I tap on Item and scroll down the list then the Button is always highlighted and it changes it background color.
But when I just tap on it is working normally.
### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI:3.3.1

**Comment by NickIliev** [comment] 2018-02-19 15:57
@markomiljkovic thanks for reporting this issue - I can confirm that indeed the highlighted state is not released if the ListView is scrolled while the button is pressed.

However I am experiencing this only on Android - can you confirm that you are seeing the same on iOS?


Steps to reproduce:
- use [this demo app](https://github.com/NickIliev/NS-Issues-2018/tree/master/NativeScript/issue_5438)
- use either ListView or RadListView (the same results)
- press a Button to trigger highlighted state and without releasing it scroll the ListView.

Result: the highlighted effect is not removed.

**Comment by NickIliev** [comment] 2018-02-20 11:14
@markomiljkovic it appears that the issue is a known bug logged [here](https://github.com/NativeScript/NativeScript/issues/4967).

Closing as duplicate to [https://github.com/NativeScript/NativeScript/issues/4967](https://github.com/NativeScript/NativeScript/issues/4967)

**Closed by NickIliev** 2018-02-20 11:14 UTC
Labels: bug, os: android
