### ISSUE TITLE
CSS animation infinite not working

### ISSUE THREAD

**Issue by vallemar** [NativeScript/NativeScript#9416] opened 2021-05-24 22:51 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
√ Component nativescript has 8.0.2 version and is up to date.
‼ Update available for component @nativescript/core. Your current version is 8.0.5 and the latest available version is 8.0.6.
× Component @nativescript/ios is not installed.
√ Component @nativescript/android has 8.0.0 version and is up to date.

**Describe the bug**
When I put an animation to infinity the animation repeats 2 times and then stops.

```
.box-animation {
  width: 15;
  height: 100%;
  background-color: white;
  background: linear-gradient(90deg, white, blue);
  animation-name: shimmer;
  animation-duration: 1s;
  animation-iteration-count: infinite;
}

@keyframes shimmer {
  0% {
    transform: translate(-200, 0);
  }
  100% {
    transform: rotate(100);
  }
}
```

In [stackoverflow ](https://stackoverflow.com/questions/59637102/nativescript-rotate-animation-with-infinite-iteration-not-working)I found this trick and it works but I understand that it should work with the previous example

```
@keyframes shimmer {
  0% {
    transform: translate(-200, 0);
  }
  99.9% {
    transform: translate(100);
  }
  100% {
    transform: translate(-200, 0);
  }
}
```

**Comment by vallemar** [comment] 2021-05-25 10:06
I am seeing that this behavior was already mentioned [here](https://github.com/NativeScript/NativeScript/issues/8487) and [here](https://github.com/NativeScript/NativeScript/issues/7712#issuecomment-708218923)

**Comment by jcassidyav** [comment] 2021-05-25 12:26
When it works do you see this issue #9406 i.e. when the element is unloaded it does not stop the animation consuming cycles?

**Comment by vallemar** [comment] 2021-05-25 12:36
@jcassidyav I have never profiled with android studio but I will look at it as soon as I can

**Comment by janoshrubos** [comment] 2021-09-09 12:02
Duplicate of https://github.com/NativeScript/NativeScript/issues/7712

**Closed by janoshrubos** 2021-09-09 12:02 UTC
