### ISSUE TITLE
Limitations of StackLayout? Can't put WebView inside

### ISSUE THREAD

**Issue by emiloberg** [NativeScript/NativeScript#224] opened 2015-05-27 10:29 UTC
Are there (undocumented?) limitations of the StackLayout? When putting a WebView inside a StackLayout it simply does not display. Or is this a limitation of the WebView? Or simply a bug?

Compare the two following; does not work:

```
<Page xmlns="http://www.nativescript.org/tns.xsd">
        <StackLayout>
            <WebView url="http://www.example.com" />
        </StackLayout>
</Page>
```

Does indeed work:

```
<Page xmlns="http://www.nativescript.org/tns.xsd">
        <GridLayout>
            <WebView url="http://www.example.com" />
        </GridLayout>
</Page>
```

**Comment by hshristov** [comment] 2015-05-28 14:19
Hi @emiloberg,

Is this on iOS or Android?

**Comment by emiloberg** [comment] 2015-05-28 14:20
iOS emulator, actually haven't tested on Android (as my emulator environment is acting up)

**Comment by TheLastHeir** [comment] 2015-05-29 13:54
its about android too

**Comment by devangpaliwal** [comment] 2015-06-02 21:11
+1

**Comment by vchimev** [comment] 2015-08-11 11:07
Hi @emiloberg,

the issue here is that the WebView does not return the correct size it requires, so currently in order to work on iOS an explicit height/minHeight value should be set. For example:

```
<Page xmlns="http://www.nativescript.org/tns.xsd">
        <StackLayout>
            <WebView url="http://www.example.com" minHeight="250" />
        </StackLayout>
</Page>
```

We are going to further investigate if there is any way to fix this issue or behave as expected out of the box.

@TheLastHeir I was unable to reproduce the problem on Android.

**Comment by dbenninger** [comment] 2017-03-03 09:42
Is there a workaround for this one? My text and it's size is dynamic, setting a fixed height is not an option.

**Comment by NickIliev** [comment] 2017-05-18 06:25
@dbenninger instead of using StackLayout with fixed size you can use GridLayout with row and col size of * (meaning take all available space left)

e.g.
```
<GridLayout rows="*" columns="*">
    <WebView row="0" col="0" src="https://docs.nativescript.org"></WebView>
</GridLayout>
```

**Comment by RyanSMurphy** [comment] 2017-07-17 11:09
@NickIliev this doesnt work on ios

**Comment by RyanSMurphy** [comment] 2017-07-17 11:15
@NickIliev This doesnt work if the gridlayout is not the top parent, for example if tkmaincontent is a scroll view or anything else this will not work. Any chance of a fix for this?

**Comment by hettiger** [comment] 2017-12-18 09:57
You could try something like this as a workaround until this get's fixed:

```html
<script>
    (function() {
        window.addEventListener("load", function onWindowLoaded() {
            window.removeEventListener("load", onWindowLoaded, false);
            
            window.nsWebViewInterface.emit('setWebViewHeight', {
                height: Math.max(
                    +document.documentElement.clientHeight,
                    +document.documentElement.scrollHeight,
                    +document.documentElement.offsetHeight,
                    +document.body.scrollHeight,
                    +document.body.offsetHeight
                )
            });
        }, false);
    })();
</script>
```

```ts
public onWebViewLoaded(args: EventData): void {
    const webView = args.object as WebView;

    if (isAndroid) {
        const settings: android.webkit.WebSettings = webView.android.getSettings();
        settings.setBuiltInZoomControls(true);
        settings.setDisplayZoomControls(false);
    }

    this.htmlPreprocessorService.process(this.data.html).then(
        html => {
            webView.src = html;

            webViewInterface.on("setWebViewHeight", (args: { height: number }): void => {
                webView.height = args.height;
            });
        }
    );
}
```

Please be aware that you need the plugin nativescript-webview-interface and your own implementation of htmlPreprocessorService. You can not copy paste this example. It is just for inspiration...

**Comment by NickIliev** [comment] 2018-01-09 08:07
The issue is not reproducible on Android (with NativeScript 3.4.0) and is considered the expected behavior on iOS.

Playground demonstration of WebView nested in a ScrollView for iOS can be found [here](https://play.nativescript.org/?template=play-tsc&id=Ye2KQE) (works on Android as well)

**Comment by hettiger** [comment] 2018-01-17 14:16
I've updated my code above which does now work pretty well. When setting the height of the WebView's to 10000 initially this renders pretty accurate and without nasty jumping. 

@NickIliev The heights I get from the WebView are somewhat unreliable. Sometimes The returned height is about ~10px bigger even thought the content stays the same and is not dynamic... Please keep that in mind when fixing this bug.

**Comment by NickIliev** [comment] 2018-05-15 10:15
Tested with NativeScript 4.0.0 (tns-core-modules 4.0.0) and latest nativescript-angular and the issue is working as expected on both iOS and Android. 

Test Playground [here](https://play.nativescript.org/?template=play-tsc&id=Ye2KQE&v=3)

**Closed** 2019-02-08 12:05 UTC
Labels: done, ready for test
