### ISSUE TITLE
When I make a change nothing happens 

### ISSUE THREAD

**Issue by ThibautMelen** [NativeScript/NativeScript#6086] opened 2018-07-18 16:02 UTC
Hello everyone;
I expose you my problem:
I am new to Native Script. I follow the quick tutorial, after installing and running the project, I am trying to edit the main original file but nothing modification happens.
When I change titles, it does not change on the emulator side. Even when restarting the command npm run watch, nothing happens.
![capture](https://user-images.githubusercontent.com/20891897/42893470-b2957f6e-8ab4-11e8-9df9-c11a8084c6bd.PNG)

**Comment by tsonevn** [comment] 2018-07-19 05:00
HI @ThibautMelen,
Can you provide some more info about your environment (`tns-core-modules`, `tns-android` and NativeScript CLI versions)? Also, it will help if you give us info about the Android emulator and its API level. 
We have an [issue](https://github.com/NativeScript/nativescript-cli/issues/3602) with the LifeSync process with Android P. The problem might be the same.

**Comment by dtopuzov** [comment] 2018-07-19 18:54
Hi @ThibautMelen, 
Can you please point the tutorial you used?
' npm run watch' - I'm not sure this is recommended by latest official tutorials.

**Comment by ThibautMelen** [comment] 2018-07-21 15:16
Hello, I finally solved the problem. I do not know why but the problem comes from the emulator. Version 28 of android does not work, so I'm going to version 27 and everything works fine

**Comment by dtopuzov** [comment] 2018-07-22 07:53
Closing as duplicate of https://github.com/NativeScript/nativescript-cli/issues/3602

**Closed by dtopuzov** 2018-07-22 07:53 UTC
Labels: needs more info, os: android
