### ISSUE TITLE
Accessing to android.R class is slow in first call

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/NativeScript#7284] opened 2019-05-24 15:05 UTC
I started to wrap a native plugin into NativeScript plugin. I use [sneaker ](https://github.com/Hamadakram/Sneaker)plugin. When I used the Custom method to set the color as following:
```JAVA
android.R.color.white
```

I noticed a significant delay on the first tap of the button. Then I just removed it and just logged the color:
```TYPESCRIPT
console.log(android.R.color.white);
// Also this freeze:
let x = android.R;

```

But:
```TYPESCRIPT
// this doesn't freeze"
let x = android;
```
Any idea?

**Comment by NickIliev** [comment] 2019-05-27 10:36
@vahidvdn I've tested your scenario[ via this project ](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/NativeScript/issue-7284)but everything is working with no delays or freezing ([here ](https://github.com/NickIliev/NS-Issues-2019-I/blob/master/NativeScript/issue-7284/app/main-view-model.ts)is the actual code used). Please check the project and let me know if there is something more specific on your side and also if the issue is reproducible on a specific API level (device) and with the test project.

**Comment by vahidvdn** [comment] 2019-05-27 11:07
@NickIliev You are accessing `android.R` in constructor first. The delay happens in just first access. So, it happens while you see the splash screen. 

So, just remove it from the constructor and add it to a button tap event to see the result. If still couldn't be able to reproduce it, please let me know.

**Comment by NickIliev** [comment] 2019-05-27 11:19
I've added the constructor logic at later point. Even without it, I am still not experiencing any difference (I've just revised the project to exclude the constructor logic)

**Comment by danielgek** [comment] 2019-05-27 11:29
@NickIliev and @vahidvdn this is related to https://github.com/NativeScript/android-runtime/issues/1330

**Comment by NickIliev** [comment] 2019-05-27 11:47
Closing the issue as related to the one linked above

**Closed by NickIliev** 2019-05-27 11:47 UTC
Labels: needs more info, os: android

**Comment by vahidvdn** [comment] 2019-05-27 11:50
@NickIliev Sorry, but your repo size was really huge, and couldn't get it. Btw, I provide a playground demo. Would you please test it, and see the result? https://play.nativescript.org/?template=play-ng&id=kAkQLP

 For my device I get:

```
[Vahid]: js access: 0.00ms
[Vahid]: native access: 901.00ms
```
