### ISSUE TITLE
tns-core-modules 1.5.1 to 1.6.0 upgrade, App is not able to build

### ISSUE THREAD

**Issue by katturajam** [NativeScript/NativeScript#1740] opened 2016-03-11 11:59 UTC
**My First issue:**

What went wrong:
Execution failed for task ':mergeNativescript-appwidgetNativescript-snackbarNativescript-push-notificationsNativescriptswiperefreshlayoutNativescript-timedatepickerNativescript-facebook-loginNativescript-plugin-google-play-servicesDebugResources'.
>Some file crunching failed, see logs for details

Solved By adding below lines in build.gradle
```
aaptOptions {
           useNewCruncher false
}

```
**My Issue-2:**

What went wrong:
Execution failed for task ':mergeNativescript-appwidgetNativescript-snackbarNativescript-push-notificationsNativescriptswiperefreshlayoutNativescript-timedatepickerNativescript-facebook-loginNativescript-plugin-google-play-servicesDebugResources'.

>/home/katturaja/NetBeansProjects/nativescript-apps/smarp_tvsi_dev/smarpshare/platforms/android/src/main/res/drawable-xhdpi/pencil.png: Error: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/bin/sdk/android-sdk-linux/build-tools/23.0.2/aapt'' finished with non-zero exit value 42

**What would to approach this to solve?**

**Comment by NathanaelA** [comment] 2016-03-11 14:15
See my blog: http://fluentreports.com/blog/?p=270
Duplicate of: https://github.com/NativeScript/android-runtime/issues/369

**Closed** 2016-03-12 07:42 UTC

**Comment by katturajam** [comment] 2016-03-14 06:12
@NathanaelA  I am using Linux Ubuntu 15.10. still i am not able to build. Following steps i tried tns platform remove android , tns platform add android, tns install, tns prepare android, tns build android but still i am not able to build in 1.6.0. It was ran successfully in 1.5.1.

**Comment by katturajam** [comment] 2016-03-14 06:14
@NathanaelA , Kindly do reopen this issue because since i am not able to build.

**Comment by katturajam** [comment] 2016-03-14 06:39
@enchev  
I am using Linux Ubuntu 15.10. still i am not able to build. Following steps i tried tns platform remove android , tns platform add android, tns install, tns prepare android, tns build android but still i am not able to build in 1.6.0. It was ran successfully in 1.5.1.

**Comment by katturajam** [comment] 2016-03-14 07:38
@enchev @NathanaelA My issue was thrown by pencil.png. It contains error. Now i replaced file without error. It was built successfully without fail. My first exception also get fixed through this.
