### ISSUE TITLE
tns run android --bundle not working

### ISSUE THREAD

**Issue by Volterra90** [NativeScript/NativeScript#9287] opened 2021-03-29 07:53 UTC
Hi!

I'm trying to build a new app with nativescript, but I can't do it properly.

I have installed nativescript versión 7.2.1 and the new node LTS version 14.16.0 in my machine.

First, I run tns create and choose the Hello World template, and the project builds correctly apparently.

Next I run tns run android --bundle, and the app is installed in the emulator I'm opening with Android Studio, but when I open the app, the app crashes with the next error:

Android version is 11.0.0.

```
An uncaught Exception occurred on "main" thread.
Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.

StackTrace:
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
	at com.tns.Module.bootstrapApp(Module.java:316)
	at com.tns.Runtime.run(Runtime.java:680)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
	... 8 more
Caused by: com.tns.NativeScriptException: Failed to find module: "./", relative to: app//
	at com.tns.Module.resolvePathHelper(Module.java:151)
	at com.tns.Module.bootstrapApp(Module.java:314)
	... 12 more
```

And this is the package.json that's generated automatically:

```
{
  "name": "@nativescript/template-hello-world-ng",
  "main": "main.js",
  "version": "7.0.10",
  "author": "NativeScript Team <oss@nativescript.org>",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "publishConfig": {
    "access": "public"
  },
  "keywords": [
    "nativescript",
    "mobile",
    "angular",
    "{N}",
    "template"
  ],
  "repository": "<fill-your-repository-here>",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "dependencies": {
    "@angular/animations": "~11.0.0",
    "@angular/common": "~11.0.0",
    "@angular/compiler": "~11.0.0",
    "@angular/core": "~11.0.0",
    "@angular/forms": "~11.0.0",
    "@angular/platform-browser": "~11.0.0",
    "@angular/platform-browser-dynamic": "~11.0.0",
    "@angular/router": "~11.0.0",
    "@nativescript/angular": "~11.0.0",
    "@nativescript/core": "~7.1.0",
    "@nativescript/theme": "~3.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.6.0",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~11.0.0",
    "@nativescript/android": "7.0.1",
    "@nativescript/types": "~7.0.0",
    "@nativescript/webpack": "~4.0.0",
    "@ngtools/webpack": "~11.0.0",
    "typescript": "~4.0.0"
  },
  "private": "true",
  "readme": "NativeScript Application"
}
```

I tried building the app again, with the same result. I also tried to clean npm cache and rebuild the app, with the same result. 

Let me know if you need more data to check the issue.

Thanks!

**Comment by P3kka** [comment] 2021-04-02 18:55
I having same problem. Have you solve what is wrong?

**Comment by rigor789** [comment] 2021-04-02 19:27
Can you share a project (even privately) with this issue? The provided details look ok to me.

**Comment by P3kka** [comment] 2021-04-02 20:08
I run this
ns create my-tab-ng --template @nativescript/template-tab-navigation-ng

A few days ago it works fine but now after update NativeScript 8.0.0 i got this error message:
Restarting application on device emulator-5554...
Successfully synced application org.nativescript.nskotisivu on device emulator-5554.
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{org.nativescript.nskotisivu/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.nskotisivu/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:223)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7656)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:29)
System.err:     at android.app.Activity.performCreate(Activity.java:8000)
System.err:     at android.app.Activity.performCreate(Activity.java:7984)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
System.err:     ... 11 more
System.err: Caused by: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
System.err:     at android.view.ViewGroup.addView(ViewGroup.java:5056)
System.err:     at android.view.ViewGroup.addView(ViewGroup.java:5036)
System.err:     at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:564)
System.err:     at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:171)
System.err:     ... 22 more

**Comment by rigor789** [comment] 2021-04-02 20:32
@P3kka can you try again, that template received an update in the last few hours!

**Comment by P3kka** [comment] 2021-04-03 05:10
Now its working, thank you!!

**Comment by P3kka** [comment] 2021-04-03 05:11
Can you tell me what was wrong?

**Comment by NathanWalker** [comment] 2021-04-03 16:19
Glad it's working now! We'll go ahead and close this... there were a few other updates and you can check the change differences in the git history here @P3kka 👍 
https://github.com/NativeScript/nativescript-app-templates/tree/master/packages/template-tab-navigation-ng

**Closed by NathanWalker** 2021-04-03 16:19 UTC
Labels: needs more info

**Comment by rigor789** [comment] 2021-04-03 19:01
@P3kka It was still using BottomNavigation - which was removed in 8.0 - this branch has the updated version: https://github.com/NativeScript/nativescript-app-templates/tree/chore/cleanup-8.0/packages/template-tab-navigation-ng and will land back to the main branch sometime next week along with other cleanups.
