### ISSUE TITLE
Modal size problem using ipad multitasking

### ISSUE THREAD

**Issue by Quovadisqc** [NativeScript/NativeScript#3434] opened 2017-01-06 19:29 UTC
**Versions**
- CLI: `2.4.2`
- Cross-platform modules: `2.4.3`
- Runtime(s): ios: `2.4.0`
- Plugin(s): 
```
"dependencies": {
    "@angular/common": "2.1.2",
    "@angular/compiler": "2.1.2",
    "@angular/core": "2.1.2",
    "@angular/forms": "2.1.2",
    "@angular/http": "2.1.2",
    "@angular/platform-browser": "2.1.2",
    "@angular/platform-browser-dynamic": "2.1.2",
    "@angular/router": "3.1.2",
    "@types/lodash": "^4.14.44",
    "lodash": "^4.17.2",
    "moment": "^2.16.0",
    "nativescript-angular": "1.1.2",
    "nativescript-barcodescanner": "^2.1.4",
    "nativescript-iqkeyboardmanager": "^1.0.1",
    "nativescript-mapbox": "^2.3.0",
    "nativescript-theme-core": "^0.1.3",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "^2.4.3",
    "tns-core-modules-widgets": "^2.4.0"
  },
  "devDependencies": {
    "babel-traverse": "6.19.0",
    "babel-types": "6.19.0",
    "babylon": "6.14.1",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^2.0.10",
    "zone.js": "~0.6.21"
  }
```

**Details**
There seems to be a weird issue when you show a modal inside an app that is shown on the side of the ipad using multitasking. It seems to be using the width of the whole screen rather than the size of the application inside the split-view. The modal works perfectly on all other devices or orientation.

<img width="377" alt="screen shot 2016-12-28 at 11 53 12 am" src="https://cloud.githubusercontent.com/assets/7490432/21526718/43956bc6-ccf4-11e6-9494-9d71585826eb.png">

<img width="769" alt="screen shot 2016-12-28 at 11 46 38 am" src="https://cloud.githubusercontent.com/assets/7490432/21526634/98348e38-ccf3-11e6-8d22-b9b88ab131b1.png">

**Comment by tsonevn** [comment] 2017-01-09 09:21
Hi @Quovadisqc, 
Thank you for reporting your problem. 

If I understand you correctly, you have problem with the NativeScirpt application width, while using iPad multitasking functionality.
For your case you could open `<project_name>/app/App_Resources/iOS/Info.plist` file using XCode and you could change `UIRequiresFullScreen` to `NO`. This should solve the problem with the width of the app. I have tested this case with [nativescript-sdk-examples-ng](https://github.com/NativeScript/nativescript-sdk-examples-ng/) project. 

Let me know, whether this helps or if I could assist you further.

Regards,
@tsonevn

**Comment by Quovadisqc** [comment] 2017-01-10 16:47
It works perfectly!
For future references, I also had to set 
`fullscreen: false` in the options parameter

Thanks for the help @tsonevn

**Comment by Quovadisqc** [comment] 2017-09-18 13:17
The problem seemed to have re-appeared with an update of packages. The modal now takes the full width of the screen even with `fullscreen: false`.

My Info.plist still contains:
```
<key>UIRequiresFullScreen</key>
<false/>
```
**Versions**
- CLI: `3.2.1`
- Cross-platform modules: `3.2.0`
- Runtime(s): ios: `3.2.0`
Plugin(s):
```
"dependencies": {
    "@angular/common": "4.4.1",
    "@angular/compiler": "4.4.1",
    "@angular/core": "4.4.1",
    "@angular/forms": "4.4.1",
    "@angular/http": "4.4.1",
    "@angular/platform-browser": "4.4.1",
    "@angular/platform-browser-dynamic": "4.4.1",
    "@angular/router": "4.4.1",
    "lodash": "4.17.4",
    "moment": "2.16.0",
    "nativescript-angular": "4.2.0",
    "nativescript-barcodescanner": "2.6.1",
    "nativescript-iqkeyboardmanager": "1.1.0",
    "nativescript-printer": "1.2.0",
    "nativescript-screenshot": "0.0.2",
    "nativescript-telerik-ui": "3.1.1",
    "nativescript-theme-core": "1.0.4",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.3",
    "tns-core-modules": "3.2.0"
  },
  "devDependencies": {
    "@types/lodash": "4.14.74",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "0.5.0",
    "typescript": "2.3.2",
    "zone.js": "0.8.17"
 }
```
![screen shot 2017-09-18 at 9 04 37 am](https://user-images.githubusercontent.com/7490432/30543315-99a64f0e-9c50-11e7-88ce-8eb2c3b8ba90.png)
![screen shot 2017-09-18 at 9 05 17 am](https://user-images.githubusercontent.com/7490432/30543314-99a4a73a-9c50-11e7-88a1-22eccc0b8e1e.png)

**Comment by NickIliev** [comment] 2018-04-12 06:12
Closing the issue as I was not able to reproduce it with NativeScript 4.0.0 and nativescript-sdk-examples.ng demo application.

**Closed by NickIliev** 2018-04-12 06:12 UTC
Labels: os: ios, question
