### ISSUE TITLE
iOS HtmlView always having unexpected bottom pad

### ISSUE THREAD

**Issue by Dennis-kw-yiu** [NativeScript/NativeScript#6666] opened 2018-12-05 09:57 UTC
**Describe the bug**
I am investigating to use the HtmlView in iOS to show the HTML content. However, I found there is an unexpected bottom pad

**To Reproduce**
Use HtmlView

**Expected behavior**
The height of the HtmlView match the HTML content inside

**Sample project**
https://play.nativescript.org/?template=play-js&id=EFhLf5&v=7

**Comment by NickIliev** [comment] 2018-12-05 15:04
The observed is not a padding but the default size of HtmlView when no height is assigned.

This is a limitation of the HtmlView control. The HTML have different ways of setting width and height (compared to Android and iOS APIs). The HtmlView (which is actually a TextView with some HTML capabilities behind the "scenes") doesn't "know" the exact size to span dynamically based on the HTML content. So a default size is created when you are not explicitly setting the `height`. 

To overcome this you can assign `height` (for the Stacklayout or directly to the Html View). This would be harder if your Html is generated dynamically (e.g. coming from a server) but in this case, I would advise of using [Nativescript-WebView-Interface](https://www.npmjs.com/package/nativescript-webview-interface) - a plugin that provides two-way communication between the webview and the native mobile app. With that, you could pass the actual size from the Html file to the native app and assign the correct values as the size of your web view.

**Comment by Dennis-kw-yiu** [comment] 2018-12-05 15:33
Thank you Nick, however in iOS, how can I pass the actual size of the HTML content but not HTML file to the native app? Is there any sample project in playground can have a reference? Thank you again.

**Comment by NickIliev** [comment] 2018-12-06 07:42
@Dennis-kw-yiu I don't have a specific example but what I am thinking is that you might use the `nativescript-webview-interface` and once the HTML loads pass its size via a callback from the raised event.  Perhaps using [something like this](https://stackoverflow.com/questions/38903331/how-to-get-inner-html-content-height/38903375) to get the HTML content and then pass it through [HTML loaded event](https://developer.mozilla.org/en-US/docs/Web/Events/load).

Details about the plugin API can be found [here](https://www.npmjs.com/package/nativescript-webview-interface)..

Closing this one as the issue is not related to a bug.

**Closed by NickIliev** 2018-12-06 07:42 UTC
Labels: os: ios, question
