### ISSUE TITLE
NS 3.0.0 fails to build, android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]

### ISSUE THREAD

**Issue by dxshindeo** [NativeScript/NativeScript#4117] opened 2017-05-04 19:12 UTC
Android
NS 3.0.0
Windows 10

I have installed Android SDK with Google Play Services and all that jazz (2.5.4 builds fine).
Steps to reproduce the problem:

1. `tns create test3 --ng`
2. Add a dependency in app.gradle file:
```
dependencies {
    compile 'com.google.android.gms:play-services:10.2.4'
}

android {  
  defaultConfig {  
    generatedDensities = []
    applicationId = "org.nativescript.test3"  
  }  
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }  
}
```

Build fails with error: 
```
:transformClassesWithDexForF0Debug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForF0Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 30.134 secs
Multiple errors were thrown:
Command gradlew.bat failed with exit code 1
```

If I change `10.2.4` to `+` (which is the preferred way), the build fails with this error:
```
`-- tns-android@3.0.0

  | Installing tns-android
Project successfully created.
Executing before-prepare hook from D:\Projects\test3\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 2.3.2
Preparing project...
> Configuring > 0/3 projects > root project
 :config phase:  createDefaultIncludeFiles
> Configuring > 0/3 projects > root project
 :config phase:  addAarDependencies
        +adding dependency: D:\Projects\test3\platforms\android\libs\aar\widgets-release.aar
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
Incremental java compilation is an incubating feature.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_1tm7tnjkjhko18glkp9np6ojv.run(D:\Projects\test3\platforms\android\build-tools\android-static-binding-generator\build.gradle:126)
:asbg:clean UP-TO-DATE
:deleteMetadata
:deleteFlavors
:deleteConfigurations UP-TO-DATE
:deleteGeneratedBindings UP-TO-DATE
:clean

BUILD SUCCESSFUL

Total time: 3.206 secs
Successfully prepared plugin nativescript-angular for android.
Successfully prepared plugin nativescript-intl for android.
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared (android)
Searching for devices...
Building project...
> Configuring > 0/3 projects > root project
:config phase:  createDefaultIncludeFiles
        +found plugins: tns-core-modules-widgets
         + creating include.gradle file for D:\Projects\test3\platforms\android\configurations\tns-core-modules-widgets
Renaming plugin directory to flavor name: D:\Projects\test3\platforms\android\src\tns-core-modules-widgets -> D:\Projects\test3\platforms\android\src\F0

:config phase:  createPluginsConfigFile
         Creating product flavors include.gradle file in D:\Projects\test3\platforms\android/configurations folder...

:config phase:  pluginExtend
        +applying configuration from: D:\Projects\test3\platforms\android\configurations\include.gradle
        +applying configuration from: D:\Projects\test3\platforms\android\configurations\tns-core-modules-widgets\include.gradle
> Configuring > 0/3 projects > root project
 :config phase:  addAarDependencies
        +adding dependency: D:\Projects\test3\platforms\android\libs\aar\widgets-release.aar
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
Incremental java compilation is an incubating feature.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_1tm7tnjkjhko18glkp9np6ojv.run(D:\Projects\test3\platforms\android\build-tools\android-static-binding-generator\build.gradle:126)
:preBuild UP-TO-DATE
:preF0DebugBuild UP-TO-DATE
:checkF0DebugManifest
:preF0ReleaseBuild UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2531Library
:prepareComAndroidSupportAppcompatV72531Library
:prepareComAndroidSupportDesign2531Library
:prepareComAndroidSupportMediarouterV72400Library
:prepareComAndroidSupportPaletteV72400Library
:prepareComAndroidSupportRecyclerviewV72531Library
:prepareComAndroidSupportSupportCompat2531Library
:prepareComAndroidSupportSupportCoreUi2531Library
:prepareComAndroidSupportSupportCoreUtils2531Library
:prepareComAndroidSupportSupportFragment2531Library
:prepareComAndroidSupportSupportMediaCompat2531Library
:prepareComAndroidSupportSupportV42531Library
:prepareComAndroidSupportSupportVectorDrawable2531Library
:prepareComAndroidSupportTransition2531Library
:prepareComGoogleAndroidGmsPlayServices1024Library
:prepareComGoogleAndroidGmsPlayServicesAds1024Library
:prepareComGoogleAndroidGmsPlayServicesAdsLite1024Library
:prepareComGoogleAndroidGmsPlayServicesAnalytics1024Library
:prepareComGoogleAndroidGmsPlayServicesAnalyticsImpl1024Library
:prepareComGoogleAndroidGmsPlayServicesAppinvite1024Library
:prepareComGoogleAndroidGmsPlayServicesAuth1024Library
:prepareComGoogleAndroidGmsPlayServicesAuthBase1024Library
:prepareComGoogleAndroidGmsPlayServicesAwareness1024Library
:prepareComGoogleAndroidGmsPlayServicesBase1024Library
:prepareComGoogleAndroidGmsPlayServicesBasement1024Library
:prepareComGoogleAndroidGmsPlayServicesCast1024Library
:prepareComGoogleAndroidGmsPlayServicesCastFramework1024Library
:prepareComGoogleAndroidGmsPlayServicesClearcut1024Library
:prepareComGoogleAndroidGmsPlayServicesDrive1024Library
:prepareComGoogleAndroidGmsPlayServicesFitness1024Library
:prepareComGoogleAndroidGmsPlayServicesGames1024Library
:prepareComGoogleAndroidGmsPlayServicesGass1024Library
:prepareComGoogleAndroidGmsPlayServicesGcm1024Library
:prepareComGoogleAndroidGmsPlayServicesIdentity1024Library
:prepareComGoogleAndroidGmsPlayServicesIid1024Library
:prepareComGoogleAndroidGmsPlayServicesInstantapps1024Library
:prepareComGoogleAndroidGmsPlayServicesLocation1024Library
:prepareComGoogleAndroidGmsPlayServicesMaps1024Library
:prepareComGoogleAndroidGmsPlayServicesNearby1024Library
:prepareComGoogleAndroidGmsPlayServicesPanorama1024Library
:prepareComGoogleAndroidGmsPlayServicesPlaces1024Library
:prepareComGoogleAndroidGmsPlayServicesPlus1024Library
:prepareComGoogleAndroidGmsPlayServicesSafetynet1024Library
:prepareComGoogleAndroidGmsPlayServicesTagmanager1024Library
:prepareComGoogleAndroidGmsPlayServicesTagmanagerApi1024Library
:prepareComGoogleAndroidGmsPlayServicesTagmanagerV4Impl1024Library
:prepareComGoogleAndroidGmsPlayServicesTasks1024Library
:prepareComGoogleAndroidGmsPlayServicesVision1024Library
:prepareComGoogleAndroidGmsPlayServicesWallet1024Library
:prepareComGoogleAndroidGmsPlayServicesWearable1024Library
:prepareComGoogleFirebaseFirebaseAnalytics1024Library
:prepareComGoogleFirebaseFirebaseAnalyticsImpl1024Library
:prepareComGoogleFirebaseFirebaseAppindexing1024Library
:prepareComGoogleFirebaseFirebaseAuth1024Library
:prepareComGoogleFirebaseFirebaseCommon1024Library
:prepareComGoogleFirebaseFirebaseConfig1024Library
:prepareComGoogleFirebaseFirebaseCrash1024Library
:prepareComGoogleFirebaseFirebaseDatabase1024Library
:prepareComGoogleFirebaseFirebaseDatabaseConnection1024Library
:prepareComGoogleFirebaseFirebaseIid1024Library
:prepareComGoogleFirebaseFirebaseMessaging1024Library
:prepareComGoogleFirebaseFirebaseStorage1024Library
:prepareComGoogleFirebaseFirebaseStorageCommon1024Library
:prepareTest3RuntimeUnspecifiedLibrary
:prepareWidgetsReleaseLibrary
:prepareF0DebugDependencies
:compileF0DebugAidl
:compileF0DebugRenderscript
:generateF0DebugBuildConfig
:cleanLocalAarFiles
:ensureMetadataOutDir
:collectAllJars
:setProperties
:generateTypescriptDefinitions SKIPPED
:copyTypings SKIPPED
:asbg:generateInterfaceNamesList
:asbg:traverseJsFiles
:asbg:runAstParser
Running full build
finished with reading lines with js files
:asbg:generateBindings
:generateF0DebugResValues
:generateF0DebugResources
:mergeF0DebugResources
Exception while processing task java.io.IOException: The pipe is being closed
Thread(png-cruncher_21): The pipe is being closed
java.io.IOException: The pipe is being closed
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
Exception while processing task java.io.IOException: The pipe is being closed
Thread(png-cruncher_22): The pipe is being closed
java.io.IOException: The pipe is being closed
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
```

Sometimes, after the build fails, I can't manually delete `platforms` folder, because it is being used by a program. When I check task manager, a bunch (7-20) processes callled `aapt` are the ones keeping folder busy, so I have to manually cancel every process and only then I can delete the platforms folder.

And sometimes, when building, it will just randomly freeze, mostly noticed at 60% (`> Building 60% > :mergeF0DebugResources`), pressing any key does not revive the console, I have to quit the building with `Ctrl + C` and start the building process again.

**Comment by NickIliev** [comment] 2017-05-05 07:59
@dxshindeo as a possible workaround you can enable multiDex support using **multiDexEnabled** **_true_** . Still, we need to investigate this scenario further so we can prevent build time errors when the dependency is coming from a plugin.
e.g.
```
dependencies {
    compile 'com.google.android.gms:play-services:10.2.4'
}

android {  
  defaultConfig {  
    generatedDensities = []
    applicationId = "org.nativescript.test3"  
    multiDexEnabled true
  }  
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }  
}
```
^^^
@Pip3r4o is this applicable solution for our runtime?

**Comment by dxshindeo** [comment] 2017-05-05 10:39
`The pipe is being closed` error now just gets thrown around randomly - even if I do a clean rebuild (deleting `platforms` AND `node_modules`), sometimes the error will be there, sometimes it will not.

**Comment by Pip3r4o** [comment] 2017-05-09 07:47
@dxshindeo The processes staying alive in your platforms/android directory are the result of using a newer Gradle version which we introduced in 3.0, it ensures that initial and consecutive builds are times faster than before as most of the configurations and resources are cached in memory. To remove the `platforms` directory properly one should execute `tns platform remove` as it takes care of terminating the continuously running gradle process by implicitly calling `./gradlew --stop` of the gradle wrapper in `platforms/android`.

As for the actual reported error - it is recommended to bring only the packages you need to use in your application from the whole google-play-services package. 

Installing the whole thing means you will need to enable multidex as described in the article - https://developer.android.com/studio/build/multidex.html#mdex-gradle. @NickIliev already hinted at an easy way to get past the limitation when targeting devices of API 21 and up, but if you also need to reach an audience using API 19 and lower, you will have to implement a custom Application class as pointed out earlier in the article.

It is recommended against using dynamic versions (`+` instead of a specific version) as different versions may introduce incompatibilities with your code.

The '`pipe`' error that shows up randomly is unrelated to what dependencies you install, and seems to appear where native resources are concerned during the build process (`Exception while processing task java.io.IOException: The pipe is being closed
Thread(png-cruncher_22)`). Perhaps there are corrupted or invalid android resources which Gradle can't handle. I haven't encountered that error myself.

**Comment by dxshindeo** [comment] 2017-05-10 07:50
Not working:
```
D:\Projects\test>tns platform remove android
rm: could not remove directory (code EBUSY): D:/Projects/test/platforms/android
```

**Comment by Pip3r4o** [comment] 2017-05-10 07:56
@dxshindeo do you get that using the 3.0 NativeScript CLI? It will implicitly `gradlew --stop` inside `platforms/android`. Doesn't fail on my end, so I can't reproduce it. If all else fails - execute the command manually. In addition you could create a new project, run it, and attempt to remove its platforms by again using `tns platform remove android` to make sure that the gradle process is killed properly.

**Comment by dxshindeo** [comment] 2017-05-10 11:14
It was with NS 2.5.4, so I guess that is why it did not remove them.

**Comment by dxshindeo** [comment] 2017-05-10 11:15
But the pipe error is major - I can't make an AOT release build because the pipe error is blocking it.

**Comment by Pip3r4o** [comment] 2017-05-10 11:54
@dxshindeo We'd need additional info to be able to reproduce the pipe error.

**Comment by dxshindeo** [comment] 2017-05-10 12:26
These are the steps required on Windows 10 with NS 2.5.4:

1. Do `tns create test --ng`
2. Change app.gradle file to:
```
android {  
	defaultConfig {  
		generatedDensities = []
		applicationId = "__PACKAGE__"
		minSdkVersion 17
		targetSdkVersion 25
	}  
	aaptOptions {  
		additionalParameters "--no-version-vectors"  
	}
} 

project.ext {
    googlePlayServicesVersion = "+"
}

dependencies {
	compile('com.github.eoinsha:JavaPhoenixChannels:0.2') {
		exclude module: 'groovy-all'
	}
    compile 'com.google.android.gms:play-services-location:+'
    compile 'com.google.maps.android:android-maps-utils:+'
}
```

3. Change `tsconfig.json` to:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "lib": [
            "es2016",
            "es2015.iterable"
        ],
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true
    },
    "exclude": [
        "node_modules",
        "platforms",
        "**/*.aot.ts"
    ]
}
```

4. Change `package.json` to:
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.test"
  },
  "dependencies": {
    "@angular/common": "4.0.3",
    "@angular/compiler": "4.0.3",
    "@angular/core": "4.0.3",
    "@angular/forms": "4.0.3",
    "@angular/http": "4.0.3",
    "@angular/platform-browser": "4.0.3",
    "@angular/platform-browser-dynamic": "4.0.3",
    "@angular/router": "4.0.3",
    "nativescript-angular": "1.5.2",
    "nativescript-angular-snapshot": "1.5.2-5.5.372.32",
    "nativescript-geolocation": "0.0.19",
    "nativescript-gif": "1.0.9",
    "nativescript-google-maps-sdk": "1.4.3",
    "nativescript-permissions": "^1.2.3",
    "nativescript-phone": "1.3.0",
    "nativescript-toast": "1.4.5",
    "nativescript-vibrate": "1.1.2",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.3.0",
    "tns-core-modules": "2.5.2",
    "nativescript-theme-core": "~1.0.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "4.1.0",
    "@ngtools/webpack": "1.2.13",
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.0",
    "copy-webpack-plugin": "4.0.1",
    "extract-text-webpack-plugin": "2.1.0",
    "htmlparser2": "3.9.2",
    "lazy": "1.0.11",
    "nativescript-css-loader": "0.26.1",
    "nativescript-dev-android-snapshot": "0.*.*",
    "nativescript-dev-typescript": "0.4.2",
    "nativescript-dev-webpack": "0.4.0",
    "raw-loader": "0.5.1",
    "resolve-url-loader": "2.0.2",
    "typescript": "2.1.6",
    "webpack": "2.4.1",
    "webpack-sources": "0.2.3",
    "zone.js": "0.8.9"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --start-app",
    "start-ios-bundle": "npm run ns-bundle --ios --start-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}

```

5. Create a file: `app/App_Resources/Android/values/nativescript_google_maps_api.xml`
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
	<string name="nativescript_google_maps_api_key">TEST_KEY</string>
</resources>
```

6. Delete folders `hooks`, `node_modules`, `platforms` and do `npm install`
7. Do `npm run start-android-bundle`

And then we either get pipe error OR building gets frozen at `> Building 64% > :mergeF0F1F2F3F4F5F6DebugResources`.

**Comment by dxshindeo** [comment] 2017-05-15 14:41
Now sometimes I get the pipe error even when building in JIT. Current workaround is to just stop the build [CTRL+C] and start it again, then the error is gone.

**Comment by Pip3r4o** [comment] 2017-05-15 20:30
@dxshindeo sounds like a problem with the android build tools and or the gradle wrapper. Unfortunately at this point I am unable to think up of a solution or a workaround.

**Comment by NickIliev** [comment] 2017-05-26 09:56
@dxshindeo as we resolved the main issue I am closing this issue in favor of [this one](https://github.com/NativeScript/android-runtime/issues/768) where we can continue discussing the reason behind `The pipe is being closed` error.

**Closed by NickIliev** 2017-05-26 09:56 UTC
Labels: Android, T:Question
