### ISSUE TITLE
ImageSource's creates images with wrong dimensions on iOS

### ISSUE THREAD

**Issue by abhayastudios** [NativeScript/NativeScript#6011] opened 2018-06-30 16:30 UTC
### Tell us about the problem
It seems that after resizing an `ImageSource` any resulting images (e.g. through `saveToFile`) have dimensions that are 'off' by a factor of `imageSource.ios.scale` on iOS (on Android it works fine). See the code example below to reproduce the problem. So on an iPhone 6 it will result in an image with width/height of factor 2 and on an iPhoneX with factor 3.

See also [this](https://github.com/NativeScript/nativescript-imagepicker/issues/185) where the same issue is reported in the context of `nativescript-image-picker`, but I was able to reproduce it also with using an image from an URL (see the code below).

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
```
$ tns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 4.1.2 version and is up to date.
✔ Component tns-core-modules has 4.1.0 version and is up to date.
✔ Component tns-android has 4.1.3 version and is up to date.
✔ Component tns-ios has 4.1.1 version and is up to date.
```

```
$ cat package.json
{
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"readme": "NativeScript Application",
	"repository": "<fill-your-repository-here>",
	"nativescript": {
		"id": "org.nativescript.imagetest",
		"tns-ios": {
			"version": "4.1.1"
		},
		"tns-android": {
			"version": "4.1.3"
		}
	},
	"dependencies": {
		"@angular/animations": "~6.0.0",
		"@angular/common": "~6.0.0",
		"@angular/compiler": "~6.0.0",
		"@angular/core": "~6.0.0",
		"@angular/forms": "~6.0.0",
		"@angular/http": "~6.0.0",
		"@angular/platform-browser": "~6.0.0",
		"@angular/platform-browser-dynamic": "~6.0.0",
		"@angular/router": "~6.0.0",
		"nativescript-angular": "~6.0.0",
		"nativescript-imagepicker": "^6.0.2",
		"nativescript-theme-core": "~1.0.4",
		"reflect-metadata": "~0.1.8",
		"rxjs": "~6.1.0",
		"tns-core-modules": "~4.1.0",
		"zone.js": "^0.8.26"
	},
	"devDependencies": {
		"babel-traverse": "6.26.0",
		"babel-types": "6.26.0",
		"babylon": "6.18.0",
		"lazy": "1.0.11",
		"nativescript-dev-typescript": "~0.7.0",
		"typescript": "~2.7.2"
	}
}
```

### Please tell us how to recreate the issue in as much detail as possible.
Playground doesn't work due to the need for `nativescript-imagepicker` plugin (I didn't find any other way to create an ImageAsset, actually would be interesting to see how it behaves if there is).

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```
import { Component, OnInit } from "@angular/core";
import { ImageSource } from "tns-core-modules/image-source";
import { ImageAsset, ImageAssetOptions } from "tns-core-modules/image-asset"; // imagepicker returns ImageAsset type
import { ImagePickerMediaType, Options as ImagePickerOptions, create as ImagePickerCreate } from "nativescript-imagepicker";
import * as imageSource from "tns-core-modules/image-source";
import * as fs from "tns-core-modules/file-system";
import * as BitmapFactory from "nativescript-bitmap-factory";

@Component({
  template: `
    <StackLayout>
      <Button text="Image from Url" (tap)="getImageFromUrl()"></Button>
      <Button text="Image from Picker" (tap)="getImageFromPhone()"></Button>
      <Label text="Output"></Label>
      <Label textWrap="true" [text]="output" class="output"></Label>
    </StackLayout>
  `,
  styles: [`
    .output { margin-top:20; font-size: 10; }
  `]
})
export class ImageTestComponent implements OnInit {
    private demoImageUrl: string = 'https://scontent.fsdv2-1.fna.fbcdn.net/v/t1.0-9/20292767_10154648602877623_5404697562855970638_n.jpg?_nc_cat=0&oh=4b571c581d742440a5414dc104095d7b&oe=5BA0DADC';
    public output:string = '';

    constructor() {
    }

    ngOnInit(): void {}

    public getImageFromPhone() {
    const pickerOptions:ImagePickerOptions = {
      mode: 'single', // use "multiple" for multiple selection
      mediaType: ImagePickerMediaType.Image
    }

    let picker = ImagePickerCreate(pickerOptions);

    picker.authorize().then(() => { return picker.present(); }).then((selection) => {
      selection.forEach((selectedPhoto:ImageAsset) => {

        const imageAssetOptions:ImageAssetOptions = {
          keepAspectRatio: true,
          height: 500,
          width:500          
        }

        selectedPhoto.options = imageAssetOptions;

        let sourceImage = new ImageSource();

        sourceImage.fromAsset(selectedPhoto).then((imageSource: ImageSource) => {
          this.output+=`original height: ${imageSource.height} - width: ${imageSource.width}\n`;

          this.saveImageSource(imageSource).then((metadata:any) => {
            this.output+=`processed height: ${metadata.height} - width: ${metadata.width}\n\n`;
          }, (error) => {
            this.output+=`Error -> ${error}\n\n`;
          });
        }, (error) => { console.log('Error -> ' + error); }); // end of fromAsset
      }); // end of forEach loop
    }).catch((error) => {
      this.output+=`Error -> ${error}\n\n`;
    });
  }

  public getImageFromUrl() {
    imageSource.fromUrl(this.demoImageUrl).then((imageSrc: ImageSource) => {
      this.output+=`original height: ${imageSrc.height} - width: ${imageSrc.width}\n`;

      this.resizeImageSource(imageSrc, 500).then((resizedImageSrc: ImageSource) => {
        this.saveImageSource(resizedImageSrc).then((metadata:any) => {
          this.output+=`processed height: ${metadata.height} - width: ${metadata.width}\n\n`;
        }, (error) => { console.log('Error -> ' + error); });
      });
    }).catch((error) => {
      this.output+=`Error -> ${error}\n\n`;
    });
  }

  public saveImageSource(imageSrc:ImageSource) {
    return new Promise((resolve, reject) => {
      const targetFilename = `temp_image.jpg`;
      const tempPath = fs.knownFolders.temp().path;
      const localFullPath = fs.path.join(tempPath, targetFilename);

      const fullImageSaved = imageSrc.saveToFile(localFullPath, 'jpeg');

      if (fullImageSaved) {
        this.output+=`in-processing height: ${imageSrc.height} - width: ${imageSrc.width}\n`;

        let sourceImage = new ImageSource();
        sourceImage.fromFile(localFullPath).then(() => {
          resolve({
            width: sourceImage.width,
            height: sourceImage.height,
            localFullPath: localFullPath
          })
        });
      } else { reject(`Error saving photo to local temp folder: ${localFullPath}`); }
    });
  }

  private resizeImageSource(imageSrc:ImageSource, maxSize) : Promise<ImageSource> {
    return new Promise((resolve, reject) => {
      const bitmap = BitmapFactory.create(imageSrc.width, imageSrc.height);
      bitmap.dispose((imageBitmap) => {
        imageBitmap.insert(BitmapFactory.makeMutable(imageSrc));
        const resizedBitmap = imageBitmap.resizeMax(maxSize);
        resolve(resizedBitmap.toImageSource());
      }, (error) => { reject(error); });
    });
  }
}
```

**Comment by NickIliev** [comment] 2018-07-02 11:30
Confirming this one as unexpected behaviour on iOS and marking it as a bug.
Steps to reproduce:
- use [this test application](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/NativeScript/issue-6011)  (which is using the above logic)

The application is resizing an image and the resized image is returning scaled height and width on iOS (by a factor of the currently used device).

**Comment by NickIliev** [comment] 2018-07-18 06:05
After some additional investigation of your code it appears that the issue is related to two things:
- the usage of nativescript-bitmap-factory
- the compressionQuality on iOS that is being applied by default with `saveFile` method (when the quality is omitted.)

In your code base, before saving the file you are calling `resizeImageSource` which is using the method `resizeMax` from nativescript-bitmap-factory. Now, this method is not considering the scale factor on iOS which is causing the image size to be bigger by that scale factor. You could contact the authors of the plugin and discuss with him this specific method (perhaps a parameter for the scale factor can be added to the method).

There is also the concept of what compression quality to apply when using `UIImageJREGRepresentation`. Common suggestion is to use 0.7 as a value for the quality - details on why to prefer it over the full quality (1) can be found [here](https://stackoverflow.com/a/50466110/4936697)

All that said the above should not be considered a bug in the modules.as the size of the image is resized via `nativescript-bitmap-factory` and the method `resizeMax`

**Closed** 2018-07-18 07:22 UTC
Labels: backlog, os: ios

**Comment by abhayastudios** [comment] 2018-07-18 08:21
@NickIliev thanks for investigating this. 

Maybe I am not following you completely, but if what you say about the `nativescript-bitmap-factory` is true then I would expect it to return the wrong image size.

When I add additional logging to `getImageFromUrl` then it seems that `resizeImageSource` does return the correct image size (post-resize in the log).

```
public getImageFromUrl() {
    imageSource.fromUrl(this.demoImageUrl).then((imageSrc: ImageSource) => {
      this.output+=`original height: ${imageSrc.height} - width: ${imageSrc.width}\n`;

      this.resizeImageSource(imageSrc, 500).then((resizedImageSrc: ImageSource) => {
        this.output+=`post-resize height: ${resizedImageSrc.height} - width: ${resizedImageSrc.width}\n`;
        this.saveImageSource(resizedImageSrc).then((metadata:any) => {
          this.output+=`processed height: ${metadata.height} - width: ${metadata.width}\n\n`;
        }, (error) => { console.log('Error -> ' + error); });
      });
    }).catch((error) => {
      this.output+=`Error -> ${error}\n\n`;
    });
  }
```

**Comment by ADjenkov** [comment] 2018-07-18 10:47
@abhayastudios specifying `80` won't work because there is a bug in tns-core-modules@4.1.0. You should set `0.8` instead of `80` or just use tns-core-modules@next (if you want to set 80).

**Comment by ADjenkov** [comment] 2018-07-31 07:16
@abhayastudios as you may have seen we've introduced `autoScaleFactor` boolean property for the ImageAssetOptions (iOS specific). You could disabled it in your sample in order to reduce final image resolution and size. 

_To try the new option you should use `tns-core-modules@next` since it is not yer officially released_
