### ISSUE TITLE
Socket connection timed out.. (Crashlytics issue with nativescript-plugin-firebase)

### ISSUE THREAD

**Issue by alereisan** [NativeScript/NativeScript#6534] opened 2018-11-09 10:20 UTC
**Environment**
tns info: output
![image](https://user-images.githubusercontent.com/14333479/48256680-a6921000-e410-11e8-9bd7-2f43a2cd3672.png)

**Describe the bug**
![image](https://user-images.githubusercontent.com/14333479/48256717-bf9ac100-e410-11e8-998d-a1ef90b6ed32.png)
I cannot run my app. 

> Error detected during LiveSync on emulator-5554 for /Users/iamacpro2018/Documents/nativescript/tns-yoojis-kies. Error: Socket connection timed out.

I tried to start it from the CLI, from Sidekick, on an Android Emulator, on 2 different Android Devices. I deleted the project folder and re-cloned the github repository. 

I followed all the inputs from related errors on Github, Slack and Stackoverflow.

I wrote a cleanup script (which worked for one day):
```
sudo chmod -R 777 .
npm cache clean --force
echo "Starting Nativescript cleanup..."
echo "removing node_modules folder..."
rm -rf node_modules/ 
echo "removing platforms folder..."
rm -rf platforms/ 
echo "removing package-lock.json file..."
rm -rf package-lock.json 
echo "removing hooks folder..."
rm -rf hooks/
npm i
echo "Nativescript cleanup successfull!"
echo "Configuring TypeScript for NativeScript..."
./node_modules/.bin/ns-upgrade-tsconfig
echo "Configuring Webpack for NativeScript..."
./node_modules/.bin/update-ns-webpack --deps --configs
echo "Configuring Angular dependencies for NativeScript..."
./node_modules/.bin/update-app-ng-deps
echo "Running npm install..."
npm install
echo "npm install done!"
echo "Starting Android Build..."
tns build android
echo "Android build successfull!"
```

The "Socket connection timed out..." error persists.

(If I start a new project in Sidekick, the new project runs)

**Sample project**
as this is a private repository, please tell me whom i should add as a collaborator

tns doctor output:
![image](https://user-images.githubusercontent.com/14333479/48256622-734f8100-e410-11e8-9eea-cb9306806f99.png)

package.json:
```
{
  "nativescript": {
    "id": "ch.inaffect.yoojis.kies",
    "tns-ios": {
      "version": "5.0.0"
    },
    "tns-android": {
      "version": "5.0.0"
    }
  },
  "description": "Android App for Yooji's KIES consoles",
  "license": "-",
  "repository": "https://github.com/inaffect-ag/tns-yoojis-kies",
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "~6.1.0",
    "@angular/common": "~6.1.0",
    "@angular/compiler": "~6.1.0",
    "@angular/core": "~6.1.0",
    "@angular/forms": "~6.1.0",
    "@angular/http": "~6.1.0",
    "@angular/platform-browser": "~6.1.0",
    "@angular/platform-browser-dynamic": "~6.1.0",
    "@angular/router": "~6.1.0",
    "@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^3.0.1",
    "moment": "^2.22.2",
    "nativescript-angular": "^6.2.0",
    "nativescript-permissions": "^1.2.3",
    "nativescript-plugin-firebase": "^7.3.0",
    "nativescript-ripple": "2.1.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-listview": "3.7.2",
    "nativescript-ui-sidedrawer": "~4.2.0",
    "reflect-metadata": "~0.1.10",
    "rxjs": "^6.0.0",
    "tns-core-modules": "^5.0.2",
    "tns-platform-declarations": "^4.2.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~6.1.0",
    "@ngtools/webpack": "~6.2.0",
    "codelyzer": "~4.3.0",
    "nativescript-dev-sass": "~1.6.0",
    "nativescript-dev-typescript": "^0.7.4",
    "nativescript-dev-webpack": "^0.17.0",
    "tslint": "~5.11.0",
    "typescript": "~2.7.2"
  },
  "readme": "NativeScript Application"
}
```

Here is the log output while running: ```tns run android --log trace```
https://gist.github.com/alereisan/cdd27d6ea6df48f6879957251d97f2ab

**Comment by NickIliev** [comment] 2018-11-09 11:12
@alereisan the issue might be caused by an error in the code that prevents the compiling. Or for a number of other reasons. Closing as du0plicate to [https://github.com/NativeScript/nativescript-cli/issues/4029](https://github.com/NativeScript/nativescript-cli/issues/4029)

**Comment by djokone** [comment] 2018-11-13 14:07
@alereisan, I've had the same problem, and it was the Firebase Crashanalytics plugin who's not compatible with the Android Runtime 5.0. Try to take it off.

in your firebase.nativescript.json : 
...
"crashlytics": false,
...

rm -rf nodes_modules
npm i

**Comment by alereisan** [comment] 2018-11-13 14:52
@djokone Yes thanks, I figured out yesterday that it was related with firebase and I completely disabled firebase for now.

**Comment by NickIliev** [comment] 2018-11-14 15:53
Issue moved to [NativeScript/nativescript-cli #4138](https://github.com/NativeScript/nativescript-cli/issues/4138) via [**ZenHub**](https://www.zenhub.com/)

**Closed by NickIliev** 2018-11-14 15:53 UTC

**Comment by delino12** [comment] 2019-04-11 16:46
I don't have any of these and still i'm having the same issue, I trying run on Nokia 1 device which android version is 8.1.0 and it worked fine but when i try to build on Tecno LA7 which android version is 8.1.0

**Comment by delino12** [comment] 2019-04-11 17:12
Solved. It was the device storage issues. It was trying to install the staging app on the device. I had to check the device once again to discover this. Delete some files or uninstalled some apps and trying running your platform again you should see your app.
