### ISSUE TITLE
[iOS] TabView does not resize when status bar changes height.

### ISSUE THREAD

**Issue by aleph1** [NativeScript/NativeScript#6979] opened 2019-03-02 03:46 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.2.0
 - Cross-platform modules: 5.2.2
 - Android Runtime: 5.2.0
 - iOS Runtime: 5.2.0
 - Plugin(s): 

**Describe the bug**
I am using a TabView as a direct child of a Page. When I open another application that uses location services and switch back into my app the TabView strip is pushed past the bottom of the screen due to the change in the status bar height. This is the taller status bar that appears in these cases.

![lluwh](https://user-images.githubusercontent.com/485722/53676670-98902580-3c73-11e9-84b4-15e072154250.png)

I can provide a sample image of the issue if needed.

**To Reproduce**
Open any app that uses location services in the background (Nike Run Club, Google Maps), and navigate back to the application built with NativeScript. This is occurring on device, iPhone 8 but I don't have another physical device to test on.

**Expected behavior**
The TabView height should adjust so that the tabs are not pushed past the bottom of the screen.

**Comment by tsonevn** [comment] 2019-03-04 05:43
Duplicate of https://github.com/NativeScript/NativeScript/issues/6917

**Closed by tsonevn** 2019-03-04 05:43 UTC
