### ISSUE TITLE
Implement CSS Box Shadow

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#550] opened 2015-08-04 03:32 UTC
Would be great to see a CSS3 style box shadow for UI elements.

Possible implementation:
`box-shadow: none|h-shadow v-shadow blur spread color |inset|initial|inherit;`

**Comment by mischah** [comment] 2015-12-15 22:23
Would love to have this too. 
Is this on the roadmap? Since #191 is closed.

**Comment by jlooper** [comment] 2015-12-16 01:21
I'd like to see this too, to make nice looking card interfaces. Pretty!

**Comment by lyonzy** [comment] 2015-12-16 10:56
If anyone's interested, I've discovered this sort-of-hack:
`view.android.setBackgroundResource(android.R.drawable.dialog_holo_light_frame)`
which gives an alright drop shadow on Android.

However add my +1 to this as well, it would be great to have a customisable, cross platform solution!

**Comment by aliatsis** [comment] 2015-12-28 20:10
+1

**Comment by tiagordc** [comment] 2016-01-07 08:27
+1

**Comment by andreyluiz** [comment] 2016-01-12 14:22
+1

**Comment by shantamg** [comment] 2016-01-16 22:28
+1

**Comment by gabrielbiga** [comment] 2016-02-01 02:37
+1

**Comment by arnolduis** [comment] 2016-02-13 21:14
+1

**Comment by ljx0517** [comment] 2016-02-24 16:22
+1

**Comment by treio** [comment] 2016-03-04 23:57
+1

**Comment by burkeholland** [comment] 2016-03-13 20:25
+1

**Comment by Premitium** [comment] 2016-03-15 09:28
+1

**Comment by k3yb0ardn1nja** [comment] 2016-03-29 16:13
+1

**Comment by TheOriginalJosh** [comment] 2016-04-01 11:56
+1

**Comment by kamilmac** [comment] 2016-04-12 18:02
+1

**Comment by vjoao** [comment] 2016-04-19 17:52
+1

**Comment by hekigan** [comment] 2016-05-09 03:08
+1

**Comment by theBEERd** [comment] 2016-05-10 02:00
+1

**Comment by Alphmega** [comment] 2016-05-12 06:17
+1

**Comment by yezarela** [comment] 2016-05-20 11:28
+1

**Comment by abinici** [comment] 2016-05-24 07:59
I've found out how to achieve the box shadow effect on iOS, for example on a TextField:

```
    import {Color} from "color";
    import * as view from "ui/core/view";
    ...
    let myTextField = view.getViewById(this.page, 'myTextField');
    myTextField.ios.layer.masksToBounds = false;
    myTextField.ios.layer.shadowOpacity = 1.0;
    myTextField.ios.layer.shadowRadius = 0.0;
    myTextField.ios.layer.shadowColor = new Color('#000000').ios.CGColor;
    myTextField.ios.layer.shadowOffset = CGSizeMake(2.0, 2.0);
```

In order to reference this field from code you need to give the element an ID:

```
    <TextField id="myTextField"></TextField>
```

If you use TypeScript then you'll also need to declare some iOS-specific functions:

```
    declare var CGSizeMake: any;
```

**Comment by gabrielbiga** [comment] 2016-05-29 06:11
@abinici is there some Android implementation?

**Comment by abinici** [comment] 2016-05-29 18:13
@gabrielbiga, look higher up in this thread, @lyonzy suggests a solution for Android.

**Comment by elinswilberg** [comment] 2016-06-26 20:40
+1

**Comment by maddy2get** [comment] 2016-07-28 01:08
+1

**Comment by IvRRimum** [comment] 2016-08-09 18:26
+1

**Comment by Hirbod** [comment] 2016-08-10 12:19
+1

**Comment by chief10** [comment] 2016-08-18 16:09
+1

**Comment by SjurWarEagle** [comment] 2016-08-22 16:55
+1

**Comment by spstratis** [comment] 2016-08-31 19:18
@lyonzy is it possible to adjust the color using your work around?

**Comment by lyonzy** [comment] 2016-09-01 00:14
You can, but it's not super easy. You can either find another inbuilt drawable (instead of `dialog_holo_light_frame`) that does what you want, or make your own 9-patch pngs. If you create your own, you can start with one of the inbuilt ones (these are open source so they're usually available online) and tweak the colours, then add it to your apk and use it. Unfortunately though it doesn't play well with NativeScript Livesync, since they need to be built into the apk, so make sure you rebuild and redeploy.

**Comment by edelvalle** [comment] 2016-09-06 09:44
+1

**Comment by valentinstoychev** [comment] 2016-09-06 10:30
Thank you, everyone, for all the +1 and the comments! This issue is not implemented currently for two main reasons:
 - shadows are not part of the native design guidelines
 - it will be very very slow (that is why it is mostly excluded from the design guidelines from Apple, Google, and Microsoft)


Given those two above, what would be the scenario to help us raise the priority on this issue? Why you struggle because of this missing functionality?

**Comment by edelvalle** [comment] 2016-09-06 10:41
Because the TextField sets a underline shadow color that is different from the App theme; and looks bad.... So if I could tell, android, for example... hey I want this color in the theme color will be great.

**Comment by valentinstoychev** [comment] 2016-09-06 10:59
hey @edelvalle - what you described smells more like a bug. Can you please provide a screenshot?

**Comment by lyonzy** [comment] 2016-09-06 11:03
Aren't shadows a big part of Material Design?

**Comment by lyonzy** [comment] 2016-09-06 11:04
https://material.google.com/material-design/elevation-shadows.html

**Comment by valentinstoychev** [comment] 2016-09-06 11:10
@lyonzy - this is a good point! We are getting these shadows out of the box from the underlying native elements that implement the material design (in Android).

Do you want to be able to modify these shadows?

What about iOS - is there a real scenario there?

**Comment by lyonzy** [comment] 2016-09-06 12:02
Ah ok - I should admit I haven't used {N} in a few months so I haven't tried lollipop elements. For iOS it's probably alright but I'm not that far into my project yet :)
As for modification, perhaps if we can use the android inbuilt ones it's not necessary. I'm not actively using NativeScript at the moment so I'll have to defer to some one the +1s above :P

**Comment by edelvalle** [comment] 2016-09-06 12:08
@valentinstoychev ohh sorry, this is not what I'm talking about.... I'm talking about this.

![](https://s22.postimg.org/c86d6w2b5/Captura_de_pantalla_2016_09_06_14_05_43.png)

Do you see the blue underline in the TextField? How do I change that color?

**Comment by tsonevn** [comment] 2016-09-10 11:34
Hi @edelvalle,
You could change the blue color by setting the appropriate colors in your colors.xml files in `app/App_Resources/Android/values` and in `app/App_Resources/Android/values-v21`. You should change color value of `ns_accent`. I am attaching  example:

main-page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" >
  <StackLayout>
    <TextField id="textFieldid" hint="Sample text" text="" />
  </StackLayout>
</Page>
```
`app/App_Resources/Android/values/colors.xml`
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ns_primary">#F5F5F5</color>
	<color name="ns_primaryDark">#757575</color>
	<color name="ns_accent">#0d0d0d</color>
    <color name="ns_blue">#272734</color>
</resources>
```
`app/App_Resources/Android/values-v21/colors.xml`
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
	<color name="ns_accent">#0d0d0d</color>
</resources>
```
 related with issue: [#1698](https://github.com/NativeScript/NativeScript/issues/1698)

I hope this is applicable for you.

**Comment by djlugade** [comment] 2016-10-02 10:25
+1

**Comment by joshcomley** [comment] 2016-11-29 01:48
+1

**Comment by timricker** [comment] 2016-12-03 10:15
+1

**Comment by CodeXtinction** [comment] 2016-12-15 17:47
+1

**Comment by maddy2get** [comment] 2016-12-31 12:07
+1

**Comment by llcan1120** [comment] 2017-01-07 16:02
+1 useful in many scenarios

**Comment by vtvz** [comment] 2017-01-10 18:43
+1

**Comment by viniciodeltoro** [comment] 2017-01-10 23:43
+1

**Comment by haschu** [comment] 2017-01-12 18:05
+1

**Comment by tybeck** [comment] 2017-01-21 06:34
+1

**Comment by tskweres** [comment] 2017-03-09 14:45
+1

**Comment by lukeramsden** [comment] 2017-03-29 15:53
Any chance of this being done?

**Comment by Habeeb-mohamed** [comment] 2017-03-30 08:28
+1

**Comment by danieloprado** [comment] 2017-04-01 03:05
+1

**Comment by BenGermany** [comment] 2017-04-04 10:08
+1

Don't understand why this is not implemented but a property. Since years the box-shadow is a necessary feature of nearly everything in graphics design, and shadows might be expensive on very bad hardware, but never - never - on actual hardware! Never it would be very very slowly, in maybe  0.5 percent of devices it just could be eventually?! There are 1000 other things for developers to break the resources of such minimal hardware. I have never seen a device that was slowly because of shadows. 

Every modern UI have (box) shadows about 10 years?? How could I ever use z-axis without? That's annoying.

**Comment by talatccan** [comment] 2017-05-14 02:51
+1

**Comment by lukeramsden** [comment] 2017-05-14 02:53
Please stop commenting +1, we have GitHub reactions for that.

**Comment by caiusCitiriga** [comment] 2017-05-14 21:56
+1

**Comment by 0mkara** [comment] 2017-05-30 19:25
+1

**Comment by silent-coder** [comment] 2017-05-30 19:27
+1

**Comment by xsilen** [comment] 2017-06-01 04:50
Please stop commenting +1, we have GitHub reactions for that.

**Comment by silent-coder** [comment] 2017-06-01 10:47
+1

**Comment by Pinny3** [comment] 2017-06-20 07:39
Need this as soon as possible

+1

**Comment by purplerune** [comment] 2017-06-26 14:02
+1

**Comment by Jaishankarb** [comment] 2017-07-05 15:19
any update on this issue

**Comment by renatograel14** [comment] 2017-07-17 14:56
+1

I'm trying to use setElevation() (Android.View). No success for while ;/ 

`let buttonView = this.addButton.`
`buttonView.android.setElevation(new java.lang.Float("50"));`


`let buttonView = this.addButton.`
`buttonView.android.setElevation(50);`

**Comment by silent-coder** [comment] 2017-07-29 13:34
+1

**Comment by anhtuan9113** [comment] 2017-07-29 18:46
+1

**Comment by Macarthurval** [comment] 2017-08-05 04:39
+1

**Comment by ChangJoo-Park** [comment] 2017-08-12 08:39
+1

**Comment by AdityaChoudhary** [comment] 2017-08-17 05:45
+1

**Comment by basketofsoftkittens** [comment] 2017-08-19 05:00
+1

**Comment by mrhirsch** [comment] 2017-09-14 05:50
+1

**Comment by ucfan** [comment] 2017-09-19 14:53
+1

**Comment by sergebruni** [comment] 2017-09-19 18:35
+1

**Comment by airandfingers** [comment] 2017-09-20 20:24
+1

**Comment by silent-coder** [comment] 2017-09-22 12:42
+1

**Comment by Saadoosh8** [comment] 2017-09-24 05:36
1+

**Comment by yamaoto** [comment] 2017-10-05 00:30
+1

**Comment by Nurgunkalol** [comment] 2017-10-05 05:23
+10

**Comment by kalininskiy** [comment] 2017-10-05 05:24
+1

**Comment by berardo** [comment] 2017-10-15 02:43
In the meantime, for those who work with Angular, I've created a directive that deals with native shadows according to material design guidelines (even for iOS).
It can be as easy as a simple attribute:
```html
<Label shadow="2"></Label>
```
If you guys want to check it out: https://github.com/Especializa/nativescript-ng-shadow

**Comment by silent-coder** [comment] 2017-10-29 15:09
+1

**Comment by mathieuwinn** [comment] 2017-11-16 18:42
+1 definitely a must-have

**Comment by GrEg00z** [comment] 2017-11-20 17:12
@berardo  : you plugin not compile, we get this error at pre-compilation :

https://github.com/Especializa/nativescript-ng-shadow/issues/4

**Comment by bnussey** [comment] 2017-12-08 22:33
+1

**Comment by mudlabs** [comment] 2018-01-22 05:50
@abinici Can you apply shadow to the StackLayout view? 

I can't get it to work on anything other than a Label, which only works if there's no borderRadius. Or on a TextField, But that's always inset.

I'm trying to make a card that floats, a bit like the ones in the Today tab in the App Store (mobile).

**Comment by schoettler** [comment] 2018-03-04 19:15
+1

**Comment by reworking** [comment] 2018-03-09 18:15
+1

**Comment by suisseworks** [comment] 2018-05-01 14:38
+1

**Comment by surafel-nigussie** [comment] 2018-05-29 13:28
+1

**Comment by bhavincb** [comment] 2018-06-07 08:57
+1

**Comment by laimonas** [comment] 2018-06-07 09:32
This is essential for good looking UI.

**Comment by ogmedia** [comment] 2018-06-07 09:38
The nativescript-cardview plugin did it for me in the meantime.

**Comment by bhavincb** [comment] 2018-06-19 10:55
+1

**Comment by slasho** [comment] 2018-06-20 16:19
+1

**Comment by neillin** [comment] 2018-07-07 21:30
+1

**Comment by Tyg-g** [comment] 2018-07-09 12:29
I propose to implement a simplified alternative to CSS3 box-shadow:

    box-shadow: none | shadow

When shadow is on , it uses the system-implemented shadow keeping the native UI look.

**Comment by tsili852** [comment] 2018-07-10 13:38
+1

**Comment by silent-coder** [comment] 2018-07-15 08:54
+1

**Comment by zeesulehria** [comment] 2018-07-23 20:56
we can use shadow plugin but in some cases its result is not as what we desire so if it is possible to add css support then its a massive advantage .

**Comment by karim007** [comment] 2018-07-25 17:34
+1

**Comment by clrh** [comment] 2018-07-27 07:50
+1

**Comment by RichardM99** [comment] 2018-07-31 15:31
+1

**Comment by tomcatmwi** [comment] 2018-07-31 23:06
+0.99999894
Sorry I use an old Pentium!

**Comment by IAMtheIAM** [comment] 2018-08-03 16:30
Until its supported natively, use [nativescript-ng-shadow](https://github.com/Especializa/nativescript-ng-shadow)

**Comment by silent-coder** [comment] 2018-08-06 08:32
When will this be natively supported, asking for a friend...

**Comment by kefahB** [comment] 2018-08-08 09:27
👍

**Comment by papmodern** [comment] 2018-08-24 03:04
+1

**Comment by vondritz** [comment] 2018-08-29 09:51
we need this please

**Comment by Tarens2** [comment] 2018-08-30 13:57
+1

**Comment by jofftiquez** [comment] 2018-09-04 12:35
@leocaseiro +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1

**Comment by EddyVerbruggen** [comment] 2018-09-04 12:42
There's a 👍"reaction" icon at the first post ⬆️ up there. Use that to upvote instead of spamming every subscriber of this thread with a comment. Thanks!

And to get notificed of changes/comments, hit that "Subscribe" button at the right, near the top:
<img width="237" alt="screenshot 2018-09-04 at 14 41 39" src="https://user-images.githubusercontent.com/1426370/45031948-a82a0b00-b050-11e8-8a43-449d5e71dc08.png">

**Comment by silent-coder** [comment] 2018-09-12 11:50
+1

**Comment by mojimi** [comment] 2018-11-20 17:32
Really could use this, specially for non-angular users as the only plugin is for angular...

**Comment by eric-blue** [comment] 2018-11-20 17:47
For those wondering, I was able to hack a solution out of this: 
https://github.com/bradmartin/nativescript-cardview

Basically, make every element that needs a shadow into a card.

**Comment by EddyVerbruggen** [comment] 2018-11-20 19:13
@eric-blue OMG that's actually a very good idea!

For iOS, `<CardView radius="3" shadowRadius="3" shadowOpacity="0.2" shadowOffsetHeight="0">` gives me this nice subtle shadow (which extends into the dark searchbar) to enhance the 'splitview' experience (on the left there's a scrollable list, on the right the details). Thanks! 💯 

![simulator screen shot - ipad pro 9 7-inch - 2018-11-20 at 20 08 34](https://user-images.githubusercontent.com/1426370/48796604-56fcef80-ed00-11e8-971e-244497eb27f3.png)

**Comment by TheOriginalJosh** [comment] 2018-11-22 14:50
@edusperoni and I have been maintaining a fork of the [nativescript-ng-shadow](https://github.com/Especializa/nativescript-ng-shadow) project that is bundled with ng-packagr so that it is compatible with bundling and aot. 

https://github.com/TheOriginalJosh/nativescript-ngx-shadow
https://www.npmjs.com/package/nativescript-ngx-shadow

**Comment by mojimi** [comment] 2018-11-23 11:14
nativescript-cardview is nice but doesn't work with border-radius, so no round buttons.

**Comment by eric-blue** [comment] 2018-11-24 02:13
@mojimi give the param `radius` a try. 

From the docs: https://github.com/bradmartin/nativescript-cardview

> The default values are set to:
>radius = 2;
>shadowOffsetWidth = 0;
>shadowOffsetHeight = 2;
>shadowColor = new Color('#000').ios
>shadowOpacity = 0.4;
>shadowRadius = 1;

**Comment by sitefinitysteve** [comment] 2018-12-19 15:34
Nobody vote 👎

**Comment by tjvantoll** [comment] 2018-12-19 16:03
I support 👍, but I’ll add that—since you’ve done some research here—a write up on 😕 would be super useful. Maybe even, I don’t know, a Marketplace code sample that shows a few of the options live 😉

**Comment by edusperoni** [comment] 2018-12-19 16:16
@EddyVerbruggen IIRC, setting elevation on Android screws with the border-radius from Nativescript. We had to work around this on [ngx-shadow](https://github.com/TheOriginalJosh/nativescript-ngx-shadow).

I've already looked at this issue and couldn't find a solution that would fit all.

Currently, ngx-shadow generates consistent shadows across platforms. This was one of the main reasons we forked the project from ng-shadow. We do this by doing the following:

## Android
- Creates 2 background classes extending: LayerDrawable for when we have an existing background and want to copy border-radius and etc. GradientDrawable for setting a simple background with border-radius.
- Extract border-radius from the view style and apply to a mask
- Add this mask to the layer along with the original background
- Set elevation, translationZ and StateListAnimator
- Some monkey patching so to not mess with Nativescript's background logic

Without LayerDrawable, setting elevation does not cast shadows on most of NS views.

## iOS
- Wrap the element with StackLayout
- Apply shadow layer options to this StackLayout
If you don't do this, elements inside the original element get individual shadows

----

An elevation property would probably be the best fit, but there are some inherent changes that must be made to make sure they look the same on both platforms.

I'm willing to help develop this feature

**Comment by farfromrefug** [comment] 2018-12-19 19:52
@edusporini have you tried with outline on android? this should work perfectly on post Lollipop and allow for all kind of transformation. should be dead easy to make it to work with border radius. Done it in another framework.
[explanation](https://blog.usejournal.com/playing-with-elevation-in-android-91af4f3be596)

**Comment by edusperoni** [comment] 2018-12-19 20:04
@farfromrefug that could work, have to see how it interacts with the rest of NS clipping/etc.

Some views (without a shape) don't work just by setting elevation :(

**Comment by farfromrefug** [comment] 2018-12-19 20:17
@edusperoni can you give an example of view failing?

**Comment by edusperoni** [comment] 2018-12-19 20:41
@farfromrefug 
Check the just-elevation branch. https://github.com/edusperoni/nativescript-ngx-shadow/tree/just-elevation

Run `npm i && tns run android --syncAllFiles`

I've commented out everything about replacing the background, all I'm doing is: `nativeView.setElevation()`. It works for button, doesn't work for any other view.

**Comment by edusperoni** [comment] 2018-12-19 21:34
Ok, I got it working with outline!

This is how to do it:

```
const MyProvider = android.view.ViewOutlineProvider.extend({
  getOutline: function(view, outline) {
    const outerRadii = Array.create("float", 8);
    outerRadii[0] = outerRadii[1] = Length.toDevicePixels(30, 0);
    outerRadii[2] = outerRadii[3] = Length.toDevicePixels(30, 0);
    outerRadii[4] = outerRadii[5] = Length.toDevicePixels(0, 0);
    outerRadii[6] = outerRadii[7] = Length.toDevicePixels(0, 0);
    const test = new android.graphics.Path();
    test.addRoundRect(new android.graphics.RectF(0, 0, view.getWidth(), view.getHeight()), outerRadii, android.graphics.Path.Direction.CW)
    test.close();
    // outline.setRoundRect(0, 0, view.getWidth(), view.getHeight(), view.getHeight() / 2);
    outline.setConvexPath(test);
  }
})
```

this allows a 30 topleft,topright border-radius and 0 bottomleft,bottomright radius. Then just set it as the outline provider and it's good to go.

Worth noting that we have to work around some views that already provide outlines (like button). Probably something like .getOutline().isEmpty() should do the trick.

I'll try to work on it tomorrow. If everything goes right I'll open a PR to nativescript-ngx-shadow.

**Comment by edusperoni** [comment] 2018-12-19 22:14
Couldn't wait until tomorrow 😃  I've just updated my branch:
https://github.com/edusperoni/nativescript-ngx-shadow/tree/just-elevation

With this I can create a ViewOutline passing the current view as owner. It detects border-radius correctly and sets the outline as it should.

Things we could probably optimize/improve:

- do we need to calculate the outline every time getOutline is called? If we cache it, how to properly detect changes? (maybe storing width, height and each radius)
- detect when we don't need to set an Outline (button gets bugged). Maybe by doing view.getBackgroun().getOutline() and checking if it's empty?
- **we could make BorderDrawable return the correct outline by overriding [getOutline](https://developer.android.com/reference/android/graphics/drawable/Drawable#getOutline(android.graphics.Outline))** <- this is probably the best approach, as the default outline providers checks this

**Comment by edusperoni** [comment] 2018-12-20 01:17
PR is out!

With this, we just have to check is if all views that have shadow must have backgrounds (maybe create transparent BorderDrawables if they don't?)

Is overriding the StateListAnimator out of the scope? (if the view is tappable, we can make it behave like the button)

@EddyVerbruggen Should we move this discussion to a [WIP] PR? Or slack, maybe

**Comment by EthanSbbn** [comment] 2019-02-06 14:01
+1

**Comment by demetrio812** [comment] 2019-02-21 23:33
Hello, is the PR stuck for some reason?

**Comment by xitude** [comment] 2019-03-20 01:37
+1

**Comment by bundyo** [comment] 2019-05-10 10:01
This issue seems improperly closed by the bot, as only Android implementation landed?

**Comment by alexziskind1** [comment] 2019-05-17 02:45
Should this issue be closed? The iOS version hasn't been implemented

**Comment by dschniepp** [comment] 2019-05-17 23:10
@manoldonev was this issue closed accidentally, as iOS is not implemented yet? Thank you for clarification.

**Comment by manoldonev** [comment] 2019-05-23 13:56
@dschniepp yup, reopened it now

**Comment by AdamAtri** [comment] 2019-06-27 21:51
on ios this works for me:
```javascript
function _iosShadow(view:UIView, options:ShadowOptions):boolean {
  const {radius, offsetX, offsetY, color, opacity} = options
  view.layer.shadowRadius = radius;
  view.layer.shadowOffset = CGSizeMake(offsetX, offsetY);
  view.layer.shadowColor = 
    color == 'black' ? UIColor.blackColor.CGColor :
    color == 'blue' ? UIColor.blueColor.CGColor : UIColor.grayColor.CGColor;
  view.layer.shadowOpacity = opacity;  
  return true;
}
```

**Comment by vahidvdn** [comment] 2019-07-29 08:17
Any plan for iOS implementation?

**Comment by cherimo** [comment] 2019-08-07 20:37
The designs that you can create with shadows effect is substantial, Really looking forward to this.. ps: Thx for the amazing NativeScript library ❤️

**Comment by elvticc** [comment] 2019-08-20 12:11
+1

**Comment by octavvartan** [comment] 2019-09-13 14:18
+

**Comment by OPADA-Eng** [comment] 2019-10-08 12:42
any news?

**Comment by darkyelox** [comment] 2019-10-29 19:29
For me is worrying that the more I use NativeScript the more I see issues like this unclosed, there are plenty of required features that are ignored

**Comment by Smiley01987** [comment] 2019-11-04 13:12
How is this issue still open?

**Comment by MrSnoozles** [comment] 2019-12-02 12:11
The roadmap at https://www.nativescript.org/roadmap-and-releases#roadmap says more CSS properties are planned for 2019. I really hope this includes box shadow as it's crucial to implement most designs. NativeScript is a wonderful technology ❤️ but a lot of times it's frustrating to implement interface designs because of the limited CSS support

**Comment by thd-fox** [comment] 2020-01-30 19:48
Is there any progress on this? -push-

**Comment by alqabali** [comment] 2020-05-02 07:54
any news?

**Comment by vahidvdn** [comment] 2020-06-11 11:05
@NathanWalker Any idea in order to make this work for both iOS and Android? (Since there is a new team and maybe new roadmaps)

**Comment by rigor789** [comment] 2020-06-11 11:10
@vahidvdn I'm 💯 for adding shadows that work for both platforms, however last time I checked, customizing the shadows on Android is very limited to the elevation property. 

I do think we should figure out a clever way to support both platforms using the standard css syntax, and try to find the closest match of elevation on Android until there's proper shadow support. This wouldn't be perfect though.

**Comment by iamabs2001** [comment] 2020-06-11 11:55
Nativescript will be more powerful if we get almost all css properties in nativescript.
😀🔥

**Comment by vahidvdn** [comment] 2020-06-11 14:12
@rigor789 Thanks. I think this is the most favorite feature that almost all of the nativescripters really love it and waiting for it.

**Comment by Tyler-V** [comment] 2020-06-16 17:24
This would be awesome! +1

**Comment by steve-79** [comment] 2020-08-25 21:07
+1

**Comment by kennethkeim** [comment] 2020-09-01 13:38
Is there any estimate of when this might be a thing? We aren't deploying our app right away so can afford to wait for a bit, if someone could tell me if it's a few months out or more like a year, that would be super helpful.

Thanks to all of you who maintain NativeScript. ❤️

**Comment by kan101** [comment] 2020-09-25 20:04
They are busy pushing support for Angular 10 but ignoring such basic popular features.

**Comment by NathanWalker** [comment] 2020-09-26 01:06
Agreed here - we have often implemented this in angular projects via directives - will bring up in next weeks TSC meeting to put on the plan for 7.1 or shortly after, would be nice to close the loop here.

**Comment by oslc15** [comment] 2020-10-23 05:19
@NathanWalker any news on this from the TSC meeting? :)

**Comment by NathanWalker** [comment] 2020-10-23 05:28
Yes we are putting this on the 8.0 plan for sure however there may be an option to introduce in 7.x series.

**Closed** 2021-04-02 23:46 UTC
Labels: css, ux

**Comment by alexgritton** [comment] 2021-04-10 21:06
@NathanWalker I've noticed the box shadow disappears when a border-radius is applied. Is this the expected behavior for box shadows right now?

**Comment by NathanWalker** [comment] 2021-04-10 22:31
Hey @alexgritton thats correct we are adding combined with border radius in 8.1.

**Comment by PetroSuch** [comment] 2021-05-12 07:26
<FlexboxLayout width="200" height="200" style="box-shadow: 0 0 5px rgba(0, 0, 0, 0.8);" >

i add it to my code, but i still can not see box-shadow 
use  "@nativescript/core": "~8.0.0"

**Comment by PetroSuch** [comment] 2021-05-13 06:59
i also downloaded your demo project, but box-shadow doesnt work there too 
https://github.com/williamjuan027/nativescript-movies-demo

**Comment by cascading-jox** [comment] 2021-12-11 15:39
I can't see it either. I just cloned [nativescript-movies-demo](https://github.com/williamjuan027/nativescript-movies-demo) and ran `tns run android`. I see no box-shadow on any element. 
![Screenshot from 2021-12-11 16-37-01](https://user-images.githubusercontent.com/8418570/145682413-ec5e73e0-8072-4597-9be9-62519ff87433.png)
