### ISSUE TITLE
Input blocked by empty area in UI element

### ISSUE THREAD

**Issue by thomaspaniagua** [NativeScript/NativeScript#4535] opened 2017-07-10 00:17 UTC
Hey, so I'm trying to have a custom navbar in my app, placed at the bottom. I'm trying to use a dock layout that spans the whole screen on top of my actual UI and then setting the dock of my navbar to bottom, this works well visually, but since the DockLayout is technically on top of the rest of my UI, my UI doesn't receive input even if the area on the DockLayout is empty. 
Is this expected behavior? If so what would be a good way to propagate the input to lower layers of ui?

**Comment by thomaspaniagua** [comment] 2017-07-10 00:17
Using NS 3.0 and happens on iOS and Android

**Comment by NickIliev** [comment] 2017-07-10 06:50
@thomaspaniagua this is expected as by your structure the DockLayout (although mainly empty) is on top and all events propagate through it. There are several plugins resolving the matter with bottom toolbar/navigation which you can use tho resolve this issue. You can also see how the problem is tackled in this blog post: [NativeScript: How to create a fixed bottom navigation](https://notes.devlabs.bg/nativescript-how-to-create-a-fixed-bottom-navigation-bfe8b059ad1e)

**Closed by NickIliev** 2017-07-10 06:50 UTC
Labels: T:Question
