### ISSUE TITLE
TextView formattedText binding undeifned

### ISSUE THREAD

**Issue by cdev38399** [NativeScript/NativeScript#6161] opened 2018-08-08 04:39 UTC
### Tell us about the problem
Textview formattedText binding failed => TypeError: undefined is not an object (evaluating 'formattedString.parent.textTransform')

### Which platform(s) does your issue occur on?
both but mostly iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0
- Cross-platform modules: tns-core-modules@4.2.0
- Runtime(s): android@4.1.3, iOS@4.1.1
- Plugin(s): 	
````
"dependencies": {
		"moment-timezone": "^0.5.17",
		"nativescript-background-http": "^3.2.7",
		"nativescript-camera": "^4.0.2",
		"nativescript-chatview": "^1.0.3",
		"nativescript-feedback": "^1.2.0",
		"nativescript-floatingactionbutton": "^4.1.3",
		"nativescript-iqkeyboardmanager-ns": "^1.0.3",
		"nativescript-material-icons": "^1.0.3",
		"nativescript-open-app": "^0.2.0",
		"nativescript-push-notifications": "^1.1.4",
		"nativescript-statusbar": "^4.0.1",
		"nativescript-theme-core": "~1.0.4",
		"nativescript-toasts": "^1.0.3",
		"nativescript-ui-autocomplete": "^3.7.1",
		"nativescript-ui-calendar": "^3.6.0",
		"nativescript-ui-listview": "^3.5.7",
		"nativescript-ui-sidedrawer": "^4.1.1",
		"nativescript-webview-interface": "^1.4.2",
		"tns-core-modules": "^4.2.0"
	},
	"devDependencies": {
		"babel-traverse": "6.26.0",
		"babel-types": "6.26.0",
		"babylon": "6.18.0",
		"lazy": "1.0.11"
	}
````
### Please tell us how to recreate the issue in as much detail as possible.
XML
```
<TextView fontSize="16" textWrap="true" editable="false" formattedText="{{ answer_formatted, answer_formatted, false }}" />
```
JS 
````
const formattedString = require('text/formatted-string');
const formattedSpan = require('text/span');

            let fstring = new formattedString.FormattedString();
            let fspan = new formattedSpan.Span();
            fspan.text = "anything";
            fstring.spans.push(fspan);
            answer_formatted = fstring; // attached to page binding context model
````
Running result:
````
CONSOLE ERROR file:///app/tns_modules/tns-core-modules/trace/trace.js:166:30: Binding: Binding error while setting property formattedText of TextView(483)@file:///app/views/main/main.xml:102:31;: TypeError: undefined is not an object (evaluating 'formattedString.parent.textTransform')
````

**Comment by cdev38399** [comment] 2018-08-10 01:30
@NickIliev yes, I did bound to proper observable and its just fine in Android (even not perfect). 
More detail that raise the error is when using template selector for listview multiple item template.

**Comment by NickIliev** [comment] 2018-08-20 10:10
@cdev38399 can you create [a demo Playground](https://play.nativescript.org/) ?

**Comment by mpochron** [comment] 2018-08-21 12:37
Here same.

https://play.nativescript.org/?template=play-ng&id=5y633k

**Comment by NickIliev** [comment] 2018-08-22 07:08
@mpochron the playground works on my side on both iOS and Android (prints "anything")

**Comment by mpochron** [comment] 2018-08-22 07:31
@NickIliev 
I found problem with CSS which crashes with using `width 100%` of Label with formattedString.

Updated:
https://play.nativescript.org/?template=play-ng&id=5y633k&v=2

Try it , but i dont have iphone to confirm error with app Playground.

Will be two errors:
- `TypeError: undefined is not an object (evaluating 'formattedString.parent.textTransform')`
- `JS ERROR Error: Vew not added to this instance. View: ej  CurrentParent: Label(444) ExpectedParent: Label(415)`

**Comment by NickIliev** [comment] 2018-08-22 07:44
@mpochron still not being able to reproduce the issue. Try to wrap the label in your list view template in a layout container (e.g. GridLayout or StackLayout) - [this demo ](https://play.nativescript.org/?template=play-ng&id=5y633k)is working flawlessly on my side

**Comment by NickIliev** [comment] 2018-08-28 10:35
Closing as the issue is not reproducible 0n my side with the linked Playground. Will reopen if there is a project that can reproduce the issue.

**Closed by NickIliev** 2018-08-28 10:35 UTC
Labels: needs more info, question
