### ISSUE TITLE
java.lang.NullPointerException  com.tns.gen.java.lang.Object_frnal_ts_helpers_l58_c38__EditTextListenersImpl.onEditorAction

### ISSUE THREAD

**Issue by mikloshumli** [NativeScript/NativeScript#5433] opened 2018-02-19 05:52 UTC
Google crash analytics I get this crash and I have no idea what can I do.
Devices:
Galaxy S6 Edge (zerolte)
Galaxy A5(2017) (a5y17lte)
Galaxy J5(2016) (j5xnlte)
Galaxy A3(2016) (a3xelte)
Galaxy A5(2016) (a5xelte)
Galaxy A8(2018) (jackpotlte)
S90-A (sisleyr)
Galaxy S6 (zeroflte)
P8 Lite (hwALE-H)
Galaxy A3(2017) (a3y17lte)
Liquid Z520 (acer_z520)

tns 3.4.2
typescript > 7
tns builds --bundle --env.aot --env.uglify 

Crash problem:
```
java.lang.NullPointerException
com.tns.gen.java.lang.Object_frnal_ts_helpers_l58_c38__EditTextListenersImpl.onEditorAction
```
Anybody can help me?
Thnx Miklos

**Comment by tsonevn** [comment] 2018-02-19 06:24
Hi @mikloshumli,
Could you provide some more info about the project and if you can reproduce the problem locally on your side?
It will help if you could send us the project as well as the full crash log.

**Comment by mikloshumli** [comment] 2018-02-19 08:42
Sorry but local I can't repeoduce this crash. Everything is ok Genymotion Virtual devices and htc desire nokia5 device.

My project Nativescript angular 5 and use nativescript telerik ui pro
build aot and uglify release version.

All Google crash analitycs:

java.lang.NullPointerException: 
  at com.tns.gen.java.lang.Object_frnal_ts_helpers_l58_c38__EditTextListenersImpl.onEditorAction (Object_frnal_ts_helpers_l58_c38__EditTextListenersImpl.java:45)
  at android.widget.TextView.onEditorAction (TextView.java:5633)
  at com.android.internal.widget.EditableInputConnection.performEditorAction (EditableInputConnection.java:138)
  at com.android.internal.view.IInputConnectionWrapper.executeMessage (IInputConnectionWrapper.java:364)
  at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage (IInputConnectionWrapper.java:91)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6776)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1386) 

Thanx Miklos

**Comment by NickIliev** [comment] 2018-02-22 13:17
@mikloshumli It seems that you are hitting [this known bug](https://github.com/NativeScript/NativeScript/issues/5130). The issue is fixed and the fix will be included in our next official release. You can see the linked issue for more details and [a possible temporary workaround](https://github.com/NativeScript/NativeScript/issues/5130#issuecomment-359698297),

**Comment by tsonevn** [comment] 2018-03-08 11:58
Duplicate of #5130

**Closed by tsonevn** 2018-03-08 11:58 UTC
Labels: needs more info, os: android
