### ISSUE TITLE
CSS property selector not working for GridLayout -> col+row attributes

### ISSUE THREAD

**Issue by vekexasia** [NativeScript/NativeScript#2579] opened 2016-08-13 15:51 UTC
### Which platform(s) does your issue occur on?

Probably Both (Android for sure)
### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) 2.2.0
- Cross-platform modules: (check the 'version' attribute in the
  `node_modules/tns-core-modules/package.json` file in your project) 

```
  "nativescript": {
    "platforms": {
      "ios": "2.2.0",
      "android": "2.2.0"
    }
  },
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project) 2.2.0


### Please tell us how to recreate the issue in as much detail as possible.
Write a layout having a GridLayout. 
try to apply a css to every "element" having col="1" or row="1"

```

**Comment by tsonevn** [comment] 2016-08-15 06:11
Hi @vekexasia,

Thank you for reporting your problem.
I made sample project to test the given scenario, however I was unable to reproduce problems with the GridLayout and or some of its attributes. I am attaching sample code, which you could test in your   local project. You could also read more about GridLayout [here](https://docs.nativescript.org/cookbook/ui/layouts/grid-layout). In regard to that it would help if you could give me some more info about your problem or if you could send me  sample project. 


main-page.xml

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
   <GridLayout rows="50 *" columns="150 *" backgroundColor="green" >
       <Label row="0" col="0" text="Label1" textWrap="true" backgroundColor="red" />
       <Label row="0" col="1" text="Label2" textWrap="true" backgroundColor="yellow"/>
       <Label row="1" col="0" text="Label3" textWrap="true" />
       <Label row="1" col="1" text="Label4" textWrap="true" class="lastLabelStyle"/>
   </GridLayout>
</Page>
```

app.css

```
.lastLabelStyle{
    color:red;
    background-color: blue;
}
```

I hope this helps

**Comment by vekexasia** [comment] 2016-08-15 09:39
hello @tsonevn sorry for being dump and not reporting this correctly.

What i'm saying is that you are not able to do 
```css
Label[col="1"] {
  color: red;
}
```

to select all column 1 labels.

**Comment by tsonevn** [comment] 2016-08-15 14:33
Hi @vekexasia ,
Thank you for your reply.

At the moment it is not possible to use `col` property to set style to all Views for a specific column in a GridLayout. As a temporary solution you could set custom attributes in the XML elements and then you would be able to use such a syntax in your CSS file to style elements. You could  review my sample example below.


main-page.xml

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
   <GridLayout rows="50 *" columns="150 *" backgroundColor="green" >
       <Label row="0" col="0" text="Label1" textWrap="true" backgroundColor="red" />
       <Label row="0" colAttr="1" col="1" text="Label2" textWrap="true" />
       <Label row="1" col="0" test="2" text="Label3" textWrap="true" class="lastLabelStyle"/>
       <Label row="1" colAttr="1" col="1"  test="2" text="Label4" textWrap="true" />
   </GridLayout>
</Page>
```

app.css

```
Label[colAttr='1']{
    background-color: yellow;
}
```

I hope this helps.

**Comment by toddanglin** [comment] 2017-02-02 14:46
As a follow-up, is there any way to target the Columns and Rows in a GridLayout via CSS?

There are many cases where the ability to target columns via CSS would be helpful. Example:

```
<GridLayout class="myGrid" columns="auto, *" rows="auto">
    <Label text="I'm left" col="0" />
    <Label text="I'm right" col="1" />
</GridLayout>

.myGrid[col="0"] {
   text-align: left;
}

.myGrid[col="2"]{
   text-align: right;
}
```
Achieving this today requires extra in-line styles (or custom attributes as suggested previously).

**Comment by hshristov** [comment] 2017-02-06 14:36
@toddanglin This will be supportd in modules 3.0. There we have registered row/col as properties of the View so this case will work out of the box.

**Comment by atanasovg** [comment] 2017-08-18 13:16
@hshristov Could you please confirm whether this works with modules 3.0+ and close the issue if appropriate?

**Comment by tsonevn** [comment] 2017-08-21 06:59
Hi @atanasovg,
I tested this scenario on my side and indeed this setting a style of a component via CSS while using the column and row attributes works as expected with latest NativeScript. I am attaching sample projects.
![screen shot 2017-08-21 at 9 46 40 am](https://user-images.githubusercontent.com/17448734/29507080-4d7251d2-8657-11e7-9c23-5fb35f0ae5b5.png)
![screen shot 2017-08-21 at 9 47 42 am](https://user-images.githubusercontent.com/17448734/29507081-4d74cc96-8657-11e7-948b-bdd2dcc0f3d9.png)
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1238006/Archive.zip)
[ArchiveNG.zip](https://github.com/NativeScript/NativeScript/files/1238005/ArchiveNG.zip)

**Comment by atanasovg** [comment] 2017-08-21 09:21
Great, thanks @tsonevn for the info and the sample project! I am closing this issue as it is already done.

**Closed by atanasovg** 2017-08-21 09:21 UTC
Labels: css, feature
