### ISSUE TITLE
Bugs on page https://docs.nativescript.org/angular/start/ns-setup-os-x

### ISSUE THREAD

**Issue by vslugin** [NativeScript/NativeScript#9206] opened 2021-02-10 10:52 UTC
First 

When run command `pip install six` return error because pip is not installed. In result resolved commands `brew install python; pip3 install six`

Second

Before `brew cask install <SOMETHING>` return error `Error: Unknown command: cask.
Resolved by use commands without cask: `brew install <SOMETHING>`

Both cases is not obvious for users which not used homebrew before (MacOS Big Sur)...

**Comment by flipperlite** [comment] 2021-03-04 13:35
I was looking to help out and update these documents since I've recently run these commands on two different Macs (Intel and Apple Silicon) and at two different times (last month and two days ago). I'm not an expert in homebrew, environment variables, zsh versus bash, TNS, or the intended/recommended direction of `tns doctor`. A number of issues were encountered.

On the Intel (MBP early 2015), I installed the NodeJS LTS 14 version instead of running through homebrew. I don't think it would have mattered because homebrew 2.7.5 had `HOMEBREW_PREFIX: /usr/local` when running `brew config`. With that prefix, node would have installed to the same location. Command `which node` returns `/usr/local/opt/node@14/bin/node`. On the M1 (MBA late 2020), I tried to follow the instructions on the page in question installing homebrew, node, pods, SDK, etc. and the documentation should explicitly call out additional commands that should be run after commands are executed like `echo 'eval $(/opt/homebrew/bin/brew shellenv)' >> ~/.zprofile`. The terminal also seems to be using zsh versus bash now and I'm not even sure what the difference is. The M1 still has python version 2.7.16 which required `sudo easy_install pip==20.3.4` to install `pip install six`. Homebrew 3.0.4-8-gb024954 (last commit 2021-03-03) config has `HOMEBREW_PREFIX: /opt/homebrew`. The issue is that `tns doctor` looks to be expecting the Android SDK and sdkmanager to be installed in `/usr/local/share/android-sdk` and `/usr/local/bin/sdkmanager` respectively. I'm also aware of other issues with the M1 chip and TNS https://gist.github.com/shirakaba/87aabee6e2ec70e298e3d7c42f701675. I'm not confident enough to resolve the difference in installation directories given the change in homebrew config and how it should match to `tns doctor`. Net, I was able to get the Intel Mac to run TNS but the M1 is busted.

Given the many variables and complex issues, I think it's going to require someone with more experience to update the documentation especially with the M1.

**Comment by medoalmdar** [comment] 2021-03-20 07:43
![Screenshot_20200604_103836_com facebook katana](https://user-images.githubusercontent.com/79682777/111862878-8922c880-8971-11eb-8528-dc829fb61fb9.jpg)

**Comment by medoalmdar** [comment] 2021-03-20 07:45
I take this photo in video from Facebook but i can't find this video anymore can someone help me

**Comment by medoalmdar** [comment] 2021-03-20 07:45
Help

**Comment by janoshrubos** [comment] 2021-09-06 08:28
Thank you for your issue!

Closing this since in the [new docs](https://docs.nativescript.org/environment-setup.html#macos-ios) the environment setup had been rewritten with fixes.

**Closed by janoshrubos** 2021-09-06 08:28 UTC
Labels: help wanted, good first issue
