### ISSUE TITLE
Unexpected keyword 'function' on iOS

### ISSUE THREAD

**Issue by debevv** [NativeScript/NativeScript#5154] opened 2017-12-10 16:33 UTC
Execution with `tns run ios` on iOS 10.3 device emulator produces
```
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10bb3ebc8 -[TNSRuntime executeModule:referredBy:]
2   0x10b4c08c1 main
3   0x11084d65d start
JavaScript stack trace:
1   @file:///app/login.js:20:22
JavaScript error:
file:///app/login.js:20:22: JS ERROR SyntaxError: Unexpected keyword 'function'
```
with this code (first line is line 20 in the error):
```
login.facebookLoginButton = async function() {
    var result = await new Promise((resolve, reject) => {
        fbApi.login((error, data) => {
            if(error)
                reject(error)
            else
                resolve(data)
        })
    })
}
```
and the application freezes.

### Which platform(s) does your issue occur on?
iOS 10.3 on device emulator  
Xcode 8.3.3, macOS Sierra
This is not happening on Android.

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.3.1
- Cross-platform modules: 3.3.0
- Runtime(s):  ios: 3.3.0, android: 3.4.0-2017-10-31-1
- Plugin(s): 
```
"dependencies": {
		"moment": "^2.19.3",
		"nativescript-facebook": "^2.0.1",
		"nativescript-localize": "^2.0.5",
		"nativescript-pro-ui": "^3.2.0",
		"nativescript-theme-core": "~1.0.2",
		"tns-core-modules": "~3.3.0"
	},
	"devDependencies": {
		"babel-traverse": "6.26.0",
		"babel-types": "6.26.0",
		"babylon": "6.18.0",
		"lazy": "1.0.11"
	}
```
I guess it is something about the `async` keyword, because this is the first encounter in the execution flow of my app, and when I tried to change `function()` with `() =>` it started complaining about token `=>`

I also noticed that CocoaPods is forcing my iOS Deployment Target to 8.0. Hoping that the error was caused by the missing support for ES6 in older versions of iOS, I tried to change it to 10.3 on Xcode, but the result it's the same.

**Comment by NickIliev** [comment] 2017-12-11 06:54
@debevv NativeScript is using ES5 so it is expected that some ES6 related features won\t work.
You can use TypeScript as from version 2.x.x TS is supporting await/async syntax and the code with being transpiled to ES5 which is the target for a NativeScript application. More about this can be found [here](https://www.nativescript.org/blog/use-async-await-with-typescript-in-nativescript-today) and [here](https://github.com/NativeScript/NativeScript/issues/1611).

Please do le mt know more about the second issue you are describing - can you clarify what do you mean by **_" CocoaPods is forcing my iOS Deployment Target to 8.0."_**. Is specific CocoaPod causing your deployment traget to change? I would recomend if that is the case to open separate issue , describing the problem a nd steps to reproduce so we could resolve each issue in separate thread.

**Comment by debevv** [comment] 2017-12-11 10:33
I did some research, and looks like async/await were introduced in **ES7**, not 6. This explains why every other feature in my code (classes, arrow functions, let, template literals) are working on both platforms, but async/await doesn't. Also, if this depends on Nativescript, why it isn't working only on iOS?
I don't want move the codebase from Javascript to Typescript, it's not a viable solution for me.
I tried to install the Babel plugin and it made the app run, but it added even more problems to the code so it wasn't worth it.

About the second issue, this is the Podfile generated in platforms/:
```
use_frameworks!

target "neon" do
 pod 'FBSDKCoreKit', '~> 4.7'
 pod 'FBSDKLoginKit', '~> 4.7' 

end
```
First time I did `tns build ios` I got a warning from CocoaPods about setting the target to default 8.0 because I didn't specify it anywhere. I tried on another machine (different macOS, different Xcode) and the warning is not shown. The result is the same anyway: every project/target in the Xcode workspace has the Deployment target set to 8.0.
I thought this was the default behaviour, so I didn't open an issue.

**Comment by NickIliev** [comment] 2017-12-11 12:22
@debevv regarding the question about why async/await does not work only on iOS - because of the JavaScript virtual machine - look here for [more details](https://github.com/NativeScript/NativeScript/issues/2882#issuecomment-253511172)

**_Regarding the second question_** - it looks like a regression (once resolved via [this issue](https://github.com/NativeScript/nativescript-cli/issues/1012))

If possible, please provide a workflow that can demonstrate the issue (via sample project or detailed steps), so I can test the case on my side and then when confirmed to open a new bug report in the nativescript-cli repository. Meanwhile, I will try to reproduce the case on my side (and if successful will open the issue myself)

**Closed by NickIliev** 2017-12-11 12:22 UTC
Labels: question

**Comment by debevv** [comment] 2017-12-11 14:39
Ok, so do you have any plans for an iOS runtime release that will support async/await? I can continue the development of my application with ES7 if I know that its support is on the way.

Yes, I forgot to mention that I added that entry in `build.xcconfig` and it is being picked up only for the app target.

The workflow is (using macOS):
- Create a new project
- `tns pugin add nativescript-facebook`
- `tns build ios`
- In some cases, you should see a warning about the verison set to 8.0
- Open the workspace file in the platforms/ios folder and check the Deployment Target value for every project/target
