### ISSUE TITLE
tns run android enables auto rotate on device

### ISSUE THREAD

**Issue by aaayushsingh** [NativeScript/NativeScript#4591] opened 2017-07-24 08:06 UTC
### Tell us about the problem
When installing an app using `tns run android` , auto rotate of device is turned on every time.

### Which platform(s) does your issue occur on?
Android
(iOS not tested)

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.3
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): android

### Please tell us how to recreate the issue in as much detail as possible.
1.  Open powershell(windows)
2.  do `tns create appName`
3.  `cd` to directory
4.  turn off auto rotate on android device
5. `tns run android`

this turns auto rotate on.

**Comment by shabib3** [comment] 2017-07-24 08:45
Same thing here...

**Comment by tsonevn** [comment] 2017-07-24 11:45
Hi @aaayushsingh, @shabib3,
Could you provide some more info about this case and the problem, which you are facing?
It would also help if you could provide some further info about the Android device, which you are using for testing and its API level.

**Comment by bradmartin** [comment] 2017-07-25 01:55
I've meant to look into this for a long time, been happening since the 2x days from what I recall. Device has disable screen rotation but once you run a NS app it enables screen rotation without any indication.

**Comment by aaayushsingh** [comment] 2017-07-25 04:50
@tsonevn Apparently you removed your comment, however, I've tested this on Xiaomi Redmi Note 3 android 6.0.1 and Moto G5 plus android 7.

And also, looks like I'm not the only one facing this.

**Comment by tsonevn** [comment] 2017-07-25 07:01
Hi @aaayushsingh,
Indeed we were able to reproduce this issue on our side. However, we will need some time to research, what is causing this behavior.

**Comment by aaayushsingh** [comment] 2017-07-25 10:16
@tsonevn It happens between these two tasks. Could it be something in the nativescript-cli?
`Refreshing application...
Successfully synced application org.nativescript.create on device 8c66cee7.`

and also that auto-rotate is enabled every time a hot-swap of code takes place.

**Comment by Plamen5kov** [comment] 2017-07-25 11:27
@aaayushsingh, @shabib3, @bradmartin, @tsonevn the problem is we use the [`monkey` tool](https://github.com/telerik/mobile-cli-lib/blob/cf3276e6bd5fdd66070a88cd70bc40d29fc65a5a/mobile/android/android-application-manager.ts#L46) to start the application and for some reason, it turns on autorotate.

One possible solution is to revert the way we start the application:
```
await this.adb.executeShellCommand(["am",
	"start", "-a", "android.intent.action.MAIN",
	"-n", appIdentifier + "/com.tns.NativeScriptActivity"
	]);
```
but that means we need to specify the main activity we want to start: `/com.tns.NativeScriptActivity`, and if the user changes the main activity, cli wouldn't be able to start the application.

PS. I'm working to find a better way to fix the problem and disable the "autorotate" option on application start.

**Comment by Pip3r4o** [comment] 2017-07-26 07:41
@Plamen5kov I don't like the idea of forcing device rotation manually, for one, you may have to know of the original state, to be able to do it properly, and I've also noticed that the `adb monkey` tool doesn't always unlock automatic rotation.

In order to determine which Activity to send a MAIN intent to using the Activity Manager (`adb am`), we could do a package dump, and grep the Activity Resolver Table. For an application with a single activity it looks like this:

```
  Activity Resolver Table:
    Non-Data Actions:
        android.intent.action.MAIN:
          2e5610f org.nativescript.volunteerupapp/com.tns.NativeScriptActivity filter c0aef3
            Action: "android.intent.action.MAIN"
            Category: "android.intent.category.LAUNCHER"
            AutoVerify=false
```

If I executed `adb shell pm dump org.nativescript.volunteerupapp | grep -A 1 MAIN` I would end up with just this, which is fairly parseable:
```
        android.intent.action.MAIN:
          2e5610f org.nativescript.volunteerupapp/com.tns.NativeScriptActivity filter c0aef3
            Action: "android.intent.action.MAIN"
            Category: "android.intent.category.LAUNCHER"
```

There is an alternative to using pm dump to get the Activity Resolver table, and that's using `cmd package resolve-activity --brief org.nativescript.volunteerupapp`, which unfortunately appears to be **unavailable** on devices *API 24* or lower. Following is the result when the command is executed:
```
priority=0 preferredOrder=0 match=0x108000 specificIndex=-1 isDefault=false
org.nativescript.volunteerupapp/com.tns.NativeScriptActivity
```

**Comment by Plamen5kov** [comment] 2017-07-26 07:55
> I've also noticed that the adb monkey tool doesn't always unlock automatic rotation.

@Pip3r4o can you share those cases?

**Comment by rosen-vladimirov** [comment] 2017-07-26 07:57
Maybe we can pass some additional argument to monkey tool in order to stop this behavior. For example `--pct-rotation 0`. I'm not familiar with all possible options, but we can try some of them described [here](https://github.com/android/platform_development/blob/ef7ff204e2ad4ba1094db8e9dc891a13c1f7ba31/cmds/monkey/src/com/android/commands/monkey/Monkey.java)

Some more infromation:
https://stackoverflow.com/questions/12872917/change-screen-orientations-during-monkey-run

**Comment by Pip3r4o** [comment] 2017-07-26 08:05
@Plamen5kov the SO post that Roskata posted contains other commenters claiming that Rotation may or may not happen, and that it is all random. - https://stackoverflow.com/a/12873010/6408287

**Comment by Plamen5kov** [comment] 2017-07-26 12:54
@rosen-vladimirov @Pip3r4o my vote goes towards removing the `monkey` altogether and using the Android Activity Manager `am` tool instead. What do you think?

**Comment by Plamen5kov** [comment] 2017-08-03 12:55
Based on popular vote: removing `monkey` from implementation and replacing it with `am` tool.

**Comment by shabib3** [comment] 2017-08-03 15:28
@Plamen5kov 
You have any ETA about when it will be out?

**Comment by Plamen5kov** [comment] 2017-08-04 05:04
@shabib3 the fix will be in for the next release. It's already implemented, but it's not in master branch yet.

**Closed** 2017-08-28 12:08 UTC
Labels: Android
