### ISSUE TITLE
After upgrade to 1.6, Android will crash sometimes just for a normally "go back"

### ISSUE THREAD

**Issue by wisonye** [NativeScript/NativeScript#1701] opened 2016-03-07 00:35 UTC
Try many times, the "first call" of "frame.topmost().goBack()" will crash !!!!, and it only happen on Android, Ios is fine, here is the crash log :

com.tns.NativeScriptException: 
Calling js method onCreateView failed

Error: Corrupted navigation stack; page: undefined; currentNavigationPage: undefined
File: "/data/data/com.easywhv.MobileApp/files/app/tns_modules/ui/frame/frame-common.js, line: 173, column: 12

StackTrace: 
	Frame: function:'Frame._processNavigationQueue', file:'/data/data/com.easywhv.MobileApp/files/app/tns_modules/ui/frame/frame-common.js', line: 173, column: 19
	Frame: function:'_completePageAddition', file:'/data/data/com.easywhv.MobileApp/files/app/tns_modules/ui/transition/transition.js', line: 228, column: 15
	Frame: function:'_onFragmentShown', file:'/data/data/com.easywhv.MobileApp/files/app/tns_modules/ui/transition/transition.js', line: 197, column: 9
	Frame: function:'onFragmentShown', file:'/data/data/com.easywhv.MobileApp/files/app/tns_modules/ui/frame/frame.js', line: 129, column: 22
	Frame: function:'android.app.Fragment.extend.onCreateView', file:'/data/data/com.easywhv.MobileApp/files/app/tns_modules/ui/frame/frame.js', line: 60, column: 17

	at com.tns.Platform.callJSMethodNative(Native Method)
	at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:812)
	at com.tns.Platform.callJSMethod(Platform.java:711)
	at com.tns.Platform.callJSMethod(Platform.java:690)
	at com.tns.Platform.callJSMethod(Platform.java:680)
	at com.tns.gen.android.app.Fragment_ftns_modules_ui_frame_frame_l34_c42__.onCreateView(android.app.Fragment.java)
	at android.app.Fragment.performCreateView(Fragment.java:2059)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:899)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1076)
	at android.app.BackStackRecord.popFromBackStack(BackStackRecord.java:1595)
	at android.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1565)
	at android.app.FragmentManagerImpl$3.run(FragmentManager.java:507)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1461)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:448)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5538)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by erkanarslan** [comment] 2016-03-11 12:16
+1

**Comment by maknz** [comment] 2016-03-15 02:46
Yeah, we're seeing a few corrupt backstack exceptions on Android. Although, the app usually crashes with a weak reference error before that happens.

**Comment by NathanaelA** [comment] 2016-03-15 03:28
Are you using the clearHistory anywhere in your navigation?   If so, this will cause the corruption and you need to upgrade to the latest core modules.

**Comment by maknz** [comment] 2016-03-15 03:29
Ah, yes we use `clearHistory` a lot. I'll try `@latest`.

**Comment by wisonye** [comment] 2016-03-15 04:31
@NathanaelA Yes, some of them, as that's from Login page, and I've already got the latest core modules already, what version you expected ?

**Comment by NathanaelA** [comment] 2016-03-15 05:01
You should be using v1.6.2 of the TNS Core Modules for the main fix.  I do believe there might be another issue with navigation they are looking into; but this one fixes the clearHistory issue.

**Comment by wisonye** [comment] 2016-03-15 05:10
@NathanaelA Here is my "package.json" which under "/node_modules/tns-core-modules", let me know if I use an older version :

```javascript
{
  "name": "tns-core-modules",
  "description": "Telerik NativeScript Core Modules",
  "version": "1.6.2",
  "homepage": "https://www.nativescript.org",
  "repository": {
    "type": "git",
    "url": "https://github.com/NativeScript/NativeScript/commit/a3b688a3b9000497a1ab153d45df3f06b0ba3bc5"
  },
  "files": [
    "**/*.*",
    "**/*",
    "!.baseDir.*",
    "!node-tests/",
    "!apps/"
  ],
  "license": "Apache-2.0",
  "devDependencies": {
    "chai": "3.2.0",
    "grunt": "0.4.5",
    "grunt-contrib-clean": "0.6.0",
    "grunt-contrib-copy": "git+https://github.com/ErjanGavalji/grunt-contrib-copy.git#1c976a133210be4ce8c96313f5daf14833f7f8f9",
    "grunt-env": "0.4.4",
    "grunt-exec": "0.4.6",
    "grunt-mkdir": "0.1.2",
    "grunt-multi-dest": "1.0.0",
    "grunt-shell": "1.1.2",
    "grunt-simple-mocha": "0.4.0",
    "grunt-ts": "5.3.2",
    "grunt-typedoc": "0.2.3",
    "grunt-untar": "0.0.1",
    "mocha": "2.2.5",
    "shelljs": "0.5.3",
    "grunt-tslint": "3.0.0",
    "time-grunt": "^1.3.0",
    "tslint": "3.3.0",
    "typescript": "1.7.5"
  },
  "typings": "tns-core-modules.d.ts",
  "dependencies": {
    "tns-core-modules-widgets": "1.6.1"
  },
  "nativescript": {
    "platforms": {
      "ios": "1.6.0",
      "android": "1.6.0"
    }
  },
  "_id": "tns-core-modules@1.6.2",
  "_shasum": "05bbf174813448b1cb0f76b1897c72573927fbec",
  "_resolved": "https://registry.npmjs.org/tns-core-modules/-/tns-core-modules-1.6.2.tgz",
  "_from": "tns-core-modules@latest",
  "scripts": {},
  "_npmVersion": "3.7.1",
  "_nodeVersion": "5.5.0",
  "_npmUser": {
    "name": "hdeshev",
    "email": "hristo@deshev.com"
  },
  "dist": {
    "shasum": "05bbf174813448b1cb0f76b1897c72573927fbec",
    "tarball": "http://registry.npmjs.org/tns-core-modules/-/tns-core-modules-1.6.2.tgz"
  },
  "maintainers": [
    {
      "name": "enchev",
      "email": "vladimir.enchev@gmail.com"
    },
    {
      "name": "erjangavalji",
      "email": "erjan.gavalji@gmail.com"
    },
    {
      "name": "fatme",
      "email": "hfatme@gmail.com"
    },
    {
      "name": "hdeshev",
      "email": "hristo@deshev.com"
    },
    {
      "name": "ligaz",
      "email": "stefan.dobrev@gmail.com"
    },
    {
      "name": "nsndeck",
      "email": "nedyalko.nikolov@telerik.com"
    },
    {
      "name": "sdobrev",
      "email": "stefan.dobrev@gmail.com"
    },
    {
      "name": "valio.stoychev",
      "email": "valio.stoychev@gmail.com"
    }
  ],
  "_npmOperationalInternal": {
    "host": "packages-9-west.internal.npmjs.com",
    "tmp": "tmp/tns-core-modules-1.6.2.tgz_1456230220993_0.6211725694593042"
  },
  "directories": {},
  "readme": "ERROR: No README data found!"
}
```

**Comment by NathanaelA** [comment] 2016-03-15 14:19
No, that is the latest as of yesterday.   
@hshristov - Here is another case of navigation issues, not clearHistory related apparently.

**Comment by hshristov** [comment] 2016-03-17 15:39
@NathanaelA This should be working with 1.7.0.
If not please let me know how to reproduce it.

**Comment by NathanaelA** [comment] 2016-03-17 18:24
@hshristov I'm not the one with the issue; Check above my name.  I was tagging you because I knew you were working on these issues...  So all the nav issues are now fixed in 1.7?

**Comment by hshristov** [comment] 2016-03-25 12:22
@NathanaelA, @maknz, @wisonye, @erkanarslan - All android navigation issues should be resolved for 1.7.1.
If you encounter some problems please open up new issue with sample app to reproduce it.
I will be happy to investigate it.

**Closed by hshristov** 2016-03-25 12:22 UTC

**Comment by kwameboateng** [comment] 2018-08-27 17:57
The grimlins are back!!!! Transition not working on tns 4.2.0! 

this.router.navigate(["/ready"], {
            clearHistory: true,
            transition: {
                name: "slideLeft",
                duration: 500,
                curve: "linear"
            }

        });

and i found that it is solely the transition code causing the issue... I have removed clearHistory and tried it but error persists....

ystem.err: java.lang.NullPointerException: Attempt to read from field 'int android.app.Fragment.mContainerId' on a null object reference
System.err: 	at android.app.BackStackRecord$1.onPreDraw(BackStackRecord.java:1131)
System.err: 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1018)
System.err: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2327)
System.err: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1314)
System.err: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7057)
System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:829)
System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:606)
System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:576)
System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:815)
System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:145)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6934)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at java.lang.reflect.Method.invoke(Method.java:372)

**Comment by kwameboateng** [comment] 2018-08-27 17:57
*gremlins
