### ISSUE TITLE
android.graphics.Typeface.getStyle() error on latest version

### ISSUE THREAD

**Issue by mast3rd3mon** [NativeScript/NativeScript#4233] opened 2017-05-19 09:09 UTC
### Which platform(s) does your issue occur on?
Android - not tested on IOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.1
- Cross-platform modules: 3.0.0
- Runtime(s): 3.0.0

### Please tell us how to recreate the issue in as much detail as possible.
`tns create appName --ng`
`npm install nativescript@next` - should install `3.0.1-2017-05-19-8940`
then add the following to the items.component.html in place of the listview:
```
<Button class="btn">
    <FormattedString>
        <Span fontSize="20" text="Text to Display"></Span>
    </FormattedString>
</Button>
```

This will then give you an `android.graphics.Typeface.getStyle()` error.

Apparently this got fixed in #4109 but it still appears to not work

**Comment by tsonevn** [comment] 2017-05-19 10:32
Hi @mast3rd3mon,
Thank you for contacting us.
I reviewed the described problem and the fix for this issue is included in `tns-core-modules` `@next`.
To be able to test the fix on your side, you should install next modules instead @next CLI.
For this case you could follow the below-described steps:

1. `tns plugin remove tns-core-modules`
2. `npm install tns-core-modules@next --save`
3. delete `platforms` and `node_modules` folders
4, run `tns run android`

**Comment by mast3rd3mon** [comment] 2017-05-19 10:34
sorry, i forgot to add that, i also did `npm install tns-core-modules@next` and that issue still occurs

**Comment by tsonevn** [comment] 2017-05-19 12:53
Hi @mast3rd3mon,
I tested ones again this problem on my side, while using @next `CLI` and `tns-core-modules`, however still unable to reproduce this case. It would help if you could send us your sample project and some more info about the Android simulator or device, which you are using for testing.

For your convenience, I am attaching a screenshot, from the simulator.
![screen shot 2017-05-19 at 3 46 48 pm](https://cloud.githubusercontent.com/assets/17448734/26248484/4cb60022-3cab-11e7-813b-deb1595f78eb.png)

**Comment by mast3rd3mon** [comment] 2017-05-19 12:58
It's running on a genymotion trial android device running 6.0. I believe I also got this issue when I ran the app on the standard android emulator, again running 6.0. It could just be the image or how the styles look on ns3 but that doesnt look like its a button.

**Comment by tsonevn** [comment] 2017-05-19 14:05
Hi @mast3rd3mon,
This style to the button has been applied from `nativescript-theme-core`, while using `btn` CSS class. You could review the attached image, where the default Android Button style is used.
![screen shot 2017-05-19 at 5 01 21 pm](https://cloud.githubusercontent.com/assets/17448734/26251270/66a1e1c2-3cb5-11e7-8f7f-784c33ea0377.png)

Regarding the issue, could you verify again, whether you will have the same problem while using default android emulator? For some further help,  you could review [this article](https://docs.nativescript.org/tooling/android-virtual-devices) from the documentation.

**Comment by mast3rd3mon** [comment] 2017-06-08 15:01
@NickIliev how come this was closed? It was never resolved?

**Comment by NickIliev** [comment] 2017-06-09 11:11
@mast3rd3mon the issue does not seems to be reproducible with **next** version of tns-core-modules.
NO errors are thrown and the FormattedString is applied as expected.

Test application [here](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/NativeScript/issue_4233/app/item/items.component.html#L4-L8)
the result is as follows:

**Closed** 2017-06-09 11:11 UTC
Labels: Android, T:Question

**Comment by mast3rd3mon** [comment] 2017-06-09 11:13
Unless there has been another update since i opened this issue, the styles still break the formatted string

**Comment by NickIliev** [comment] 2017-06-09 11:15
@mast3rd3mon I will reopen the issue immediately if the problem persists! Please send us sample project that can reproduce this or modify my test project [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4233)
