### ISSUE TITLE
RadListView with multiple item templates toggling visibility

### ISSUE THREAD

**Issue by glennsyang** [NativeScript/NativeScript#6491] opened 2018-11-01 21:47 UTC
**Environment**
 - CLI: 4.2.4
 - Cross-platform modules: 4.2.1
 - Android Runtime: 4.2.0
 - iOS Runtime: 4.2.0
 - Plugin(s):  nativescript-ui-listview": "^3.7.2"

**Describe the bug**
I have an issue with the radlistview with multiple item templates and toggling visibility. I'm trying to re-create an according type display without using the nativescript-accordion plugin. By toggling the visibility attribute for a given item

**To Reproduce**
see Playground example below.

**Expected behavior**
It's hiding the items below the header item, but all the items below, even the ones that were not set to visibilty="collapsed". Please see .gif for the behavior.

This is working fine on Android, just not on iOS.

Any ideas?
It seems like momentarily its doing the right thing, but then it hides everything under, which is not what I want. I want it to just hide the items under the tapped header.
I've also tried using the refresh() method of listview, same result in terms of behavior.

![ljcga](https://user-images.githubusercontent.com/38868199/47881891-dc1d7480-dde4-11e8-95d3-22136dab70b9.gif)

**Sample project**
https://play.nativescript.org/?template=play-js&id=eC5qGO&v=34

I've posted here earlier but probably wrong place. 
https://github.com/telerik/nativescript-ui-feedback/issues/895

Just reposting in this forum.

**Comment by tsonevn** [comment] 2018-11-02 06:46
Duplicate of https://github.com/telerik/nativescript-ui-feedback/issues/895

**Closed by tsonevn** 2018-11-02 06:46 UTC
