### ISSUE TITLE
Assignment variable in the fetch module

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#5934] opened 2018-06-10 12:56 UTC
```JS
export class RestApi() 
{
//....
public request() {

     var result; // The var what i need to return

      var $_this = this.

      fetch($url, {
                method: $method,
                headers: new Headers($headers),
                body: $body
        }).then(r => { 
            return r.json();
        })
        .then(response => {
            //console.log(response)
            result = response; 
            return response;

        
        })
        .catch((err)=> {
                console.log(`Error Fetch >> ${err}`)
        });

        return result; // HERE I GET undefined !

    }

}
`
``

When i call :

```JS
var rest = new RestApi();
var result = rest.request();
console.log(result); // undefined
```

Please can you explain for me.

Thanks

**Comment by NickIliev** [comment] 2018-06-11 11:13
The call from `fetch` module is asynchronous so this is the reason you result is `undefined`.
You could create a promise and use resolve/reject to handle this case ([example here](https://github.com/NativeScript/NativeScript/blob/c02bb283a9766f84e2a549d57302eaf8cd704779/tns-core-modules/http/http.ts#L6-L16)). Closing as the issue is how-to related.

**Closed by NickIliev** 2018-06-11 11:13 UTC
Labels: question

**Comment by kefahB** [comment] 2018-06-11 11:29
Thank you for your reactivity.

I do fetch with async await and this done, but this approach is true ?

Thanks
