### ISSUE TITLE
Plugins are not working with the nativescript version 3.1.2

### ISSUE THREAD

**Issue by venkatTammareddy** [NativeScript/NativeScript#4708] opened 2017-08-17 04:42 UTC
Hi,

I am using the nativescript version 3.1.2, I have tried to use 'nativescript-carousel-view', 'nativescript-carousel', 'natovescript-slides'. None of them are working. In runtime they are throwing the exception.

**Exception:** 
com.tns.exception: Failed to load module.

Can anyone help me out about the issue.

**Comment by NickIliev** [comment] 2017-08-17 12:53
Ping @alexrainman for nativescript-carousel-view.

@venkatTammareddy the issue seems to be related only to carousel view plugin. The nativescript-slides works as expected.

Closing this as a duplicate of [the issue in the plugin's repository](https://github.com/alexrainman/nativescript-carousel-view/issues/19).

**Closed by NickIliev** 2017-08-17 12:53 UTC
Labels: question
