### ISSUE TITLE
Custom component's CSS isn't loaded from the 2nd level and on [$900]

### ISSUE THREAD

**Issue by sserdyuk** [NativeScript/NativeScript#4405] opened 2017-06-16 13:31 UTC
This is an old issue #1639  that was marked fixed and closed, but still isn't working right. When you nest components into components, starting with the 2nd level, the CSS files aren't loaded and "Error: CSS file found but no page specified. Please specify page in the options!" is shown in the logs. The test for this is already built into NS "apps" app, under issues and 1639.

```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.0.3           │ 3.0.3          │ Up to date  │
│ tns-core-modules │ 3.0.1           │ 3.0.1          │ Up to date  │
│ tns-android      │ 3.0.1           │ 3.0.1          │ Up to date  │
│ tns-ios          │ 3.0.1           │ 3.0.1          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘
```

![simulator screen shot jun 15 2017 10 34 56 am](https://user-images.githubusercontent.com/395998/27228625-5b392666-5276-11e7-9283-2e0a13534f80.png)

**Comment by NickIliev** [comment] 2017-06-19 08:28
@sserdyuk confirming this as a bug for nested custom components from the 2nd level and below.

As a temporary workaround, you can set the styles for your deeply nested components in the main `app.css` file.

Related to [https://github.com/NativeScript/NativeScript/issues/1639](https://github.com/NativeScript/NativeScript/issues/1639)

**Comment by giorgiopiatti** [comment] 2017-11-10 18:57
I confirm that this issue happens also with the latest version of Nativescript with angular.
There isn't still a solution ?

**Comment by na2axl** [comment] 2018-04-13 13:46
Facing the same issue when the custom component is in a Repeater...
This doesn't work
```xml
<ScrollView height="100%">
    <Repeater items="{{ mediaList }}">
        <Repeater.itemsLayout>
            <StackLayout />
        </Repeater.itemsLayout>
        <Repeater.itemTemplate>
            <mediaListItem:MediaListItem data="{{ media }}" />
        </Repeater.itemTemplate>
    </Repeater>
</ScrollView>
```

But this one works and show the CSS
```xml
<ScrollView height="100%">
    <mediaListItem:MediaListItem data="{{ media }}" />
</ScrollView>
```

Using {N} 4.0.0

**Comment by tsonevn** [comment] 2018-07-27 11:37
The issue is reproducible with NativeScript 4.1. 
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2235592/Archive.zip)

**Comment by Yassine-ala** [comment] 2019-06-27 09:06
Hello, 
I cloned @tsonevn 's archive and was able to reproduce the issue.
This fixes the issue for me:

**nestedComponent.xml** 

`<Page loaded="onPageLoaded">
content
</Page>`

**nestedComponent.ts**
```
import {Page} from "tns-core-modules/ui/page";
import {EventData} from "tns-core-modules/data/observable";

export function onPageLoaded(args: EventData): void {
    let page = <Page>args.object;
    page.addCssFile(pathFromRoot);
}
```

**Important notes** 
Lets say you have the following structure 
(-> = contains)
parent -> child1 -> child2 -> child3

- Parent and last child (child3) css works fine 
- child1 and child2 are respectively applying child2 and child3 css for some reason
- The middle nestedcomponents will still have their direct child css applied, but atleast the solution i'm suggesting applies the target css file and overrides the styling on the same tags.

**Comment by PeterStaev** [comment] 2019-07-11 08:09
Has this been confirmed that it is still an issue with 6.0 RC? Downloading the archive from @tsonevn  and running `tns migrate` and then running for iOS/android all the 3 labels are colored correctly.

**Comment by hakxru** [comment] 2019-07-22 15:18
Hello,
@rdlauer seven days ago, I pushed  [PR #7523](https://github.com/NativeScript/NativeScript/pull/7523) that fixes and closes this issue. How soon can it be reviewed and merged?

All the child components styled properly as seen in the screenshot below
![screenshot-2019-07-07_23 08 27 326](https://user-images.githubusercontent.com/51954653/61235642-45a49f80-a736-11e9-93fe-becec97c2100.png)

**Comment by vchimev** [comment] 2019-07-29 08:45
Hey All,

Thank you for your collaboration.

As @PeterStaev noticed, this has no longer been an issue since 6.0 RC.

It has been addressed and officially released along with the `webpack`-only efforts by the core team.

I am closing this issue as it is no more.

**Closed** 2019-07-29 08:46 UTC
Labels: backlog, bounty, bug, css, help wanted, os: android, os: ios, severity: medium
