### ISSUE TITLE
ListView background doesn't update unless cell is scrolled out of view on iOS

### ISSUE THREAD

**Issue by EddyVerbruggen** [NativeScript/NativeScript#4489] opened 2017-07-02 15:31 UTC
### Tell us about the problem
The GIF below is [this app](https://github.com/EddyVerbruggen/nativescript-listview-backgroundcolor-changedetection-issue) which is a slightly adjusted version of [this template](https://github.com/NativeScript/template-hello-world-ng).

Note that the background color of the listview items is not changed to green until it's scrolled out of view, and scrolled back in (NOK). The label at the top is updated immediately (OK). Als note that the text color *is* changed immediately, so it's not *all* bad.

<img src="https://user-images.githubusercontent.com/1426370/27771145-25a0409a-5f49-11e7-9188-9704985cfe24.gif" width="280px"/>

### Which platform(s) does your issue occur on?
iOS (Android is fine) - *only with tns-core-modules 3.1.0*

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.1.0
- Cross-platform modules: 3.1.0 (3.0.1 is fine)
- Runtime(s): tns-ios 3.1.0
- Plugin(s): n/a

### Please tell us how to recreate the issue in as much detail as possible.
Created a [minimal demo app](https://github.com/EddyVerbruggen/nativescript-listview-backgroundcolor-changedetection-issue) with instructions.

### Fix
The [fix branch in the same repo](https://github.com/EddyVerbruggen/nativescript-listview-backgroundcolor-changedetection-issue/tree/fix) suggests a solution (and can be used locally as a temporary workaround). Note that it break 2 testcases if you would apply it, so I'm quite sure there's a better way to solve it.

**Comment by NickIliev** [comment] 2017-07-03 15:03
@EddyVerbruggen thank you for the sample project demonstrating the issue.
Steps to reproduce - The code to reproduce the issue is implemented in [this line](https://github.com/EddyVerbruggen/nativescript-listview-backgroundcolor-changedetection-issue/blob/fix/app/item/items.component.html#L33)

**Comment by NickIliev** [comment] 2017-07-11 10:19
@EddyVerbruggen closing this as a duplicate to [https://github.com/NativeScript/nativescript-angular/issues/377](https://github.com/NativeScript/nativescript-angular/issues/377).  We will continue the discussion in the linked issue.

For everyone interested a temporary workaround is given [here](https://github.com/NativeScript/nativescript-angular/issues/377#issuecomment-275272724)

**Closed by NickIliev** 2017-07-11 10:19 UTC
Labels: iOS, T:Bug

**Comment by drmistral** [comment] 2018-07-14 10:35
I found the solution above fixes the problem also [in my case ](https://github.com/NativeScript/NativeScript/issues/6061). 
In my case where I have a custom component (button with data+style logic) in a list, it is the only fix I found that does not require to do strange tricks as bind style parameters  from the caller context.
I'm still testing at the moment but it seems working fine. Is there any known collateral effect?

**Comment by ostadsaleh** [comment] 2019-06-05 17:09
hi guys
look at this exercise:
### Create a page that displays a green background when in portrait mode, but red when in landscape
**Solutions:**
Assume the page name is main-page.xml.
▪ Create two page-specific XML files named main-page.port.css and main-page.land.css.
▪ Add Page { background-color: green; } to the main-page.port.css file.
▪ Add Page {background-color: red; } to the main-page.land.css file.

then i have done this job but still not working.i have done this with emulator.
can anybody help me?
