### ISSUE TITLE
Keyboard hides when moving to next textfield using "next" key

### ISSUE THREAD

**Issue by RaghavMSG** [NativeScript/NativeScript#5539] opened 2018-03-15 05:45 UTC
Keyboard hides when moving to next textfield using "next" key in both android and iOS.

nativescript-version : 3.3.0 ,
"tns-ios": {
      "version": "3.3.0"
    },
"tns-android": {
      "version": "3.3.1"
    }
For iOS i am using IQKeyboardManager but the next and previous arrow buttons are not available.

**Comment by tsonevn** [comment] 2018-03-15 06:13
Hi @RaghavMSG,
This issue seems to be duplicate of #2809. You could also review the provided temporary solution [here](https://github.com/NativeScript/NativeScript/issues/2809#issuecomment-312358843)

**Closed by tsonevn** 2018-03-15 06:13 UTC
Labels: os: ios
