### ISSUE TITLE
How to place borders in between the images as shown in the  uploaded image

### ISSUE THREAD

**Issue by karumurikiran** [NativeScript/NativeScript#2057] opened 2016-05-02 10:57 UTC
![capture1](https://cloud.githubusercontent.com/assets/10797035/14952967/c1b9d854-1082-11e6-8115-fe8b8d49142a.PNG)

**Comment by hdeshev** [comment] 2016-05-03 06:38
Duplicate of #2058

**Closed by hdeshev** 2016-05-03 06:38 UTC
Labels: T:Question
