### ISSUE TITLE
accordian issue

### ISSUE THREAD

**Issue by kapiltiwari61** [NativeScript/NativeScript#7229] opened 2019-05-10 09:16 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by kapiltiwari61** [comment] 2019-05-10 09:18
Hi Guys, please find the log.
`JavaScript stack trace:
1   measure@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:58:124
2   measureChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:888:26
3   measureChild@file:///app/tns_modules/tns-core-modules/ui/layouts/grid-layout/grid-layout.js:585:63
4   measure@file:///app/tns_modules/tns-core-modules/ui/layouts/grid-layout/grid-layout.js:528:34
5   onMeasure@file:///app/tns_modules/tns-core-modules/ui/layouts/grid-layout/grid-layout.js:112:28
6   measure@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:55:27
7   measureChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:888:26
8   tableViewViewForFooterInSection@file:///app/tns_modules/nativescript-accordion/src/ios/accordion.js:445:56
9   UIApplicationMain@[native code]
10  _start@file:///app/tns_modules/tns-core-modules/application/application.js:275:26
11  start@file:///app/tns_modules/tns-core-modules/application/application.js:302:11
12  anonymous@file:///app/app.js:29:18
13  evalua<…>
JavaScript error:
file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:58:124: JS ERROR Error: onMeasure() did not set the measured dimension by calling setMeasuredDimension() Label(574)@file:///app/pages/bottom-pages/second-tab/second-tab-component.xml:99:17;`

have a look to package.json 
`{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "abc.com.kk",
    "tns-android": {
      "version": "5.2.1"
    },
    "tns-ios": {
      "version": "5.3.1"
    }
  },
  "dependencies": {
    "ajax-request": "^1.2.3",
    "base-64": "^0.1.0",
    "lodash": "^4.17.11",
    "nativescript-accordion": "^5.0.3",
    "nativescript-appversion": "^1.4.1",
    "nativescript-bottom-navigation": "^1.5.0",
    "nativescript-cardview": "^2.0.4",
    "nativescript-carousel": "^4.1.0",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-downloader": "^1.0.3",
    "nativescript-drawingpad": "^3.0.2",
    "nativescript-drop-down": "^3.2.5",
    "nativescript-exit": "^1.0.1",
    "nativescript-geolocation": "^4.5.0",
    "nativescript-globalevents": "^1.2.2",
    "nativescript-grid-view": "^3.2.2",
    "nativescript-image-cache": "^1.1.5",
    "nativescript-insomnia": "^1.2.2",
    "nativescript-iqkeyboardmanager": "^1.4.0",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-pdf-view": "^2.0.1",
    "nativescript-sqlite": "https://github.com/divyanshujain12/sqlite-nativescript.git",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toasty": "^1.3.0",
    "nativescript-ui-listview": "^6.2.0",
    "tns-core-modules": "^4.2.1",
    "utf8": "^3.0.0"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "^0.9.2",
    "nativescript-worker-loader": "^0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-sources": "~1.1.0"
  }
}
`

**Comment by NickIliev** [comment] 2019-05-10 09:43
@kapiltiwari61 simply posting the log is not enough to investigate your case. Consider following the "report a bug" prerequisites including providing a sample app or Playground demo which reproduces your issue. Here are the needed fields to reproduce & investigate an issue

> **Environment**
> Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
>  - CLI: 
>  - Cross-platform modules:
>  - Android Runtime:
>  - iOS Runtime:
>  - Plugin(s):
> 
> **Describe the bug**
> 
> 
> **To Reproduce**
> 
> 
> **Expected behavior**
> 
> **Sample project**
> 
> 
> **Additional context**
>

**Comment by kapiltiwari61** [comment] 2019-05-10 09:51
HI @NickIliev,

App is crashing while accordian is populating...Earlier the below code was working but not now.

<accordion:Accordion.footerTemplate>
            <GridLayout columns="auto,*">
99->                <Label text="{{footer}}"/>
                <Label col="1" text="-"/>
            </GridLayout>
        </accordion:Accordion.footerTemplate>
Please check the log..I mentioned the line number 99, where the app is crashing.

`1   measure@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:58:124
2   measureChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:888:26
3   measureChild@file:///app/tns_modules/tns-core-modules/ui/layouts/grid-layout/grid-layout.js:585:63
4   measure@file:///app/tns_modules/tns-core-modules/ui/layouts/grid-layout/grid-layout.js:528:34
5   onMeasure@file:///app/tns_modules/tns-core-modules/ui/layouts/grid-layout/grid-layout.js:112:28
6   measure@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:55:27
7   measureChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:888:26
8   tableViewViewForFooterInSection@file:///app/tns_modules/nativescript-accordion/src/ios/accordion.js:445:56
9   UIApplicationMain@[native code]
10  _start@file:///app/tns_modules/tns-core-modules/application/application.js:275:26
11  start@file:///app/tns_modules/tns-core-modules/application/application.js:302:11
12  anonymous@file:///app/app.js:29:18
13  evalua<…>
JavaScript error:
file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:58:124: JS ERROR Error: onMeasure() did not set the measured dimension by calling setMeasuredDimension() Label(574)@file:///app/pages/bottom-pages/second-tab/second-tab-component.xml:99:17;`

**Comment by kapiltiwari61** [comment] 2019-05-10 09:53
HI @NickIliev,

App is crashing while accordian is populating...Earlier the below code was working but not now.

<accordion:Accordion.footerTemplate>
            <GridLayout columns="auto,*">
                <Label text="{{footer}}"/> .         //line 99
                <Label col="1" text="-"/>
            </GridLayout>
        </accordion:Accordion.footerTemplate>
Please check the log..I mentioned the line number 99, where the app is crashing.

`1 measure@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:58:124 2 measureChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:888:26 3 measureChild@file:///app/tns_modules/tns-core-modules/ui/layouts/grid-layout/grid-layout.js:585:63 4 measure@file:///app/tns_modules/tns-core-modules/ui/layouts/grid-layout/grid-layout.js:528:34 5 onMeasure@file:///app/tns_modules/tns-core-modules/ui/layouts/grid-layout/grid-layout.js:112:28 6 measure@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:55:27 7 measureChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:888:26 8 tableViewViewForFooterInSection@file:///app/tns_modules/nativescript-accordion/src/ios/accordion.js:445:56 9 UIApplicationMain@[native code] 10 _start@file:///app/tns_modules/tns-core-modules/application/application.js:275:26 11 start@file:///app/tns_modules/tns-core-modules/application/application.js:302:11 12 anonymous@file:///app/app.js:29:18 13 evalua<…> JavaScript error: file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:58:124: JS ERROR Error: onMeasure() did not set the measured dimension by calling setMeasuredDimension() Label(574)@file:///app/pages/bottom-pages/second-tab/second-tab-component.xml:99:17;`

**Comment by kapiltiwari61** [comment] 2019-05-10 09:56
HI @NickIliev,

App is crashing when accordian is populating..Earlier it was working but not now.
`<accordion:Accordion.footerTemplate>
            <GridLayout columns="auto,*">
                <Label text="{{footer}}"/>
                <Label col="1" text="-"/>
            </GridLayout>
        </accordion:Accordion.footerTemplate>`

crashing at '<Label text="{{footer}}"/>' with bwlow log

`1 measure@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:58:124 2 measureChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:888:26 3 measureChild@file:///app/tns_modules/tns-core-modules/ui/layouts/grid-layout/grid-layout.js:585:63 4 measure@file:///app/tns_modules/tns-core-modules/ui/layouts/grid-layout/grid-layout.js:528:34 5 onMeasure@file:///app/tns_modules/tns-core-modules/ui/layouts/grid-layout/grid-layout.js:112:28 6 measure@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:55:27 7 measureChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:888:26 8 tableViewViewForFooterInSection@file:///app/tns_modules/nativescript-accordion/src/ios/accordion.js:445:56 9 UIApplicationMain@[native code] 10 _start@file:///app/tns_modules/tns-core-modules/application/application.js:275:26 11 start@file:///app/tns_modules/tns-core-modules/application/application.js:302:11 12 anonymous@file:///app/app.js:29:18 13 evalua<…> JavaScript error: file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:58:124: JS ERROR Error: onMeasure() did not set the measured dimension by calling setMeasuredDimension() Label(574)@file:///app/pages/bottom-pages/second-tab/second-tab-component.xml:99:17;`

**Comment by NickIliev** [comment] 2019-05-10 10:38
@kapiltiwari61 the issue seems related to a third-party plugin. Consider posting the issue with full details on how to reproduce it [in the original repository](https://github.com/triniwiz/nativescript-accordion/issues). 

It would help a lot if you can isolate the case in a sample template app. Closing the issue as unrelated to NativeScript and related to `nativescript-accordion` plugin but I will reopen this one if there is an application which demonstrates that the issue is in `tns-core-modules`.

**Closed by NickIliev** 2019-05-10 10:38 UTC
Labels: needs more info, question
