### ISSUE TITLE
Map Component

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#67] opened 2015-04-24 12:51 UTC
_From @ligaz on March 14, 2015 21:19_

...

_Copied from original issue: NativeScript/cross-platform-modules#177_

**Comment by N3ll** [comment] 2015-10-07 08:43
You can vote on our voting site https://nativescript.ideas.aha.io/ideas/NS-I-65.

**Comment by N3ll** [comment] 2015-10-08 13:31
The issue is closed in favor of https://github.com/NativeScript/NativeScript/issues/769.

**Closed by N3ll** 2015-10-08 13:31 UTC
