### ISSUE TITLE
[ios] text is reloaded when entering text view

### ISSUE THREAD

**Issue by dosomder** [NativeScript/NativeScript#8620] opened 2020-06-07 14:32 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime: 6.5.1
 - iOS Runtime: 6.5.1
 - Plugin(s):

**Describe the bug**
If you enter (focus) a text field, the ios variant will reload the text defined in the property. This is different behavior to the android version where this does not happen. Basically I am using both `text` and `formattedText` property of the text view. By pressing a button I am using the user input from `text` and adding some formatting to it. This works fine on Android. On iOS since both properties are set, every time the text view is focused, the text from `formattedText` is reloaded thus clearing the user input if the button was not pressed.

I don't see the point why this is implemented like this on iOS and I think it can be removed to match the behavior of Android. See https://github.com/NativeScript/NativeScript/blob/master/nativescript-core/ui/text-view/text-view.ios.ts#L33

**To Reproduce**
1. Open the playground app
2. Type something in the text view
3. Close the text view
4. Focus the text view again -> text from before disappears

**Expected behavior**
Try the same on Android -> text does not disappear

**Sample project**
https://play.nativescript.org/?template=play-vue&id=lVTKFT

**Additional context**

**Comment by dosomder** [comment] 2020-06-13 19:07
@NathanWalker any comment on this? Can I do a PR removing this behavior?

**Comment by NathanWalker** [comment] 2020-06-17 01:52
@dosomder thanks - if you want to suggest a fix you could add on your current pending PR or do a separate one for this 👍

**Comment by dosomder** [comment] 2020-06-17 08:07
@NathanWalker Thanks, I will do a separate PR. The only reason I can think of this logic was added is to hide a hint / placeholder if it was shown. I noticed though that for `TextView` on iOS no `hint` is shown.
Documentation shows this should be possible with TextView:
https://nativescript-vue.org/en/docs/elements/components/text-view/

Is this a bug?

**Comment by farfromrefug** [comment] 2020-06-20 06:56
I think you break hint if you disable this. Also about you using both text and formattedText and the TextView behaving like that, it might not have been the intended use case and thus kind of normal to not behave as intended. I don't think there are rules defines on which property to use when both are defined. The best thing would be for you to handle that behavior correctly in your app. As for now you should never pass both props at the same time. Maybe they even should be only one prop(I think this is the issue !) .

**Comment by dosomder** [comment] 2020-06-20 09:20
@farfromrefug thanks for your comment. I think you are right. The reason I am using both properties is because formattedText is not updated on user input. In my opinion the better fix would be to update formattedText on user input. What do you think?

**Comment by farfromrefug** [comment] 2020-06-20 11:46
well in a sense formattedText is not meant to be dynamic. However it is really easy to do so. Simply hold an instance of FormattedString in your component. When you get an text change event, update your formattedString programmatically. Then set it in the textView. You should get the behavior you want. It won't be optimized for "big" formatted strings with a lot of formatting (because the whole formatted string will be re evaluated every time) but it will work as you expect.

**Comment by dosomder** [comment] 2020-06-20 15:32
Your comment is helpful. Although reevaluating the formatted string on every character change is not really optimal in my opinion. I will see if I can somehow optimize it in my code

**Comment by farfromrefug** [comment] 2020-06-20 16:07
You can write it the right away very easily using native api from js. Very easy to do. A lot of examples around for iOS and android

**Comment by dosomder** [comment] 2020-06-21 11:00
Care to link some of these many examples?

**Comment by farfromrefug** [comment] 2020-06-21 13:50
@dosomder simply search for 'textview markdown'.
One example is this libray https://github.com/yydcdut/RxMarkdown

It is not an ugly hack as you have to do it this way. and yes you have to set the cursor to the right position.
Android wont do that all for you...

**Comment by dosomder** [comment] 2020-06-21 18:34
The thing is my formatted text has images in it (some words get converted to images). So this might work fine for android where the ImageSpan has an underlying text but it does not work for iOS TextAttachment. I guess I'm just going to do a custom text view then.

**Comment by farfromrefug** [comment] 2020-06-21 18:53
I honestly don't see why it would not be possible on iOS. But if you think it is best go for it

**Comment by dosomder** [comment] 2020-06-21 19:00
Ok so basically your idea is to listen to onTextChange event, then conver the `textView.text` to a a formatted text right? Well once you converted a word to an image, the next time the text changes the image is not part of the text property anymore (just as character 0xfffc, i.e. TextAttachment).

Let's make an example. Word "beach" gets converted to an image, all other character / words stay as is.

Type b -> text is "b" / set formatted text to "b"
Type e -> text is "be" / set formatted text to "be"
Type a -> text is "bea" / set formatted text to "bea"
Type c -> text is "beac" / set formatted text to "beac"
Type h -> text is "beach"  / set formatted text to **image**
Type x -> text is **"x" (not "beachx")**

**Comment by farfromrefug** [comment] 2020-06-21 19:28
Ok don't think it is the place to have such a discussion. But to close it what you want to do is totally feasible. you need to hold both the string version (edit) and the formattedstring. Then you need to write a parser to dynamically gonfrom the text version to the formatted version. I think This is exactly what the linked library does in the deminon their github page. Let s close that discussion here as it is not related to the initial issue

**Closed** 2020-06-30 05:18 UTC
Labels: bug
