### ISSUE TITLE
Nativescript building android errors

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/NativeScript#4200] opened 2017-05-16 06:22 UTC
I have a nativescript (3.0) application which I am developing on mac (ElCapitan). I am able to run the iOS emulator without a problem, but I cannot find a way to build the app for Android. I am getting the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'MyApp'.
> Flavor 'nativescript-telerik-ui' has unknown dimension 'nativescript-telerik-ui'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.004 secs
Command ./gradlew failed with exit code 1
```

I followed the nativescript documentation strictly, removed the android platform and added it again, reinstalled the Android SDK and tools, but without any success.

At this point I am out of ideas. Any help would be greatly appreciated.

Thank you.

**Comment by NickIliev** [comment] 2017-05-16 07:36
@dpdragnev can you share with us the content of your **package.json** file.

**Comment by dpdragnev** [comment] 2017-05-16 13:24
Sure.  Here it is:

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.VLMobile",
    "tns-ios": {
      "version": "3.0.0"
    },
    "tns-android": {
      "version": "3.0.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/router": "~4.1.0",
    "@progress/nativescript-telerik-ui-pro": "^2.0.1",
    "nativescript": "^3.0.1",
    "nativescript-angular": "~3.0.0",
    "nativescript-appversion": "^1.4.1",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "~3.0.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.1",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.4.0",
    "tns-platform-declarations": "^3.0.1",
    "typescript": "~2.2.1"
  }
}

```

Is there a problem with the latest version of the UI suite?

**Comment by dpdragnev** [comment] 2017-05-16 13:44
If it helps, I used the trial version of the Nativescript UI for a day or two before purchasing the full version.  I did uninstall the trial before installing the full version, but perhaps something stayed behind causing problems.

**Comment by dpdragnev** [comment] 2017-05-18 12:27
No suggestions?

**Comment by jvelezc** [comment] 2017-05-19 06:28
exact same scenario and we installed trial version then bought the pro one. We are using http://docs.telerik.com/devtools/nativescript-ui/getting-started npm way...

**Comment by NickIliev** [comment] 2017-06-05 07:47
@dpdragnev, @jvelezc I am sorry for the delay in my answer!
The issue is fully addressed as a bug [here](https://github.com/telerik/nativescript-ui-feedback/issues/191) and our developers are currently working on a fix.
Meanwhile, you can use [this workflow](https://github.com/telerik/nativescript-ui-feedback/issues/191#issuecomment-303009121) as a temporary solution

> For the time being, you can easily overcome this by placing the nativescript-telerik-ui-pro folder out of 
> @progress in node_modules at the same level with the other modules. This fixes it for me.

Closing as duplicate to [https://github.com/telerik/nativescript-ui-feedback/issues/191](https://github.com/telerik/nativescript-ui-feedback/issues/191)

**Closed by NickIliev** 2017-06-05 07:47 UTC
Labels: Android
