### ISSUE TITLE
TextBase UI components do not display as content view of UITableViewCell in {N} 3.0+

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/NativeScript#4670] opened 2017-08-08 12:05 UTC
_From @RVEIII on August 3, 2017 13:29_

I have an app where we allow the designer to modify a UITableView to display whatever {N} view they would like in the cells.  They simply write their code in typescript and give us information about where to find it.  As long as it implements the methods we need, we use it.

This worked for all {N} types we tried when we were using 2.5.  We upgraded to {N} 3.1.3 and we're seeing that all TextBase derived UI controls do not display.  They do display when we put them directly on a page.  But if we call over from native code to get the view, it displays as empty.

Here's what our ts code looks like:
```
import * as LabelModule from 'tns-core-modules/ui/label';

export class MySimpleExtension {
  public _label: LabelModule.Label;

  public view(): any {
    this._label = new LabelModule.Label();
    this._label.text = 'TESTING LABELS';
    return this._label;
  }
...
...
}
```

Here's what our native code does at cellForRow:
```
let cell = (tableView.dequeueReusableCell(withIdentifier: self.extensionReuseID))
      cell?.contentView.autoresizesSubviews = true
      if let view = sectionType.getView() {
        view.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        view.frame = (cell?.contentView.frame)!
        cell?.contentView.addSubview(view)
      }
      return cell!
```

If I switch view() to return a {N} switch control, it works fine.  If I use that view() method from a page in TypeScript code, it works fine.  It's just when I put it in a table view cell that it doesn't display the text.  

_Copied from original issue: NativeScript/ios-runtime#784_

**Comment by NickIliev** [comment] 2017-08-08 12:19
@RVEIII based on the provided code it is not entirely clear how the UITableView works and how the cells are created. For example what stands behind `sectionType.getView()` If possible please provide test project which best illustrates the described issue so we could investigate further.

**Comment by RVEIII** [comment] 2017-08-08 12:54
Hi @NickIliev - getView() is simply a call from our Swift code into our ts code.  Here's what that method does in Swift:

    return self.callback.perform(NSSelectorFromString("getView"), with: row as NSNumber!)?.takeUnretainedValue() as? UIView

From our ts code, getView simply returns the result of the view() method above.

**Comment by srinijonala** [comment] 2017-09-05 05:55
@RVEIII;@NickIliev 
Hi Guys:
Did you guys found any solution for this issue, any permanent / temp fix?
 
We also have same code, and also facing same issue, the view in the cell not visible.
	•	First time we can see the view.
	•	When we scroll down / up, so that the cell(view) goes to out of screen area.
	•	Scroll back to cell, the view in the cell disappears, we only see the blank area.
 
thanks
Srini

**Comment by hshristov** [comment] 2017-09-05 10:04
@RVEIII @srinijonala Please attach project where we can reproduce the issue.

**Comment by RVEIII** [comment] 2017-09-26 13:50
Hi @NickIliev  - Was there a fix for this issue?  I am unable to provide a sample application for this issue.  But the basic setup is to have a native UITableView in Swift.  That table view has a callback to display {N} views as the subview to the UITableViewCell's content view.

**Comment by RVEIII** [comment] 2017-10-12 12:36
Hi @NickIliev, @srinijonala, my application setup is not complicated.  I explained it before.  However, I'm not able to provide our code.

Can you please reopen this issue or tell me a work around/fix?

**Comment by NickIliev** [comment] 2017-10-12 12:42
@RVEIII I am reopening the issue - however without a code base to debug it is really hard to investigate what is happening. Perhaps, you can isolate the issue in a basic demo project instead of disclosing your application.

**Comment by RVEIII** [comment] 2017-10-16 20:00
Hey @NickIliev - I've started trying to build a sample app to reproduce this.  I've been pulled onto something else here but hopefully I'll have something to give you within a few days.  Thanks!

**Comment by RVEIII** [comment] 2017-10-17 16:47
Hey @NickIliev and @hshristov - I have created a repo with a sample app that shows this issue: https://github.com/RVEIII/TestApp

**Comment by hshristov** [comment] 2017-10-19 08:38
Hi @RVEIII,

Thank you for providing sample application. After some debugging I found out that you are creating NS views `MyLabelExtension().view().ios` but you never actually add them to NS view hierarchy. We did some optimizations so we set native values only when a NS view isLoaded is true, has parent and has nativeView. Since you didn't add Label anywhere to NS view hierarchy we didn't call any native setters so UILabel default text is null.

I don't know what is the scenario you are after but I will recommend to either your our ListView component or use directly native views only. Mixing both is not good because if you are not using our NS view hierarchy a lot of things won't work like - bindingContext, Layouts, Styling/CSS and some other optimizations we are doing under the hood.

In case you really want to mix both and you are ok losing all the goods of NS views you could set directly the text on the nativeView.
```
export class MyLabelExtension {
  public _label: Label;

  public view(): any {
    if (!this._label) {
      this._label = new Label();
      this._label.nativeViewProtected.text = 'Initial label';
      this._label.nativeViewProtected.backgroundColor = new Color('#aadbf7').ios;
    }

    return this._label;
  }

  public setLabel(text: any) {
    this._label.text = text;
  }
}
```

**Closed by hshristov** 2017-10-19 08:38 UTC
Labels: iOS, question
