### ISSUE TITLE
[iOS] SideDrawer does not stretch on iPhone X

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#5782] opened 2018-05-04 14:40 UTC
### Tell us about the problem

Here are cases based on the [template-tab-navigation-ts](https://github.com/NativeScript/template-drawer-navigation-ts).

### Which platform(s) does your issue occur on?

iOS

### Please tell us how to recreate the issue in as much detail as possible.

[Quick start](https://github.com/NativeScript/template-drawer-navigation-ts#quick-start):
```
tns create my-drawer-ts --template https://github.com/NativeScript/template-drawer-navigation-ts
```

### Screenshots

drawer-navigation-portrait-current
![drawer-navigation-portrait-current](https://user-images.githubusercontent.com/12251337/39633553-f769d268-4fc0-11e8-9139-afe6b23d655b.png)
Expected: SideDrawer content should span under the home indicator.

---

drawer-navigation-landscape-current
![drawer-navigation-landscape-current](https://user-images.githubusercontent.com/12251337/39633614-2cee19f8-4fc1-11e8-8d31-98b3ca11bf9d.png)
Expected: SideDrawer background should stretch.

**Comment by p-3** [comment] 2018-05-16 06:12
It is possible to get around this very easily with the help of safe areas (using - margins on iphone x). I am using this in multiple projects and it works flawfless. :D

Check out how Eddy has solved this in his plugins showcase project . https://github.com/EddyVerbruggen

**Comment by drewcovi** [comment] 2018-10-24 21:17
@p-3 not entirely flawless... these values would have to be adjusted on rotation.

**Comment by tsonevn** [comment] 2018-12-04 13:31
Hi all,
This issue should be fixed with the latest `nativescript-ui-sidedrawer` (v. 5.0.0). I will close the issue. If the issue appears again, I will reopen it.

**Closed by tsonevn** 2018-12-04 13:31 UTC
Labels: backlog, bug, os: ios

**Comment by stefan-kolb** [comment] 2019-03-15 14:02
@tsonevn I experience the same issue with `nativescript-ui-sidedrawer` (v6.0.0). However, I'm using the side drawer only on one page not as a global root sidedrawer. Is it possible that the issue was only fixed for the global case?

**Comment by tsonevn** [comment] 2019-03-19 07:47
HI @stefan-kolb,
Currently, by design, if you want to display  SideDrawer, which is shown above the ActionBar, you need to define the Drawer as a root component. In your case, you can disable the RadSideDrawer on some of the pages by setting up `gesturesEnabled` property to `false`.

**Comment by stefan-kolb** [comment] 2019-03-19 07:53
@tsonevn Is the homeindicator on the bottom part of the action bar? I'm not referring to the action bar but the bottom of the screen.
![image](https://user-images.githubusercontent.com/2141507/54588896-7ee92f00-4a24-11e9-9d71-a43f17366f8d.png)

**Comment by tsonevn** [comment] 2019-03-20 06:59
Hi @stefan-kolb,
The blue line, shown below the SideDrawer might be related to some global CSS style that might apply this background color to the Drawer component. Keep in mind that this is only an assumption. It will help if you can provide the project, that will help us in investigating further, where this line comes from.

**Comment by stefan-kolb** [comment] 2019-03-20 12:52
Hi @tsonevn,

here's a demo project which reproduces the issue:
https://play.nativescript.org/?template=play-ng&id=9dMwDw&v=25

![image](https://user-images.githubusercontent.com/2141507/54685476-3199ba00-4b17-11e9-903f-17756d24bbf8.png)

![image](https://user-images.githubusercontent.com/2141507/54685496-3d857c00-4b17-11e9-89fe-9da9fbea718d.png)

In Android, the page including the background and the drawer spans the whole page.

**Comment by tsonevn** [comment] 2019-03-21 07:32
Hi @stefan-kolb,
Thank you for the demo project. I discussed your case with the dev team and it seems that this is expected behaviour(the RadSideDrawer not to be stretched) when the component is nested inside the page. On that matter, I would suggest opening a new feature request in the  [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback/issues) repository, for providing support for your scenario.
Meanwhile, as I suggested in my previous comment, you can set up the Drawer as root and you can disable it on some of the pages by setting up `gesturesEnabled` property to `false`.

**Comment by stefan-kolb** [comment] 2019-03-21 08:38
Hi @tsonevn,

how can this be expected behavior? If the side drawer is used in the app component it also stretches.
Furthermore, on Android it stretches expectedly or am I using just a wrong Android device? This feels like a bug to me. Also, disabling the side drawer on every page (there might be quite a few) feels like a hack (and it is even pretty hacky to do so, as the side drawer is not immediately available to the page. If I'm not mistaken it was something like:

```typescript
`ngAfterViewInit() {`
    // use setTimeout otherwise there is no getRootView valid reference
    setTimeout(() => {
        const drawer = <RadSideDrawer>app.getRootView();
        drawer.gesturesEnabled = false;
    }, 100);
}
```

Additionally, if I move the side drawer to the root component, I get problems with the side drawer and `ScrollView` on pages. It will disable scrolling and hide form fields when the soft keyboard comes up.

**Comment by tsonevn** [comment] 2019-03-22 06:47
Hi @stefan-kolb,
In the introduction of the [safe area feature](https://developer.apple.com/documentation/uikit/uiview/positioning_content_relative_to_the_safe_area) for iOS, a few changes were made on the RadSideDrawer component for its properly layouting. Those changes currently affect only the cases when the component is used as a root container. On that matter, since the case(not stretched SideDrawer inside the child component) is related to the safe area iOS feature, in my opinion [nativescript-ui-feedback#1058](https://github.com/telerik/nativescript-ui-feedback/issues/1058) is more likely a feature request rather then a bug reported.
On Android, there is no Safe Area and the RadSideDrawer will be stretch correctly in both scenarios( while using the component as root or inside the child components).

Regarding the solution with `gesturesEnabled = false`. Once SideDrawer is defined as a root container, you should be able to access it without the timeout. As a reference, you can check our [template-drawer-navigation-ng](https://github.com/NativeScript/template-drawer-navigation-ng) template.

About the ScrollView, you can try nesting it inside a `GridLayout`, which should solve the issue.

**Comment by tsonevn** [comment] 2019-03-22 07:25
HI @stefan-kolb,
I've discussed the case again with the team and we've decided to mark issue  https://github.com/telerik/nativescript-ui-feedback/issues/1058 as a bug, which we will investigate further. For now, I would suggest keeping track on issue https://github.com/telerik/nativescript-ui-feedback/issues/1058 for further info.
