### ISSUE TITLE
Don't automatically dismissSoftInput() on return pressed

### ISSUE THREAD

**Issue by bernica** [NativeScript/NativeScript#8287] opened 2020-01-28 17:19 UTC
**Is your feature request related to a problem? Please describe.**
When implementing a textField with _next_ return key type, the keyboard is dismissed and focusing another textField brings it back BUT a flick is produced.

**Describe the solution you'd like**
I'd like to be able to prevent the textFieldShouldReturn implementation from always dimissing soft input.

**Describe alternatives you've considered**
Modify the implementation for it to check a user set flag.

**Additional context**
The code is in https://github.com/NativeScript/NativeScript/blob/master/nativescript-core/ui/text-field/text-field.ios.ts#L69

**Comment by NickIliev** [comment] 2020-01-29 13:18
@bernica the implementation is by design to handle cases where you have multiple stacked text-fields. When pressing return from one text-field the user should go to the other (which is why we are automatically closing the keyboard on pressing return).

**Closed** 2020-03-20 08:19 UTC
Labels: feature, good first issue
