### ISSUE TITLE
[iOS] ListView on initial load not displaying last item

### ISSUE THREAD

**Issue by praven07** [NativeScript/NativeScript#3818] opened 2017-03-17 06:40 UTC
I tried to use the ListView and it kinda displays weird it does not size properly.
You can see the problem when you scroll the view.

<img width="383" alt="screen shot 2017-03-17 at 1 39 02 am" src="https://cloud.githubusercontent.com/assets/2223191/24031794/8c6232b6-0ab2-11e7-8208-48c5a33b26ec.png">

<img width="379" alt="screen shot 2017-03-17 at 1 39 40 am" src="https://cloud.githubusercontent.com/assets/2223191/24031810/9ebc4df2-0ab2-11e7-9648-5ddf86b1d1c2.png">

**Comment by NickIliev** [comment] 2017-03-17 07:13
Hi @praven07, please provide more information regarding your issue
- on which platform this occurs (Android or iOS)
- code snippet used for creating ListView including the CSS styling (orr a sample project to reproduce the issue)

As a possible workaround keep in mind that if you are creating ListView in iOS, you need to wrap in a container with predefined sizes.(meaning that if your ListView is wrapped in a StackLayout with no sizes similar clipping might occur)

**Comment by praven07** [comment] 2017-03-17 18:48
It's on iOS. I just created a new angular project and I removed the some of the items and just left like 4 items and It creates this problem. If you see the 4th item is hidden so you would have to scroll to view the item. But when you click on an item and navigate to the details page and then come back to the main page it resizes correctly. As you can see in the 3rd screenshot. 

![screen shot 2017-03-17 at 1 41 20 pm](https://cloud.githubusercontent.com/assets/2223191/24058073/b4f97c4c-0b17-11e7-926c-bea47e427c1c.png)

<img width="487" alt="screen shot 2017-03-17 at 1 41 07 pm" src="https://cloud.githubusercontent.com/assets/2223191/24058063/b05dbfd6-0b17-11e7-8780-dbd3feefb597.png">

<img width="487" alt="screen shot 2017-03-17 at 1 46 20 pm" src="https://cloud.githubusercontent.com/assets/2223191/24058185/229177a0-0b18-11e7-919f-e21f2584b6e8.png">

**Comment by NickIliev** [comment] 2017-03-28 10:12
Hey @praven07 first of all please excuse me for my late answer!
I tested the described case and indeed it seems that on initial load the ListView is not displaying the last loaded item. However, if some navigation is initialized to the list view then the item is loaded.

Project to reproduce this issue can be found [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_3818)

Steps to reproduce:
- just open the application. On initial load we expect the LiastView to show all 4 items (players) **however, it shows only 3**
- navigate to some player details page and then come back to the main page - now the ListView is loading all four items as expected 

Observable only in iOS (works as expected in Android)

**Comment by pursuitofepic** [comment] 2017-05-06 16:17
I just ran into this as well. I was able to get it to stop doing this by setting a height for the ListView. So it seems like the ListView is not sized correctly on initial load, but is when you navigate back to it. 

I also noticed that the more items in the list, the more is missing from the bottom. So it seems to be taking a bit from each item off the bottom.

**Comment by praven07** [comment] 2017-05-17 02:39
is there any solution to this?

**Comment by leoelcoder** [comment] 2017-07-12 21:52
Hey I have the same problem and I think that this is the problematic situation:
UITableView iOS take items height without padding or margin and with that value set the listView height.

I have a temporal solution:

`<ListView items="{{ items }}" loaded="tableLoaded">`

In JS:

```
export function tableLoaded(args) {
    args.object._ios.rowHeight = UITableViewAutomaticDimension;
    args.object._ios.estimatedRowHeight = 120;
}
```

The code above tell to UITableView native component to set an automatic dimension and set then
an estimated item height in my case with margin and padding is above 120
all you need is adjust the `estimedRowHeight` value to your needs.

**Comment by marco-gagliardi** [comment] 2017-07-26 14:44
Same problem here. List items are loaded from a static json object.The last item is hidden on page load, then it appears when navigating to another page and then back.  (Everything works fine on Android)

**Comment by marco-gagliardi** [comment] 2017-07-31 13:46
Any news about this issue or any workaround for NS + Angular?

**Comment by vakrilov** [comment] 2017-10-18 12:49
One work-around I found is to put the list-view inside a `GridView` instead of `StackLayout`:
```
<GridLayout class="page">
    <ListView [items]="items" class="list-group">
        <ng-template let-item="item">
            <Label [nsRouterLink]="['/item', item.id]" [text]="item.name"
                class="list-group-item"></Label>
        </ng-template>
    </ListView>
</GridLayout>
```

Probably in the root of the bug is that when the list-view is inside a stack-layout. The stack requests the size form the list which probably reports wrong size. When the list view is inside a container with fixed height - it will just fill all the space given to it.

**Comment by zenz** [comment] 2017-10-26 02:07
So, it's still not fixed in 3.3......

**Comment by mudlabs** [comment] 2018-01-14 23:14
Still not working as expected in 3.4, last item not displayed (ever).

My workaround for now is the add a fake empty item to the end of the list.

**Closed** 2018-03-22 12:03 UTC
Labels: bug, in progress, os: ios, severity: high

**Comment by slolam** [comment] 2018-04-28 20:40
I had the same problem and the culprit was the border-bottom-left-radius and border-bottom-right-radius that was limiting the height of the list scroll. If I see capture view hierarchy on XCode while debugging, I could see the items but not displayed. I removed border-bottom-* styles and it started to show all the rows
