### ISSUE TITLE
[NS8][Webpack5] Wrong bundling in release build

### ISSUE THREAD

**Issue by PackagedCat** [NativeScript/NativeScript#9358] opened 2021-04-26 19:54 UTC
**Environment**
 - CLI: 8.0.1
 - Cross-platform modules: 8.0.3
 - Android Runtime: 8.0.0
 - Webpack: 5.0.0-beta.9
 - Plugin: @nativescript-community/ui-material-button

**Describe the bug**
In release build on app launch I geting error `ReferenceError: androidElevationProperty is not defined`. I looked at the vendor.js and there really was no declaration of this variable. On debug build it works fine and vendor.js has implementation of this properties. In NS7 there is no such problem.

**To Reproduce**
`ns create demo --ts --vue`
`ns plugin add @nativescript-community/ui-material-button`
`*importing plugin*`
`ns build android --release ...`

**Stack trace**
```
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
    ReferenceError: androidElevationProperty is not defined
    File: (file:///data/user/0/***/files/app/vendor.js:2:17209)

    StackTrace:
    5055(file:///data/user/0/***/files/app/vendor.js:2:17210)
        at __webpack_require__(file:///data/user/0/***/files/app/bundle.js:1:112605)
        at 2670(file:///data/user/0/***/files/app/vendor.js:2:414)
        at __webpack_require__(file:///data/user/0/***/files/app/bundle.js:1:112605)
        at 5865(file:///data/user/0/***/files/app/bundle.js:1:111613)
        at __webpack_require__(file:///data/user/0/***/files/app/bundle.js:1:112605)
        at (file:///data/user/0/***/files/app/bundle.js:1:112814)
        at __webpack_require__.O(file:///data/user/0/***/files/app/bundle.js:1:113304)
        at __webpack_require__.x(file:///data/user/0/***/files/app/bundle.js:1:113004)
        at __webpack_require__.x(file:///data/user/0/***/files/app/bundle.js:1:114554)
        at (file:///data/user/0/***/files/app/bundle.js:1:114585)
        at (file:///data/user/0/***/files/app/bundle.js:1:114688)
        at require(:1:266)
```

**Comment by NathanWalker** [comment] 2021-04-27 05:06
This could be webpack5 being aggressive with terser settings in production mode whereby removing references if not used since that property maps to an empty method here:
https://github.com/nativescript-community/ui-material-components/blob/1e017bf88896e83a359bc1b881d1a4b0eef10de6/src/button/button.android.ts#L131

@farfromrefug any thoughts?

**Comment by NathanWalker** [comment] 2021-05-04 18:54
@PackagedCat when you get a chance could you try adding this inside your webpack.config.js:

```
module.exports = (env) => {
  webpack.init(env);

  webpack.chainWebpack(config => {
    config.optimization.minimizer = [
        new TerserPlugin({
            parallel: true,
            terserOptions: {
                ecma: 2017,
                module: true,
                output: {
                    comments: false,
                    semicolons: false
                },
                compress: {
                    collapse_vars: env.platform !== 'android',
                    sequences: env.platform !== 'android',
                    passes: 2,
                    drop_console: !!env.production
                },
                keep_fnames: true
            }
        })
    ];
});
```

**Comment by PackagedCat** [comment] 2021-05-04 21:27
@NathanWalker added this changes but issue still persists.

if I understand correctly, the problem is that the property used only in empty method, and Webpack mistakenly excludes it, but it does it even after I added it to it `console.log("")`. Is there some temporary hack to get around this?

**Comment by NathanWalker** [comment] 2021-05-05 00:22
We're curious by the report definitely. We are making release builds with {N} 8 and that same version of @nativescript/webpack (using latest) and not running into the issue. But curious if some certain code setup may lead you to it. Possible to share that particular project (even privately) and/or if you saw a small repro case from a project setup with similar where we could look at it in more detail. We have not yet been able to repro it.

**Comment by NathanWalker** [comment] 2021-05-05 00:23
It'd also help to share the full build command you're using.

**Comment by PackagedCat** [comment] 2021-05-05 10:27
Here is a demo example where the error occurs.

[demo.crash.zip](https://github.com/NativeScript/NativeScript/files/6426374/demo.crash.zip)

The build command:
`ns build android --release --key-store-path *keystore* --key-store-password *keypassword* --key-store-alias *alias* --key-store-alias-password *password*`

**Comment by NathanWalker** [comment] 2021-05-05 17:31
Excellent thanks for this!

**Comment by tinybigideas** [comment] 2021-05-10 07:08
Also suffering with this issue. Is there a way to hack around this issue for the time being?

**Comment by NathanWalker** [comment] 2021-05-10 15:21
@tinybigideas @PackagedCat in meantime while we are implementing a fix in webpack for this case, you can do this:

1. set your devDependencies to this:
```
"@nativescript/webpack": "~4.1.0",
```

2. Delete `webpack.config.js`

3. `npm install --legacy-peer-deps` (This will generate a fresh webpack.config.js)

- Install sass if using .scss files in project: `npm install sass -D --legacy-peer-deps`

- If using Vue, be sure to install the following: 
- `npm install vue-loader @babel/core @babel/preset-env babel-loader -D --legacy-peer-deps`
- You may also want to add `'global.__DEV__': !production,` to `new webpack.DefinePlugin({` section -- the sample app provided used that.

4. In `package.json`, change to `"main": "app.js"` (or if using Angular or any other with a main bootstrap file), change to `"main": "main.js"`

5. Run app and confirm runs just the same. Now make the release build. 

We'll close this issue once we have the webpack5 fix out.

**Comment by rigor789** [comment] 2021-05-27 10:38
Still looking into the details, but a workaround is to disable webpack's export tracking with 

```js
webpack.chainWebpack(config => {
  config.optimization.usedExports(false)
})
```

What's happening is that (in this particular case) the class in `ui-material-core`: 

https://github.com/nativescript-community/ui-material-components/blob/e0fbd59f678a23214958d5895e3185e6a6241cba/src/core/index.android.ts#L286-L295

is detected as unused in the app (since it's not exported, and the `installMixins`/`overrideViewBase` functions are not called) - however webpack doesn't drop it from the `vendor` chunk - and it's definition stays as-is. The imports for those 2 properties aren't converted to proper webpack imports either, so we end up with `undefined.setNative` that crashes...

`vendor.js` ends up looking like this: 
```js
class ViewOverride extends (/* unused pure expression or super */ null && (View)) {
    [androidElevationProperty.setNative](value) {
        this[elevationProperty.setNative](value);
    }
    [androidDynamicElevationOffsetProperty.setNative](value) {
        this[dynamicElevationOffsetProperty.setNative](value);
    }
}
```

If we opt-out of the used exports tracking, webpack processes it correctly:
```js
class ViewOverride extends view_index_android.View {
    [style_properties.androidElevationProperty.setNative](value) {
        this[elevationProperty.setNative](value);
    }
    [style_properties.androidDynamicElevationOffsetProperty.setNative](value) {
        this[dynamicElevationOffsetProperty.setNative](value);
    }
}
```
(`style_properties` is defined)

**Comment by edusperoni** [comment] 2021-06-23 18:01
This has been fixed in webpack 5.40.0 https://github.com/webpack/webpack/releases/tag/v5.40.0

https://github.com/webpack/webpack/issues/13575
https://github.com/webpack/webpack/pull/13590

**Comment by bmacdonald** [comment] 2021-07-15 12:58
@NathanWalker @rigor789 - Any updates on this issue?

We would like to move to the newer webpack model.
Here is a reference to my other issue which was marked as a duplicate of this.

#https://github.com/NativeScript/NativeScript/issues/9422

**Comment by rigor789** [comment] 2021-07-15 13:31
This has been fixed as far as I'm aware, partially by our changes and a webpack update with a fix for an issue @edusperoni reported.

**Closed** 2022-06-24 19:48 UTC
Labels: in progress, solution posted
