### ISSUE TITLE
5.4.0 update to webpack breaks background-color and background-image properties

### ISSUE THREAD

**Issue by SephReed** [NativeScript/NativeScript#7259] opened 2019-05-17 15:59 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.4.0 version and is up to date.
✔ Component tns-core-modules has 6.0.0-next-2019-05-16-141945-01 version and is up to date.
✔ Component tns-android has 6.0.0-2019-05-16-172644-03 version and is up to date.
✔ Component tns-ios has 6.0.0-2019-05-16-165318-01 version and is up to date.

**Describe the bug**

I'm posting this early to get prepared for 6.0.0.  I tried using the webpack bundler for my app and a lot of my styling ended up breaking.  It was largely in regards to background image and color on components.

**To Reproduce**

Set `"useLegacyWorkflow": false` and use background-images and colors.  I can't imagine any reason it would happen...

**Expected behavior**
Styling should be the same before and after.

**Sample project**

I'll have to create one of these later

**Additional context**

The reason I'm posting this is to get an early start on working towards fixing these problems.  As long as 6.0.0 has not yet been released, I can hold back on diving into this... it isn't yet a priority.  Still, lots of ui bugs came from switching to webpack for me.

**Comment by SephReed** [comment] 2019-05-17 16:04
Here's some pics of before and after:
### Legacy workflow true
<img width="342" alt="Screen Shot 2019-05-17 at 11 00 05 AM" src="https://user-images.githubusercontent.com/14002040/57941045-70d45500-7893-11e9-998d-c973bd1e0fed.png">
<img width="318" alt="Screen Shot 2019-05-17 at 11 00 17 AM" src="https://user-images.githubusercontent.com/14002040/57941046-70d45500-7893-11e9-99e3-7790b592e818.png">
<img width="347" alt="Screen Shot 2019-05-17 at 11 00 45 AM" src="https://user-images.githubusercontent.com/14002040/57941047-70d45500-7893-11e9-9abe-4e2837d31dd7.png">

### Legacy workflow false
<img width="332" alt="Screen Shot 2019-05-17 at 11 02 05 AM" src="https://user-images.githubusercontent.com/14002040/57941048-70d45500-7893-11e9-9852-bd9a86b9708d.png">
<img width="285" alt="Screen Shot 2019-05-17 at 11 02 19 AM" src="https://user-images.githubusercontent.com/14002040/57941049-716ceb80-7893-11e9-9435-210246e5dcef.png">
<img width="347" alt="Screen Shot 2019-05-17 at 11 03 00 AM" src="https://user-images.githubusercontent.com/14002040/57941050-72058200-7893-11e9-84f5-71b601ce2969.png">

**Comment by NickIliev** [comment] 2019-05-20 07:18
@SephReed can you post the code and styles behind the screenshots?

**Comment by SephReed** [comment] 2019-05-20 18:47
The button is "BacklitButton."  It uses multiple layers of padding with a background color to get a background shadow.

```
.BacklitButtonShadow {
	width: 230;

	&.accent {
		.ShadowLayer { background-color: transparentize($accent, 0.97); }
		.BacklitButtonBorder { background: linear-gradient(to bottom right, $accent, $accentDark); }
	}



	.ShadowLayer {
		border-radius: 100;
               padding: 1;
	}

	.BacklitButtonBorder {
		padding: 4;
		border-radius: 100;

		&>.BacklitButton {
			background-color: $bg;
			border-radius: 100;
			padding: 10;
			justify-content: center;
			font-weight: 700;
			// color: green;
		}
	}

	&.--disabled {
		.ShadowLayer { background-color: transparent; }
		.BacklitButtonBorder {
			background: $borderLight;
			color: $fgInactive;

			&>.BacklitButton {
				@extend %weightLight;
				background-color: transparent;
			}
		}
	}
}
```


The other one is just a background image only applied in some circumstances.  The blue arrow is `right_arrow_ready.png`

```
	&>.FollowLink {
						padding: 15 20 10 15;
						width: 100%;
						border-bottom-left-radius: 5;
						border-bottom-right-radius: 5;
						justify-content: space-between;
						align-items: center;

						&.--active {
							background-color: $bgFade1;
						}

						&.--intro_unseen {
							&>.LinkArrow {
								color: $bg;
								background: $border;

								&>.Icon {
									background-image: url("~/images/icons/ui/right_arrow_inactive.png");
								}
							}

							&.--has_results > .LinkArrow {
								// background: linear-gradient(to bottom right, $accent, $accentDark);
								background-image: url("~/images/icons/ui/right_arrow_ready.png");
							}
						}
```

Where that black arrow is is the same place any of the icons should ever go.

**Comment by NickIliev** [comment] 2019-05-27 11:58
@SephReed regarding `It uses multiple layers of padding with a background color to get a background shadow.`

With `tns-core-modules@5.4.0` wee now have implemented elevation (so you could apply shadow on elements like Button - see[ this PR that will push a new documentation example](https://github.com/NativeScript/docs/pull/1659/files) on how to use the new property.

The same functionality changed the default behavior of the NativeScript's Button element so there might be some side effects in your code. Overall I would recommend using the new property to apply shadows and elevation. See this thread for [a similar issue](https://github.com/NativeScript/NativeScript/issues/7266)

**Comment by SephReed** [comment] 2019-05-28 17:02
I saw the bit about shadow, but it didn't appear to handle colored dropshadows.

In any case, this should not break anything, and is unrelated to other issues I was seeing in the rendering.

**Comment by vakrilov** [comment] 2019-06-25 06:39
Hi @SephReed 
We are trying to isolate the issue, but we have a hard time reproducing it. Can you please try to isolate the issue in a project and send it to us.
This issue might also be related to https://github.com/NativeScript/NativeScript/issues/7308 which seems to be resolved when using the versions from `next`.

**Comment by SephReed** [comment] 2019-06-26 00:29
I'm pretty sure most of it was an issue with css classes using "--my-classname", for which there is currently an issue open.  I've since fixed it, and I don't remember the details of how, but I think the primary route was not using flag notation for css classes.

**Comment by vakrilov** [comment] 2019-06-28 07:00
Ok - I'm closing this issue then.
Will reopen it if needed.

**Closed by vakrilov** 2019-06-28 07:00 UTC
Labels: needs more info
