### ISSUE TITLE
webview not displaying images

### ISSUE THREAD

**Issue by dbay920** [NativeScript/NativeScript#5504] opened 2018-03-06 21:43 UTC
### Tell us about the problem
**I'm using webview to display my website's wordpress blog as a view in my app. The main page is fine but when you go to a single post, the image does not display (see screenshot)**

![webview](https://user-images.githubusercontent.com/4195311/37060084-40743968-215d-11e8-88c3-067c7f9c917e.png)

### Which platform(s) does your issue occur on?
**Both**

### Please provide the following version numbers that your issue occurs with:
- CLI: **3.2.1**
- Cross-platform modules: **3.4.1**
- Runtime(s): **3.2.0**

### Please tell us how to recreate the issue in as much detail as possible.
[https://github.com/dbay920/phn-app.git](https://github.com/dbay920/phn-app.git)

**./app/news/ - the affected view directory**

**Comment by tsonevn** [comment] 2018-03-07 07:32
Hi @dbay920,
Thank you for the attached sample project. 
I tested it on our side, however, was unable to recreate the issue. For your convenience, I am attaching Screenshots for iOS and Android. 

ios
![screen shot 2018-03-07 at 9 23 55 am](https://user-images.githubusercontent.com/17448734/37079173-5aed7466-21ea-11e8-8a47-c399678b418f.png)

android
![angleropr6 170623 019ntsonev03072018092128](https://user-images.githubusercontent.com/17448734/37079197-6c78ccbc-21ea-11e8-82d7-2f453ccb1543.png)


Regarding that, could you check if the problem images are related to some temporary issue with the image URL? 

Also, I notice that you are using an old version of the modules and runtime and I would suggest updating to the latest version. 
1. `tns plugin remove tns-core-modules`
2. `tns plugin add tns-core-modules`
3. `tns platform remove android`
4. `tns platform add android`
5. `tns platform remove ios`
6. `tns platform add ios`

**Comment by dbay920** [comment] 2018-03-07 14:18
Thanks for testing but it looks to me like you are at the landing page for the News view. You need to tap on a blog post title or the continue reading button to see the issue I am having. I will take your advice and update my modules.

**Comment by dbay920** [comment] 2018-03-07 15:13
So I just figured this out! I noticed that literally every image we are using for the blog has either a dash or an underscore included in the name. By replacing an existing image with one that had a text only name the image displays in my app. This is really unusual since other images on our site with dashes/underscores do display in the app. Maybe it has something to do with wordpress

**Comment by tsonevn** [comment] 2018-03-08 07:56
Hi @dbay920,
Indeed it might be related to an issue with the image URL generated by WordPress. 
Regarding your last comment, I have considered that the problem is fixed and we could close the issue.

**Closed by tsonevn** 2018-03-08 07:56 UTC
Labels: needs more info
