### ISSUE TITLE
After wrong import path have to restart client

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [NativeScript/NativeScript#8520] opened 2020-04-11 17:58 UTC
I am always facing issue that i have to restart android client if i define some wrong import path.
Steps to reproduce:
1) run tns android
2) add wrong path to some file and save
3) after webpack watch rebuilds it shows an error
4) fix import and save again

console shows no erros and says that solution is synced to emulator however after sync is complete emulator still shows same error.

This behaviour is very annoying because it forces me to restart client many times

**Comment by NickIliev** [comment] 2020-04-13 05:53
I tried to reproduce the issue while using t[his demo app](https://github.com/NickIliev/NS-Issues-2020/tree/master/NativeScript/issue-8520) but to no avail. 

Closing due to not enough information provided.

**Closed by NickIliev** 2020-04-13 05:53 UTC
