### ISSUE TITLE
TextView auto height sort of works

### ISSUE THREAD

**Issue by dottodot** [NativeScript/NativeScript#6699] opened 2018-12-11 19:10 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules: 5.0.5
 - Android Runtime: n/a
 - iOS Runtime: 5.0.0
 - Plugin(s): nativescript-angular

**Describe the bug**

I know this has been raised before and I guessing it's considered fixed as they have been closed but I'm sure not the TextView auto height is working as it should. For example on the first return the first line of text gets cut off, then second return it's all ok, but then third return it gets cut off again. i.e every alternate return causes the text to be cut off as you see in the gif below.

![textview 2018-12-11 18_51_43](https://user-images.githubusercontent.com/811652/49823139-e5501880-fd76-11e8-9a74-2acac800580d.gif) 

**To Reproduce**

I'm using Angular Reactive Forms if that's at all related  but does the same on Playground so probably the same everywhere
```
<StackLayout [formGroup]="group">
  <TextView formControlName="description"></TextView>
  <StackLayout class="hr-light"></StackLayout>
</StackLayout>
```
**Expected behavior**
TextView should increase in size in a smooth manner and all text should be visible at all times.

**Sample project**

https://play.nativescript.org/?template=play-ng&id=nGVjMM

**Comment by tsonevn** [comment] 2018-12-12 05:56
Duplicate of https://github.com/NativeScript/NativeScript/issues/6658

**Closed by tsonevn** 2018-12-12 05:56 UTC
Labels: tab-view
