### ISSUE TITLE
Custom Fonts not displaying all weights iOS

### ISSUE THREAD

**Issue by cfoulkes** [NativeScript/NativeScript#5951] opened 2018-06-14 00:03 UTC
### Tell us about the problem
I've added a set of Custom Fonts in the app/fonts folder  in a new nativescript angular app, and displayed a label for each font weight.

Not all weights are being shown (100,200 and 300 are all using the same font/weight).

When I open the individual .otf files in xcode the contained fonts display with different weights, so the otf contents seem fine.

It appears that the fonts are not being mapped to the weights properly?
Is there something else I need to do to show all the font weights correctly?

Thanks 
Colin

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0
- Cross-platform modules: 4.1.0
- Runtime(s): "tns-ios" 4.1.0

### Please tell us how to recreate the issue in as much detail as possible.
add fonts from https://github.com/JulietaUla/Montserrat/tree/master/fonts/otf

![image](https://user-images.githubusercontent.com/2602584/41384336-c2d3a242-6f3a-11e8-94f7-be7c9bed5fb1.png)

 

### Is there code involved? 

add to css

.label {
    margin: 10;
    font-size: 20;
}

.w100 {
    font-weight: 100;
}

.w200 {
    font-weight: 200;
}

.w300 {
    font-weight: 300;
}

.w400 {
    font-weight: 400;
}

.w500 {
    font-weight: 500;
}

.w600 {
    font-weight: 600;
}

.w700 {
    font-weight: 700;
}

.w800 {
    font-weight: 800;
}

.w900 {
    font-weight: 900;
}

.bold {
    font-weight: bold;
}

.montserrat {
    font-family: Montserrat;    
}

and html

    <StackLayout col="1" class="label montserrat">

        <Label text="Montserrat"></Label>
        <Label text="ABCD efgh 100" class="w100"></Label>
        <Label text="ABCD efgh 200" class="w200"></Label>
        <Label text="ABCD efgh 300" class="w300"></Label>
        <Label text="ABCD efgh 400" class="w400"></Label>
        <Label text="ABCD efgh 500" class="w500"></Label>
        <Label text="ABCD efgh 600" class="w600"></Label>
        <Label text="ABCD efgh 700" class="w700"></Label>
        <Label text="ABCD efgh 800" class="w800"></Label>
        <Label text="ABCD efgh 900" class="w900"></Label>
        <Label text="ABCD efgh bold" class="bold"></Label>

    </StackLayout>

On iOS I get... (shown next to equivalent labels using the default font)

![image](https://user-images.githubusercontent.com/2602584/41384444-6cd6217a-6f3b-11e8-8e86-d03d89c92f5d.png)

**Comment by tsonevn** [comment] 2018-06-14 05:30
Duplicate of [#5920](https://github.com/NativeScript/NativeScript/issues/5920)

**Closed by tsonevn** 2018-06-14 05:30 UTC

**Comment by cfoulkes** [comment] 2018-06-14 10:58
Thanks tsonevn, 
but my reading of issue #5920 appears to be problem with the font being registered as Solid vs UltraBlack.

Whereas this appears to have the individual fonts correctly named but not picked up.


Colin

**Comment by AresDev** [comment] 2018-10-05 16:49
This issue is annoying, we can use custom fonts but font variants are not supported in iOS and wherever I search they say that we use font-weight but when I use it, the font goes back to default. Has anyone had a workaround of this? I've read that changing font names with a font editor but I had no luck, maybe I'm doing something wrong.
