### ISSUE TITLE
1.3 - Can not build new project due to missing App_Resources

### ISSUE THREAD

**Issue by emiloberg** [NativeScript/NativeScript#763] opened 2015-09-17 13:20 UTC
Feel free to move this to the correct repo if needed.

As of 1.3, when creating a new project, it is unbuildable on Android due to missing App_Resources-folder.

When creating a new project:
```
tns create clean
cd clean
tns platform add ios
tns platform add android

tns deploy android --device 1
```

This fails with:

```
/Users/emiloberg/code/slask/clean-nativescript-project/clean/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml:24:23-37 : No resource found that matches the given name (at 'icon' with value '@drawable/icon').

:processDebugResources FAILED

FAILURE: Build failed with an exception.
```

Reason for this is because there is no `App_Resources` folder (and it's content) in the `app` folder. When copying an `App_Resources` folder from another project, the build works.

I'd say this is quite major as new users can not create their first project.

(The project is buildable on iOS as iOS do not need an app icon).

**Comment by NathanaelA** [comment] 2015-09-17 18:43
I can confirm this -- I created a brand new project, **tns create test123** then **tns platform add android** then **tns.cmd run android --emulator --geny**  it fails with the exact error:
AndroidManifest.xml:24:23-37 : No resource found that matches the given name (at 'icon' with value '@drawable/icon').

**Comment by NathanaelA** [comment] 2015-09-18 00:27
For anyone else who runs into this; until the template is fixed; you can download the App_Resource fodler in a compressed zip from http://nativescript.rocks

**Comment by dtopuzov** [comment] 2015-09-18 08:11
Hi, this should be npm cache issue, please run:
npm cache clean 
or manually delete your npm cache folder (at lest tns-* folders)

**Comment by emiloberg** [comment] 2015-09-18 08:43
Working. Running 

```
npm cache clean
tns create newproject
```

will create a project with the `App_Resources`-folder.

Ouch, this could be kinda hard to figure out, even for the seasoned developer. Hmm, is it possible to do a clean (or at least a check if clean is needed) as a part of the postinstall of nativescript?

**Comment by dtopuzov** [comment] 2015-09-18 08:50
We will try to provide some fix in next release of {N}, may be CLI will clean cache (only tns-* folders if possible) on installation.

**Comment by NathanaelA** [comment] 2015-09-18 09:16
So did you accidentally release a faulty **tns-template-hello-world** because the v1.3.0 I had, is different than the v1.3.0 that is being currently up on npm...

**Comment by rosen-vladimirov** [comment] 2015-09-18 09:20
Hi @NathanaelA ,
The release version is not incorrect. The problem is with the npm cache itself, it somehow misses the AppResources directory. When you clean the cache, the template is downloaded again and it is the real one with AppResources dir.

**Comment by NathanaelA** [comment] 2015-09-18 10:14
@rosen-vladimirov -- I understand the copy I got in my cache was incorrect; what my question was is how did it happen.  How did I manage to get a version of tns-template-hello-world (& Emilo) that was a full tgz, tagged as v1.3.0 that is different than the final release?

Did you accidentally release a version that somehow got tagged as v1.3.0 in the NPM cache?   Or is their some other way you are populating the npm cache?     I'm looking at the package.json file that was in the faulty package.tgz v1.30 and it also says v1.30   However, this package.json is quite a bit different from the release one.   In fact it actually looks almost exactly like this one:
https://github.com/NativeScript/template-hello-world/blob/53852631837dbf149a0e48af4c555ef55949dffe/package.json#L19 Where it has the repo pointing to the nativescript/nativescript/commit/commit_id and has none of the extra information in it.

**Comment by NathanaelA** [comment] 2015-09-19 06:36
@rosen-vladimirov / @dtopuzov / @valentinstoychev 

Please note, the reason I ask this question is so that maybe we can figure out why it occurred so that maybe something can be done so this can't / won't occur in the future.   

The npm cache was not corrupt it actually had a valid v1.30; even the **bad** package.json states it is 1.30 -- but we need to figure out WHERE it came from -- how/where did npm get it from?      This is the question.    I don't know how I got it or how Emilo also got it.     If a new person who was just trying out NativeScript and they got it; that might have been enough to make them quit.   So to me this is a very important question on where a "Different" installable but broken version of v1.30 tns-template-hello-world came from.

**Comment by NathanaelA** [comment] 2015-09-23 09:10
@rosen-vladimirov / @dtopuzov / @valentinstoychev 
I just had this happen again.  I have NO idea why my **tns-template-hello-world** v1.30 that was in my cache was replaced by the bad version again.  I also have no idea where it pulled it from; is it possible it is in one of your Namespaces on npm that it somehow pulling it from -- is their a easy way to determine where it is getting it from.   I also noticed while looking at my cache that the **tns-template-hello-world-ts** is also the bad version.  I'm not even sure how this package was populated  into my cache as I haven't done any installs of the typescript version of this package.

**Comment by rosen-vladimirov** [comment] 2015-09-25 09:08
Hi @NathanaelA ,

Please excuse me for the late reply, somehow I've missed this messages.
We are not sure what is causing this behavior. The fact is that it happens when we use npm api (NativeScript CLI executes `npm cache add` command via npm api) it causes corruptions of the cache. In order to fix this, we are working on a SHA Sum check of the downloaded package and compare it to the one from `registry.npmjs.org`. We are already doing this for `tns-android` and `tns-ios` runtimes, I'll add the check for `tns-template-hello-world*` packages as well.

Once again, please excuse me for the late reply and for the caused inconvenience.

**Comment by rosen-vladimirov** [comment] 2015-09-28 10:39
Ok, I've added the fix for this issue in CLI's master branch. Hopefully we'll not face this problem anymore. Feel free to contact us in case you have any problems or concerns.

**Closed** 2015-10-06 14:35 UTC
Labels: 5 - Done, T:Bug

**Comment by msangapu** [comment] 2017-03-01 04:23
I am  facing a similar same issue today 2/28/2017. I tried the multiple suggestions (npm cache clean, copying App_Resources folder, redoing the tutorial, reinstalling {N}...) and nothing works for me. Can someone help me out?

21:52:40.432 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
21:52:40.436 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command 'C:\Users\spectre007\AppData\Local\Android\android-sdk\build-tools\25.0.2\aapt.exe'.
21:52:40.443 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
21:52:40.448 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
21:52:40.448 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command 'C:\Users\spectre007\AppData\Local\Android\android-sdk\build-tools\25.0.2\aapt.exe''
**21:52:41.043 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED**
21:52:41.047 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'C:\Users\spectre007\AppData\Local\Android\android-sdk\build-tools\25.0.2\aapt.exe'' finished with exit value 1 (state: FAILED)
21:52:41.067 [ERROR] [org.gradle.api.Project] **C:\tns\sendSMS\platforms\android\build\intermediates\manifests\full\F0F1\debug\AndroidManifest.xml:26:23-37: AAPT: No resource found that matches the given name (at 'icon' with value '@drawable/icon').**

**21:52:41.075 [ERROR] [org.gradle.api.Project] C:\tns\sendSMS\platforms\android\build\intermediates\manifests\full\F0F1\debug\AndroidManifest.xml:33:28-52: AAPT: No resource found that matches the given name (at 'theme' with value '@style/LaunchScreenTheme').**

21:52:41.083 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter                                                                                          ]                                                                                          Finished executing task ':processF0F1DebugResources'
21:52:41.086 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :processF0F1DebugResources                                                                                           FAILED
21:52:41.091 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :processF0F1DebugResources (Thread[main,5,main]) completed. Took 0.952 secs.
21:52:41.093 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 3.415 secs, idle: 0.301 secs
**21:52:41.102 [ERROR] [org.gradle.BuildExceptionReporter]
21:52:41.114 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.**

**Comment by vchimev** [comment] 2017-03-01 08:45
@msangapu,

Could you please open a new issue following the issue template and providing the information requested?

Locking conversation here ...
