### ISSUE TITLE
button tap event does not fire  in action bar item view ! 

### ISSUE THREAD

**Issue by c1ngular** [NativeScript/NativeScript#3578] opened 2017-02-04 09:01 UTC
i have updated Nativescript to 2.5 , created new project .
then i found my button in ActionItem.actionView does not fire tap event at all (android and iOS both) ! 
then i tried to change my button to Label ,it works ! then , i lost my button [active and inactive] effect under iOS ,though this effect never worked under Android !
please take a look for me , thank you !

```          
 <ActionBar.actionItems>

                <ActionItem ios.position="left">
                    <ActionItem.actionView>
                        <Button  class="action-item fa text-left" text="&#xf0c9;" id="drawerBtn" tap="toggleDrawer"/>
                    </ActionItem.actionView>
                </ActionItem>

                <ActionItem ios.position="right">
                    <ActionItem.actionView>
                        <Button  class="action-item fa text-right" text="&#xf2b9;" id="contactBtn" tap="toggleDrawer"/>
                    </ActionItem.actionView>
                </ActionItem>

            </ActionBar.actionItems>
`

**Comment by tsonevn** [comment] 2017-02-06 13:06
Hi @c1ngular,

I reviewed your case and was able to reproduce this problem with `Button` `tap` event fire inside the `ActionBar` component. We will research this behavior and will provide further info about the issue.

As a workaround you could set the `tap` event to the `ActionItem` component, which will be fired as expected and you will be able to use `Button`s in the `ActionItem.actionView` component. For example:

main-page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page">

    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
                <ActionBar.actionItems>
                    <ActionItem ios.position="left" tap="toggleDrawer">
                            <ActionItem.actionView>
                                <Button  class="action-item fa text-left" text="left" id="drawerBtn"/>
                            </ActionItem.actionView>
                        </ActionItem>

                        <ActionItem ios.position="right" tap="toggleDrawer">
                            <ActionItem.actionView>
                                <Button  class="action-item fa text-right" text="right" id="contactBtn"/>
                            </ActionItem.actionView>
                        </ActionItem>

                </ActionBar.actionItems>
        </ActionBar>
    </Page.actionBar>
    <StackLayout class="p-20">
        <Label text="Tap the button" class="h1 text-center"/>
        <Button text="TAP" tap="{{ onTap }}" class="btn btn-primary btn-active"/>
        <Label text="{{ message }}" class="h2 text-center" textWrap="true"/>
    </StackLayout>
</Page>
```
main-page.ts
```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';

export function navigatingTo(args: EventData) {

    let page = <Page>args.object;

    page.bindingContext = new HelloWorldModel();
}

export function toggleDrawer(args){
    console.log("button tap")
}
```
Hope this helps.

**Comment by tsonevn** [comment] 2018-07-30 11:44
reproducible with modules 4.1

**Comment by NickIliev** [comment] 2018-12-11 09:25
Closing as the issue is no longer reproducible with `tns-core-modules@5.0.5`

`[Playground demo here](https://play.nativescript.org/?template=play-ng&id=ttffx4)`

**Closed** 2018-12-12 06:20 UTC
Labels: action-bar, os: android, os: ios, severity: low
