### ISSUE TITLE
Error parsing mappings with webpack 5.47

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#9487] opened 2021-07-27 16:23 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.2
 - Cross-platform modules: 8.0.8
 - Android Runtime: 8.0.0
 - iOS Runtime: 6.5.4
 - XCode Version: 12.5
 - Plugin(s):

**Describe the bug**
This is a strange one. So couple of hours ago webpack pushed a new version (5.47) and since I was cleaning/rebuilding an app it got picked up and I started getting an error just after CLI restarts the app on an iOS simulator:
```
The build result is located at: /Users/peter/Projects/SwyftCG/platforms/ios/build/Debug-iphonesimulator/SwyftCG.app
Installing on device E75378E4-75AD-47ED-9DE1-EB6E2719E1BD...
Successfully installed on device with identifier 'E75378E4-75AD-47ED-9DE1-EB6E2719E1BD'.
Successfully transferred all files on device E75378E4-75AD-47ED-9DE1-EB6E2719E1BD.
Restarting application on device E75378E4-75AD-47ED-9DE1-EB6E2719E1BD...
Error: Error parsing mappings (code 1): the mappings contained a negative line, column, source index, or name index
    at BasicSourceMapConsumer._parseMappings (/usr/local/lib/node_modules/nativescript/node_modules/source-map/lib/source-map-consumer.js:360:13)
    at BasicSourceMapConsumer._getMappingsPtr (/usr/local/lib/node_modules/nativescript/node_modules/source-map/lib/source-map-consumer.js:315:12)
    at /usr/local/lib/node_modules/nativescript/node_modules/source-map/lib/source-map-consumer.js:510:14
    at Object.withMappingCallback (/usr/local/lib/node_modules/nativescript/node_modules/source-map/lib/wasm.js:95:11)
    at BasicSourceMapConsumer.originalPositionFor (/usr/local/lib/node_modules/nativescript/node_modules/source-map/lib/source-map-consumer.js:508:16)
    at LogSourceMapService.getOriginalFileLocation (/usr/local/lib/node_modules/nativescript/lib/services/log-source-map-service.js:123:46)
    at /usr/local/lib/node_modules/nativescript/lib/services/log-source-map-service.js:79:43
    at Array.forEach (<anonymous>)
    at LogSourceMapService.replaceWithOriginalFileLocations (/usr/local/lib/node_modules/nativescript/lib/services/log-source-map-service.js:77:15)
    at DeviceLogProvider.logData (/usr/local/lib/node_modules/nativescript/lib/common/mobile/device-log-provider.js:18:42)
```
The app is started on the device, but the CLI breaks and exists. If I install webpack 5.46 as a dev dependency everything works as expected. 

Trying on a blank demo app works fine, so seems it is something related with the given app source. Also running on android works fine. 

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by cjohn001** [comment] 2021-07-28 11:33
+1

**Comment by wuilmerj24** [comment] 2021-08-01 01:01
+1

**Comment by edusperoni** [comment] 2021-08-05 17:58
It seems webpack may have fixed this on 5.47.1 and 5.48.0

**Comment by cjohn001** [comment] 2021-08-05 20:54
@edusperoni : I can confirm that it is now also working for me with 5.48.0

**Comment by wuilmerj24** [comment] 2021-08-05 21:06
With webpack version 5.0.0-beta.15 it works correctly

**Comment by rigor789** [comment] 2021-08-06 15:42
`@nativescript/webpack` is also now in `rc` (`5.0.0-rc.0`) - but the issue was fixed by the webpack update.

**Closed by rigor789** 2021-08-06 15:42 UTC

**Comment by cjohn001** [comment] 2021-08-06 16:02
@rigor789 : I unfortunately could not try it out, due to another issue I was running into, which is documented here:

https://github.com/NativeScript/nativescript-dev-webpack/issues/1159

**Comment by rigor789** [comment] 2021-08-06 17:22
@cjohn001 the beta/rc is unrelated to the webpack release - as long as you delete your lockfiles, the latest version should be automatically installed, and if you want to be explicit, just add `webpack` to your `devDependencies`.

As for that issue, we'll need to debug the build hang, if possible with a reproduction app where the issue can be seen (and I'll move the issue here, since we'll no longer use the `nativescript-dev-webpack` repository, it's all inside the `packages` of this repo).

**Comment by cjohn001** [comment] 2021-08-07 20:36
@rigor789 : Thanks for letting me know. I only have the following two packages in my devDependencies

"@nativescript/webpack": "5.0.0-beta.15",
"@ngtools/webpack": "~12.2.0",

The explicit webpack dependency I have thrown out once the bug was fixed. This brings the lates package in like you mentioend.

Regarding the other scss bug, I will try to create a demo app as soon as I find time. I have seen there is a more up-to-date scss package available. I want to try first if this might fix the issue.
