### ISSUE TITLE
iOS images render with blue foreground [3.x]

### ISSUE THREAD

**Issue by triniwiz** [NativeScript/NativeScript#4261] opened 2017-05-24 15:18 UTC
The issue is similar to https://github.com/NativeScript/NativeScript/issues/3057 but i'm not setting any blue background-color on the parent also all my images are local 

<img width="166" alt="screen shot 2017-05-24 at 10 31 30 am" src="https://cloud.githubusercontent.com/assets/6695919/26410930/9c7928a8-4072-11e7-9c19-05d43b732f59.png">

tns 3.0.1
tns-ios 3.0.0 and 3.0.1
core-modules: 3.0.0 , 3.0.1 and next

**Comment by tsonevn** [comment] 2017-05-25 08:01
Hi @triniwiz,
I tested this case on my side and created sample project, where I am displaying several images in a ListView, however, everything seems to be rendered as expected on both iOS and Android.

For your convenient, I am attaching the project, you could review it and make the needed changes, which will allow me to debug the issue locally on my side.


[Archive.zip](https://github.com/NativeScript/NativeScript/files/1028340/Archive.zip)
![screen shot 2017-05-25 at 11 00 36 am](https://cloud.githubusercontent.com/assets/17448734/26441537/83fb8ee8-4139-11e7-8161-4b04f7e1dd14.png)
![screen shot 2017-05-25 at 11 00 25 am](https://cloud.githubusercontent.com/assets/17448734/26441538/8416e094-4139-11e7-997d-f503420eb5bf.png)

**Comment by triniwiz** [comment] 2017-05-25 10:59
I forgot to mention I'm using angular

**Comment by tsonevn** [comment] 2017-05-25 11:55
Hi @triniwiz, 
I tested the same scenario also in NativeScript Angular project, however, I am still unable to reproduce the sane error. 
I am attaching the project, which I use for testing.
![screen shot 2017-05-25 at 2 52 06 pm](https://cloud.githubusercontent.com/assets/17448734/26449293/133ad4cc-415a-11e7-8392-692da318e6a1.png)
![screen shot 2017-05-25 at 2 51 44 pm](https://cloud.githubusercontent.com/assets/17448734/26449294/13421dea-415a-11e7-90eb-e4a746b95625.png)
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1028862/Archive.zip)

**Comment by triniwiz** [comment] 2017-05-25 17:59
A little update sometimes when i'm updating the code via livesync some parts of the app the image displays as it should another this app has been using 2.4 , 2.5 and none of the code was changed only when i attempted to upgrade the app to 3.0 i ran into this bug and a couple others so i'm guessing since it's close to the launch date i'll just stick with 2.5 until 3.0 is ready

**Comment by tsonevn** [comment] 2017-05-26 08:04
Hi @triniwiz,
Could you send me sample project or at least some code snippet, where this behavior could be reproduced locally?

**Comment by triniwiz** [comment] 2017-05-29 12:57
I noticed @kilka has the same problem https://github.com/NativeScript/NativeScript/issues/3057#issuecomment-304510895

**Comment by kilka** [comment] 2017-05-29 13:34
@triniwiz Are you using the nativescript-checkbox plugin by chance? I have narrowed down the issue for my application and found that nativescript-checkbox is calling a method to change tint-color property for ios and that is what's causing the issue. I removed all references to tint from the plugin and I no longer have the blue picture issue.

https://github.com/bradmartin/nativescript-checkbox/blob/b2652866efe22ee68f27d78edb8949ebf8828c20/checkbox.ios.ts

If you look at the nativescript-checkbox code that same color that is showing up in your picture and was showing up in mine shows up as the default value for tint-color "defaultValue: '#0075ff',"

I am not sure if this is an issue with the checkbox plugin or with the tns core modules as I know it has had issues with Images inheriting tint colors in the past.

**Comment by triniwiz** [comment] 2017-05-29 13:52
@kilka nice find and seems like a tns core bug

**Comment by tsonevn** [comment] 2017-05-30 10:17
Hi @triniwiz @kilka,
I tested the same scenario while using the both demo apps from [nativescript-checkbox](https://github.com/bradmartin/nativescript-checkbox) repository, however still not able to recreate the same scenario. If you are able to isolate the problem in a sample project, please share it with us.
[demo_ng.zip](https://github.com/NativeScript/NativeScript/files/1037944/demo_ng.zip)
[demo.zip](https://github.com/NativeScript/NativeScript/files/1037946/demo.zip)

**Comment by tsonevn** [comment] 2017-06-07 12:00
Hi @triniwiz 
Were you able to reproduce this behavior on sample project? If you still have an issue, please send us sample project.

**Comment by triniwiz** [comment] 2017-06-07 13:36
I'll try again :)

**Comment by suresh-selvaraj** [comment] 2017-06-08 20:49
Same issue we are facing in NS3.0 with nativescript-checkbox plugin.

**Comment by NickIliev** [comment] 2017-06-09 08:01
@suresh-selvaraj please send us sample project or snippet that can reproduce your issue - up to this moment we do not have reproducible project or code for this issue so it is really hard to investigate what is causing your case.

**Comment by triniwiz** [comment] 2017-06-09 12:29
@NickIliev the plugin uses tintColor so my eyes are on that atm

**Comment by nicHoch** [comment] 2017-06-09 12:42
having the same issue. using checkbox and all images are blue

**Comment by tsonevn** [comment] 2017-06-12 09:27
HI @triniwiz , @suresh-selvaraj , @nicHoch,
Could you review the attached sample project from [this comment](https://github.com/NativeScript/NativeScript/issues/4261#issuecomment-304835828) and to make the needed changes, which will allow us to reproduce the issue. 
As already @NickIliev mentioned 
> up to this moment we do not have reproducible project or code for this issue so it is really hard to investigate what is causing your case.

**Comment by NickIliev** [comment] 2017-06-14 12:00
@triniwiz, @nicHoch  @suresh-selvaraj I was able to reproduce the issue (Special thanks to @suresh-selvaraj for the sample project) and I can confirm that the issue is related to the tint color of nativescript-checkbox plugin as @triniwiz suggested. The solution is pretty straight forward - just remove the default value of tintColor property in the ios implementation file of the plugin (as shown [here](https://github.com/bradmartin/nativescript-checkbox/issues/44#issuecomment-308407895)).

@bradmartin ^^^

**Comment by tsonevn** [comment] 2017-06-15 06:46
fixed with `nativescript-checkbox` 2.1.5

**Closed by tsonevn** 2017-06-15 06:46 UTC
Labels: T:Question

**Comment by bradmartin** [comment] 2017-06-15 10:48
If using angular make sure to use 2.1.7 I broke the build prior to that :)
but all good now.
