### ISSUE TITLE
Nanaimo::Reader::ParseError - [!] Array missing ',' in between objects

### ISSUE THREAD

**Issue by alibahjat** [NativeScript/NativeScript#6121] opened 2018-07-25 20:26 UTC
hello 
i got this error when run ios

`### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.4 (17E202)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.16.3
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 540a04ca8a8a33a2881b9db2ce4c2d65c0ff0b83
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target "ali" do
# Begin Podfile - /D/nativescript/ali/node_modules/nativescript-app-tour/platforms/ios/Podfile
 pod 'MaterialShowcase', :git => 'https://github.com/hamdiwanis/material-showcase-ios.git'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      configuration.build_settings['SWIFT_VERSION'] = "3.2"
    end
  end
end
 # End Podfile
# Begin Podfile - /D/nativescript/ali/node_modules/nativescript-carousel/platforms/ios/Podfile
 pod 'DKCarouselView', :git => 'https://github.com/manijak/DKCarouselView'
 # End Podfile
# Begin Podfile - /D/nativescript/ali/node_modules/nativescript-fancyalert/platforms/ios/Podfile
 pod 'SCLAlertView-Objective-C'
 # End Podfile
# Begin Podfile - /D/nativescript/ali/node_modules/nativescript-gif/platforms/ios/Podfile
 pod 'FLAnimatedImage', '~> 1.0'
 # End Podfile
# Begin Podfile - /D/nativescript/ali/node_modules/nativescript-image-cache/platforms/ios/Podfile
 pod 'SDWebImage', '~> 4.0.0'

 # End Podfile
# Begin Podfile - /D/nativescript/ali/node_modules/nativescript-loading-indicator/platforms/ios/Podfile
 pod 'MBProgressHUD'

 # End Podfile
# Begin Podfile - /D/nativescript/ali/node_modules/nativescript-onesignal/platforms/ios/Podfile
 #

use_frameworks!

pod 'OneSignal'


 # End Podfile

end
```

### Error

```
Nanaimo::Reader::ParseError - [!] Array missing ',' in between objects
   #  -------------------------------------------
   #                            HEADER_SEARCH_PATHS = (
   #                                    "$(inherited)",
410>                                    /D/nativescript/ali/node_modules/tns-core-modules/platforms/ios/src,
                                                             ^
   #                            );
   #                    };
   #  -------------------------------------------

/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:174:in `parse_array'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:134:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:107:in `parse!'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.9/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.9/lib/xcodeproj/project.rb:201:in `initialize_from_file'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.9/lib/xcodeproj/project.rb:103:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:918:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:917:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:917:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:912:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:78:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5B%21%5D+Array+missing+%27%2C%27+in+between+objects%0A+++%23++-------------------------------------------%0A+++%23++%09%09%09%09HEADER_SEARCH_PATHS+%3D+%28%0A+++%23++%09%09%09%09%09%22%24%28inherited%29%22%2C%0A410%3E++%09%09%09%09%09%2FD%2Fnativescript%2Fali%2Fnode_modules%2Ftns-core-modules%2Fplatforms%2Fios%2Fsrc%2C%0A++++++%09%09%09%09%09+++++++++++++++++++++%5E%0A+++%23++%09%09%09%09%29%3B%0A+++%23++%09%09%09%7D%3B%0A+++%23++-------------------------------------------%0A&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Unable to apply changes on device: 1626D133-057C-4418-AFDC-C3F0DCA491D8. Error is: Commandpod failed with exit code 1 Error output:
 /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:95:in `parse_results': undefined method `map' for nil:NilClass (NoMethodError)
Did you mean?  tap
        from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:34:in `search'
        from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:68:in `search_query'
        from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:62:in `search_exception'
        from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
        from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:67:in `report_error'
        from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:396:in `handle_exception'
        from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:337:in `rescue in run'
        from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:325:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
        from /usr/local/bin/pod:22:in `load'
        from /usr/local/bin/pod:22:in `<main>'
.
Executing after-watch hook from /D/nativescript/ali/hooks/after-watch/nativescript-dev-typescript.js
Executing after-watch hook from /D/nativescript/ali/hooks/after-watch/nativescript-dev-webpack.js
Stopping webpack watch`

my package.json is

`{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.ali.ali",
    "tns-android": {
      "version": "4.1.3"
    },
    "tns-ios": {
      "version": "4.1.1"
    }
  },
  "dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "nativescript-angular": "~5.3.0",
    "nativescript-app-tour": "^0.9.1",
    "nativescript-barcodescanner": "^2.7.7",
    "nativescript-carousel": "^3.1.1",
    "nativescript-fancyalert": "^1.2.0",
    "nativescript-gif": "^4.0.0",
    "nativescript-image-cache": "^1.1.6",
    "nativescript-image-swipe": "^3.0.0",
    "nativescript-image-zoom": "^3.0.0",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-ng2-carousel": "0.0.5",
    "nativescript-ng2-slides": "0.0.11",
    "nativescript-onesignal": "^1.0.7",
    "nativescript-rotate-3d": "^0.8.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-sidedrawer": "^4.1.1",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~5.5.5",
    "tns-core-modules": "^4.2.0-2018-07-23-02",
    "tns-core-modules-widgets": "^4.2.0",
    "tns-platform-declarations": "^4.1.0",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "@angular-devkit/core": "~0.6.3",
    "@angular/cli": "^6.0.8",
    "@angular/compiler-cli": "~5.2.0",
    "@ngtools/webpack": "~6.0.3",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "~0.1.19",
    "copy-webpack-plugin": "~4.5.1",
    "css-loader": "~0.28.11",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "^0.12.0",
    "nativescript-worker-loader": "~0.9.0",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.3.0",
    "typescript": "~2.7.2",
    "uglifyjs-webpack-plugin": "~1.2.5",
    "webpack": "~4.6.0",
    "webpack-bundle-analyzer": "~2.13.0",
    "webpack-cli": "~2.1.3",
    "webpack-sources": "~1.1.0"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}
`

**Comment by alibahjat** [comment] 2018-07-25 20:30
my pod file  is

`use_frameworks!

target "ali" do
# Begin Podfile - /D/nativescript/ali/node_modules/nativescript-app-tour/platforms/ios/Podfile 
 pod 'MaterialShowcase', :git => 'https://github.com/hamdiwanis/material-showcase-ios.git'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      configuration.build_settings['SWIFT_VERSION'] = "3.2"
    end
  end
end 
 # End Podfile 
# Begin Podfile - /D/nativescript/ali/node_modules/nativescript-carousel/platforms/ios/Podfile 
 pod 'DKCarouselView', :git => 'https://github.com/manijak/DKCarouselView' 
 # End Podfile 
# Begin Podfile - /D/nativescript/ali/node_modules/nativescript-fancyalert/platforms/ios/Podfile 
 pod 'SCLAlertView-Objective-C' 
 # End Podfile 
# Begin Podfile - /D/nativescript/ali/node_modules/nativescript-gif/platforms/ios/Podfile 
 pod 'FLAnimatedImage', '~> 1.0' 
 # End Podfile 
# Begin Podfile - /D/nativescript/ali/node_modules/nativescript-image-cache/platforms/ios/Podfile 
 pod 'SDWebImage', '~> 4.0.0'
 
 # End Podfile 
# Begin Podfile - /D/nativescript/ali/node_modules/nativescript-loading-indicator/platforms/ios/Podfile 
 pod 'MBProgressHUD'
 
 # End Podfile 
# Begin Podfile - /D/nativescript/ali/node_modules/nativescript-onesignal/platforms/ios/Podfile 
 # 

use_frameworks!

pod 'OneSignal'

 
 # End Podfile 

end`

**Comment by tsonevn** [comment] 2018-07-26 06:42
Hi @alibahjat,
I tested your scenario with the pod installation, however, was unable to recreate the issue. I have created a demo plugin via our [nativescript plugin seed](https://github.com/NativeScript/nativescript-plugin-seed). For your convenience, I am attaching the demo project. 

[nativescript-plugin-seed.zip](https://github.com/NativeScript/NativeScript/files/2230730/nativescript-plugin-seed.zip)
You can also test it on your side while following the below-described steps:
1. `cd nativescript-plugin-seed/src`
2. `npm run demo.ios`
The second command will build the demo project with the sample plugin. As a result the pods described in the Podfile will be installed, and the app will be started on the device.

Also, it will help if you provide more info about the problem and what you are trying to achieve as a final result. Also send us a demo, which can be used for reproducing the issue.

Meanwhile, try to update the pod repo via `pod repo update` command. Then remove `platforms`, `node_modules` and `hooks` folders from the project and build it again.

**Closed** 2018-07-31 10:26 UTC
Labels: needs more info, os: ios

**Comment by zeesulehria** [comment] 2018-07-31 11:02
please reopen this issue .
i perform those commands @tsonevn  but still not working

**Comment by zeesulehria** [comment] 2018-07-31 11:04
package.json is 

> {
  "description": "HireGoat Application",
  "nativescript": {
    "id": "com.hiregoat.ui",
    "tns-android": {
      "version": "4.2.0-2018-07-20-02"
    },
    "tns-ios": {
      "version": "4.2.0-2018-07-21-01"
    }
  },
  "dependencies": {
    "@angular/animations": "~6.0.0",
    "@angular/common": "~6.0.0",
    "@angular/compiler": "~6.0.0",
    "@angular/core": "~6.0.0",
    "@angular/forms": "~6.0.0",
    "@angular/http": "~6.0.0",
    "@angular/platform-browser": "~6.0.0",
    "@angular/platform-browser-dynamic": "~6.0.0",
    "@angular/router": "~6.0.0",
    "email-validator": "^2.0.4",
    "nativescript-angular": "~6.0.0",
    "nativescript-gradient": "^2.0.1",
    "nativescript-insomnia": "^1.2.1",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-ngx-fonticon": "4.2.0",
    "nativescript-nodeify": "^0.7.0",
    "nativescript-pager": "8.0.2",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-dataform": "^3.6.1",
    "nativescript-ui-gauge": "^3.6.0",
    "nativescript-ui-listview": "3.5.7",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~6.1.0",
    "rxjs-compat": "6.1.0",
    "tns-core-modules": "^4.2.0-2018-07-23-02",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "@angular-devkit/core": "~0.6.3",
    "@angular/compiler-cli": "~6.0.0",
    "@ngtools/webpack": "~6.0.3",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "~0.1.19",
    "copy-webpack-plugin": "~4.5.1",
    "css-loader": "~0.28.11",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.6.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "~0.12.0",
    "nativescript-worker-loader": "~0.9.0",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.3.0",
    "tns-platform-declarations": "4.1.0",
    "typescript": "~2.7.2",
    "uglifyjs-webpack-plugin": "~1.2.5",
    "webpack": "~4.6.0",
    "webpack-bundle-analyzer": "~2.13.0",
    "webpack-cli": "~2.1.3",
    "webpack-sources": "~1.1.0",
    "sass-loader": "~7.0.1"
  },
  "author": "HireGoat"
}


Complete Logs of error
```
Installing pods...
Analyzing dependencies
4:01:40 PM - File change detected. Starting incremental compilation...




――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.18.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a3992887d2dcc424bc1c472d1fc76a6c14fed490
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target "HireGoatUI" do
# Begin Podfile - /Volumes/My files/HireGoat-UI/node_modules/nativescript-iqkeyboardmanager/platforms/ios/Podfile 
 pod 'IQKeyboardManager', '~> 5.0.0'
 
 # End Podfile 

end
```

### Error

```
Nanaimo::Reader::ParseError - [!] Array missing ',' in between objects
   #  -------------------------------------------
   #  				HEADER_SEARCH_PATHS = (
   #  					"$(inherited)",
680>  					/Volumes/My files/HireGoat-UI/node_modules/tns-core-modules/platforms/ios/src,
      					            ^
   #  				);
   #  			};
   #  -------------------------------------------

/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:174:in `parse_array'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:134:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:107:in `parse!'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.9/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.9/lib/xcodeproj/project.rb:201:in `initialize_from_file'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.9/lib/xcodeproj/project.rb:103:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:918:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:917:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:917:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:912:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:78:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5B%21%5D+Array+missing+%27%2C%27+in+between+objects%0A+++%23++-------------------------------------------%0A+++%23++%09%09%09%09HEADER_SEARCH_PATHS+%3D+%28%0A+++%23++%09%09%09%09%09%22%24%28inherited%29%22%2C%0A680%3E++%09%09%09%09%09%2FVolumes%2FMy+files%2FHireGoat-UI%2Fnode_modules%2Ftns-core-modules%2Fplatforms%2Fios%2Fsrc%2C%0A++++++%09%09%09%09%09++++++++++++%5E%0A+++%23++%09%09%09%09%29%3B%0A+++%23++%09%09%09%7D%3B%0A+++%23++-------------------------------------------%0A&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Unable to apply changes on device: 5BBEC7AF-0407-4C99-B761-683BDC06C1AC. Error is: Command pod failed with exit code 1 Error output: 
 /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:95:in `parse_results': undefined method `map' for nil:NilClass (NoMethodError)
Did you mean?  tap
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:34:in `search'
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:68:in `search_query'
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:62:in `search_exception'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:67:in `report_error'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:396:in `handle_exception'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:337:in `rescue in run'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:324:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:22:in `load'
	from /usr/local/bin/pod:22:in `<main>'
.
Executing after-watch hook from /Volumes/My files/HireGoat-UI/hooks/after-watch/nativescript-dev-sass.js
Executing after-watch hook from /Volumes/My files/HireGoat-UI/hooks/after-watch/nativescript-dev-typescript.js
Stopping tsc watch
Executing after-watch hook from /Volumes/My files/HireGoat-UI/hooks/after-watch/nativescript-dev-webpack.js


```

**Comment by tsonevn** [comment] 2018-07-31 12:10
HI @zeesulehria,
Can you check if you will be able to recreate the issue with the latest official version of NativeScript modules `4.1.0`, tns-android `4.1.0` and tns-android `4.1.0`? I noticed that you are using `@next` version.

Also, Did you try to update the local spec cocoapods repos via ` pod repo update` command as it is mentioned in my previous comment. It will help if you provide sample project, where this issue can be reproduced.

**Comment by tarun29061990** [comment] 2019-08-22 09:37
Any update on this , I am getting Nanaimo parse error while doing pod install.

### Error

```
Nanaimo::Reader::ParseError - [!] Array missing ',' in between objects
   #  -------------------------------------------
   #  			sourceTree = "<group>";
   #  		};
263>  		5D96C02C2E854BCA87D8C9B6 /* Resources */ = {
      		                                         ^
   #  			isa = PBXGroup;
   #  			children = (
   #  -------------------------------------------

/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:174:in `parse_array'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:134:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:107:in `parse!'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.12.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.12.0/lib/xcodeproj/project.rb:210:in `initialize_from_file'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.12.0/lib/xcodeproj/project.rb:112:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-deintegrate-1.0.4/lib/cocoapods/command/deintegrate.rb:40:in `validate!'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:333:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by tsonevn** [comment] 2019-08-26 10:18
Hi @tarun29061990,
Try to [upgrade your project ](https://docs.nativescript.org/releases/upgrade-instructions)to the latest {N} `6.0` version and check if you will have the same problem.

**Comment by shehanrg** [comment] 2020-02-18 12:52
Let me help anyone who is experiencing this issue afterward. 
This is due to a corrupt project file. Take a hint from the error thrown to you and find the exact place. Check the syntax and fix it. This might be caused by merge conflicts or auto-merge scripts.

In my case I was missing the closures of following syntax.
`children = (
            );
            path= ;
            sourceTree="<group>"`

**Comment by shrutisoni20** [comment] 2021-01-21 13:22
Hello 

> Let me help anyone who is experiencing this issue afterward.
> This is due to a corrupt project file. Take a hint from the error thrown to you and find the exact place. Check the syntax and fix it. This might be caused by merge conflicts or auto-merge scripts.
> 
> In my case I was missing the closures of following syntax.
> `children = ( ); path= ; sourceTree="<group>"`

....
Thanks a lott , you saved me .
