### ISSUE TITLE
View.resetNativeView() is not yet fully implemented.

### ISSUE THREAD

**Issue by SephReed** [NativeScript/NativeScript#7183] opened 2019-04-26 15:41 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 5.3.1 and the latest available version is 5.3.4.
✔ Component tns-core-modules has 5.4.0-next-2019-04-17-135741-01 version and is up to date.
✔ Component tns-android has 5.4.0-2019-04-03-095324-01 version and is up to date.
✔ Component tns-ios has 5.4.0-2019-04-03-180044-02 version and is up to date.

**Describe the bug**

As far as I can tell, `resetNativeView()` doesn't do anything.

I've run into a few very troublesome rendering issues so far, all of which would seem to require the ability to manually tell the app to refresh its views.  From this answer (https://github.com/NativeScript/NativeScript/issues/7121) it would appear View.resetNativeView() is supposed to be able to do something like this, but it never works.  So far, these are the two major rendering issues I'm running into:
- updating label width: https://github.com/NativeScript/NativeScript/issues/5081
- re-aligning flex items: https://github.com/NativeScript/NativeScript/issues/7119

**To Reproduce**

I don't know what causes these problems.  I've found that flex layouts don't like having child content updated mid animation.  I've also found that flex layouts don't like child label text being updated.  It seems mostly to affect iOS.  But the point here is: if at any point one breaks the rendering, `resetNativeView()` will do nothing to fix it.

**Expected behavior**
I would expect there to be some function which very deliberately tells the views to re-render, for sure.  

**Additional context**

I looked into resetNativeView() and it would appear it really does do nothing:
- View Base:     https://github.com/NativeScript/NativeScript/blob/d35e14ed0fb12965c0ee0d80cbf95ee688143824/tns-core-modules/ui/core/view-base/view-base.ts#L655-L657
- View Common: https://github.com/NativeScript/NativeScript/blob/d35e14ed0fb12965c0ee0d80cbf95ee688143824/tns-core-modules/ui/core/view/view-common.ts#L1059-L1065
- View IOS (does not override resetNativeView): https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/core/view/view.ios.ts

**Comment by SephReed** [comment] 2019-04-26 15:53
I would like to add that solving this problem would relieve what has been the biggest thorn in my side with this project.  I've written a lot of really bad code to get around issues caused by bad renders.  Things like arbitrary timeouts, or just straight up re-rendering an entire page every time a bit of text changes.  They've been stop-gap solutions, all of which could be eliminated by making this function really do what it says.

**Comment by SephReed** [comment] 2019-05-02 17:35
Just bumping this.  It's still a pretty serious issue for me.

Another problem I'm running into which this function might solve is that my views break when added/removed too many times.  In particular, the event listeners stop working.

Please, if there is anything I can do to push this forward, let me know.

**Comment by SephReed** [comment] 2019-05-08 21:09
> so they are most likely related to the specific controls and or implementation and app code logic

I've not had any issues whatsoever with event listeners on views that have not been recycled, and I've never had any issues with layout on views that are not animated close to the time they are being rendered.  Also, it's very sporadic.  Which is why...

> Can you please create or share with us, a base project that is demonstrating the issue you are dealing 

I have not been able to set up an MVCE yet.  There is not enough consistency in the issue, and that's one of the biggest reasons it's killing me and I'm looking for a sledgehammer solution.  Still, I can share the code with you, and maybe you'll see something strange:

https://gist.github.com/SephReed/7560920259c216b0a5dbccfd4275a39a

**Comment by NickIliev** [comment] 2019-07-08 07:26
Closing the issue as I was not able to reproduce the issue via a stable demo app. If you have a sample app that can consistently hit this one please do let me know and I will reopen for further investigation.

**Closed by NickIliev** 2019-07-08 07:26 UTC
Labels: needs more info, question
