### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by praven07** [NativeScript/NativeScript#4161] opened 2017-05-10 21:11 UTC
Hi,
I just upgraded to version 3.0 and the modal page not working properly. I have attached some pictures below. As you can see the initial state of the page and then when I click the search icon the modal page comes to view and the action bar moves to the side and then it disappears.
 
<img width="278" alt="screen shot 2017-05-10 at 4 03 41 pm" src="https://cloud.githubusercontent.com/assets/2223191/25921375/c9a1a720-359a-11e7-8d31-41c175de5429.png">
<img width="274" alt="screen shot 2017-05-10 at 4 09 28 pm" src="https://cloud.githubusercontent.com/assets/2223191/25921451/11842798-359b-11e7-852a-315e49b004c9.png">

**Comment by tsonevn** [comment] 2017-05-11 05:30
Hi @praven07,
Could you share some more info about the problem and your environment(CLI, tns-core-modules, node versions)? I tested on my side, however, was unable to reproduce the exact scenario, you are reporting.
I am attaching the sample project. please review it and make the needed changes, which will help to debug this issue.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/991953/Archive.zip)

**Comment by praven07** [comment] 2017-05-11 18:27
I just downloaded the project that you provided and ran it. I still get the error.
I'm using 
nativescript 3.0.0,
node 6.10.0

**Comment by tsonevn** [comment] 2017-05-12 05:55
Hi @praven07,
If I understand you correctly, you are having an issue with ActionBar, which is hided after you return back from the modal page.
In case this is the problem, you could review issue [#4141](https://github.com/NativeScript/NativeScript/issues/4141), where this is already reported and you could keep track on it for further info.

**Comment by NickIliev** [comment] 2017-05-16 13:06
Closing as related to [https://github.com/NativeScript/NativeScript/issues/4141](https://github.com/NativeScript/NativeScript/issues/4141)

The issue is fixed and the fix will be included in our next release (3.1)

**Closed by NickIliev** 2017-05-16 13:06 UTC
Labels: iOS, T:Question
