### ISSUE TITLE
[TNS 3.0 RC] Console.dir not working as expected compared to Console.dump

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#3973] opened 2017-04-11 08:52 UTC
When logging objects or arrays with the replaced Console.dir I get a non-detailed dump.

```js
const arr = [
  { id: 1, title: "Item 1" },
  { id: 2, title: "Item 2" },
  { id: 3, title: "Item 3" }
];

console.dir(arr);
```

The logged dump:

```
CONSOLE LOG file:///app/main-page.js:33:14: [object Object],[object Object],[object Object]
	0: [object Object]
	1: [object Object]
```

I want to see the properties of each object, but they render as `[object Object]`. Also, it doesn't even log the last, third, item.

**Comment by tsonevn** [comment] 2017-04-11 11:42
Hi @NordlingArt,
Could you verify, whether you are using the latest `@rc` version? I tested your case while reusing the above-given code snippet and the object was dumped in the console as expected:

Result:
```
JS: === dump(): dumping members ===
JS: [
JS:     {
JS:         "id": 1,
JS:         "title": "Item 1"
JS:     },
JS:     {
JS:         "id": 2,
JS:         "title": "Item 2"
JS:     },
JS:     {
JS:         "id": 3,
JS:         "title": "Item 3"
JS:     }
JS: ]
JS: === dump(): dumping function and properties names ===
JS: === dump(): finished ===
```

**Comment by NordlingArt** [comment] 2017-04-11 11:56
@tsonevn - This is taken from the tns-core-modules package.json file:

```json
{
  "_from": "tns-core-modules@rc",
  "version": "3.0.0-rc.2"
}
```

**Comment by tsonevn** [comment] 2017-04-11 12:35
Hi @NordlingArt,
In my further research, I found that this issue is reproducible only when you building the app for iOS with `tns run ios`. For `tns run android` `console.dir` should work as expected.
Could you verify on your side, whether this is reproducible only while building for iOS?

**Comment by NordlingArt** [comment] 2017-04-11 12:43
@tsonevn That may be true. I am unable to check on Android unfortunately. Maybe someone else here can test?

**Comment by Cae2** [comment] 2017-04-11 15:48
@NordlingArt just tested on android and it works (tns 3.0 rc)

![1](https://cloud.githubusercontent.com/assets/24416663/24917963/2464c5f4-1eb5-11e7-9103-3abf8fc4e805.jpg)

**Comment by NordlingArt** [comment] 2017-04-26 08:49
@tsonevn - Will this be fixed for iOS in 3.0 release? It's extremely hard to debug without a proper console.

**Comment by tsonevn** [comment] 2017-04-26 11:08
Hi @NordlingArt,
I discussed this issue with the NativeScript team, however, we will provide a fix for this issue for some of the next version after 3.0 release.
As a temporary solution, you could use `console.log(JSON.stringify(<parametar_name>))`, which will help you to print in the terminal the argument similar to `console.dir`.

Let me know, whether this is applicable for you.

**Comment by NordlingArt** [comment] 2017-04-26 12:07
@tsonevn - I have used console.log(JSON.stringify(variable, null, 2)) sometimes as a work-around. However, it doesn't work when the object has a circular structure as that would cause an infinity JSON tree.

I hope it will be part of a version not too long in the future as it slows down production a lot :/

**Comment by matheusabr** [comment] 2017-06-13 20:08
This issue persists in version 3.0.3

**Comment by tsonevn** [comment] 2017-06-15 08:41
HI @matheusabr,
I just tested `console.dir`  on my side on iOS and it seems to dump the object as expected. for your convenience, I am attaching sample project, you could review it and to verify, whether I am missing something.

**Comment by two-bridges** [comment] 2017-06-27 22:52
Hi @tsonevn 

I'm seeing the problem in 3.0.3, iOS

Steps to reproduce:
1. installed nativescript (3.0.3) on Mac OS X.
2. Followed the NativeScript tutorial, Chapter 1 here on debugging: http://docs.nativescript.org/angular/tutorial/ng-chapter-1#13-debugging-apps 

This code:
`export class AppComponent {
  constructor() {
    console.log({
      type: "Apple",
      color: "Red"
    });
  }
}
`

Logs this (missing 'color' property):
`CONSOLE LOG file:///app/app.component.js:7:20: [object Object]
        type: Apple
`

Insetad of this:
`JS: === dump(): dumping members ===
JS: {
JS:     "type": "Apple",
JS:     "color": "Red"
JS: }`

**Comment by zbranzov** [comment] 2017-07-11 08:21
Hi @two-bridges 
I think you should use console.dir instead of console.log. Give it a try and let us know the output.

**Comment by dxshindeo** [comment] 2017-09-14 14:01
This is quite bothersome, I see the same problem here, on ios (NS 3.2).
What's even more annoying is the fact that running `console.log(JSON.stringify(data, null, 4));` prints out as `{`, and if I remove `, 4`, it prints out as a bulk of text which is cut off randomly (current data object got cut off after 881 symbols, it simply prints out nothing after that)

**Comment by dxshindeo** [comment] 2017-09-14 14:03
Current workaround for me, to read the actual data received, is to use one helper function (it allows one to see data in circular json, however, it prints only current depth level):
```
listObject(data) {
        // allows us to console.log circular objects, but prints only current level depth
        for (var key in data) {
            if (data.hasOwnProperty(key)) {
                console.log(key + ” -> ” + data[key]);
            }
        }
    }
```

**Comment by NathanaelA** [comment] 2017-09-14 16:54
I can confirm I've had issue with iOS and 3.x (including 3.2) and console.dir just printing [object Object].  I could have sworn in v2.x console.dump always worked.    The easist struture to see this on is:

`var data = [{name: "hi"}];  console.dir(data);`

In addition there is a console.log issue like @dxshindeo mentioed above about lossing log data on TNS on iOS, not sure if it is present on Android; that I already reported to the cli repo.

**Comment by mudlabs-monster** [comment] 2017-12-11 23:11
Just tested in 3.3.1
```js
console.dir({
    type: "Apple",
    color: "Red"
})
```
```console
CONSOLE LOG file:///app/main-page.js:3:14: [object Object]
```

**Comment by TimoWestland** [comment] 2018-01-15 11:05
Issue still persists in version 3.4.0 tns core modules and 3.4.1 iOS/Android platforms.

**Comment by terreb** [comment] 2018-02-16 10:11
"tns-core-modules": "3.4.0"
"version": "3.4.1"

Still having the issue on iOS.

**Comment by tsonevn** [comment] 2018-02-19 12:25
The issue seems to be related to iOS runtime. duplicated with [#875](https://github.com/NativeScript/ios-runtime/issues/875)

**Closed by tsonevn** 2018-02-19 12:25 UTC
Labels: bug, os: ios

**Comment by Neutrino-Sunset** [comment] 2018-04-01 10:39
@tsonevn why are you saying this issue seems to be related to iOS runtime when @TimoWestland 's post above which has 5 thumbs up makes it quite clear this is an issue on the Android platform too?

I see this exact same issue on Linux Mint 18.3 using Android.

**Comment by Neutrino-Sunset** [comment] 2018-04-01 11:00
After modifying the app several times and tns run refreshing it, it started working.
