### ISSUE TITLE
backgroundPosition with percent/number is not working

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/NativeScript#4201] opened 2017-05-16 08:55 UTC
Let's say you have a background image, and you try to apply backgroundPosition through css. The following is working:
```
background-position: center;
```

However, neither of these is:
```
background-position: 50%;
background-position: 50;
background-position: 0.5;
```

I'm attaching a stripped version of [groceries](https://github.com/NativeScript/NativeScript/files/1003727/groceries.tar.gz). The `app/groceries/groceries.component.html` contains a single GridLayout with a backgroundImage and class - list-page. The list-page class is defined in `app.css`.

Related to https://github.com/NativeScript/nativescript-dev-webpack/issues/135

**Comment by airandfingers** [comment] 2017-12-08 01:06
This works for me now, but only if I specify it as `background-position: 14 8;`.

Values that didn't work: `left 14` and `left 14 top 8`.

**Comment by tsonevn** [comment] 2018-07-27 14:31
The issue is still reproducible with NativeScript 4.1.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2236095/Archive.zip)

**Comment by abozanona** [comment] 2019-06-22 09:53
@sis0k0 Did you find any solution for this problem?

**Comment by mahmoudajawad** [comment] 2020-11-19 05:57
I came across this issue when I tried using `background-position-y`, but then realised I can stick to using `background-position` with two values. However, I also tried the OP brought-up bug and can confirm the merged PR resolves this issue. I guess it can be closed.

**Comment by janoshrubos** [comment] 2021-09-16 07:48
Closing this issue since the implementation is merged to master. 
If this error is still relevant, feel free to open a new issue!

**Closed by janoshrubos** 2021-09-16 07:48 UTC
Labels: backlog, bug, severity: low, css
