### ISSUE TITLE
TypeScript compiler failed with exit code 1

### ISSUE THREAD

**Issue by Farjallahmed** [NativeScript/NativeScript#7509] opened 2019-07-11 19:51 UTC
Hi developers, i am using nativescript to develop mobile app project,
i ve used photoviewer plugin, and it works fine when debuging the app in my phone but when i try to publish the app, iget always this error 

> Found peer TypeScript 3.1.6
> node_modules/nativescript-photoviewer/photoviewer.d.ts(48,22): error TS2304: Cannot find name 'UIColor'.
> node_modules/nativescript-photoviewer/photoviewer.d.ts(54,24): error TS2304: Cannot find name 'UIColor'.
> node_modules/nativescript-photoviewer/photoviewer.d.ts(60,23): error TS2304: Cannot find name 'UIColor'.
> node_modules/nativescript-photoviewer/photoviewer.d.ts(89,13): error TS2304: Cannot find name 'UIImage'.
> node_modules/nativescript-photoviewer/photoviewer.d.ts(94,24): error TS2304: Cannot find name 'UIImage'.
> TypeScript compiler failed with exit code 1

i ve tried to delete hooks, node_modules and platform folder and rerun npm install but nothing works, 
i ll be so gratefull if any one help 
Thank you

**Comment by tsonevn** [comment] 2019-07-12 05:24
Duplicate of https://github.com/manijak/nativescript-photoviewer/issues/45

**Closed by tsonevn** 2019-07-12 05:24 UTC

**Comment by Farjallahmed** [comment] 2019-07-12 08:31
thank youuuuu
