### ISSUE TITLE
#ask-follow up about nativescript 50.0 http for upload image

### ISSUE THREAD

**Issue by budineverend** [NativeScript/NativeScript#6512] opened 2018-11-06 05:50 UTC
https://github.com/NativeScript/nativescript-background-http/issues/179

please help me.......URgent!!!!!!!!!

**Comment by tsonevn** [comment] 2018-11-06 06:07
Duplicate of https://github.com/NativeScript/nativescript-background-http/issues/179

**Closed by tsonevn** 2018-11-06 06:07 UTC
