### ISSUE TITLE
segmented bar in side drawer shows error: View already has a parent

### ISSUE THREAD

**Issue by handoyo** [NativeScript/NativeScript#6083] opened 2018-07-18 08:25 UTC
Hi, i'm trying to add segmented bar via code behind into side drawer. I get the items via rest api and i get Error: View already has a parent. View: SegmentedBarItem(128) Parent: SegmentedBar(127). 

This is my xml:
https://pastebin.com/SuwbmarB

and my js file:
[https://pastebin.com/2Vfep63y](https://pastebin.com/2Vfep63y)

Please point me on my mistakes. Thanks.

**Comment by NickIliev** [comment] 2018-07-18 11:41
@handoyo the issue is most likely related to the way the SegmentedBar is working - more details can be found [here](https://github.com/NativeScript/NativeScript/issues/5471#issuecomment-372654604).

Closing as a how-to related issue.

**Closed by NickIliev** 2018-07-18 11:41 UTC
Labels: question

**Comment by handoyo** [comment] 2018-07-19 06:30
Hi @NickIliev , i have followed it yet i still get the binding error.
