### ISSUE TITLE
Error with ObservableArray

### ISSUE THREAD

**Issue by thiagoterleski** [NativeScript/NativeScript#2645] opened 2016-08-30 14:21 UTC
Hi, I'm starting with nativescript, I'm trying to create a listView and in my list.js:
`
var results = new ObservableArray([]);
var pageData = new Observable({
  results: results
})
`

But when I run, this error happens:
`TypeError: cannot set property 'disableNotifications' of undefined.`

### TNS version is 2.2.1

My entire code is:

```
var dialogsModule = require("ui/dialogs");
var LoadingIndicator = require("nativescript-loading-indicator").LoadingIndicator;
var Observable = require("data/observable").Observable;
var ObservableArray = require("data/observable-array").ObservableArray;
var SchoolModel = require("../../shared/view-models/schools-list-view-model");
var page;

var schoolsList = new SchoolModel();
var results = new ObservableArray([]);

var pageData = new Observable({
  results: results
})

var loader = new LoadingIndicator();

exports.loaded = function(args) {
  page = args.object;
  page.bindingContext = pageData;

  loader.show({
    message: 'Carregando lista..'
  });

  schoolsList.load()
  .then((results) => {

    // Update array

    loader.hide();
  });

};
```

**Comment by tsonevn** [comment] 2016-08-31 06:20
Hi @thiagoterleski,
Thank you for contacting us.
I reviewed your case, however I was unable to reproduce the problem. For your convenience I am attaching  sample code. 

main-page.xml

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <StackLayout>
    <ListView items="{{ source }}">
        <ListView.itemTemplate>
            <Label text="{{name}}" textWrap="true" />
        </ListView.itemTemplate>
    </ListView>
  </StackLayout>
</Page>
```

main-page.ts

```
import { EventData, Observable } from "data/observable";
import { Page } from "ui/page";
import { HelloWorldModel } from "./main-view-model";
import {ObservableArray} from "data/observable-array"
import {LoadingIndicator} from "nativescript-loading-indicator";
import {setTimeout} from "timer"
// Event handler for Page "navigatingTo" event attached in main-page.xml
let newloadingindicator:LoadingIndicator;

var options = {
  message: 'Loading...',
  progress: 0.65,
  android: {
    indeterminate: true,
    cancelable: false,
    max: 100,
    progressNumberFormat: "%1d/%2d",
    progressPercentFormat: 0.53,
    progressStyle: 1,
    secondaryProgress: 1
  },
  ios: {
    details: "Additional detail note!",
    square: false,
    margin: 10,
    dimBackground: true,
    color: "#4B9ED6"
  }
};


export function navigatingTo(args: EventData) {
    // Get the event sender
    var page = <Page>args.object;
    var observable = new Observable([]);
    var array:ObservableArray<any> = new ObservableArray();
    array.push({name:"name1"});
    array.push({name:"name2"});
    array.push({name:"name3"});
    newloadingindicator = new LoadingIndicator();

    observable.set('source', array);

    setTimeout(function(){
        newloadingindicator.show(options);
    }, 2000)

     setTimeout(function(){
        newloadingindicator.hide();
    }, 4000)


    page.bindingContext = observable;
}
```

main-page.js

```
var observable_1 = require("data/observable");
var observable_array_1 = require("data/observable-array");
var nativescript_loading_indicator_1 = require("nativescript-loading-indicator");
var timer_1 = require("timer");
// Event handler for Page "navigatingTo" event attached in main-page.xml
var newloadingindicator;
var options = {
    message: 'Loading...',
    progress: 0.65,
    android: {
        indeterminate: true,
        cancelable: false,
        max: 100,
        progressNumberFormat: "%1d/%2d",
        progressPercentFormat: 0.53,
        progressStyle: 1,
        secondaryProgress: 1
    },
    ios: {
        details: "Additional detail note!",
        square: false,
        margin: 10,
        dimBackground: true,
        color: "#4B9ED6"
    }
};
function navigatingTo(args) {
    // Get the event sender
    var page = args.object;
    var observable = new observable_1.Observable([]);
    var array = new observable_array_1.ObservableArray();
    array.push({ name: "name1" });
    array.push({ name: "name2" });
    array.push({ name: "name3" });
    newloadingindicator = new nativescript_loading_indicator_1.LoadingIndicator();
    observable.set('source', array);
    timer_1.setTimeout(function () {
        newloadingindicator.show(options);
    }, 2000);
    timer_1.setTimeout(function () {
        newloadingindicator.hide();
    }, 4000);
    page.bindingContext = observable;
}
exports.navigatingTo = navigatingTo;
```

Could you give us some more info about your problem or if you could send us sample project, which could be debugged localy.

Regards, 
@tsonevn

**Comment by nsndeck** [comment] 2016-09-01 14:37
@thiagoterleski This issue is fixed with `tns-core-modules@next` version and will be part of the official release 2.3.0 (mid september), meanwhile using next build is OK.

**Closed** 2016-09-30 06:38 UTC
Labels: 5 - Done, T:Bug
