### ISSUE TITLE
Control of keyboard  back button

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#7664] opened 2019-08-09 10:38 UTC
I need  control the keyboard's back button. This is the standard button to close the keyboard. In Android this is a triangle pointing down, with spoken label "back". This is different from the android back button  which in Android is a triangle pointing left and spoken label "back". I have control over this button, but not over the keyboard back (down) button.

I can open/close the keyboard, so that is not the point. I am developing an app for the blind community. The back  button with two visual appeances and behaviours, and the same spoken label "back" is misleading for them. Moreover I need to disable the standard back (down) button behaviour and/or give it some extra functionality.

I have seen the same question multiple times on the Internet, without a solution.

**Comment by NickIliev** [comment] 2019-08-09 11:05
@jokro NativeScript provides full access to the native APIs so the question here is how the native Android and iOS developers are handling the identical case? If you have a solution that works for the native apps then you have a 99.9% chance to implement it in NativeScript by accessing the native APIs.

Closing the question is the issue is not related to a problem, bug or feature but to a how-to related case. If you have a native code that you are not sure how to convert to NativeScript, please post what you have tried so far and I will be glad to take a look at it.

P.S. My guess is that to accomplish your task you will probably need to create your own custom keyboard.

**Closed by NickIliev** 2019-08-09 11:05 UTC
