### ISSUE TITLE
Having errors when using --env.uglify

### ISSUE THREAD

**Issue by jannomeister** [NativeScript/NativeScript#6884] opened 2019-02-10 06:57 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  5.1.1
 - iOS Runtime: 5.1.1

**Describe the bug**

I'm using NS Angular, when I use the command `tns run ios --bundle --env.uglify` im getting a fatal error `Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Error: moduleId should be a string in "t"` but without using `--env.uglify` my app runs perfectly.

**Comment by dtopuzov** [comment] 2019-02-11 07:52
Hi @jannomeister,

Can you please post package.json of your app.
Can you also run `tns run ios --bundle --env.uglify -env.aot` and check if the problem is fixed.

We had similar issue in some of the older version of `nativescript-angular`, but it is fixed now:
https://github.com/NativeScript/nativescript-angular/issues/1572

**Comment by NickIliev** [comment] 2019-02-20 07:33
Closing due to inactivity but please do let us know if you are still experiencing this one (and share the requested info above)

**Closed by NickIliev** 2019-02-20 07:33 UTC
Labels: needs more info

**Comment by tigrenok00** [comment] 2019-03-20 15:58
Hi,
I am having the same issue here. 
--uglify only has the same error `Error: moduleId should be a string in "t"` , but together with AOT works fine. However, we do not wish to use AOT.
Here is my package.json, please let me know if any additional info needed. It happens both with iOS and Android.

`

{
  "nativescript": {
    "id": {
      "android": "XXX",
      "ios": "XXX"
    },
    "tns-ios": {
      "version": "5.2.0"
    },
    "tns-android": {
      "version": "5.2.1"
    }
  },
  "main": "app.js",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "7.1.2",
    "@angular/common": "7.1.2",
    "@angular/compiler": "7.1.2",
    "@angular/core": "7.1.2",
    "@angular/forms": "7.1.2",
    "@angular/http": "7.1.2",
    "@angular/platform-browser": "7.1.2",
    "@angular/platform-browser-dynamic": "7.1.2",
    "@angular/router": "7.1.2",
    "crypto-js": "^3.1.9-1",
    "nativescript-angular": "7.1.0",
    "nativescript-cognito": "nativescript-cognito-1.0.3.tgz",
    "nativescript-dom": "^2.0.2",
    "nativescript-floatingactionbutton": "^5.0.0",
    "nativescript-globalevents": "^1.2.2",
    "nativescript-iqkeyboardmanager": "~1.3.0",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-ngx-fonticon": "^4.2.0",
    "nativescript-plugin-firebase": "^8.0.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-listview": "5.0.1",
    "ng2-translate": "^5.0.0",
    "reflect-metadata": "0.1.12",
    "rxjs": "^6.2.2",
    "rxjs-compat": "^6.2.2",
    "tns-core-modules": "5.1.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "7.1.2",
    "@ngtools/webpack": "7.0.7",
    "nativescript-dev-typescript": "0.7.8",
    "nativescript-dev-webpack": "^0.18.2",
    "tns-platform-declarations": "5.1.0",
    "typescript": "3.1.6"
  },
  "readme": "NativeScript Application"
}


`

**Comment by NickIliev** [comment] 2019-03-21 07:27
@tigrenok00 your `devDependencies` seems outdated. Can you [upgrade them all](https://docs.nativescript.org/releases/upgrade-instructions) to use the latest versions.

Here is what my test project looks as of this very moment (and works as expected)

```TypeScript
  "devDependencies": {
    "@angular/compiler-cli": "~7.2.0",
    "@nativescript/schematics": "~0.5.0",
    "@ngtools/webpack": "~7.2.0",
    "nativescript-dev-typescript": "~0.8.0",
    "nativescript-dev-webpack": "~0.20.0"
  },
```

**Comment by NickIliev** [comment] 2019-03-21 09:05
@tigrenok00 also try to remove the unnecessary `moduleId` from `app.component.ts` (e.g. as done [here](https://github.com/NativeScript/nativescript-angular/pull/1686/files))

**Comment by tigrenok00** [comment] 2019-03-21 14:26
@NickIliev 
Hi, I've updated several modules here, now that error is gone, however, I have a new one which happens only with uglify:
`ERROR TypeError: o.Observable.of is not a function`
I don't have Observable.of in my code, so it might be coming from one one the plugins? How can I know which one? I do use rxjs-compat. And why does it happen only when using uglify?

{
  "nativescript": {
    "id": {
      "android": "XXX",
      "ios": "XXX"
    },
    "tns-ios": {
      "version": "5.2.0"
    },
    "tns-android": {
      "version": "5.2.1"
    }
  },
  "main": "app.js",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/http": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "crypto-js": "^3.1.9-1",
    "nativescript-angular": "^7.2.3",
    "nativescript-cognito": "nativescript-cognito-1.0.3.tgz",
    "nativescript-dom": "^2.0.2",
    "nativescript-floatingactionbutton": "^5.0.3",
    "nativescript-globalevents": "^1.2.2",
    "nativescript-iqkeyboardmanager": "~1.3.0",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-ngx-fonticon": "^4.2.0",
    "nativescript-plugin-firebase": "^8.0.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-listview": "5.0.1",
    "ng2-translate": "^5.0.0",
    "reflect-metadata": "0.1.12",
    "rxjs": "^6.4.0",
    "rxjs-compat": "^6.4.0",
    "tns-core-modules": "^5.2.2",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~7.2.0",
    "@ngtools/webpack": "~7.2.0",
    "nativescript-dev-typescript": "0.7.8",
    "nativescript-dev-webpack": "^0.20.3",
    "tns-platform-declarations": "5.1.0",
    "typescript": "~3.1.1"
  },
  "readme": "NativeScript Application"
}

**Comment by NickIliev** [comment] 2019-03-21 15:07
@tigrenok00 search through your code for `Observable.of` and replace it with just `of` as shown [here](https://stackoverflow.com/a/51082056/4936697) (and also change the import as shown)

**Comment by tigrenok00** [comment] 2019-03-21 16:09
@NickIliev 
Thanks, I saw this before and hoped it was solved because the issue is marked closed. I've installed rxjs and rxjs-compat of 6.2.2 (which is mentioned to work), however, the error still persists and when I run the `npm list rxjs` as suggested there to check, it looks like the updated dev-dependcies somehow still use a newer version:
`
+-- @ngtools/webpack@7.2.4
| +-- @angular-devkit/core@7.2.4
| | `-- rxjs@6.3.3
| `-- rxjs@6.3.3
`-- nativescript-dev-webpack@0.20.3
  `-- @angular-devkit/core@7.2.4
    `-- rxjs@6.3.3
`

Do you know why does it happen? And what should I do?
Thanks!

**Comment by NickIliev** [comment] 2019-03-22 08:25
@tigrenok00 I've tested with the latest versions of `rxjs` and `rxjs-compat` plus the `@ngtools/webpack@7.2.0` and ``@angular/compiler-cli@7.2.0` and I am not experiencing this issue. Here is[ the test application ](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/NativeScript/issue-6884)which is building with no issue on my side.

Can you double check if the application is using the `of` operator somewhere in the code and if so check how the operator is imported.

**Comment by tigrenok00** [comment] 2019-03-22 11:44
@NickIliev 
Unfortunately no, it doesn't work for me still :( Tried 6.2.2 as well as 6.4.0. The imports are correct: `import { Observable, of } from "rxjs";` in our code, could it be coming from one of the plugins?

**Comment by NickIliev** [comment] 2019-03-22 12:06
@tigrenok00 not sure what might be causing this but can you[ try this solution](https://github.com/ReactiveX/rxjs/issues/4070#issuecomment-454658907) with using aliased import
```TS
import { of as observableOf} from 'rxjs';
```

If you are still experiencing the issue try to isolate the case in a sample app - I've tested with the plugins you are using but the issue is not appearing (still I had a blank code base) so I will be happy to investigate the case with a test app that can reproduce the case.
