### ISSUE TITLE
Object dot syntax in views doesn't work

### ISSUE THREAD

**Issue by maknz** [NativeScript/NativeScript#584] opened 2015-08-14 05:02 UTC
Given an object, `obj`, we are unable to access its properties in a data binding variable, e.g. `{{ obj.prop1 }}`. It silently fails. This is documented as a feature in the data binding documentation.

**Comment by nsndeck** [comment] 2015-08-14 13:09
Hi,

I cannot reproduce the problem could you please take a look at my (testPage)[https://gist.github.com/nsndeck/fb177be7e0af654e5413]. The first run of the example should display a text in the forth label (below second label). To test dot style binding just delete `bindingContext="{{ user }}"` from GridLayout xml declaration. This will show text in the second label (below first label).
Please let me know how this work on your end.

**Comment by maknz** [comment] 2015-08-14 22:20
The scenario here is we have a JSON response from an API, which is parsed into a plain old JS object, which is then data-bound with `viewModel.set()`. Can only primitive values such a string/number be used in `viewModel.set()`?

**Comment by nsndeck** [comment] 2015-08-17 15:28
Indeed I've managed to reproduce the issue (or I think it is the right one). The problem comes from the fact that in order to support dot syntax we add a `property change` listener for the object that is parent for the source property. However in some cases like yours for example you are replacing the entire instance of the source object and `property change` listener is gone and therefore binding is not working anymore. I'll make some modifications to support such scenario (but there are could be some performance issues, so I cannot commit that this will be included in next releases). For a very quick workaround you could separate object by dot and set bindingContext for the parent property to a parent panel. For example if you have something like:

<GridLayout>
    <Label text="{{ activity.Text }}" /> 
</GridLayout>

you can change it with:

<GridLayout bindingContext="{{ activity }}" >
    <Label text="{{ Text }}" /> 
</GridLayout>

**Comment by maknz** [comment] 2015-08-17 21:12
Sweet, thanks. Seems like Github isn't displaying those examples?

**Comment by nsndeck** [comment] 2015-08-19 06:10
Indeed, so I changed them a little bit.

**Comment by nsndeck** [comment] 2015-08-26 12:08
I've just committed the change that fixes the issue (https://github.com/NativeScript/NativeScript/commit/04a8babc7ea565dd3122c9d69be6fe6761c7a46c).

**Closed by nsndeck** 2015-08-26 12:08 UTC
