### ISSUE TITLE
ListView rendering bug on scroll

### ISSUE THREAD

**Issue by shabib3** [NativeScript/NativeScript#5621] opened 2018-04-04 15:15 UTC
Hi I faced this problem a lot, but now it is actually matter to the business logic.

I have ListView of items which every item can be selected by the user (some business logic flow).
and the thing is that the ListView shows false data because some rendering problem.
In that case - when I select an item I see in visually on the item it self and also on the 5th item after him. (Actually every visual thing that happened on the a specific item happen also on the 5th item after him - seem to be related to what the screen can fit).

here is a video example -> https://www.youtube.com/watch?v=Sy4Dxk-74CI

Here I try to reproduce this issue in a [playground example](https://play.nativescript.org/?template=play-ng&id=zmTZ5q) - but actually without success...(put it here just for reference to similar UI)

**Comment by tsonevn** [comment] 2018-04-05 07:40
Duplicate of #[1245](https://github.com/NativeScript/nativescript-angular/issues/1245)

**Closed by tsonevn** 2018-04-05 07:40 UTC
