### ISSUE TITLE
error after update [;ayground app

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#6498] opened 2018-11-02 19:04 UTC
My nativscript app has just been updated. I do not know if this is the problem, or there is a bug in the following playground example:   [components ](https://play.nativescript.org/?template=play-tsc&id=o87l19&v=3) On android. It gives the following error:

[moto g(6) play]: An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onViewAttachedToWindow failed

TypeError: backstackEntry.resolvedPage.onNavigatingTo is not a function
File: "file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js, line: 266, column: 36

StackTrace: 
Frame: function:'FrameBase._onNavigatingTo', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 266, column: 37
Frame: function:'FrameBase.performNavigation', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 238, column: 14
Frame: function:'FrameBase._processNextNavigationEntry', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 231, column: 22
Frame: function:'Frame._processNextNavigationEntry', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 143, column: 58
Frame: function:'Frame._onAttachedToWindow', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 118, column: 14
Frame: function:'AttachListener.onViewAttachedToWindow', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 35, column: 27

at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
at com.tns.Runtime.callJSMethod(Runtime.java:983)
at com.tns.Runtime.callJSMethod(Runtime.java:967)
at com.tns.Runtime.callJSMethod(Runtime.java:959)
at com.tns.gen.java.lang.Object_frame_29_36_AttachListener.onViewAttachedToWindow(Object_frame_29_36_AttachListener.java:17)
at android.view.View.dispatchAttachedToWindow(View.java:17404)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3322)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3329)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3329)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3329)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3329)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3329)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1686)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1414)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6827)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
at android.view.Choreographer.doCallbacks(Choreographer.java:723)
at android.view.Choreographer.doFrame(Choreographer.java:658)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6694)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)

**Comment by tsonevn** [comment] 2018-11-05 07:18
Hi @jokro,
The problem which you are facing was caused by the fact that there was `XML` defined outside the `Page` scope in the home-page.xml file. Check out the code snippet below:
```
<Page loaded="pageLoaded" class="page" xmlns:widget="home" xmlns="http://www.nativescript.org/tns.xsd">

	<ActionBar title="Home" class="action-bar">
	</ActionBar>

	<ScrollView>
		<StackLayout class="home-panel">
			<!--Add your page content here-->
			<Label textWrap="true" text="Play with NativeScript!" class="h2 description-label" />
			<Label textWrap="true" text="Write code in the editor or drag and drop components to build a NativeScript mobile application."
			 class="h2 description-label" />
			<Label textWrap="true" text="Scan the QR code with your mobile device and watch the changes sync live while you play with the code."
			 class="h2 description-label test" />
			<Button text="Button" tap="{{ onButtonTap }}" />
			<widget:custom />
		</StackLayout>
	</ScrollView>
</Page>
<!-- <Image src="https://play.nativescript.org/dist/assets/img/NativeScript_logo.png" />
<Slider value="80" />
<TextView editable="false">
	<FormattedString>
		<Span text="This is a text view that uses attributed text. You can use text attributes such as " />
		<Span text="bold, " fontWeight="Bold" />
		<Span text="italic " fontStyle="Italic" />
		<Span text="and " />
		<Span text="underline." textDecoration="Underline" />
	</FormattedString>
</TextView>
<TimePicker hour="{{ currentHour }}" minute="{{ currentMinute }}" verticalAlignment="center" /> -->
```
If you remove the code after the Page closing tag, the project will be built properly.

**Closed by tsonevn** 2018-11-05 07:18 UTC
Labels: os: android

**Comment by jokro** [comment] 2018-11-06 15:42
@ tsonevn
The solution is clear. Did you notice that the Natiscript documentation links to this example as a template ?  I dont remember exactly where I clicked the  link.

**Comment by tsonevn** [comment] 2018-11-07 06:45
Hi @jokro,
I am not aware of the existence of a similar example. It will help if you can find where you have seen it and to link it to the issue.

**Comment by jokro** [comment] 2018-11-07 10:08
I will try to find itOp 7 nov. 2018 07:46 schreef Nikolay Tsonev <notifications@github.com>:Hi @jokro,
I am not aware of the existence of a similar example. It will help if you can find where you have seen it and to link it to the issue.

**Comment by jokro** [comment] 2018-11-07 10:35
I found the location which references a buggy example. Look for link "try this project on the NativeScript Playground" on page [documentation](https://docs.nativescript.org/ui/styling#page-specific-css).

**Comment by tsonevn** [comment] 2018-11-07 11:17
PR https://github.com/NativeScript/docs/pull/1426
