### ISSUE TITLE
Inconsistency in NativeScript GridLayout rows/cols

### ISSUE THREAD

**Issue by ibnYusrat** [NativeScript/NativeScript#7354] opened 2019-06-14 08:59 UTC
**Is your feature request related to a problem? Please describe.**

In my humble opinion, it should either be
`<GridLayout rows="auto auto" cols="auto auto"></GridLayout>`

and then: `<Lable row="0" col="0"></Label>` etc.

*or*

`<GridLayout rows="auto auto" columns="auto auto"></GridLayout>`

and then: `<Lable row="0" column="0"></Label>` etc.

It almost always gets me when I am not copying pasting, as to which one is using col and which one is using column.

**Did anyone else ever feel this inconsistency?**

My market research in this particular subject is not vast enough.

**Describe the solution you'd like**
Would it be too much work for the NativeScript guys to simply add a wrapper for col and column in both rows and top level GridLayout tag? Because that way the existing projects wont break and new learners will be less confused.

**Comment by tsonevn** [comment] 2019-06-14 13:04
Duplicate of https://github.com/NativeScript/NativeScript/issues/7295

**Closed by tsonevn** 2019-06-14 13:04 UTC
