### ISSUE TITLE
npm list -g --depth=0 shows errors after installing nativescript@7.0.11

### ISSUE THREAD

**Issue by etelvinacunha** [NativeScript/NativeScript#9071] opened 2020-11-27 17:13 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: nativescript 7.0.11
 - OS X 10.15.7
 - Node : v12.18.3
 - npm: 6.14.9

**Describe the bug**
After installing nativescript with npm install -g nativescript, I get an error when running npm list -g --depth=0: 
![image](https://user-images.githubusercontent.com/38136226/100472131-8c006180-30d3-11eb-9ccd-a577b496e316.png)

npm ERR! peer dep missing: marked@^0.4.0 || ^0.5.0, required by marked-terminal@3.1.1

**To Reproduce**
npm install -g nativescript
npm list -g --depth=0

**Expected behavior**
No error

**Comment by rigor789** [comment] 2020-11-27 17:38
Duplicate of #9055

**Closed by rigor789** 2020-11-27 17:38 UTC
