### ISSUE TITLE
Hide background apps blue color status bar in iOS

### ISSUE THREAD

**Issue by ishaqueahmed-mev** [NativeScript/NativeScript#7833] opened 2019-09-17 05:18 UTC
Hello, 

I am using nativescript-angular, and I am having a issue in iOS SE device, when any location app is running in background and watching for location change, and I start my app, the location app notification is shown above the app at status bar, so the design gets a bit messy, is there any way where I can hide that blue-bar programmatically, or anything else for which my design doesn't suffers, also issue occurs only in SE device.

Any help would be great.

**Comment by tsonevn** [comment] 2019-09-17 07:13
Duplicate of https://github.com/NativeScript/NativeScript/issues/7812

**Closed by tsonevn** 2019-09-17 07:13 UTC
