### ISSUE TITLE
I get "Error:0-Unknown Error Http failure response for https://10.0.2.2" while oppening Android emulator

### ISSUE THREAD

**Issue by rezaee** [NativeScript/NativeScript#7500] opened 2019-07-10 16:27 UTC
This is the result of `tns info` command:
```
√ Getting NativeScript components versions information...
‼ Update available for component nativescript. Your current version is 5.4.0 and the latest available version is 5.4.2.
‼ Update available for component tns-core-modules. Your current version is 5.4.2 and the latest available version is 5.4.3.
√ Component tns-android has 5.4.0 version and is up to date.
‼ Update available for component tns-ios. Your current version is 5.4.1 and the latest available version is 5.4.2.
```

I have uploaded my project here https://github.com/rezaee/conFusion, but when I try to run it using `tns run android --device Pixel_2_API_29` it opens my emulator but shows this error message on the emulator's screen: 

`Error:0-Unknown Error Http failure response for https://10.0.2.2`

I use `json-server` on my local machine on `http://localhost:3000/` address and I can access to the contents on my PC's browser. I also can reach to the contents on my Android emulator's browser with this address: `http://10.0.2.2:3000/`, but don't know why when I open my application on my Android emulator it gives me the above error message on the emulator's screen.

In my project there is a file named baseURL at here https://github.com/rezaee/conFusion/blob/master/src/app/shared/baseurl.ts that I put the above URL address there, but don't know why it doesn't work?

Why this happens and how can I fix it?
This is about one month that I have this problem and NO ONE could give me an answer to solving the problem!

**Comment by jannomeister** [comment] 2019-07-11 01:30
try to use [ngrok](https://ngrok.com/) to have a public url to expose your local server.

**Comment by NickIliev** [comment] 2019-07-11 07:00
@rezaee the repository is for logging issues, bugs and feature request related to NativeScript framework. For how-to related issues, please consider posting the question in the community channels like StackOverflow or the community NatievScript slack channel.

CLosing as a duplicate to https://github.com/NativeScript/NativeScript/issues/7475 and to https://github.com/NativeScript/NativeScript/issues/7472.

Note: c[heck my comment here ](https://github.com/NativeScript/NativeScript/issues/7475#issuecomment-510348385)about testing non-secure HTTP request on Android 8 and above

**Closed by NickIliev** 2019-07-11 07:00 UTC
Labels: os: android, question

**Comment by NickIliev** [comment] 2019-07-11 07:25
Test on API29 and the issue is that you are probably missing the cleartext permission in `AndroidManifest.xml` file.

Set is as done [here](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/App_Resources/Android/src/main/AndroidManifest.xml#L29).

Also, I've noticed that you are using **https** for a baseURl while the json-server is providing non-secure HTTP address
so change
```TypeScript
export const baseURL = "https://10.0.2.2:3000/";
```

to

```TypeScript
export const baseURL = "http://10.0.2.2:3000/";
```

**Comment by rezaee** [comment] 2019-07-11 07:41
@NickIliev : You are GREAT man! you solved my problem after near to 1 month!

**Comment by suppadeliux** [comment] 2020-08-15 16:37
> Test on API29 and the issue is that you are probably missing the cleartext permission in `AndroidManifest.xml` file.
> 
> Set is as done [here](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/App_Resources/Android/src/main/AndroidManifest.xml#L29).
> 
> Setting `android:usesCleartextTraffic` in AndroidManifest.xml
> 
> ```
> <application android:name="com.tns.NativeScriptApplication"
>           android:allowBackup="true"
>           android:icon="@drawable/opportuity"
>           android:label="@string/app_name"
>           android:theme="@style/AppTheme"
>           android:usesCleartextTraffic="true">		
> ```
> 
> Also, I've noticed that you are using **https** for a baseURl while the json-server is providing non-secure HTTP address
> so change
> 
> ```ts
> export const baseURL = "https://10.0.2.2:3000/";
> ```
> 
> to
> 
> ```ts
> export const baseURL = "http://10.0.2.2:3000/";
> ```

This is the best solution I was able to find, thank you @NickIliev
