### ISSUE TITLE
Chrome Dev Tools Not Showing Elements

### ISSUE THREAD

**Issue by radiohe4d** [NativeScript/NativeScript#9058] opened 2020-11-20 14:27 UTC
**Environment:**
 - CLI: 7.0.11
 - @nativescript/core: 7.0.0
 - @nativescript/android:  7.0.1
 - @angular/core:  10.1.0
 - HostSystem:  Windows 10
 - Chrome: 87.0.4280.66 (x64)

**The Issue:**
When debugging the android application, either using an emulator or a real device, opening the chrome debug url `devtools://devtools/bundled/inspector.html?ws=localhost:40000` connects to the app and I can view the console output and access the loaded app .ts and .xml files.

The elements tab however is completely blank. We've used this before to help with styling the UI, so without it we're a bit in the dark. 

**Additional Context:**
Myself and another colleague have tried using both standard and incognito tabs with the same result. 

I've looked over the web quite a bit over the last few days and haven't found anything around this specific issue, so not sure if its a new bug or something specific to our project.

**Full Dependencies List:**
<details>
  <summary>package.json dependencies</summary>

```
  "dependencies": {
    "@angular/animations": "~10.1.0",
    "@angular/common": "~10.1.0",
    "@angular/compiler": "~10.1.0",
    "@angular/core": "~10.1.0",
    "@angular/forms": "~10.1.0",
    "@angular/platform-browser": "~10.1.0",
    "@angular/platform-browser-dynamic": "~10.1.0",
    "@angular/router": "~10.1.0",
    "@nativescript/angular": "~10.1.0",
    "@nativescript/core": "~7.0.0",
    "@nativescript/firebase": "^11.1.3",
    "@nativescript/theme": "~3.0.0",
    "address": "^1.1.2",
    "nativescript-fonticon": "^2.0.0",
    "nativescript-modal-datetimepicker": "^2.1.2",
    "nativescript-toasty-ns-7": "^14.0.0",
    "nativescript-ui-autocomplete": "^7.0.2",
    "nativescript-ui-chart": "^8.0.2",
    "nativescript-ui-dataform": "^7.0.4",
    "nativescript-ui-gauge": "^7.0.2",
    "nativescript-ui-listview": "^9.0.4",
    "nativescript-ui-sidedrawer": "^9.0.3",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.6.0",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~10.1.0",
    "@nativescript/android": "7.0.1",
    "@nativescript/ios": "7.0.5",
    "@nativescript/types": "~7.0.0",
    "@nativescript/webpack": "~3.0.0",
    "@ngtools/webpack": "~10.1.0",
    "sass": "^1.29.0",
    "typescript": "~4.0.0"
  }
```
</details>

**Comment by rigor789** [comment] 2020-11-20 15:46
See https://github.com/NativeScript/NativeScript/pull/8996/files and try applying the change to your webpack config.
This is for ios. Android fix is unknown at the moment.

**Comment by radiohe4d** [comment] 2020-11-20 15:59
Thanks @rigor789 . We are only developing the Android app for now, so cant test those changes on iOS.

Is there an open ticket to specifically look into the chrome dev tools fix for Android?

@NathanWalker  mentions its still under investigation here: [8996](https://github.com/NativeScript/NativeScript/pull/8996#issuecomment-726510816)

**Comment by rigor789** [comment] 2020-11-20 16:04
I'm not aware of an open issue (apart from this one I guess) just the PR that's pending as we have to find the issue on android.

**Comment by talha48** [comment] 2020-12-02 05:49
I am having same issue.

**Comment by bradrice** [comment] 2020-12-18 21:03
I was going to report this as well. I'm glad it is listed as an issue.

**Comment by billfrost** [comment] 2021-01-02 23:49
Any chance of a fix soon?
With Nativescript 7.1 not showing Elements in Chrome devtools, and VS Code debugger not allowing breakpoints, it is impossible to conduct any form of usable debugging right now.
Given that HMR is also broken and showing white screen after updates, the NS 7.1 experience is not a good one.  Productivity is gone.

**Comment by sido420** [comment] 2021-02-17 14:45
Its super important to fix this asap. Its been a pain.

Also, I dont see any network activity even in previous NS versions.

**Comment by rigor789** [comment] 2021-02-17 15:22
@sido420 ios seems to be working in latest version, but I couldn't find the issue on android - spent a few hours debugging & everything looks correct - except it doesn't show.

**Comment by sido420** [comment] 2021-02-17 16:53
@rigor789 Thanks for looking into this issue. I just checked NS 6.x and it does work.

Has network activity ever worked on any NS version?

**Comment by Carleslc** [comment] 2021-05-05 19:01
Any updates? It's frustrating to debug the UI of an Android App without this.
Is there an alternative?

**Comment by FaizulHassan** [comment] 2021-06-14 09:14
Is it resolved ? I get the same issue after upgrading to version 6 to 8..

Do we have any alternative for this ? As we find it very difficult to deal with styling.

**Comment by Bezlepkin** [comment] 2021-06-18 06:49
NS 8 + Angular 11.2.7. Same issue! The DOM element debugger in Chrome is very lacking....

**Comment by OscarMeier** [comment] 2021-07-09 09:16
I have the same issue with NS 8  & Angular 12. It would be great if you could prioritize this task, because styling can be very difficult and time-consuming without a working UI debugger.

**Comment by MohammedrezaFouladi** [comment] 2021-07-23 17:58
Seems some changes happened in chrome devtools and now NS devtools doesn't show any network trafics when api calls for me.
I think this is a new issue :(

**Comment by slejnej** [comment] 2021-08-13 16:30
Still the issue... Android (device & emulator), NS7 & Angular 11.

**Comment by s0l4r** [comment] 2021-09-06 08:46
Having the same issue with NS 8 and Angular 12 and Devtools for Chrome (Version 93.0.4577.63 (Official Build) (x86_64)). The debugger works about 10%, and in latest Chromium it does not work at all. Is there any alternative or how do we debug without it?

**Comment by Epse** [comment] 2021-09-09 08:29
This gets labeled as a bug now?? Delightful

**Comment by rigor789** [comment] 2021-09-09 08:46
@Epse https://github.com/NativeScript/android-runtime/pull/1672 should be fixed in 8.1.0 soon. And a heads up, debugging issues like these takes a while - and can end up being a lesser priority than bugs that affect production.

_PS.: Snarky comments are not motivating for anyone to then take hours of their free time to fix something, just fyi..._

**Comment by Epse** [comment] 2021-09-09 08:51
Hi @rigor789 fully aware about snariness not being terribly great fun, I should have written my comment better. What I wanted to express was that for bug reporters (not me in this case) it is also not very motivating to have it suddenly get marked a bug after a whole year. We can't see the progress, and seeing a label appear is a "oh now they notice this?" moment. In the past, I have used an "i-have-seen-this" label or similar.

Regardless, my thanks for the effort, debugging the debugging tools can't possibly be fun

**Comment by rigor789** [comment] 2021-09-09 09:00
@Epse no worries. I understand the frustration, I do experience it from both sides (maintainer and consumer), we'll try to label issues sooner and better. It is one of our roadmap goals to improve the repository health with better labeling, using the discussions more, etc.

**Comment by Epse** [comment] 2021-09-09 09:02
@rigor789 so great to hear you all are keeping this in mind! Thank you very much

**Comment by hmG3** [comment] 2022-02-21 15:23
Just updated to the latest versions of Nativescript packages and the Elements tab is working again.
```
@nativescript/core: 8.1.5
@nativescript/android: 8.1.1
@nativescript/webpack: 5.0.4
@nativescript/types: 8.1.1
```

**Closed** 2023-05-12 17:53 UTC
Labels: bug, in progress

**Comment by Sefibrah** [comment] 2024-07-28 11:16
I still get this bug... What's the problem now?

<img width="850" alt="Screenshot 2024-07-28 at 14 16 17" src="https://github.com/user-attachments/assets/9aa4f12a-d4fc-4679-9809-d1db47b3e167">

**Comment by vallemar** [comment] 2024-07-28 12:03
Hi @Sefibrah click on document for open tree of elements

**Comment by Sefibrah** [comment] 2024-07-28 12:28
@vallemar, thank you for the quick response! Yes! That worked. Apparently I needed to double click it instead of clicking the lil arrow on the left. But I am curious why can't I look at the styles of certain elements? Is the debugger really only for debugging scripts? Is this how it was intended?

<img width="1073" alt="Screenshot 2024-07-28 at 15 23 43" src="https://github.com/user-attachments/assets/f5029ebd-ea56-4603-9b03-cb2b36421e1b">

**Comment by bradrice** [comment] 2024-07-28 12:42
I like to use the Network tab for development and I can't get that to work.
