### ISSUE TITLE
Nativescript 8.0.1, Android Release APK Crashed Every time When Launch (Development/Debug APK runs fine)

### ISSUE THREAD

**Issue by maxlam79** [NativeScript/NativeScript#9363] opened 2021-04-28 06:37 UTC
Hi there,

I ported a Nativescript project from NS7 to NS8 (8.0.1). The project ran smoothly on both my Android phone and the emulator with:

```
ns run android
```
or
```
ns build android --clean && adb install ./platforms/android/app/build/outputs/apk/debug/app-debug.apk
```

BUT after producing the release/production APK with:
```
ns platform remove android && \
ns platform add android && \
ns build android \
--clean --release --env.aot \
--key-store-path ./some.keystore \
--key-store-password somepassword \
--key-store-alias myproject \
--key-store-alias-password somepassword \
--copy-to ./dist/myapp-prod.apk && \
adb install ./dist/myapp-prod.apk
```

It keeps crashing every time when it launches, be it on the emulator or the physical phone.

Since it is a production/release APK, I have no idea how to diagnose or see the stacktrace. Help needed here.

And if require, I could even send you both the debug and the release APK.

Here are the app's dependencies:
```
"dependencies": {
    "@angular/animations": "~11.2.7",
    "@angular/common": "~11.2.7",
    "@angular/compiler": "~11.2.7",
    "@angular/core": "~11.2.7",
    "@angular/forms": "~11.2.7",
    "@angular/platform-browser": "~11.2.7",
    "@angular/platform-browser-dynamic": "~11.2.7",
    "@angular/router": "~11.2.7",
    "@nativescript-community/insomnia": "^2.0.2",
    "@nativescript/angular": "~11.8.0",
    "@nativescript/core": "~8.0.0",
    "@nativescript/firebase": "^11.1.3",
    "@nativescript/social-share": "^2.0.4",
    "@nativescript/theme": "~3.0.1",
    "@nstudio/nativescript-cardview": "^2.0.1",
    "@nstudio/nativescript-exoplayer": "^5.0.6",
    "@triniwiz/nativescript-toasty": "^4.1.3",
    "jwt-decode": "^3.1.2",
    "moment": "^2.29.1",
    "nativescript-audio": "^6.2.4",
    "nativescript-ui-dataform": "^7.0.4",
    "nativescript-ui-listview": "^9.1.0",
    "ngx-moment": "^5.0.0",
    "reflect-metadata": "~0.1.13",
    "rxjs": "~6.6.7",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~11.2.7",
    "@nativescript/android": "8.0.0",
    "@nativescript/ios": "8.0.0",
    "@nativescript/types": "~8.0.0",
    "@nativescript/webpack": "beta",
    "@ngtools/webpack": "~11.2.6",
    "typescript": "~4.0.0"
  },
```

Environment:
1) Max OSX 11.2.3
2) Java (Azul JDK zulu11.45.27-ca-jdk11.0.10) 
3) Android SDK: Android 10.0 API Level 29
4) Nativescript 8.0.1

**Comment by NathanWalker** [comment] 2021-05-05 03:25
This is likely a dupe of this: https://github.com/NativeScript/NativeScript/issues/9358

**Comment by janoshrubos** [comment] 2021-09-02 13:12
@maxlam79 here is a workaround posted on the other issue by @NathanWalker: https://github.com/NativeScript/NativeScript/issues/9358#issuecomment-836831374

I hope that helps you!

**Closed** 2021-09-02 13:16 UTC
Labels: os: android
