### ISSUE TITLE
backgroundImage for urls doesnt work since nativescript 3.0

### ISSUE THREAD

**Issue by jet-lee-m** [NativeScript/NativeScript#4226] opened 2017-05-18 13:57 UTC
### Tell us about the problem

Hi, my problem is that I cannot use "backgroundImage" in my template since I updated to NativeScript 3.0. 

`<StackLayout  [backgroundImage]="'https://www.someurl.com/img.jpeg'"></StackLayout>`

The following error occurs:

`file:///app/tns_modules/tns-core-modules/ui/styling/background.js:223:15: JS ERROR TypeError: null is not an object (evaluating 'params.sizeX')`

I need the backgroundImage directive because I iterate over a item-list with different background-images ([backgroundImage]='item.url'). 

### Which platform(s) does your issue occur on?
- iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.1
- Cross-platform modules: tns-core-modules@~3.0.0
- Runtime(s): tns-ios 3.0.1

**Comment by NickIliev** [comment] 2017-05-18 14:30
@jet-lee-m I was not able to reproduce the issue.
I am using [this test application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4226) and setting backgroundImage [here](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/NativeScript/issue_4226/app/item/items.component.html#L1) just as in your example snippet and everything works as expected on my side (using tns-core-modules 3.0.0) 

If possible please provide a sample application that can reproduce this issue.

**Comment by jet-lee-m** [comment] 2017-05-18 14:50
@NickIliev You use a local image and not a web-image with an url. With an url like "www.image.com/image.jpeg" your example doesn't work.

**Comment by Jonatthu** [comment] 2017-05-18 18:35
https://github.com/NativeScript/NativeScript/issues/4143

**Comment by NickIliev** [comment] 2017-05-19 05:36
@Jonatthu is absolutely right - this bug is already fixed and the fix will be released in our next version.
Meanwhile you can test the the enxt version with
```
rm -rf node_modules
rm -rf platforms
tns plugin remove tns-core-modules
tns plugin add tns-core-modules@next
tns run android
```

Closing as resolved via [https://github.com/NativeScript/NativeScript/issues/4143](https://github.com/NativeScript/NativeScript/issues/4143)

**Closed by NickIliev** 2017-05-19 05:36 UTC
Labels: iOS, T:Question
