### ISSUE TITLE
image-cache crashes on iOS when image is not found

### ISSUE THREAD

**Issue by JWiseCoder** [NativeScript/NativeScript#7036] opened 2019-03-14 22:07 UTC
When image-cache requests an image from a url and that url does not return an image (regardless of the response code), it loads a null image.  The image cache then calls "set" with the null image, which on iOS is using NSCache.  However, NSCache cannot set a nil value, which causes the app to crash.  It will not log an error in the Simulator (it will simply crash), but if you run it on a device, it will show the following error:

`-[NSCache setObject:forKey:cost:]: attempt to insert nil value`

I think the solution would be to add a null check inside the 'set' method.

**Comment by tsonevn** [comment] 2019-03-15 05:56
Duplicate of #7033

**Closed by tsonevn** 2019-03-15 05:56 UTC
