### ISSUE TITLE
...`darwin-x64-v8-3.28/binding.node` is missing. Try reinstalling `prebuilt`?

### ISSUE THREAD

**Issue by diego-vieira** [NativeScript/NativeScript#278] opened 2015-06-04 16:24 UTC
After installing and now getting this when trying to add the platform.

```shell
diego@Diegos-MacBook-Pro:~/Nativescript/hello-world$ tns platform add ios
`/usr/local/lib/node_modules/nativescript/node_modules/ref/bin/darwin-x64-v8-3.28/binding.node` is missing. Try reinstalling `prebuilt`?
Usage:
    $ tns platform add <Platform> [--frameworkPath <File Path>] [--symlink]
```

**Comment by Fatme** [comment] 2015-06-04 17:47
Hi @diego-vieira,
It seems that you have installed NativeScrtipt CLI with node 0.12.x but now you are using node 0.10.x. I can suggest you to change your node version or reinstall the CLI.

**Comment by diego-vieira** [comment] 2015-06-05 00:11
Hi @Fatme thanks for the suggestion.
I'm running node 0.12.2 and npm 2.7.4

This is what I got when I tried to uninstall
```
> nativescript@1.0.2 preuninstall /Users/diego/npm/lib/node_modules/nativescript
> node preuninstall.js

unable to resolve cancellationService
Error: Unknown command 'dev-preuninstall'. Try '$ tns help' for a full list of supported commands.
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:488:15)
    at /Users/diego/npm/lib/node_modules/nativescript/lib/nativescript-cli.js:16:45
    - - - - -
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:488:15)
    at /Users/diego/npm/lib/node_modules/nativescript/lib/common/dispatchers.js:37:85
    at Function.settle (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    at /Users/diego/npm/lib/node_modules/nativescript/lib/nativescript-cli.js:16:45
    - - - - -
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:488:15)
    at /Users/diego/npm/lib/node_modules/nativescript/lib/common/services/commands-service.js:72:100
    at Function.settle (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    at /Users/diego/npm/lib/node_modules/nativescript/lib/common/dispatchers.js:37:85
    at Function.settle (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    at /Users/diego/npm/lib/node_modules/nativescript/lib/nativescript-cli.js:16:45
    - - - - -
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:488:15)
    at /Users/diego/npm/lib/node_modules/nativescript/lib/common/errors.js:107:40
    at Function.settle (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    at /Users/diego/npm/lib/node_modules/nativescript/lib/common/services/commands-service.js:72:100
    at Function.settle (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    at /Users/diego/npm/lib/node_modules/nativescript/lib/common/dispatchers.js:37:85
    at Function.settle (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    - - - - -
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:488:15)
    at /Users/diego/npm/lib/node_modules/nativescript/lib/common/services/commands-service.js:50:55
    at Function.settle (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    at /Users/diego/npm/lib/node_modules/nativescript/lib/common/errors.js:107:40
    at Function.settle (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    at /Users/diego/npm/lib/node_modules/nativescript/lib/common/services/commands-service.js:72:100
    at Function.settle (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    - - - - -
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:488:15)
    at /Users/diego/npm/lib/node_modules/nativescript/lib/common/commands/help.js:24:87
    at Function.settle (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    at /Users/diego/npm/lib/node_modules/nativescript/lib/common/services/commands-service.js:50:55
    at Function.settle (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    at /Users/diego/npm/lib/node_modules/nativescript/lib/common/errors.js:107:40
    at Function.settle (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    - - - - -
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:488:15)
    at /Users/diego/npm/lib/node_modules/nativescript/lib/common/services/html-help-service.js:126:68
    at Function.settle (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    at /Users/diego/npm/lib/node_modules/nativescript/lib/common/commands/help.js:24:87
    at Function.settle (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    at /Users/diego/npm/lib/node_modules/nativescript/lib/common/services/commands-service.js:50:55
    at Function.settle (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:220:26)
    at FiberFuture.Future.wait (/Users/diego/npm/lib/node_modules/nativescript/node_modules/fibers/future.js:487:10)
    - - - - -
    at Object.<anonymous> (/Users/diego/npm/lib/node_modules/nativescript/lib/common/errors.js:7:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Yok.resolveDependency (/Users/diego/npm/lib/node_modules/nativescript/lib/common/yok.js:330:13)
    at Yok.resolveByName (/Users/diego/npm/lib/node_modules/nativescript/lib/common/yok.js:307:35)
    at Yok.resolve (/Users/diego/npm/lib/node_modules/nativescript/lib/common/yok.js:247:25)
Failed to complete all pre-uninstall steps. 
{ [Error: Command failed: /bin/sh -c node bin/nativescript.js dev-preuninstall
]
  killed: false,
  code: 127,
  signal: null,
  cmd: '/bin/sh -c node bin/nativescript.js dev-preuninstall' }
unbuild nativescript@1.0.2
```

Reinstalling didn't solve either.
Thanks

**Comment by Nathanaela** [comment] 2015-06-05 02:06
It might be related to #208 -- this is fixed in a later version of TNS; but install/deinstall can still be affected by it.

**Comment by teobugslayer** [comment] 2015-06-05 08:06
I have verified that this is a genuine bug in the CLI, the issue is at https://github.com/telerik/mobile-cli-lib/blob/f11ecb9071bee846bd0964da3cdf59ba41c214b1/services/cancellation.ts#L83 - we are registering one name but requiring another one at https://github.com/telerik/mobile-cli-lib/blob/f11ecb9071bee846bd0964da3cdf59ba41c214b1/commands/preuninstall.ts#L14 .

I will fix this issue in master for the release and will provide a work-around as soon as possible.

**Comment by ErjanGavalji** [comment] 2015-06-05 08:10
This issue was moved to NativeScript/nativescript-cli#525

**Closed by ErjanGavalji** 2015-06-05 08:10 UTC
