### ISSUE TITLE
Can't compile the app with Xcode 12 in a iOS14 device

### ISSUE THREAD

**Issue by alexrcid** [NativeScript/NativeScript#8866] opened 2020-09-18 16:08 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.5.0
 - Cross-platform modules: angular
 - Android Runtime: 6.5.0
 - iOS Runtime: Tried with 6.5.0 & 6.5.2
 - Plugin(s): "nativescript-cfalert-dialog": "1.0.15",
    "nativescript-clipboard": "^1.2.0",
    "nativescript-local-notifications": "4.2.1",
    "nativescript-material-bottomsheet": "3.2.8",
    "nativescript-material-textfield": "3.2.9",
    "nativescript-mediafilepicker": "3.0.1",
    "nativescript-ngx-fonticon": "^4.2.0",
    "nativescript-pdf-view": "2.2.0",
    "nativescript-plugin-firebase": "^10.5.2",
    "nativescript-social-share": "^1.6.0",
    "nativescript-ui-listview": "8.2.0",

**Describe the bug**
When I try to compile, the app can´t be compiled. If i have already installed on the device, it works but if not, it never compiles.
'Unable to apply changes on device: 7B97420C-7C57-489B-8C5A-A84D33CE33D0. Error is: Command xcodebuild failed with exit code 65.'

**To Reproduce**

**Expected behavior**
Compile the app

**Sample project**

**Additional context**

**Comment by Ross-Olivares** [comment] 2020-09-18 19:22
Hi @alexrcid 
Thank you for reporting this issue.
We are going to try replicate this case on our end. Let me know if you can send us a sample project so we can reproduce the issue.

**Comment by joralegre** [comment] 2020-09-19 16:15
Same problem here!

**Comment by syonfabian** [comment] 2020-09-24 09:34
Is there any update, since our app always crashes at the startup. Same applies e.g. for NS Playground app.

**Comment by huyaxiong** [comment] 2020-10-02 11:58
Any updates? Same problem here!

**Comment by rigor789** [comment] 2020-10-02 12:01
All updates are in #8867

**Comment by NathanWalker** [comment] 2020-10-03 22:25
See closing details here: https://github.com/NativeScript/NativeScript/issues/8867#issuecomment-703171842

**Closed by NathanWalker** 2020-10-03 22:25 UTC

**Comment by adideas** [comment] 2022-04-11 21:08
HI !

Here is what helped me 
- XCODE 13.3.1
- NativeScript 8.0.2 cli
- Platform IOS "6.5.2"

STEP 1 (build.xcconfig)

```
// xcode 13
EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64=arm64 arm64e armv7 armv7s armv6 armv8
EXCLUDED_ARCHS=$(inherited)
$(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT))

IPHONEOS_DEPLOYMENT_TARGET = 12.0
```


STEP 2 (Podfile)

```
pod 'CocoaAsyncSocket'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] ='NO'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
    end
  end
end

IPHONEOS_DEPLOYMENT_TARGET = 12.0
```
give me a star thanks
