### ISSUE TITLE
how to remove the curved borders from modal popup innativescript

### ISSUE THREAD

**Issue by kanchanagarwal3** [NativeScript/NativeScript#6316] opened 2018-09-28 05:02 UTC
nativescript-4.1.1

Using ModalDialogParams Module for entrycomponent 
Is it possible to resize the modal popup and also to remove the curved boundaries

**Comment by NickIliev** [comment] 2018-09-28 05:59
@kanchanagarwal3 the modal pages can have custom size on Andriod but on iOS can only be fullscreen  ([documentation section](https://docs.nativescript.org/core-concepts/navigation#modal-pages)).

To achieve custom size on Android when opening the modal page via showModal you should pass the fullscreen boolean parameter as `false`

Demonstration in [this Playground demo](https://play.nativescript.org/?template=play-tsc&id=1jSlkT).

Not sure what you mean by curved borders so you might need to provide more information on what you have tried and what you are trying to achieve. As the issue is how-to related I am closing this one - please consider posting how-to related issues in the community channels (e.g. [SO nativescript tag](https://stackoverflow.com/questions/tagged/nativescript))

**Closed by NickIliev** 2018-09-28 05:59 UTC
Labels: question
