### ISSUE TITLE
Issue with TabView, while using it directly in the page

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#5901] opened 2018-06-01 12:26 UTC
The TabView's Tabs will not be rendered while using the component directly inside the Page. For example:
```
<Page
    navigatingTo="onNavigatingTo"  
    xmlns="http://schemas.nativescript.org/tns.xsd">
//.........
  <TabView>
     <TabViewItem title="First tab">
		<TabViewItem.view>
        <GridLayout rows="" columns="">
            <ScrollView>
                <StackLayout>
                   //............
                </StackLayout>
            </ScrollView>
        </GridLayout>
            
		</TabViewItem.view>  
     </TabViewItem>
     <TabViewItem title="Second tab">
        <TabViewItem.view>
        <GridLayout rows="" columns="">
            <ScrollView>
                <StackLayout>
                 //............
                </StackLayout>
            </ScrollView>
        </GridLayout>
        </TabViewItem.view>
     </TabViewItem>
    </TabView>
</Page>
```
t.1167415

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1
- Cross-platform modules: 4.1

- Runtime(s): 4.1

**Comment by vakrilov** [comment] 2018-10-04 08:41
It seems that this issue is no longer reproducible. I have tested with the following code:
```
<Page
    navigatingTo="onNavigatingTo"  
    xmlns="http://schemas.nativescript.org/tns.xsd">
    <TabView>
        <TabViewItem title="First tab">
            <TabViewItem.view>
                <GridLayout rows="" columns="">
                    <ScrollView>
                        <StackLayout>
                            <Label text='hello form tab 1' />
                        </StackLayout>
                    </ScrollView>
                </GridLayout>
                    
                </TabViewItem.view>  
            </TabViewItem>
            
            <TabViewItem title="Second tab">
                <TabViewItem.view>
                <GridLayout rows="" columns="">
                    <ScrollView>
                        <StackLayout>
                            <Label text='Hello from tab 2' />
                        </StackLayout>
                    </ScrollView>
                </GridLayout>
            </TabViewItem.view>
        </TabViewItem>
    </TabView>
</Page>
```

Closing this one. Please comment if you find another repro case.

**Closed by vakrilov** 2018-10-04 08:41 UTC
Labels: backlog, bug, os: ios, severity: medium

**Comment by sarfraznawaz2005** [comment] 2019-01-12 17:39
The problem is that you cannot use `<Frame defaultPage="home/home-page"></Frame>` in that markup, it gives error of invalid markup then.
