### ISSUE TITLE
How to highlight selected tab in BottomNavigation?

### ISSUE THREAD

**Issue by shiv19** [NativeScript/NativeScript#7560] opened 2019-07-21 21:51 UTC
```
<BottomNavigation androidTabsPosition="bottom">
    <TabStrip>
        <TabStripItem ios:iconSource="res://tabIcons/home" android:iconSource="res://home"></TabStripItem>
        <TabStripItem ios:iconSource="res://tabIcons/browse" android:iconSource="res://browse"></TabStripItem>
        <TabStripItem ios:iconSource="res://tabIcons/search" android:iconSource="res://search"></TabStripItem>
    </TabStrip>
    <TabContentItem>
        <Frame defaultPage="home/home-items-page"></Frame>
    </TabContentItem>
    <TabContentItem>
        <Frame defaultPage="browse/browse-page"></Frame>
    </TabContentItem>
    <TabContentItem>
        <Frame defaultPage="search/search-page"></Frame>
    </TabContentItem>
</BottomNavigation>
```

Suppose I have markup like this, and I want to use different icons in the tab strip for when the tab is selected, is there any support for doing this currently?

**Comment by tsonevn** [comment] 2019-07-22 05:53
Duplicate of https://github.com/NativeScript/NativeScript/issues/7470

**Closed by tsonevn** 2019-07-22 05:53 UTC
