### ISSUE TITLE
Color animations don't work on iOS

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/NativeScript#800] opened 2015-09-22 19:19 UTC
The code below animates the background color of a `<Label>` on Android. On iOS, however, the background color of the `<Label>` instantly changes—there is no animation.

``` xml
<Page loaded="loaded">
    <StackLayout>
        <Label id="message" text="Hello NativeScript!" />
    </StackLayout>
</Page>
```

```js
var colorModule = require("color");

exports.loaded = function(args) {
    var page = args.object;
    var message = page.getViewById("message");
    message.animate({
        backgroundColor: new colorModule.Color("#3D5AFE"),
        duration: 1000
    });
};
```

**Comment by hshristov** [comment] 2015-09-23 05:54
Duplicate of #793. Closing it because there is no bullet proof way of hacking it.

**Closed by hshristov** 2015-09-23 05:54 UTC
