### ISSUE TITLE
[CLI bug] Cound not run any CLI command

### ISSUE THREAD

**Issue by meow0703** [NativeScript/NativeScript#2290] opened 2016-06-10 23:21 UTC
Console log on Windows 10 ! Please help investigate. Thanks !
C:\Users\root\Downloads>tns create MyApp
Unexpected token
SyntaxError: Unexpected token
    at FiberFuture.Future.wait (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:535:15)
    at C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\lib\nativescript-cli.js:21:45
    - - - - -
    at Object.parse (native)
    at C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\lib\common\file-system.js:222:29
    at Function.settle (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:249:26)
    at FiberFuture.Future.wait (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:534:10)
    at C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\user-settings-service.js:50:89
    at Function.settle (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:249:26)
    at FiberFuture.Future.wait (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:534:10)
    at C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\user-settings-service.js:12:42
    at Function.settle (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:249:26)
    at FiberFuture.Future.wait (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:534:10)
    at C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\analytics-service.js:124:92
    at Function.settle (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:249:26)
    at FiberFuture.Future.wait (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:534:10)
    at C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\analytics-service.js:218:64
    at Function.settle (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:249:26)
    at FiberFuture.Future.wait (C:\Users\root\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:534:10)

C:\Users\root\Downloads>

**Comment by dtopuzov** [comment] 2016-06-11 13:12
Duplicate of https://github.com/NativeScript/NativeScript/issues/2291

**Closed by dtopuzov** 2016-06-11 13:12 UTC
