### ISSUE TITLE
debugging modals

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#6585] opened 2018-11-20 14:38 UTC
@webleaf commented on [Mon Nov 19 2018](https://github.com/NativeScript/nativescript-cli/issues/4146)

**Environment**
✔ Component nativescript has 5.0.1 version and is up to date.
✔ Component tns-core-modules has 5.0.2 version and is up to date.
✔ Component tns-android has 5.0.0 version and is up to date.
✔ Component tns-ios has 5.0.0 version and is up to date.

**Describe the bug**
Don's see any changes with modals in DevTools (Elements tab with XML)

**To Reproduce**
1. `tns debug android`
2. open modal via `showModal()`
3. check Elements tab in DevTools

**Expected behavior**
I expect that I could see and edit XML elements of modals via DevTools

**Additional context**
tested on Android only

**Comment by NickIliev** [comment] 2018-11-21 06:46
Issue moved to [NativeScript/android-runtime #1213](https://github.com/NativeScript/android-runtime/issues/1213) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tsonevn** [comment] 2018-11-21 14:43
Duplicate of https://github.com/NativeScript/NativeScript/issues/4480

**Closed by tsonevn** 2018-11-21 14:43 UTC
Labels: bug, enhancement
