### ISSUE TITLE
Css placeholder-color not working with dynamic hint values

### ISSUE THREAD

**Issue by vincentduprez** [NativeScript/NativeScript#4458] opened 2017-06-27 08:16 UTC
###Did you verify this is a real problem by searching
-> Yes

### Tell us about the problem
-> I wasn't able to change the color of some textfields hints and I figured out they all had dynamic hints because of internationalisation.
textfields with static hints don't have this issue.

### Which platform(s) does your issue occur on?
At least on IOS, had not had the chance to test on Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.1.0-2017-06-22-9245
- Runtime(s): 3.0.0
- Plugin(s): Angular/* ~4.1.0

### Please tell us how to recreate the issue in as much detail as possible.
Simply by creating a textfield with dynamic hints, sample provided:

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
`<TextField col="1" [(ngModel)]="loginData.fname" hint="{{lang._('fname')}}" style="color:#04ccf0; placeholder-color:rgba(255,255,255,.6); text-align:center; padding:10;"></TextField>`

lang._() returns a simple string and is used all over the code for translation.

**Comment by NickIliev** [comment] 2017-06-27 11:24
@vincentduprez I have tested your case and everything seems to work as expected. However, the color used for placeholder-color along with the alpha transparency is making it almost impossible to distinguish. Use more contrast color and you will see the changes being applied to your TextField.
e.g.
```
<TextField hint="SOME HINT" style="color:#04ccf0; background-color:lightgray; placeholder-color:rgba(255,122,255,0.6);"></TextField>
```

Test application used can be found [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4458)

**Comment by vincentduprez** [comment] 2017-06-27 14:36
Hi @NickIliev thanks for testing out,
unfortunately it's not, I'm working on a dark background and the default greyish color of the placeholder makes it impossible to read, the half transparent white color makes it a light grey easy to read on the other items.

I'll have a look a what element can cause this to happen.

**Comment by NickIliev** [comment] 2017-07-05 13:03
@vincentduprez any updates on the issue? I am struggling to understand the problem as the placeholder color seems to be applied with no hassle - let me know if you have some additional information that can help me reproduce the problem.

**Comment by NickIliev** [comment] 2017-07-06 13:44
@vincentduprez closing this issue as it is not reproducible on our side but please if you have additional information that can help us let me know and I will retest and reopen the issue.

**Closed by NickIliev** 2017-07-06 13:44 UTC
Labels: T:Question

**Comment by gabitoesmiapodo** [comment] 2017-09-20 18:39
Something similar is happening to me, only when using iOS (Android is fine): I'm using nativescript-localize for translations, and using some language keys for the TextField's hints.

When I get into the login screen I get something like this (if you squint your eyes you will see the placeholder text is there):

<img width="382" alt="screen shot 2017-09-20 at 15 31 07" src="https://user-images.githubusercontent.com/4015436/30661050-2f4a631e-9e19-11e7-8bf8-d9884c11ad3c.png">

I should add that if I login, and then logout, I get this :

<img width="370" alt="screen shot 2017-09-20 at 15 32 31" src="https://user-images.githubusercontent.com/4015436/30660972-f2457526-9e18-11e7-95cb-e25f68b09d71.png">

Placeholders magically appear.

The actual code for the TextFields is like this:

```
<TextField
        autocapitalizationType="none"
        autocorrect="false"
        class="form-input"
        hint="{{ 'public-form:username:placeholder' | L }}"
        keyboardType="email"
        returnKeyType="next"
></TextField>
```

The CSS class is this one:

```
.form-input {
    background-color: transparent;
    background-position: 0% 50%;
    background-repeat: no-repeat;
    border-bottom-color: #fff;
    border-bottom-width: 1;
    color: #ffffff;
    padding-left: 45;
    padding-right: 10;
    placeholder-color: #ffffff;
}
```

**Comment by vincentduprez** [comment] 2017-09-20 18:43
Yes, I still have this issue as well, and behaves the same way as yours.
I really think this issue should be reopened.
Don't have much time to narrow it down. but if I have I will try to create a repo to reproduce the issue.

**Comment by hugoangelo** [comment] 2017-10-03 14:30
I had the same issue and after two-way binding the textfield with an ngModel it started to apply the placeholder-color to the textfield.

**Comment by gabitoesmiapodo** [comment] 2017-10-03 14:40
Should we report this again?

I'm not sure how they handle this reports.

**Comment by NickIliev** [comment] 2017-10-04 11:18
@vincentduprez  @hugoangelo  @gabitoesmiapodo 
I see that you all have the same issue reoccurring - I will retest with the additional information and log this as a bug after confirming the bug - stay tuned for updates.

**Comment by NickIliev** [comment] 2017-10-04 11:50
@vincentduprez  @hugoangelo  @gabitoesmiapodo 

Update: I can now confirm that indeed dynamically changing the hint value is resetting the placeholder-color on iOS. I have opened a new issue and logged this as a bug. You can find [the issue here](https://github.com/NativeScript/NativeScript/issues/4915) - I will update the info once we have stable solution or workaround.

**Comment by creativeJoe** [comment] 2017-12-14 01:55
tried style.placeholderColor="red" ?

**Comment by mudlabs** [comment] 2018-02-03 05:13
@creativeJoe Yes, 

Setting `style.placeholderColor="color"` works in code-behind and `xml`. But I think the desirable approach would be from `css` or `bindingContext`.

`{N} 3.4.1`
