### ISSUE TITLE
Switch component has broken animation in NS 6 when using CSS

### ISSUE THREAD

**Issue by tomfaltesek** [NativeScript/NativeScript#7576] opened 2019-07-24 18:11 UTC
**Environment**
 - CLI: 6.0.2
 - tns-core-modules: 6.0.1
 - nativescript-angular: 8.0.1
 - Android Runtime: 6.0.0
 - iOS Runtime:6.0.1

**Description**
After upgrading to NS 6 everything seems to work fine other than the `<Switch>` components. They no longer animate correctly. They seem fine when they're in the _off_ state:

![image](https://user-images.githubusercontent.com/10088641/61817121-698d7280-ae13-11e9-8160-d1f98393fe54.png)

But when toggled, the animation quickly hides the control and then reveals it again in the _on_ state. Also, the background color and the handle color are both the same shade of blue in the _on_ state. So essentially, the animation looks like an ugly flash of blue.

![image](https://user-images.githubusercontent.com/10088641/61817407-17991c80-ae14-11e9-84e1-20f74f8fb4b0.png)

I can set the background color and handle color of the _off_ state. That handle color carries over to the _on_ state. However, I cannot use the default iOS handle color (with the nice little shadow). That always breaks the animation. Here's an example of changing the background to red and the handle to white.

![image](https://user-images.githubusercontent.com/10088641/61818289-21238400-ae16-11e9-84b2-e184f6f576f3.png)
![image](https://user-images.githubusercontent.com/10088641/61818296-24b70b00-ae16-11e9-90b2-a04d7fbf1993.png)

I've done nothing to the project, other than run `tns migrate` to upgrade to NS 6.

Is anyone else having this issue?

**Steps to Reproduce**
Place a `<Switch>` component in one of your templates with no attributes other than a class:
```
<Switch class="switch"></Switch>
```

Reproduction sample project: https://play.nativescript.org/?template=play-ng&id=9vELIw&v=5

**Comment by tsonevn** [comment] 2019-07-25 04:47
Hi @tomfaltesek,
I reviewed the described case, however, I was not able to recreate the issue with the Switch's animation. Also, the mentioned colour (handle colour) seems to be applied correctly on my side. For your convenience, I am [attaching a link to the project ](https://play.nativescript.org/?template=play-ng&id=9vELIw) that I used for testing. Please review and make the needed changes, that will allow us to recreate the problem. I have tested this project on iPhone 6 device (iOS 12.4) and simulator (iOS 12.3).

**Comment by tomfaltesek** [comment] 2019-07-25 14:17
@tsonevn - Thanks for attempting to recreate. I should have set up a sample project originally. Sorry about that.

I've edited [your sample project](https://play.nativescript.org/?template=play-ng&id=9vELIw&v=4) to use a CSS class to style the background. Take a look at the behavior when I simply change the background with CSS instead of the attribute. It's quite strange. The handle sort of flies in from the top left and is an unspecified blue color.

**Comment by tomfaltesek** [comment] 2019-07-25 14:25
Here's [another version of your sample project](https://play.nativescript.org/?template=play-ng&id=9vELIw&v=5) in which I reference a class that has no styles specified. In this case the animation looks like my first two images from the description of this issue (default iOS switch => fully blue switch).

**Comment by tsonevn** [comment] 2019-07-26 08:19
HI @tomfaltesek,
Thank you for the project,
I was able to recreate the issue and found out that this problem is caused by the `nativescript-theme-core`, which contains some predefined CSS classes ( one of them is`switch`). When you add this CSS class to the Switch component, you the plugin will apply the predefined style and will brake the animation. To solve the issue you can rename the CSS class. For example:
```
 <Switch class="switch-test" checked="false"></Switch>
``` 
[Demo](https://play.nativescript.org/?template=play-ng&id=o3LsdN&v=2)


This problem seems to be fixed in the [beta version of nativescript-theme-core](https://github.com/NativeScript/theme/tree/next).

**Comment by tomfaltesek** [comment] 2019-07-26 13:56
Ah. It was a conflict with the CSS class name. Hah...

Thanks for looking into it. I'll change the class name for now. Glad it's fixed in the next version of the nativescript-theme-core package.

**Closed** 2019-07-26 14:04 UTC
