### ISSUE TITLE
HMR css removal issue

### ISSUE THREAD

**Issue by rigor789** [NativeScript/NativeScript#6320] opened 2018-09-28 16:20 UTC
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
yes

### Tell us about the problem
There is no way to remove css at runtime. If you delete a css property and the app syncs with hmr, the property will still affect the app.

Example:
```xml
<Label class="message" text="foo" />
```
```css
.message {
  font-size: 20;
  color: red;
}
```

If I remove `color: red;` the label stays red until I restart the tns commands. Changing it to `blue` does work though.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: `5.0.0-2018-09-28-12343`
- Cross-platform modules: `4.2.1`
- Runtime(s): `4.2.0`
- Plugin(s): N/A

### Please tell us how to recreate the issue in as much detail as possible.
Detailed above, only reproducible with HMR, which is not yet on playground.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
See above.

**Comment by vtrifonov** [comment] 2018-09-28 16:27
Just to add that this happens with the [Vue](https://github.com/nativescript-vue/vue-cli-template) projects. The same behaviour works in TS/JS.

**Comment by vchimev** [comment] 2019-03-05 11:33
Duplicate of https://github.com/nativescript-vue/nativescript-vue/issues/425.

**Closed** 2019-03-05 11:33 UTC
Labels: css
