### ISSUE TITLE
(Android) Bug: Pressing the smartphone's start button sometimes reverses the app to its first/prev page!

### ISSUE THREAD

**Issue by mike-ense** [NativeScript/NativeScript#1395] opened 2016-01-18 17:48 UTC
This is really weird - I have an app with approx the code below.

When being in the second page (so that is, when having started the app and then clicked "Click me", so that is at a blank screen), if you press the smartphone's start button, then the app will AUTOMATICALLY DO A frameModule.topmost().goBack(); that even shows before the switch to the smartphone's main menu screen has been completed!

(I don't know if it goes back to the previous step in history or if it's to the first page.)

The bug happens sporadically. I asked myself if it's correlated with that the display is rotated after having clicked the button. The error happened as much as twice (or thrice) in a row.

If I figure any more details I'll let you know.

Did you ever see this happen on your end??

var platformModule = require("platform");
var buttonModule = require("ui/button");

exports.loaded = function(args) {
     var page = args.object;

     var btn = new buttonModule.Button();
     btn.text = "Click me";
     page.content = btn;
     btn.on(gesturesModule.GestureTypes.tap,function () {
          frameModule.topmost().navigate({ create: function () {
               var page = new pageModule.Page();
               return page;
          }});
     });
};

**Comment by enchev** [comment] 2016-02-04 09:18
Hey @mike-ense,

Can you post more info about the API Level and device?

**Comment by mike-ense** [comment] 2016-02-04 14:45
@enchev , it's a Samsung Galaxy S4. API level Android 5.0.1 Lollipop (ie just downloaded the update).

It's really irregular. I think the bug not correlates with rotating the screen (at least clearly within the course of an individual app process execution it does not), but nto sure.

@NathanaelA told me that he experienced this frequently also. @NathanaelA what API level and device did you experience it on?

Anyone else experienced it? If so please report here.

**Comment by NathanaelA** [comment] 2016-02-04 18:46
I believe I have seen it, but not frequently, but my cause might be caused by my LiveEdit plugin.   Not sure the cause yet, I've also noticed that the navigate with attempting to not put this page in history doesn't always work.   So, disregard me in the equation at this point, until I can nail down if it is my own code causing the issue on my dev.   I have not seen it while just messing with an app...

**Comment by hshristov** [comment] 2016-02-08 14:37
We don't do frame.goBack() on application pause but what might happen is that your app is getting killed (this could happen if you OS need resources or you could simulate it by setting `Background process limit` to 0 or 1 from developer options).

In this case the process is killed and we cannot restore application state because we don't know how. So in theory we should raise an event where developer will have to save app settings and then restore them in order to resume application from its last state.

**Comment by mike-ense** [comment] 2016-02-09 05:15
@hrhristov , i am 100.0% sure that the app NOT was shut down by the OS, because it has a splash screen and that one did *not* show when I opened the app again. Instead what happened was simply that the app had been rewinded to the first(=in this case, previous) page.

So I don't think it's from the OS, but it is a real Nativescript bug.

I don't know yet if it's that Nativescript does an unintended frame.goBack or if it actually resets to the first page, as this manifests the same in my current code.

I will let you know later as soon as I have code that actually will show me which of the two it is.

Meanwhile, is there any way we could track the cause (considering both possible variants of the bug)?

**Comment by enchev** [comment] 2016-08-08 09:11
Hey @mike-ense @hshristov do we still have this issue?

**Comment by mike-ense** [comment] 2016-08-08 10:02
@enchev , I have not been in a position to check this for a while. I should be able to check it out this year but I don't know which month yet.

Did you query now as you think since some particular commit it's fixed, or just to generally followup as to close the issue in case it no longer applies?

**Comment by enchev** [comment] 2016-08-08 11:32
Hey @mike-ense,

I'm just checking if this is still valid and if not we should close the issue and focus on more important problems. Please check it when you have time/need and write here. If still valid I'll reopen the issue.

**Closed by enchev** 2016-08-08 11:32 UTC
