### ISSUE TITLE
[BottomNav] Dynamically generating tabs with font icons crashes app

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#7610] opened 2019-07-30 08:41 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.0
 - Cross-platform modules: 6.0.2
 - Android Runtime: 6.0.0
 - iOS Runtime: 6.0.0
 - Plugin(s):

**Describe the bug**
Dynamically generating tabs that have an icon source set to a font crashes the app under android. Under iOS make the tabs not visible similar to #7609 

**To Reproduce**
https://play.nativescript.org/?template=play-tsc&id=pqj9gl&v=2
Tap on the `Change` button

**Expected behavior**
To work 😀 

Related to #6967

**Comment by tsonevn** [comment] 2019-07-30 09:30
Duplicate of https://github.com/NativeScript/NativeScript/issues/7433

**Comment by PeterStaev** [comment] 2019-07-30 09:37
@tsonevn , this is not duplicate. on Android the app completely crashes and the other issue is specifically for iOS and does not even use font icons...

**Closed** 2023-09-07 13:48 UTC
Labels: bug, os: android, tabs
