### ISSUE TITLE
Freeze after: JS garbage collection encountered invalid thread

### ISSUE THREAD

**Issue by uelipeter** [NativeScript/NativeScript#6307] opened 2018-09-26 15:24 UTC
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes

### Tell us about the problem
We use a third party library (http://stormyprods.com/) to play web radio streams. There seems to be an issue with this library because after a while nativescript outputs the following error:
`ERROR: JavaScript garbage collection encountered an invalid thread (err 0x10000003): Thread [3/3: 0x133d7d320] id 148.
/Users/nsbuilduser/workspace/tns-ios-release/src/WebKit/Source/JavaScriptCore/heap/MachineStackMarker.cpp(396) : bool JSC::MachineThreads::tryCopyOtherThreadStacks(const WTF::AbstractLocker &, void *, size_t, size_t *)`

On older iphones (older than iPhone 6) this causes the app to freeze in production mode (when we build it with --release). However, the same error is thrown in debug mode, but the app does not freeze on any device. 
We tried with a custom error handler and the discardUncaughtJsExceptions flag, but the problem still appears. Can anybody elaborate on this error? And is there a way to make nativescript handle the error in production mode the same way as in debug mode? 

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.2.0
- Cross-platform modules: 4.2.0
- Runtime(s): 4.2.0

**Comment by uelipeter** [comment] 2018-09-27 07:44
I already tried the custom error handler. Unfortunately, it does not catch this error.

**Comment by NickIliev** [comment] 2018-10-10 06:59
@uelipeter try using [this experimental feature](https://github.com/NativeScript/android-runtime/pull/829) in your `app/package..json` file (as done [here](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/package.json#L4)). Keep in mind that the feature is experimental and is not officially promoted for apps in production but still it might solve your GC issue.

Closing this one as the issue is related to using a non-NativeScript package.

**Closed by NickIliev** 2018-10-10 06:59 UTC
Labels: needs more info, os: ios

**Comment by uelipeter** [comment] 2018-10-10 07:02
@NickIliev But this feature is android only. right? and my problem is ios only.

**Comment by NickIliev** [comment] 2018-10-10 10:43
@uelipeter you are right the property is Android only
