### ISSUE TITLE
CLI Livesync improvements

### ISSUE THREAD

**Issue by hshristov** [NativeScript/NativeScript#2388] opened 2016-06-30 12:40 UTC
Tasks:
- [x] Enable debugging support - with `--watch`
- [ ] Improve the speed so that `livesync` happens in less than a second
- [ ] Profile & remove unnecessary steps in `livesync` command
- [ ] Rebuild project when needed - like AndroidManifest.xml is changed, Info.plist is changed, Image is added to XCAssets or android res folder or at least console log a message
- [x] Show unhandled error on device/simulator
- [x] `tns livesync` without `ios/android` should deploy on all devices/simulators/emulators

**Comment by atanasovg** [comment] 2017-08-18 13:43
@rosen-vladimirov @hshristov @PanayotCankov @Plamen5kov Guys, could you please review this issue and update its state? I suggest that we close this issue and open new, more granular issues if needed.

**Comment by PanayotCankov** [comment] 2017-08-18 14:05
I think these were implemented. If there are further problems lets log them in separate issues.

**Closed by PanayotCankov** 2017-08-18 14:05 UTC
Labels: feature, Planned, S:High

**Comment by rosen-vladimirov** [comment] 2017-08-18 15:27
I confirm everything described in the issue is implemented in CLI.
