### ISSUE TITLE
Tap gestures are not responsive as they should be!

### ISSUE THREAD

**Issue by rrcoolp** [NativeScript/NativeScript#2974] opened 2016-10-27 16:00 UTC
Dear NS team,

I have a team of testers and developers and have asked a number of general public to play around with some of the NativeScript example apps and our own app that we are building.

The common problem all have been reporting is that the TAP action is very not 100% responsiveness on both IOS and ANDROID - when compared to other common applications running on those platforms (i.e. FB, GOOGLE, AMAZON App) etc....

For example, sometimes you have to TAP twice - because the TAP action was not registered....This is quite common on all LABELS or LAYOUTS that have a TAP action bound to it.

I am not sure if this issue has ever been picked up by anyone?

Thanks

**Comment by tsonevn** [comment] 2016-10-28 05:49
Hi @rrcoolp,
Thank you for interest in NativeScript.

I reviewed your case and tested the `tap` event for the `Label`  all of the NativeScript Layouts component and everything work as expected. However the given information is not enough to investigate further your problem. Regarding to that it will help if you could give more info for your problem  or to provide sample project, which could be debug locally. For your convenience I am also attaching sample code.

main-page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <ScrollView>
    <GridLayout rows="100 100 100 100 100 100 100 100" columns="">
        <Button row="0" col="0" text="Button" tap="onTap1" />
        <Label row="1" col="0" text="Label" tap="onTap2" textWrap="true" />
        <TextField row="2" col="0" hint="" editable="false" tap="onTap3" text="TextField" />
        <TextView row="3" col="0" hint="" editable="false" tap="onTap4" text="TextView" />
        <StackLayout row="4" col="0" tap="onTap5" backgroundColor="green"></StackLayout>
        <GridLayout row="5" col="0" tap="onTap6" backgroundColor="red"></GridLayout>
        <WrapLayout row="6" col="0" tap="onTap7" orientation="horizontal" backgroundColor="blue"></WrapLayout>
        <AbsoluteLayout row="7" col="0" tap="onTap8" backgroundColor="green">
        </AbsoluteLayout>
        <DockLayout row="8" col="0" tap="onTap9" stretchLastChild="true" backgroundColor="red">
        </DockLayout>
    </GridLayout>
   </ScrollView>
</Page>
```

main-page.ts
```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';

// Event handler for Page "navigatingTo" event attached in main-page.xml
export function navigatingTo(args: EventData) {
  // Get the event sender
  let page = <Page>args.object;
  page.bindingContext = new HelloWorldModel();
}

export function onTap1(){
  console.log("tap button")
}
export function onTap2(){
  console.log("tap Label")
}
export function onTap3(){
  console.log("tap TextField")
}
export function onTap4(){
  console.log("tap TextView")
}
export function onTap5(){
  console.log("tap StackLayout")
}
export function onTap6(){
  console.log("tap GridLayout")
}
export function onTap7(){
  console.log("tap WrapLayout")
}
export function onTap8(){
  console.log("tap AbsoluteLayout")
}
export function onTap9(){
  console.log("tap DockLayout")
}
```

Let me know whether this helps.

**Comment by vossad01** [comment] 2016-10-28 20:02
For what it is worth, I can confirm this perception.  It was my perception in using the "Examples NativeScript" app from the app strore (on my Galaxy S5 with CM13).  The thing is it is not consistently reproducible so nothing I could really report on.  Given the inconsistency I was thinking it was just a general performance deficiency which I hoped would be resolved in newer NS versions.  This is largely why I recommended measuring the timing in NativeScript/nativescript-marketplace-demo#213

In the case of "Examples NativeScript", the perceived speed could be improved by a more pronounced visual indication on tap on the main screen.  The change of white to light gray background is too subtle of change, I had completely missed it until I was re-investigating this.  This would also make it more clear when a tap was not registered.  However, from my experiences in the app I do believe there is still an underlying issue.

Based on my playing around just now one theory I have that may account for some of this.  Perhaps, it is too sensitive to swiping and incorrectly classifies some intended taps as swipes.  However, I don't know if that even makes sense because I don't know if NativeScript even interprets things at that level or if that is all in the OS.

**Closed** 2016-11-09 12:24 UTC
Labels: T:Question
