### ISSUE TITLE
Nativescript-https plugin issue

### ISSUE THREAD

**Issue by smartsanja2013** [NativeScript/NativeScript#6211] opened 2018-08-23 10:36 UTC
Highly appreciated someone can help me how to figure-out this issue. I have tried-out so many days,different certs, different domain names. nothing works.

I have to enable ssl pining in my app. So, I had to use https://github.com/gethuman/nativescript-https 1 plugin. I have follow the implementation steps correctly. But when I make the https request, iOS app crash in AFNetworking EXC_BAD_Access error. I have added two NSLogs to AFHTTPSSessionManager class.
<img width="804" alt="screen shot 2018-08-22 at 2 52 09 pm" src="https://user-images.githubusercontent.com/12458727/44520437-67ea9480-a702-11e8-88f4-5f25fbce6c5a.png">

Output
```
Securitypolicy AFSSLPinningModePublicKey
baseURL scheme (null)
```
It seems something wrong with setting the certificate and host in the angular code. By right, Securitypolicy should be AFSSLPinningModeCertificate and baseURL schme should have https.

Android app gives this error
`Https.request error javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

Implementation details as bellow
reference.d.ts
```
/// <reference path="./node_modules/tns-core-modules/tns-core-modules.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/android.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/ios.d.ts" />
```

imports
```
import { File, Folder, knownFolders, path } from 'file-system'
import * as Https from 'nativescript-https'
```

in the constructor
```
let dir = knownFolders.currentApp().getFolder('certs')
let certificate = dir.getFile('httpbin.org.cer').path
Https.enableSSLPinning({ host: 'httpbin.org', certificate: certificate});
```

method
```
clickLogin(){
        Https.request({
            url: 'https://httpbin.org/get',
            method: 'GET',
            headers: {
                'content-type': 'application/json'
            },
        }).then(function(response) {
            console.log('Https.request response', response)
        }).catch(function(error) {
            console.error('Https.request error', error)
        })
}
```

tns version 4.0.1 node v6.11.5

**Comment by NickIliev** [comment] 2018-08-23 13:45
@smartsanja2013 the error log seems to be related to a known bug in AFNetworking pod that is used in the iOS part of nativescript-https - the related issue is logged [here](https://github.com/AFNetworking/AFNetworking/issues/4150)

At this very moment, no solution is provided by the author of the pod - you could track the issue for any possible updates regarding this one and if a newer version of the pod is published you can re-pack the plugin to use the newer AFNetworking pod.

Moving this issue to the nativescript-https repository as the issue is not related to NativeScript core modules.

**Comment by NickIliev** [comment] 2018-08-23 13:50
This issue was moved to gethuman/nativescript-https#36

**Closed by NickIliev** 2018-08-23 13:50 UTC
Labels: os: ios, question
