### ISSUE TITLE
ListView causing app to crash 

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#6284] opened 2018-09-20 07:53 UTC
_From @tsonevn on August 9, 2018 6:18_

_From @vtrifonov on August 8, 2018 15:7_

_From @ludcila on August 8, 2018 14:21_

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

Found some similar issues:
- https://github.com/telerik/nativescript-ui-feedback/issues/741
- https://stackoverflow.com/questions/50901650/nativescript-list-view-crash-using-android

### Tell us about the problem

The app crashes when:
1. Using a ListView with multiple templates
2. There is a model update that causes an item to switch from one template to another
3. The app is put into background and/or navigation occurs (using slide transition)

### Please provide the following version numbers that your issue occurs with:

- CLI: 4.1.2
- Cross-platform modules: 4.1.1
- Runtime(s): 4.1.3

This seems to happen only on Android 8.0.

### Did the error happen while the app was being constructed? (buildtime error)

No

### Did the error happen while the app was executing? (runtime error)

Yes

```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method getView failed

Error: There is no entry with key 'org.nativescript.widgets.StackLayout{4b534d0 V.E...... ........ 0,-133-1080,28}' in the realized views cache for template with key'visited'.
File: "file:///data/data/org.nativescript.nsissue741/files/app/tns_modules/tns-core-modules/ui/list-view/list-view.js, line: 241, column: 20

StackTrace: 
	Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.nsissue741/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1298, column: 33
	Frame: function:'ListViewAdapter.getView', file:'file:///data/data/org.nativescript.nsissue741/files/app/tns_modules/tns-core-modules/ui/list-view/list-view.js', line: 241, column: 27


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
	at com.tns.Runtime.callJSMethod(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:954)
	at com.tns.Runtime.callJSMethod(Runtime.java:946)
	at com.tns.gen.android.widget.BaseAdapter_view_195_32_ListViewAdapter.getView(BaseAdapter_view_195_32_ListViewAdapter.java:52)
	at android.widget.AbsListView.obtainView(AbsListView.java:2428)
	at android.widget.ListView.makeAndAddView(ListView.java:2083)
	at android.widget.ListView.fillUp(ListView.java:829)
	at android.widget.ListView.fillGap(ListView.java:766)
	at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5520)
	at android.widget.ListView.trackMotionScroll(ListView.java:1991)
	at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:3660)
	at android.widget.AbsListView.onTouchMove(AbsListView.java:4086)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3904)
	at android.view.View.dispatchTouchEvent(View.java:11788)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2647)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:549)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1953)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3548)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:502)
	at android.view.View.dispatchPointerEvent(View.java:12027)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5278)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5067)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4581)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4634)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4600)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4727)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4608)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4784)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4581)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4634)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4600)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4608)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4581)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7169)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7143)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7104)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7325)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:181)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7248)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7353)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:715)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

### Please tell us how to recreate the issue in as much detail as possible.

Sample project to reproduce the issue:
https://github.com/ludcila/ns-listview-issue

_Copied from original issue: NativeScript/android-runtime#1145_

_Copied from original issue: NativeScript/NativeScript#6166_

_Copied from original issue: NativeScript/nativescript-angular#1479_

**Comment by NickIliev** [comment] 2018-09-20 07:53
_From @tsonevn on August 9, 2018 6:18_

Hi @ludcila,
Thank you for the provided sample project.
I tested it on my side and was able to recreate the problem. I will mark this as a bug. For now, I would suggest, to keep track of the issue for further info.

**Comment by NickIliev** [comment] 2018-09-20 07:53
_From @psrcek on August 24, 2018 12:43_

Can confirm this, occurs when an item switches templates while not on screen.
`tns --version`: 4.2.2
package.json:
```
{
  "description": "[removed]",
  "readme": "SEE README.md",
  "repository": "[removed]",
  "nativescript": {
    "id": "[removed]",
    "tns-ios": {
      "version": "4.1.0"
    },
    "tns-android": {
      "version": "4.2.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~6.1.0",
    "@angular/common": "~6.1.0",
    "@angular/compiler": "~6.1.0",
    "@angular/core": "~6.1.0",
    "@angular/forms": "~6.1.0",
    "@angular/http": "~6.1.0",
    "@angular/platform-browser": "~6.1.0",
    "@angular/platform-browser-dynamic": "~6.1.0",
    "@angular/router": "~6.1.0",
    "allow-publish": "^1.0.4",
    "base-64": "^0.1.0",
    "nativescript-angular": "^6.1.0",
    "nativescript-bitmap-factory": "^1.7.1",
    "nativescript-camera": "^4.0.2",
    "nativescript-imagecropper": "^1.0.4",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-modal-datetimepicker": "^1.1.3",
    "nativescript-permissions": "^1.2.3",
    "nativescript-phone": "^1.3.1",
    "nativescript-plugin-firebase": "file:./nativescript-plugin-firebase-6.5.0.tgz",
    "nativescript-share-file": "^1.0.4",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-calendar": "^3.7.0",
    "nativescript-ui-sidedrawer": "^4.2.0",
    "reflect-metadata": "^0.1.8",
    "rxjs": "^6.0.0",
    "tns-core-modules": "^4.2.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~6.1.0",
    "@ngtools/webpack": "~6.1.0",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.6.0",
    "nativescript-dev-typescript": "^0.7.3",
    "nativescript-dev-webpack": "^0.15.1",
    "tns-platform-declarations": "^3.4.1",
    "typescript": "~2.7.2"
  }
}
```

**Comment by NickIliev** [comment] 2018-09-20 07:53
_From @bachras on September 12, 2018 9:35_

I am having same issue as @psrcek

**Comment by NickIliev** [comment] 2018-09-20 07:53
Reproducible with [this Playground](https://play.nativescript.org/?template=play-js&id=h0dxyU&v=25) when tapping on the item at 0 index.

**Comment by edusperoni** [comment] 2018-10-06 19:15
Additional info:

When you tap the SECOND item:
`bindingContextChange` triggers for 1st and 2nd, even if 1st hasn't changed

When you tap the FIRST item:
`bindingContextChange` triggers for 2nd, but not for 1st

Something is preventing this event from being triggered, but I can't find out what.

https://play.nativescript.org/?template=play-js&id=h0dxyU&v=31

In the example, I'm manually triggering a bindingContextChange event just before querying the item template. which makes the listview work flawlessly.

if you comment:
```
        // COMMENT THIS LINE FOR CRASH!
        esse._itemTemplateSelectorBindable.notify({ eventName: "bindingContextChange", object: esse._itemTemplateSelectorBindable, propertyName: "bindingContext", value: dataItem });
```

you can check the current behavior (the logs will show you that after the "mudou" console line, which indicates the change has been made, the binding context event is not triggered for the first item).

I couldn't find where the bindingContextChange event is triggered, so I couldn't progress any further.

**Comment by romandragan** [comment] 2019-07-29 14:55
@NickIliev, I'm still having that issue with 5.4.0 Android runtime.

**Comment by NickIliev** [comment] 2019-07-30 07:18
@romandragan use the latest `tns-core-modules (that might require updating to the latest CLI and running `tns migrate` afterward)

**Comment by romandragan** [comment] 2019-07-31 11:46
@NickIliev, still an issue with the latest `tns-core-modules@6.0.3`, `tns-android@6.0.1` and `nativescript-vue@2.4.0`.

**Comment by NickIliev** [comment] 2019-07-31 12:41
@romandragan I've tested multiple templates via[ this Playground](https://play.nativescript.org/?template=play-tsc&id=WoMOKn) (tns-core-modules@6.0.1) and everything is working as expected. Provide a demo project so we could investigate your specific case.

**Comment by romandragan** [comment] 2019-08-22 05:48
@NickIliev, thanks it works for me now. The problem was occuring if we have `ListView` under `v-if` condition, once I changed it to `v-show` or removed the condition completely — the issue disappears.

However, I noticed a **big** difference in performance with multiple `v-template`'s for Android and iOS. I mean it works smoothly on Android, but a kind of very laggy on iOS.

FYI switching to `RadListView` parrtially solves performance problem.

**Comment by spstratis** [comment] 2020-01-16 17:39
@NickIliev It appears this bug was fixed in a newer version of the NS core-modules and framework. For those of us not able to upgrade to 6.x core-modules at this time, is @romandragan  or @edusperoni work around the only valid way to go?

**Comment by romandragan** [comment] 2020-01-16 17:47
@spstratis, you mean it has been fixed in 6.3.0 version?

**Comment by spstratis** [comment] 2020-01-16 17:52
@romandragan I was basing it on this https://github.com/NativeScript/NativeScript/pull/6634,  Which actually looks to be well before 6.3.0

**Comment by spstratis** [comment] 2020-01-17 19:54
@NickIliev Is there a way to work around this issue if my app must remain on the 5.4.3 version of the core-modules for the time being? We're seeing pretty consistent crashes on Android right now because of this problem. We're using Core TNS, not Vue or Angular. Thanks for any info!

**Comment by NathanaelA** [comment] 2020-01-17 20:13
@spstratis - 6.3.x supports NS Core great.  Any specific reason you are stuck on 5.4?    I had an app that was stuck on NS 2 for a long time.   Upgraded it to NS 5, then finally, upgraded it to NS 6; was the best decision we could have made!  Staying out of date was becoming a serious pain/time sync to maintain because of multiple issues like this.  I had a whole list of "patches" I was manually merging.   

If you are truly stuck on 5.4, then you need to manually patch your tns core modules, with some of the suggestions earlier in the thread.     But remember, staying on NS 5.4; your app might have other issues (especially with ios 13)  because you are missing a huge number of fixes that came about in the 13 releases since the version you are running.

**Comment by spstratis** [comment] 2020-01-17 20:34
@NathanaelA Thanks for the feedback! We weren't upgrading due to concerns around plugin support, a lot seemed to have moved behind a paywall in order to get the 6.x updates. It does seem with the newer version of 6.x they introduced a migrate function into the CLI that may help with the transition. We're just not at a point right now where we feel we can comfortably upgrade and still test everything out before our release date.

**Comment by NathanaelA** [comment] 2020-01-17 21:04
@spstratis - I don't speak for the Progress or the NativeScript team -- but I've been around since the beginning.  :grin:   But no one supports the ancient versions (v6.3 is 13 releases since the last 5.4, some major) -- the whole objective of NativeScript is to move forward.   Which means bugs in v5 will remain unfixed in v5 unless you manually fix it yourself or you pay someone (Progress has enterprise contracts, nStudio has service contracts).

---

As for the plugins -- yes, you are correct multiple plugins went behind the paywall; because none of those developers get paid (except now via the proplugins) for any time spent on them, and none of the community was really helping support them.    So all the work to maintain those 40+ plugins is being done by a very small group of people taking time from their families for no benefit.  Now, at least these developers now make a little bit of cash each month to justify doing all this work.

But considering most companies spend somewhere between 30k-200k per year for a developer; and ALL 40+ plugins are only $120 total a year.    The amount of time a developer wastes staying on NS 5, vs upgrading will cost way way more in labor than a yearly fee.   Example: Say you, a developer made 100k a year. (numbers ignoring all the extra money a company spends on you for taxes, health, and other benefits the company offers)    That developer wasting just **3.5 hours** on a single NS 5 issue that is fixed in NS 6, is enough to have paid for the entire year's plugin subscription.   :grinning:    

The cost of a subscription vs a developers labor cost is truly a steal and on top of that those that do subscribe help pay for the ongoing costs of maintenance on all these plugins so they continue to work in the future too.  Pretty much a win-win scenario for everyone involved.

**Comment by Firetrip** [comment] 2020-10-16 07:56
hey,
@NathanaelA  a lot has changed since this discussion but I am still seeing this issue on NS 6 with Angular. 
Those are my versions: 
```
        "tns-ios": {
            "version": "6.5.2"
        },
        "tns-android": {
            "version": "6.5.3"
        }

        "tns-core-modules": "^6.5.15",

```

Do you have an update on this, or a new possible solution?

**Comment by NathanaelA** [comment] 2020-10-16 17:29
To my knowledge all listview issues were fixin during the NS6 time frame.     However it appears you somehow managed to trigger a issue with a SwipeRefreshLayout -- are you able to duplicate this easily?

**Comment by Firetrip** [comment] 2020-10-19 06:14
not really. we still did not find a way to reliable trigger it within our app. 
But we are using a rather complex setup where we have a nativescript-carousel and each CarouselItem contains one ListView. 
Maybe we can find the time to reproduce it.

**Comment by nikoTM** [comment] 2020-10-23 08:36
I can confirm this still happens on NS7. I can see it happens in production via logs, but I am unable to reproduce it yet.

**Comment by edusperoni** [comment] 2020-11-06 16:50
I've reopened this issue as I have identified this still happens on very rare occasions where the items where updated while the view is in a suspended state (different page, app on background, screen turned off...).

I've identified the issue and should open a PR shortly to address it.

**Comment by nikoTM** [comment] 2020-11-11 14:31
```
Error: Calling js method getView failed
TypeError: Cannot read property 'get' of undefined
```
Pointing to:
https://github.com/NativeScript/NativeScript/blob/05faa867d0e9844497541d09186abe782c54f6df/packages/core/ui/list-view/index.android.ts#L306

```
Error: Calling js method onItemClick failed
TypeError: Cannot read property 'get' of undefined
```
Pointing to: 
https://github.com/NativeScript/NativeScript/blob/05faa867d0e9844497541d09186abe782c54f6df/packages/core/ui/list-view/index.android.ts#L41


I get a lot of these errors in the logs. `owner._realizedTemplates.get(template.key)` returns `undefined`

**Comment by nikoTM** [comment] 2020-11-11 16:10
@hamorphis do you by chance remember the reasoning behind this line https://github.com/NativeScript/NativeScript/blob/6.5.19/nativescript-core/ui/list-view/list-view.android.ts#L287 why does it have to throw instead of creating a new view with `template.createView()`?

**Closed** 2020-11-12 03:55 UTC
Labels: backlog, os: android, severity: high

**Comment by vicmasa** [comment] 2021-03-03 03:25
Hello everyone.

These problems also happen to me frequently. Even updating to the latest version 7.x of Nativescrip.

Hope we can solve this problem together. I have been suffering from this type of bugs for 4 years, and I can not find the solution.

System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method getView failed
System.err: Error: There is no entry with key 'org.nativescript.widgets.StackLayout{592520a V.E...... ........ 0,-445-1440,46}' in the realized views cache for template with key'image'.
System.err: 
System.err: StackTrace:
System.err: ListViewAdapter.getView(file: node_modules/@nativescript/core/ui/list-view/list-view.android.js:243:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
System.err:     at com.tns.gen.android.widget.BaseAdapter_vendor_28514_32_ListViewAdapter.getView(BaseAdapter_vendor_28514_32_ListViewAdapter.java:39)
System.err:     at android.widget.AbsListView.obtainView(AbsListView.java:2365)
System.err:     at android.widget.ListView.makeAndAddView(ListView.java:2052)
System.err:     at android.widget.ListView.fillUp(ListView.java:820)
System.err:     at android.widget.ListView.fillGap(ListView.java:759)
System.err:     at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5225)
System.err:     at android.widget.ListView.trackMotionScroll(ListView.java:1971)
System.err:     at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:3574)
System.err:     at android.widget.AbsListView.onTouchMove(AbsListView.java:3983)
System.err:     at android.widget.AbsListView.onTouchEvent(AbsListView.java:3808)
System.err:     at android.view.View.dispatchTouchEvent(View.java:11776)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2962)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2643)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
System.err:     at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:448)
System.err:     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
System.err:     at android.app.Activity.dispatchTouchEvent(Activity.java:3307)
System.err:     at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
System.err:     at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:410)
System.err:     at android.view.View.dispatchPointerEvent(View.java:12015)
System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4795)
System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4609)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4293)
System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
System.err:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4350)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
System.err:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6661)
System.err:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6635)
System.err:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6596)
System.err:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6764)
System.err:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
System.err:     at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
System.err:     at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:177)
System.err:     at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6735)
System.err:     at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6787)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:723)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:652)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
System.err:     at android.os.Handler.handleCallback(Handler.java:790)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by edusperoni** [comment] 2021-03-03 12:27
@vicmasa I'm positive that you are not in the latest 7.x  Nativescript version as this regression (not the same bug as 4 years ago) was fixed in 7.1 and that error message is no longer in the codebase, so it's not possible for it to show on >=7.1.0

**Comment by vicmasa** [comment] 2021-05-01 04:00
Hello everyone, the problem occurs whenever you have a listView with several components inside. I hope you can help us. Thanks.

An uncaught Exception occurred on "main" thread.
Calling js method getView failed
Error: There is no entry with key 'org.nativescript.widgets.GridLayout{54a6698 V.E...... ........ 0,-313-1080,27}' in the realized views cache for template with key'title'.

StackTrace:
ListViewAdapter.getView(file:///data/data/org.invianinternational.ViiAManager/files/app/vendor.js:28612:27)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
	at com.tns.Runtime.callJSMethod(Runtime.java:1160)
	at com.tns.Runtime.callJSMethod(Runtime.java:1138)
	at com.tns.Runtime.callJSMethod(Runtime.java:1134)
	at com.tns.gen.android.widget.BaseAdapter_vendor_28566_32_ListViewAdapter.getView(BaseAdapter_vendor_28566_32_ListViewAdapter.java:39)
	at android.widget.AbsListView.obtainView(AbsListView.java:2494)
	at android.widget.HwAbsListView.obtainView(HwAbsListView.java:1139)
	at android.widget.ListView.makeAndAddView(ListView.java:2119)
	at android.widget.ListView.fillUp(ListView.java:853)
	at android.widget.ListView.fillGap(ListView.java:785)
	at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5646)
	at android.widget.ListView.trackMotionScroll(ListView.java:2013)
	at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:5152)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
	at android.view.Choreographer.doCallbacks(Choreographer.java:875)
	at android.view.Choreographer.doFrame(Choreographer.java:772)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by phenric** [comment] 2021-10-15 17:53
Hi everyone,

I'm also facing this issue on some phones. I tried to live debug on all the phones I can easily access but none of them has this issue.

I only have some logs from the store returned by the affected users.
I build the app with @nativescript/android v. 8.0.0.

Any news or idea on what could be the cause?
Did you fix it on your own projects?

Thx for your passion and your time!

> Error: 
  at com.tns.Runtime.callJSMethodNative (Native Method)
  at com.tns.Runtime.dispatchCallJSMethodNative (Runtime.java:1302)
  at com.tns.Runtime.callJSMethodImpl (Runtime.java:1188)
  at com.tns.Runtime.callJSMethod (Runtime.java:1175)
  at com.tns.Runtime.callJSMethod (Runtime.java:1153)
  at com.tns.Runtime.callJSMethod (Runtime.java:1149)
  at com.tns.gen.android.widget.BaseAdapter_vendor_115393_28_ListViewAdapter.getView (BaseAdapter_vendor_115393_28_ListViewAdapter.java:39)
  at android.widget.AbsListView.obtainView (AbsListView.java:2412)
  at android.widget.ListView.makeAndAddView (ListView.java:2071)
  at android.widget.ListView.fillDown (ListView.java:797)
  at android.widget.ListView.fillFromTop (ListView.java:859)
  at android.widget.ListView.layoutChildren (ListView.java:1814)
  at android.widget.AbsListView.onLayout (AbsListView.java:2202)
  at android.view.View.layout (View.java:21973)
  at android.view.ViewGroup.layout (ViewGroup.java:6263)
  at org.nativescript.widgets.CommonLayoutParams.layoutChild (CommonLayoutParams.java:222)
  at org.nativescript.widgets.GridLayout.onLayout (GridLayout.java:354)
  at android.view.View.layout (View.java:21973)
  at android.view.ViewGroup.layout (ViewGroup.java:6263)
  at org.nativescript.widgets.CommonLayoutParams.layoutChild (CommonLayoutParams.java:222)
  at org.nativescript.widgets.GridLayout.onLayout (GridLayout.java:354)
  at android.view.View.layout (View.java:21973)
  at android.view.ViewGroup.layout (ViewGroup.java:6263)
  at org.nativescript.widgets.CommonLayoutParams.layoutChild (CommonLayoutParams.java:222)
  at org.nativescript.widgets.ContentLayout.onLayout (ContentLayout.java:73)
  at android.view.View.layout (View.java:21973)
  at android.view.ViewGroup.layout (ViewGroup.java:6263)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at android.view.View.layout (View.java:21973)
  at android.view.ViewGroup.layout (ViewGroup.java:6263)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at android.view.View.layout (View.java:21973)
  at android.view.ViewGroup.layout (ViewGroup.java:6263)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at android.view.View.layout (View.java:21973)
  at android.view.ViewGroup.layout (ViewGroup.java:6263)
  at android.widget.LinearLayout.setChildFrame (LinearLayout.java:1829)
  at android.widget.LinearLayout.layoutVertical (LinearLayout.java:1673)
  at android.widget.LinearLayout.onLayout (LinearLayout.java:1582)
  at android.view.View.layout (View.java:21973)
  at android.view.ViewGroup.layout (ViewGroup.java:6263)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at android.view.View.layout (View.java:21973)
  at android.view.ViewGroup.layout (ViewGroup.java:6263)
  at android.widget.LinearLayout.setChildFrame (LinearLayout.java:1829)
  at android.widget.LinearLayout.layoutVertical (LinearLayout.java:1673)
  at android.widget.LinearLayout.onLayout (LinearLayout.java:1582)
  at android.view.View.layout (View.java:21973)
  at android.view.ViewGroup.layout (ViewGroup.java:6263)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at com.android.internal.policy.DecorView.onLayout (DecorView.java:799)
  at android.view.View.layout (View.java:21973)
  at android.view.ViewGroup.layout (ViewGroup.java:6263)
  at android.view.ViewRootImpl.performLayout (ViewRootImpl.java:3111)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2621)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1752)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:7695)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:966)
  at android.view.Choreographer.doCallbacks (Choreographer.java:790)
  at android.view.Choreographer.doFrame (Choreographer.java:725)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:951)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:241)
  at android.app.ActivityThread.main (ActivityThread.java:7617)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:941)
