### ISSUE TITLE
Service exited due to Segmentation fault: 11

### ISSUE THREAD

**Issue by SandipFichadiya** [NativeScript/NativeScript#4187] opened 2017-05-15 06:08 UTC
### Tell us about the problem
When I am trying to run the application on simulator, I am getting following error in console.

```
CONSOLE LOG file:///app/tns_modules/nativescript-globalevents/globalevents.js:98:16: Handler onNavigatingTo navigatingTo
CONSOLE LOG file:///app/tns_modules/raven-js/src/console.js:26:42: Handler onLoaded loaded
CONSOLE LOG file:///app/tns_modules/raven-js/src/console.js:26:42: Handler onNavigatedTo navigatedTo
CONSOLE LOG file:///app/tns_modules/raven-js/src/console.js:26:42: Handler _raiseShownModallyEvent shownModally
1   0x105fb17cb NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0x1066861ee ffi_closure_unix64_inner
3   0x106686b22 ffi_closure_unix64
4   0x12676b790
file:///app/tns_modules/nativescript-raven/raven.js:14:29: JS ERROR TypeError: Sentry.SentryClient is not a function
May 15 11:24:41 Mac-mini com.apple.CoreSimulator.SimDevice.A5A5AA89-AAAA-4A50-A97A-022888AA424A.launchd_sim[763] (UIKitApplication:com.test.myProject[0x2ae7][20406]): Service exited due to Segmentation fault: 11
```

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.0
- Cross-platform modules: 2.5.2
- Runtime(s): "tns-ios": { "version": "2.5.0" }

**Comment by tsonevn** [comment] 2017-05-15 07:26
Hi @SandipFichadiya,
Thank you for reporting your issue.
I tested this case on my side, while using NativeScript 2.5.0 and 3.0, however, was unable to reproduce this problem.
Regarding that could you provide some more info about the case and about you environment(Xcode and node versions).
You could also try to upgrade to NativeScript 3.0 and to verify, whether you will have the same problem.
If the error still exists, build the project with `tns run ios --log trace` and send us the full log from the terminal.

**Comment by toddanglin** [comment] 2017-05-17 02:55
@SandipFichadiya This looks like it's related to the `nativescript-raven` plugin by @danielgek.

The plugin is noted as being in "alpha," so not sure if it's tested to work with your setup. In the meantime, I'd suggest either:

A) Remove the `nativescript-raven` plugin and test again to see if the issue persists
B) Jump over to the [nativescript-raven](https://github.com/danielgek/nativescript-raven) repo and let's see if we can fix this issue there
C) Depending on what you're trying to do, there is also this [nativescript-trace-raven](https://github.com/toddanglin/nativescript-trace-raven) plugin I worked on recently that may work in your case (uses JavaScript instead of the native Sentry.io libraries as @danielgek does)

In fact, I see you dropped an issue on that plugin I missed. I'll respond there. In the meantime, I think this issue is safe to close as it is unrelated to NativeScript "core."

**Comment by tsonevn** [comment] 2017-05-17 06:29
Hi @SandipFichadiya,
Indeed you could verify if this error is related to the `nativescript-raven` plugin? You could remove the plugin as @toddanglin  suggested with `tns plugin remove nativescript-raven`. Before rebuilding delete `platforms` and `node_modules` folders to make sure that all old files will be removed.

For now, I am closing this issue. Let me know in case you are able to reproduce some similar scenario without the plugin.

**Closed by tsonevn** 2017-05-17 06:29 UTC
Labels: iOS
