### ISSUE TITLE
A much simpler nativescript installer for each OS

### ISSUE THREAD

**Issue by emmanuelbuah** [NativeScript/NativeScript#795] opened 2015-09-21 17:16 UTC
I know nativescript is for developers but I think it will make it a lot easier for devs and for the nativescript team to create an simpler one time installer that handles the current 3-5 installation steps needed to get up and going. The current process leaves room for lots of installation error. Just a thought.

**Comment by ErjanGavalji** [comment] 2015-09-22 06:43
Closing this one for it is a duplicate of #764

**Closed by ErjanGavalji** 2015-09-22 06:43 UTC
