### ISSUE TITLE
Website Setup Guide Has Outdated Commands

### ISSUE THREAD

**Issue by JimLynchCodes** [NativeScript/NativeScript#9125] opened 2021-01-03 14:05 UTC
The ruby script referred to on [this page](https://docs.nativescript.org/angular/start/quick-setup#step-2-install-ios-and-android-requirements):

```
ruby -e "$(curl -fsSL https://www.nativescript.org/setup/mac)"
```

But it seems like pretty much every command gives me errors such as this one:
```
Error: caskroom/versions was moved. Tap homebrew/cask-versions instead.
```

**Comment by rigor789** [comment] 2021-01-03 19:21
Duplicate of #9107 - basically Homebrew made a huge breaking change in a very short period of time. 

The source of the scripts is here: https://github.com/NativeScript/setup-scripts if anyone wants to open a PR!

**Closed by rigor789** 2021-01-03 19:21 UTC
