### ISSUE TITLE
navigate on android show the color screen  before page loaded

### ISSUE THREAD

**Issue by giscafer** [NativeScript/NativeScript#4336] opened 2017-06-08 06:21 UTC
## Please, provide the details below:
navigate on android show the color screen  before page loaded
```javascript
var navigationEntry = {
        moduleName: "views/task/task-detail/task-detail",
        context: {"taskType": type, "taskId": taskId, "curPage": curPage},
        animated: false,
        clearHistory: true //if set false，the problem is solved，but we need set true
    };
    frameModule.topmost().navigate(navigationEntry);

```
### Tell us about the problem
navigate on android show the color screen when clearHistory is set true

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.2
- Cross-platform modules:2.5.2
- Runtime(s): 3.0.0

### Please tell us how to recreate the issue in as much detail as possible.
![1](https://user-images.githubusercontent.com/8676711/26914758-95b478e4-4c55-11e7-906f-ca8e3f75e0cf.png)

**Comment by NickIliev** [comment] 2017-06-08 06:40
@giscafer where is the orange screen coming from in your application? (it is not a default NativeScript template or screen).

I have tried to reproduce your issue using [this application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4269) and everything works as intended. If you still have an issue with clearHistory please send us more details on how to reproduce the issue or send us a test project that demonstrates the erosive action.

**Comment by NickIliev** [comment] 2017-06-12 08:52
@giscafer we haven't heard for you for a while - have you managed to resolve your issue?

**Comment by giscafer** [comment] 2017-06-12 10:54
@NickIliev not yet , we still can't solve the problem，we try to change the page backgroundColor=‘#fff’，but not work。it still appears the orange screen。but when i create a new demo app,it's not appears。maybe something hidden  factors accurs the problem

**Comment by NickIliev** [comment] 2017-06-12 11:12
@giscafer it's most likely related to your specific project structure - closing this one as we can not reproduce this case with a template application. 
If you need further assistance you can send me your project so I can test it on my side.

**Closed by NickIliev** 2017-06-12 11:12 UTC
Labels: Android, T:Question
