### ISSUE TITLE
NullPointerException when clicking on recent app button or opening external intent.

### ISSUE THREAD

**Issue by dali-gharbi** [NativeScript/NativeScript#5676] opened 2018-04-13 10:18 UTC
### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0
- Cross-platform modules: 4.0.0
- Runtime(s): 4.0.0
- nativescript-angular : 5.3.0
- **device : android 5.5.1** 
- **this exception does not occure on android 7.0**

### Please tell us how to recreate the issue in as much detail as possible.
you can rebroduce the issue by cloning and installing a fresh tns-template-health-survey-ng application.

1. run : tns create my-health-survey --template tns-template-health-survey-ng
2. login : click on the recent app button (this will not produce an exception).
3. **do some navigation**
4. click on the recent app button or (in another project with nativescript camera plugin installed open the camera)

```
System.err: java.lang.NullPointerException: Attempt to read from field 'int android.app.Fragment.mContainerId' on a null object reference
System.err:     at android.app.BackStackRecord$1.onPreDraw(BackStackRecord.java:1131)
System.err:     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1018)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2327)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1314)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7061)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:822)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:606)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:576)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:808)
System.err:     at android.os.Handler.handleCallback(Handler.java:739)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:145)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6917)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

is it related to  https://stackoverflow.com/a/44307694/4486121

**Comment by NickIliev** [comment] 2018-04-16 08:53
@dali-gharbi there is no **"recent app"** button in `tns-template-health-survey-ng` - are you by chance using some other template? Howevcer, we were able to reproduce the issue with opening an `intent` and the issue is logged [here](https://github.com/NativeScript/NativeScript/issues/5674). We will post any related information and fix update in the linked issue.

Closing this issue as duplciate to [https://github.com/NativeScript/NativeScript/issues/5674](https://github.com/NativeScript/NativeScript/issues/5674)

**Closed by NickIliev** 2018-04-16 08:53 UTC
Labels: os: android

**Comment by dali-gharbi** [comment] 2018-04-16 09:13
thank you @NickIliev for your answer, i will keep track on the referenced issue.
by "recent apps button" i meant this one : 

![recent-apps-button-samsung-galaxy-phone](https://user-images.githubusercontent.com/9580152/38800150-72383f6e-415e-11e8-9504-ee5a91131920.jpg)

**Comment by wershest** [comment] 2018-05-15 01:15
I have gotten the same issue. Is there any progress being made for this? I will release my app this week.
