### ISSUE TITLE
Infinite animation on Android is not working

### ISSUE THREAD

**Issue by mapo80** [NativeScript/NativeScript#8487] opened 2020-04-01 10:22 UTC
**Environment**
"@angular/animations": "8.2.14",
  "@angular/common": "8.2.14",
  "@angular/compiler": "8.2.14",
  "@angular/core": "8.2.14",
  "@angular/forms": "8.2.14",
  "@angular/platform-browser": "8.2.14",
  "@angular/platform-browser-dynamic": "8.2.14",
  "@angular/router": "8.2.14",
  "@nativescript/angular": "8.21.0",
  "@nativescript/core": "6.5.0",
  "@nativescript/theme": "2.3.3",
  "@progress-nativechat/nativescript-nativechat": "3.0.0",
  "kinvey-nativescript-sdk": "4.2.5",
  "nativescript-accelerometer": "3.0.0",
  "nativescript-angular": "8.21.0",
  "nativescript-background-http": "4.2.1",
  "nativescript-camera": "4.5.0",
  "nativescript-geolocation": "5.1.0",
  "nativescript-image": "3.0.1",
  "nativescript-imagepicker": "7.1.0",
  "nativescript-intl": "3.0.0",
  "nativescript-iqkeyboardmanager": "1.5.1",
  "nativescript-social-share": "1.6.0",
  "nativescript-theme-core": "1.0.6",
  "nativescript-ui-autocomplete": "6.0.1",
  "nativescript-ui-calendar": "6.1.0",
  "nativescript-ui-chart": "7.1.1",
  "nativescript-ui-dataform": "6.0.0",
  "nativescript-ui-gauge": "6.0.0",
  "nativescript-ui-listview": "8.0.1",
  "nativescript-ui-sidedrawer": "8.0.0",
  "nativescript-vue": "2.5.0",
  "react": "16.13.0",
  "react-hot-loader": "4.12.20",
  "react-nativescript": "0.18.0",
  "reflect-metadata": "0.1.13",
  "rxjs": "6.5.4",
  "rxjs-compat": "6.5.4",
  "svelte": "3.20.1",
  "svelte-native": "0.8.1",
  "tns-core-modules": "6.5.0",
  "zone.js": "0.10.2"

**Describe the bug**
I've created an infinite animation using animation-iteration-count on css.
On iOS animation works as expected, but on Android after the first iteration animation stops working.

**To Reproduce**
To reproduce use sample project

**Sample project**
[Playground](https://play.nativescript.org/?template=play-ng&id=zkCS6k&v=2)

**Additional context**

**Comment by NickIliev** [comment] 2020-04-01 12:39
@mapo80 this like the bug reported [here](https://github.com/NativeScript/NativeScript/issues/7712).
As a workaround, you could create the animation programmatically.

Angular example:

```TypeScript
onStackLoaded(args) {
    let stack = args.object; // StackLayout

    this.rotateAnimation(stack, 360);
}

private rotateAnimation(view, value) {
    view.animate({
        rotate: value,
        duration: 1500,
        iterations: Number.POSITIVE_INFINITY,
        curve: AnimationCurve.linear
    });
}
```

Where the **_onStackLoaded_** function is using the **loaded** event for the view you want to animate.
```HTML
<GridLayout>
    <StackLayout (loaded)="onStackLoaded($event)" backgroundColor="red">
    </StackLayout>
</GridLayout>
```

See[ this Playground demo](https://play.nativescript.org/?template=play-ng&id=zkCS6k&v=3) for the example above

**Comment by NickIliev** [comment] 2020-04-01 12:39
Duplicate to https://github.com/NativeScript/NativeScript/issues/7712

**Comment by mapo80** [comment] 2020-04-01 13:01
Ok, thanks for your answer. I thought I could use a solution using CSS only.

**Comment by jamescodesthings** [comment] 2020-10-14 07:34
Anyone who picks this up, please see https://github.com/NativeScript/NativeScript/issues/7712#issuecomment-708218923

I've got this working on rotate and infinite using the suggestion here; https://stackoverflow.com/questions/59637102/nativescript-rotate-animation-with-infinite-iteration-not-working

**Comment by janoshrubos** [comment] 2021-09-09 12:03
Duplicate of https://github.com/NativeScript/NativeScript/issues/7712

**Closed by janoshrubos** 2021-09-09 12:03 UTC
Labels: os: android, animations
