### ISSUE TITLE
iOS: Xcode 8.x signing

### ISSUE THREAD

**Issue by mikraus94** [NativeScript/NativeScript#4111] opened 2017-05-04 11:39 UTC
I've upgraded Xcode 7.3.1 to Xcode 8.3.2 and tried "tns run ios" or "tns build ios".

I get this error 

> No profiles for 'com.hidden.hidden' were found:  Xcode couldn't find a provisioning profile matching 'com.hidden.hidden'.
> Code signing is required for product type 'Application' in SDK 'iOS 10.3'
> Code signing is required for product type 'Application' in SDK 'iOS 10.3'
> Code signing is required for product type 'Application' in SDK 'iOS 10.3'
> Code signing is required for product type 'Application' in SDK 'iOS 10.3'

I works with Xcode 7.3.1 with no error. 

I've tried use --teamId but result is same.

I need Xcode 8.x because firebase isn't working with Xcode 7.x.
I can set signing to manually, but it isn't possible with webpack.

I think that nativescript 2.5.4 doesn't support Xcode 8.x auto signing.

I use 
nativescript 2.5.4
tns-core-modules 2.5.2
tns-ios 2.5.0, tried 3.0.0 too w/o success

When I switch back to Xcode 7.3.1, signing works but firebase isn't working.

**Comment by manijak** [comment] 2017-05-04 18:51
Hi @mikraus94 
I would recommend that you, after installing xcode 8.3.2, remove the ios platform from your app, and re-add it. `tns platform remove ios` then `tns pepare ios`.

**Comment by tsonevn** [comment] 2017-05-18 08:21
Hi @mikraus94,
If you still have a problem with deploying on iOS device you could use the following command `tns run ios --provision <uuid>`, where you could specify the certificate. For further info, how to use the command, please review the [comment on this](https://github.com/NativeScript/NativeScript/issues/3125#issuecomment-296212439) issue.

Bear in mind that before building the app, you should also upgrade to the latest available CLI 3.0.1 with `npm install nativescript --g`. After that you should also upgrade some of the dependencies and ios-runtime in your app.
To do that follow the below-given steps:
1. `tns plugin remove tns-core-modules`
2. `tns plugin add tns-core-modules`
3. `tns platform remove  ios`
4. `tns platform add ios`
5. `npm uninstall nativescript-dev-typescript --save-dev`
6. `npm uninstall typescript --save-dev`
7. `npm install nativescript-dev-typescript@0.4 --save-dev`

Also verify, that you are using latest versions of the plugins that you are using.
If you have some issues with the project upgrade, just for the test you could create a sample project with `tns create test` and to verify whether the app will be successfully deployed on a device.

**Comment by Buuhuu** [comment] 2017-05-19 16:10
Note: you have to install nativescript@next, this is not working with CLI 3.0.1 due to the change:

https://github.com/NativeScript/nativescript-cli/commit/9306f383f143d2acdc72c8c0dadacfd82e3dd36f

which somehow is not included in cli 3.0.1

**Comment by NickIliev** [comment] 2017-05-22 08:25
@Buuhuu just FYI: the mentioned fix for provisioning will be officially released with our next version 3.1.0 (as set in the milestone) so as our master branch is linked to the **next** tag this is the reason why currently you can find it only with the **next** tag

**Closed by NickIliev** 2017-05-22 08:25 UTC
Labels: iOS, T:Question

**Comment by xlcrr** [comment] 2017-11-11 11:40
Spent the last hour or 2 looking for a solution

Unplugged my iPhone and now it works

**Comment by xlcrr** [comment] 2017-12-15 16:00
I can confirm this happened again and I was redirected here again when installing a template. Unplugging the phone worked

**Comment by tsonevn** [comment] 2017-12-18 07:48
Hi @xlcrr,
Could you provide some more info about the steps you are using while signing the app? It would also help if you provide some more info about your project.

**Comment by xlcrr** [comment] 2017-12-18 10:55
I'm using the default settings
Sometimes when I try to run an app in the simulator I get an error when my phone is plugged in

Xcode build...
=== BUILD TARGET tns OF PROJECT tns WITH CONFIGURATION Debug ===
No profiles for 'org.nativescript.hellonsvue' were found:  Xcode couldn't find a provisioning profile matching 'org.nativescript.hellonsvue'.
Code signing is required for product type 'Application' in SDK 'iOS 10.3'
Code signing is required for product type 'Application' in SDK 'iOS 10.3'
** BUILD FAILED **

Unplugging my phone allows the simulator to run

**Comment by tsonevn** [comment] 2017-12-19 06:12
Hi @xlcrr,
If I understand you correctly, you are trying to deploy your application on Simulator and to the following error is shown when the device is plugged in. 
If this is correct and you have not setup the neede [provisioning profile ](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppStoreDistributionTutorial/CreatingYourTeamProvisioningProfile/CreatingYourTeamProvisioningProfile.html) to deploy on the device this error is expected.
The `tns run ios` will try to deploy the app on the connected device and it will fail if there is no profile, which could be used for signing.
Regarding that, you could use `tns run ios --emulator`, which will install the app only on the simulators.

Let me know if the case is different.

**Comment by xlcrr** [comment] 2017-12-24 00:15
Correct.
I was trying to run on the simulator which is why it was failing. Understood.

Now I am trying to run on the device but I'm not sure how I go about setting up code signing

**Comment by tsonevn** [comment] 2017-12-27 07:45
Hi @xlcrr,
You could review this article in the documentation, where it is described how to [create development provisioning](https://docs.nativescript.org/sidekick/user-guide/code-signing/code-signing-for-ios/create-development-provisioning)
