### ISSUE TITLE
CSS Specificity is not working properly

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#2034] opened 2016-04-25 18:18 UTC
### Did you verify this is a real problem by searching 
yes

### Tell us about the problem
CSS is applying the wrong rule when their is a more specific rule 

### Which platform(s) does your issue occur on?
Only tested on Android, but probably present on iOS too as it appears to be a css application issue.

### Please provide the following version numbers that your issue occurs with:
1.7.1

### Please tell us how to recreate the issue in as much detail as possible.
See code below.
The .red rule is applied; but the Label.green rule should be the final one applied as it is more specific (i.e. Label.green is more specific than just .red) so its changes should be the prominent values.

### Is there code involved? 
```xml
<Page>
   <Label text="Hi this is a Test and should be green" class ="red green"/>
</Page>
```

```css
.red {
   background-color: red;
}
Label.green {
  background-color: green;
}
```

**Comment by tsonevn** [comment] 2016-04-26 09:02
Hi @NathanaelA , 
I reviewed your problem. 
I've just tested given code snippets and confirm this is a real problem. This issue will be scheduled for fixing.
As a temporary solution you can set class with the global style to the `Page` and define custom style for the others objects.
```
<Page class="red">
   <Label text="Hi this is a Test and should be green" class ="green"/>
</Page>
```

**Comment by akagr** [comment] 2016-04-27 17:21
Can confirm. However, instead of the specificity, I think it's more of ordering. If you have a `<Label text="hi" class="green"/>`. And you have the following css:

```css
.green {
    color: #FF0000; // this is red
}
.green {
    color: #00FF00; // this is green
}
```
This shows the label as green on iOS (correct behaviour) and red on android (bug?).

**Comment by nsndeck** [comment] 2016-05-05 08:11
@NathanaelA I've just merged a commit with the fix for the issue.
@akagr Could you please give me a little bit more detail since I cannot reproduce `css order` issue on android.

**Comment by akagr** [comment] 2016-05-05 08:33
@nsndeck Weird. I can't seem to replicate it for a new project too. It's still happening for one of my other projects. Maybe it's something on my side after all. Feel free to ignore my comment above in that case.

**Closed** 2016-06-13 14:51 UTC
Labels: 1 - Backlog, css, T:Bug
