### ISSUE TITLE
IOS : event not fired correctly 

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#6286] opened 2018-09-20 11:14 UTC
Hi,

I think there is an issue on IOS, i have 2 same issues with loaded event when handled the event with mvvm class ! when page is loaded the event is never fired .. but if i change tab or page or switch between apps and go back the event is fired as expected !

1- i have listPicker :  
main-page.xml
```xml
<ListPicker items="{{ ticketListPicker }}" loaded="{{ updatePrice }}" id="listPickerTicket" selectedIndex="{{ selectedIndex }}" color="#000" width="40" height="100%"></ListPicker>
```

main-page.ts
```ts
import { MainPageMv } from '~/src/MainPageMv/MainPageMv';

export function pageLoaded(args) { 
    let page = args.object;
    page.bindingContext = new MainPageMv();
}

```

```ts
export class MainPageMv extends Observable
{
    public updatePrice(args)
    {
        let picker = <ListPicker>args.object;
        
            console.log(`listpicker`)
        picker.on("selectedIndexChange", (argsb:EventData)=>{
            let listpicker = <ListPicker>argsb.object;
          
            let page = listpicker.page;
            console.log(`listpicker.selectedIndex ${listpicker.selectedIndex}`)
            this.reloadPriceViewer(listpicker.selectedIndex);
        });
    }
}
```

2- Google maps sdk : the event mapReady not fired on ios and have exactly same behavior of listPicker about switch to other tab... [i post an issue here](https://github.com/dapriett/nativescript-google-maps-sdk/issues/306#issue-356222162)

config:
```sh
"nativescript": {
		"tns-android": {
			"version": "4.2.0"
		},
		"tns-ios": {
			"version": "4.2.0"
		}
	},

		"tns-core-modules": "^4.2.0",

SIMULATOR iPhone 7 plus 11.4
```

Thanks

**Comment by kefahB** [comment] 2018-09-20 11:34
its important to not : the event is fired as expected when `updatePrice` is declared on `main-page.ts`:

main-page.ts
```ts
import { MainPageMv } from '~/src/MainPageMv/MainPageMv';
import { ListPicker } from 'tns-core-modules/ui/list-picker/list-picker';
import { EventData } from 'tns-core-modules/ui/page/page';

export function pageLoaded(args) { 
    let page = args.object;
    page.bindingContext = new MainPageMv();
}

updatePrice(args)
    {
        let picker = <ListPicker>args.object;
        
            console.log(`listpicker`)
        picker.on("selectedIndexChange", (argsb:EventData)=>{
            let listpicker = <ListPicker>argsb.object;
          
            let page = listpicker.page;
            console.log(`listpicker.selectedIndex ${listpicker.selectedIndex}`)
            //this.reloadPriceViewer(listpicker.selectedIndex);
        });
    }
```

**Comment by NickIliev** [comment] 2018-09-20 12:28
@kefahB this is actually the expected behavior and the same can be observed on both iOS and Android. The thing is that when the **loaded** event for your **ListPicker** is triggered the view model initialization has already passed. This means that the `selectedChangeListener` is a bit "late" and has "missed" the initial initialization of the `selectedIndex` observable property. Now when you navigate forward and back the listener is already **created** and the whole scheme begins to work (which explains why the case is working after navigation or tab change). 

The above also explains why simply moving the ListPicker's loaded callback (called `updatePrice`) in the code-behind is also resolving your case.

However, to make this work through the MVVM, you should inject and use the picker instance. Although it would actually break the MVVM pattern it will make your case work smoothly on the initial load. 

[Modified Playground demo demonstrating injecting a Page and using to get a reference to the ListPicker](https://play.nativescript.org/?template=play-tsc&id=r84NYw&v=2)

In the demo, the MVVM is injecting a **page** in the constructor and the using **getViewById** to get the **ListPicker** and create the **selectedChange** listener

view model
```TypeScript
import { EventData, Observable } from 'data/observable';
import { ListPicker } from "tns-core-modules/ui/list-picker";
import { Page } from "tns-core-modules/ui/page";

export class HomeViewModel extends Observable {

    ticketListPicker: Array<number>;
    listPicker: ListPicker;

    private _price: number;
    private _selectedIndex: number;

    constructor(_page: Page) {
        super();

        this.ticketListPicker = [5.4, 6.3, 7.2, 8.1, 9.0];
        this.selectedIndex = 3;

        this.listPicker = _page.getViewById("my-list-picker");
        this.updatePrice(this.listPicker);
    }

    get price(): number {
        return this._price;
    }
    set price(v: number) {
        this._price = v;
        this.notifyPropertyChange("price", v);
    }

    get selectedIndex(): number {
        return this._selectedIndex;
    }
    set selectedIndex(v: number) {
        this._selectedIndex = v;
        this.notifyPropertyChange("selectedIndex", v);
    }

    updatePrice(myPicker) {
        let picker = <ListPicker>myPicker;

        picker.on("selectedIndexChange", (args: EventData) => {
            let listpicker = <ListPicker>args.object;
            console.log(`listpicker.selectedIndex ${listpicker.selectedIndex}`);

            this.price = this.ticketListPicker[listpicker.selectedIndex];

            console.log(this.price);
        });
    }
}
```

Then in the code behind provide the page reference to your view model.

```TypeScript
export function onLoaded(args: EventData) {
    let page = <Page>args.object;

    let vm = new HomeViewModel(page);
    page.bindingContext = vm;

    console.log("onLoaded");
}

```

**Comment by kefahB** [comment] 2018-09-20 12:36
Thank you @NickIliev i have à little bad idea about injecting page in mvvm !

**Comment by kefahB** [comment] 2018-09-20 17:40
There is an issue in your playground : when we go back from sub-page to main-page the app crash with this error : 

`sh 
JavaScript error:
file:///app/tns_modules/tns-core-modules/application/application.js:272:26: JS ERROR Error: NativeScript encountered a fatal error: TypeError: undefined is not a function (near '...picker.on...')
`
the problem come from observable ?! ` picker.on("selectedIndexChange"...`

```ts
public updatePrice(listPicker)
    {
        let picker = <ListPicker>listPicker;
        
            console.log(`listpicker`)
        picker.on("selectedIndexChange", (argsb:EventData)=>{
            let listpicker = <ListPicker>argsb.object;
          
            let page = listpicker.page;
            console.log(`listpicker.selectedIndex ${listpicker.selectedIndex}`)
            this.reloadPriceViewer(listpicker.selectedIndex);
        });
    }
```

**Comment by NickIliev** [comment] 2018-09-21 06:40
@kefahB here is the working demo.

```XML
<ListPicker row="0" id="my-list-picker" items="{{ ticketListPicker }}"  selectedIndex="{{ selectedIndex }}"></ListPicker> <!-- removed updatePrice from the loaded event-->
```
The error is because I've forgotten to remove the XML usage of updatePrice (which now has a changed logic and is accepting a parameter and overall is not needed as the listener is already created and attached via the view model)

**Closed by NickIliev** 2018-09-21 06:40 UTC
Labels: os: ios
