### ISSUE TITLE
ns-bot is outta sync!

### ISSUE THREAD

**Issue by pedromorgan** [NativeScript/NativeScript#5763] opened 2018-04-28 22:24 UTC
## Please, provide the details below:
when I file a PR or issue, the **ns-bot** goes and adds a few replies in thread, and send a few email; all within a few milli seconds of each other.

mostly saying `Can one of the admins verify this [patch/issue/bug]`

eg here https://github.com/NativeScript/NativeScript/pull/5762

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
I wish I knew where the code was, so I could research the problem.

# Gamble..

I bet u 2 virtual bannanas, that this issue will generate a few **ns-bot**  triggers..

Can't we just silence the bot a bit..

**Comment by vakrilov** [comment] 2018-05-02 08:35
Hey @pedromorgan - Thanks for taking time to report this. I think the issue is caused because of multiple CI builds attached to PR in this repos. We will have to check this out.

I will have to close this issue as it is not really related to the code, but thanks for reaching out.

**Closed by vakrilov** 2018-05-02 08:35 UTC
