### ISSUE TITLE
New Structure Introduce by Angular Template Causing Unit Tests Failed to Run

### ISSUE THREAD

**Issue by irwansyahwii** [NativeScript/NativeScript#6448] opened 2018-10-24 07:30 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 4.2.4

**Describe the bug**
I always get `ReferenceError: Can't find variable: exports` every time I ran `tns test ios`

**To Reproduce**
1. Create new app using angular template `tns create APP --ng`
2. Add unit tests
3. Run the unit tests `tns test ios`

**Expected behavior**

The unit tests run successfully

**Sample project**

**Additional context**

**Comment by tsonevn** [comment] 2018-10-24 08:13
Hi @irwansyahwii,
Duplicate of [#1310](https://github.com/NativeScript/nativescript-angular/issues/1310). Check out the provided workaround in [this comment](https://github.com/NativeScript/nativescript-angular/issues/1310#issuecomment-428189998).

**Closed by tsonevn** 2018-10-24 08:13 UTC

**Comment by irwansyahwii** [comment] 2018-10-24 08:29
@tsonevn but in my case it is not crashing
