### ISSUE TITLE
List Items styling between Android and iOS is inconsistent

### ISSUE THREAD

**Issue by bfattori** [NativeScript/NativeScript#452] opened 2015-07-16 17:43 UTC
I am not all that pleased with the styling differences between Android and iOS. I have been trying to mimic the styles that I _can apply_ in Android on iOS - without any luck. 

![image](https://cloud.githubusercontent.com/assets/697256/8730613/e4739900-2bbf-11e5-9d16-4f41e544c81d.png)

As you can see, the styles apply properly on Android (left) while iOS looks terrible. The item template is like so:
```XML
<ListView id="contentArea" col="0" row="1" items="{{ stockItems }}">
            <ListView.itemTemplate>
                <StackLayout orientation="vertical" style="padding: 5">
                    <GridLayout columns="100,*,*" rows="25">
                        <Label col="0">
                            <Label.formattedText>
                                <FormattedString>
                                    <FormattedString.spans>
                                        <Span fontFamily="sans-serif-condensed" fontSize="18" fontAttributes="Bold" text="{{ symbol }}"/>
                                    </FormattedString.spans>
                                </FormattedString>
                            </Label.formattedText>
                        </Label>
                        <Label text="{{ price }}" col="1" cssClass="bigText alignRight"/>
                        <Label text="{{ change }}" col="2" cssClass="{{ changeType }}"/>
                    </GridLayout>
                    <Label text="{{ description }}"/>
                </StackLayout>
            </ListView.itemTemplate>
        </ListView>
```
The CSS for the styles are shown below, with the binding `{{ changeType }}` representing a string which (in this instance) contains `bigText alignRight down`.
```CSS
.bigText {
    font-size: 18;
}

.alignRight {
    horizontal-align: right;
}

.down {
    color: #c41411;
    horizontal-align: right;
    font-size: 18;
}
```
Why the extreme difference? Is it not possible to style a ListItem on iOS? If so, this is a major drawback. Mind you, `sans-serif-condensed` is an Android font, but if the font isn't found I would expect it to default to something (which it appears to) but the styles are missing. 

Am I doing something wrong?

**Comment by nsndeck** [comment] 2015-07-20 14:00
Indeed there was an issue with fonts in ios. The issue is fixed with commit #459. With the given setup (and the fixed version) will be displayed a bold text with the default iOS font (Helvetica). Keep in mind that in iOS (some font attributes like bold and italic are set via font name for example "Helvetica-Bold" for font name will have the same result like no-font and fontAttribute set to bold. Therefore if your iOS device has your specific font bold attribute could be omitted.

**Closed** 2015-07-22 12:05 UTC
