### ISSUE TITLE
Screen width and height are reported opposite of what they should be

### ISSUE THREAD

**Issue by VeeK727** [NativeScript/NativeScript#6860] opened 2019-02-04 22:42 UTC
**Environment**
 - CLI: 5.1.1
 - Cross-platform modules: 5.1.2
 - Android Runtime: 5.1.0
 - iOS Runtime: 5.1.1
 - Plugin(s): {
    "nativescript-cardview": "3.1.1",
    "nativescript-carousel": "4.1.0",
    "nativescript-checkbox": "3.0.3",
    "nativescript-exit": "1.0.1",
    "nativescript-fresco": "5.2.0",
    "nativescript-gif": "4.0.2",
    "nativescript-image-cache-it": "4.1.1",
    "nativescript-loading-indicator": "2.4.0",
    "nativescript-material-icons": "1.0.3",
    "nativescript-permissions": "1.2.3",
    "nativescript-phone": "1.4.0",
    "nativescript-photoviewer": "1.5.0",
    "nativescript-plugin-firebase": "7.7.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "2.0.0",
    "nativescript-ui-dataform": "3.10.0",
    "nativescript-ui-listview": "5.1.1",
    "nativescript-ui-sidedrawer": "5.1.0",
    "nativescript-youtubeplayer": "3.0.1",
    "tns-core-modules": "^5.1.2"
  }

**Describe the bug**
I'm reading the device width and height on orientation change and the values reported are opposite of what they should be. On landscape I'm getting `Width: 360, Height: 640` and on portrait `Width: 640, Height: 360` using the following code:

```
exports.onLoaded = function(args) {
	application.on(application.orientationChangedEvent, setOrientation);
}
function setOrientation(args) {
   // Will console out the new Orientation
   console.log(args.newValue);
   console.log("Width: "+device.screen.mainScreen.widthDIPs+", Height: "+device.screen.mainScreen.heightDIPs);
}
```
Why is this happening? Is it a phone specific issue?

**Expected behavior**
On landscape the width should be 640 and height should be 360 and vice cress on portrait.

**Comment by tsonevn** [comment] 2019-02-05 10:23
Duplicate of https://github.com/NativeScript/NativeScript/issues/6314

**Closed by tsonevn** 2019-02-05 10:23 UTC
