### ISSUE TITLE
pageRoute.activatedRoute Can't close the subscription automatically

### ISSUE THREAD

**Issue by xiaochong44** [NativeScript/NativeScript#4101] opened 2017-05-03 14:35 UTC
If you subscribe to the service method in activatedRoute, call this.routerExtensions.back (); cannot automatically unsubscribe, resulting in an error again;

**Comment by tsonevn** [comment] 2017-05-04 14:40
Hi @xiaochong44,
Could you provide info about the service, which you subscribed and when it happens?
It would help also if you could provide sample project, which could demonstrate the expected final result and will help us to debug this case on our side. 
Then we will be able to provide some solution for your scenario.

Thank you in advance for your cooperation.

**Comment by xiaochong44** [comment] 2017-05-04 15:16
Component code is as follows
constructor(private routerExtensions: RouterExtensions,private pageRoute: PageRoute,private orderService:OrderService) { 
        this.pageRoute.activatedRoute
        .switchMap(activatedRoute => activatedRoute.params)
        .forEach((params)=>{
            this.orderService.getOrder(params["id"]).subscribe(data=>{
                this.order=data.json().result as order;
            })
          }
        )        
    }
Service code is as follows
getOrder(id:string|number){
        return this.http.post(this.baseurl+"get",{id:id},{headers:this.headers});
 }
Back code
this.routerExtensions.back();
After the return of the orderService subscription can not be automatically unsubscribe, again orderDetail times wrong

**Comment by xiaochong44** [comment] 2017-05-04 15:17
@tsonevn

**Comment by tsonevn** [comment] 2017-05-05 13:13
Hi @xiaochong44,
I reviewed your case further and found that by design navigation back while using NativeScript RouterExtensions, will not unsubscribe you automatically from the used service.

Something that I could suggest is on `ngOnDestroy` to unsubscribe from the service, which should solve the case. For example:
```
import { Component, OnInit } from "@angular/core";
import { MyHttpGetService } from "./http-get.services";

@Component({
    moduleId: module.id,
    templateUrl: "./http-get.component.html",
    providers: [MyHttpGetService]
})
export class HttpGetComponent implements OnInit {
   ........
    private subscription;

    constructor(private myService: MyHttpGetService) { };

    ngOnInit() {
        this.extractData();
        this.extractResponseInfo();
    }

    extractData() {
        this.subscription=this.myService.getData()
            .subscribe(
            (result) => this.onGetDataSuccess(result),
            (error) => this.onGetDataError(error)
            );
    }
    ngOnDestroy(){
        console.log("ngOnDestroy");
        this.subscription.unsubscribe();
        console.log(this.subscription.isUnsubscribed)
    }

    ...........
}
```

**Comment by xiaochong44** [comment] 2017-05-05 15:30
Thank you @tsonevn 
But nativescript doc <page-router-outlet>MyComponent is brought back from the cache and is shown. No hooks are called
If back calls unsubscribe manually before, it doesn't look friendly. Angular router will automatically manage subscription, it is very convenient to use, I do not know whether the pageRouter optimization

**Comment by xiaochong44** [comment] 2017-05-05 15:30
I use page-router-outlet

**Comment by NickIliev** [comment] 2017-05-11 07:02
@xiaochong44 navigating back will trigger ngOnDestroy, so it should do the job.
What do you mean when saying 

> If back calls unsubscribe manually before, it doesn't look friendly

Closing this one as the provided solution is legit -but please let us know if you have further comments and details on a scenario where this is not applicable, and we will continue the discussion.

**Closed by NickIliev** 2017-05-11 07:02 UTC
Labels: T:Question
