### ISSUE TITLE
W ExifInterface:   at com.tns.Runtime.callJSMethodNative(Native Method)

### ISSUE THREAD

**Issue by bori87** [NativeScript/NativeScript#5206] opened 2017-12-26 01:27 UTC
I am getting this when calling imageSource.fromFile(`~/assets/my_image.png`);
The picture is showing.

12-26 01:03:10.055  5858  5858 W ExifInterface:         at com.tns.Runtime.callJSMethodNative(Native Method)
12-26 01:03:10.055  5858  5858 W ExifInterface:         at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
12-26 01:03:10.055  5858  5858 W ExifInterface:         at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
12-26 01:03:10.055  5858  5858 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:957)
12-26 01:03:10.055  5858  5858 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:941)
12-26 01:03:10.055  5858  5858 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:933)
### Which platform(s) does your issue occur on?
iOS/Android/Both

CLI: 3.4
tns-android: 3.4

**Comment by NickIliev** [comment] 2017-12-26 12:28
@bori87 do you have an image called `my_image.png` located in `app/assets` folder?

I have created [this demo project](https://github.com/NickIliev/NS-Issues/tree/master/NativeScript/issue_5206) demonstrating `fromFile` usage. Please do let me know if you have further information on how to reproduce your issue (you can create and share demo NativeScript project [here](https://play.nativescript.org/))

**Comment by bori87** [comment] 2017-12-26 12:30
Yes i have and image is showing.

**Comment by bori87** [comment] 2017-12-26 21:34
I launched the demo you provided and i am still geting same warnings.
![warn](https://user-images.githubusercontent.com/29092029/34365107-dbf63358-ea8c-11e7-9caf-33740f64774f.png)

**Comment by NickIliev** [comment] 2017-12-28 12:41
@bori87 using the test project linked above is not reproducing the issue - let me know if you have a sample code or application that can reproduce the error.

**Comment by bori87** [comment] 2017-12-30 10:03
@NickIliev could You check this sample?

[warning-demo.zip](https://github.com/NativeScript/NativeScript/files/1594274/warning-demo.zip)

**Comment by NickIliev** [comment] 2018-01-02 11:59
@bori87 the provided project has version mismatch (using runtime and modules 3.4.0 while using nativescript-angular 4.4.1) - please try to migrate the project to nativescript-angular 5.x.x as described [here](https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade)

**Comment by rmaugusto** [comment] 2018-01-11 00:52
Same problem here, I updated native-angular to 5.0.0.

```
  "dependencies": {
    "@angular/animations": "~5.0.0",
    "@angular/common": "~5.0.0",
    "@angular/compiler": "~5.0.0",
    "@angular/core": "~5.0.0",
    "@angular/forms": "~5.0.0",
    "@angular/http": "~5.0.0",
    "@angular/platform-browser": "~5.0.0",
    "@angular/platform-browser-dynamic": "~5.0.0",
    "@angular/router": "~5.0.0",
    "nativescript-angular": "^5.0.0",
    "nativescript-facebook": "^2.1.0",
    "nativescript-fonticon": "^1.1.1",
    "nativescript-google-maps-sdk": "^2.4.3",
    "nativescript-ngx-fonticon": "^4.0.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^5.5.0",
    "tns-core-modules": "^3.4.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.6.0",
    "typescript": "~2.4.2"
  }

```

**Comment by NickIliev** [comment] 2018-01-12 07:17
@rmaugusto can you share a sample project or demo code snippet demonstrating the issue and also let us know what API level you are testing.

**Comment by rmaugusto** [comment] 2018-01-14 20:41
I think this problem is from nativescript-facebook plugin because only happens with alert() function on callback error.

```
        Facebook.login((error, fbData) => {
            if (error) {
                alert("Error during login: " + error.message); **// THIS GENERATES ERROR**
            } else {
                console.log(fbData.token);
            }
        });

```
Let me try change dependencies and make more some tests.

**Comment by NickIliev** [comment] 2018-01-19 13:31
@rmaugusto have you managed to reproduce the issue - I have tested with the demo application from nativescript-facebook but was not able to reproduce the case.

**Comment by rmaugusto** [comment] 2018-01-22 23:00
Yes, I created a new project with tns 3.4.0 and I could reproduce it.
I am debugging directly on my phone (Galaxy S7 Android 7.0).
The error raises when plugin can not connect to Facebook account and app try to show alert().
I changed the facebook app id to force the error.

My simple sample is in attachment.
[face-login.tar.gz](https://github.com/NativeScript/NativeScript/files/1653874/face-login.tar.gz)

**Comment by NickIliev** [comment] 2018-01-23 07:04
@rmaugusto I am successfully interacting with the facebook login from the provided project.
However, on my side the alert is simply not showing and instead I got a custom Facebook modal page like the following one:
![facebookerror](https://user-images.githubusercontent.com/18008302/35262183-403dfe64-001c-11e8-8cb1-699b919c9494.png)

So perhaps remove the alert dialog and try the Facebook login with its own error modal page.

**Comment by NickIliev** [comment] 2018-01-31 07:12
Closing the issue as not reproducible.

**Closed** 2018-01-31 08:00 UTC
Labels: os: android, question
