### ISSUE TITLE
IOS : if there is view translate/animate, after rotation of device, view goes to original position

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#1752] opened 2016-03-12 06:35 UTC
Just like translate/animate never happened, but the internal translation is still there, and in android this doesnt happened

So if there is another translation/animation it will be not correct

Its maybe because theres no interception for rotation that "retranslate" the position after rotation of device

**Comment by tzraikov** [comment] 2016-06-14 14:40
We were not able to reproduce the issue with our latest release - 2.0.1. That is why I am closing the issue. Feel free to contact us if you still experience the issue.

**Closed by tzraikov** 2016-06-14 14:40 UTC
