### ISSUE TITLE
border-radius on Android 4.4.4 (Samsung Tab) not applied to <Button>

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/NativeScript#830] opened 2015-09-28 02:55 UTC
The following markup does not apply a border-radius to the <Button> on Android 4.4.2. 

     .borderRads{
    border-radius: 30;
    }

         <Button text="SIGN UP" id="register" tap="register" 
              cssClass="button-accent-a200 margin-left-40 margin-right-40" row="17" verticalAlignment="bottom" />

I've ran the same .apk through appetize.io which I believe runs the app through Android 5.0 and the border-radius works correctly.

**Comment by NathanaelA** [comment] 2015-09-28 03:49
Uhm, you aren't using the borderRads class in your cssClass's.

**Comment by bradmartin** [comment] 2015-09-28 03:51
That was just an example. Excuse the typo. It doesn't get applied on this
device but does through appetizer io when I run it there so I know it's
working just not on the 4.4.2 samsung

**Comment by enchev** [comment] 2015-09-28 06:45
Just tried locally with our [test app](https://github.com/NativeScript/NativeScript/blob/master/apps/ui-tests-app/image-view/roundbtn.xml) and everything worked as expected.
![untitled](https://cloud.githubusercontent.com/assets/5804953/10129329/9782b9c4-65c5-11e5-91a3-fcdf02b02214.png)

**Comment by x4080** [comment] 2015-09-28 07:36
Maybe because of cache problem? Strange behavior did occur. I experienced button like before flat design. In a lollipop device :)

**Comment by bradmartin** [comment] 2015-09-28 18:28
It's device specific. The same code works fine in my emulator and when I run the .apk through appetize.io but locally on my Samsung Tab with 4.4.2 no border-radius is applied to the button. I haven't checked other elements.

**Comment by tsvetan-ganev** [comment] 2015-09-28 21:35
I also encountered the same issue - **border-radius** works on versions >= 4.4, but it does not work on devices (including emulators) running Android 4.2.2.

**Comment by bradmartin** [comment] 2015-09-29 02:19
I can confirm border-radius is not applied to any element on Samsung Tab (4.4.2) when using cssClass. I have not tested setting the styles in JS.

**Comment by vchimev** [comment] 2015-10-12 15:14
Hi @tsvetan-ganev,

I tested **border-radius** on emulator running Android 4.2.2 and it seemed to work as expected. Details:
```
    Name: Api17
    Path: /Users/vchimev/.android/avd/Api17.avd
  Target: Android 4.2.2 (API level 17)
 Tag/ABI: default/x86
    Skin: WVGA800
  Sdcard: 16M
```
![screen shot 2015-10-12 at 4 39 07 pm](https://cloud.githubusercontent.com/assets/12251337/10431164/41370eb0-710c-11e5-9059-bc64059a504f.png)

@bradmartin Did you have the chance to try if setting **border-radius** in JS works on your device?

**Comment by bradmartin** [comment] 2015-10-12 15:43
Working on that now, to set the border-radius in .js with the button module. Is it this:

    button.style = 'border-radius=20';
or is it:

    button.style.border-radius: 30;

?

**Comment by bradmartin** [comment] 2015-10-12 16:00
I just tried using the XML from the test app only the SIGN UP button and as you can see no border-radius applied. I'll keep trying to set it in the .js but not sure how to do so yet. I got an error trying to set .text on a new button which I thought was strange.

    <Button text="LOGIN" id="loginBtn" tap="login" style="width:200;height:200;color:white;border-radius:100;border-width:2;border-color:red;background-color:blue"
              row="0" col="2" colSpan="1" />
               
![screen-borderrads](https://cloud.githubusercontent.com/assets/6006148/10432378/33c29e02-70d0-11e5-8f71-2e7d9c308ac0.PNG)

**Comment by tsvetan-ganev** [comment] 2015-10-12 16:03
@bradmartin,
it should be ```button.style.borderRadius = 30;```

@vchimev, I will try it when I get home.

**Comment by bradmartin** [comment] 2015-10-12 16:11
I set it in the .js and still no border-radius. It is very much a device issue. I've ran the same .apk through appetize.io and on my emulator and the border-radius works as expected but when locally on the device nothing.

    function initViews(page) {
        loginBtn = page.getViewById("loginBtn");
        loginBtn.style.borderRadius = 30;
    };

**Comment by vchimev** [comment] 2015-10-30 08:54
FYI, related issue we managed to reproduce: https://github.com/NativeScript/NativeScript/issues/1000.

**Comment by bradmartin** [comment] 2015-10-31 00:00
Using {N} 1.4 I can work with the border properties some, I think there is a combination of things going on here.

To use  border-radius on a 'BUTTON' I have to declare the border-width. I was expecting border-radius to work more web like and not needing a border-width declared. Is that a bug or by design for borders in {N}?

The other issue is the background-color 'bleeds' out beyond the border when set. This is visibile from the image I posted previously but now that I am able to generate borders I can't find a way to fix the background-color from extending beyond the element when a border-radius is applied.

**Comment by vakrilov** [comment] 2015-11-10 09:56
@bradmartin 
I just saw this issue too. Can you please try to disable the hardware acceleration for the buttons. Its done the following way:
```
var btn= page.getViewById("btn-id");
btn.android.setLayerType(android.view.View.LAYER_TYPE_SOFTWARE, null);
```
It looks like hardware acceleration may sometimes cause rendering problems and it API-level **and** device specific. Sometimes  2 devices with same Android Version will behave differently.

**Comment by bradmartin** [comment] 2015-11-10 14:18
@vakrilov - adding that to the button did add the border radius as I expected. Thanks!

I'll try this on a ListView with images and see how the performance is, that's my only concern. I have an infinite scrolling ListView with user pictures loading in so I'll let you know the results of that in terms of performance.

Also, is there no other way to remedy this or was this just a simple way to determine the cause?

**Comment by vakrilov** [comment] 2015-11-17 11:47
Hey @bradmartin - did you experience any performance drawback when changing the layer type?

**Comment by bradmartin** [comment] 2015-11-17 15:17
@vakrilov - I haven't been able to get a working ListView with 'loadMoreItems' working with this fix. I've used it with several hard coded buttons on some pages and no issue yet but I am curious if the listview with images will cause a big hit as they load in.  Just not sure best way to tackle this approach since I don't have a ref to the Image within the ListView.  If you want send me an email at bradmartin0905@gmail.com and I'll share the code I have to get a quick working sample for you to try it with. Or if you can just tell me how I'd get the image refs from the ListView to set the layer type as the ListView items are loaded in.

**Comment by bradmartin** [comment] 2015-11-18 06:12
@vakrilov - Can you help me get the pics from the ListView here so I can test the change on images? I made some changes but for some reason the following code does not get the Image element so I can't set the layer type on the view. The p variable will be undefined, I have the user.Name correctly when debugging so it's working but not getting a ref to the view. Again this is in a ListView so not sure of the internals there. 

      //Execute an initial Load for users
        users.loadUsers(20).then(function () {

            //CHECKING IMAGE BORDER 
            if (page.android) {
                for (var i = 0; i < users.length; i++) {

                    var user = users.getItem(i);
                    var p = page.getViewById(user.Name + "-picture");
                    p.android.setLayerType(android.view.View.LAYER_TYPE_SOFTWARE, null);

                }
            }
        }); 


Here is the xml:

        <list-view id="userList" items="{{ users }}" row="1"
                   loadMoreItems="loadMoreUsers"
                   itemTap="listViewItemTap"
                   class="margin-right-15 margin-left-15">
                    <list-view.itemTemplate>
                      <grid-layout columns="auto, *, auto" rows="auto, auto" style="height:72">
                        <image id="{{Name}}-picture" src="{{ ProfilePic100 }}" row="0" col="0" stretch="aspectFit" class="img-68-circle align-center" />
                        <label text="{{ Name }}" row="0" col="1" fontSize="16" style="padding-top:20;padding-bottom:20;padding-left:16" />
                      </grid-layout>
                    </list-view.itemTemplate>
                  </list-view>

Everything is working but getting the ref to the image view.

**Comment by vakrilov** [comment] 2015-11-18 09:22
@bradmartin I would recommend another (I hope more simple) approach. Attach to the `loaded`event on the image element itself and you can get it there with args.object.

**Comment by bradmartin** [comment] 2015-11-18 19:29
@vakrilov - thanks for the event tip. That was much simpler :) and it works for border-radius.

A couple of remarks about this:
1. Is there a way to patch this in the core of is this something best left to just leave out for devs to handle? Which leads to another question, if it's best for the dev to manage, do you have a guideline on the android version/os check before making this change?

2. While the border-radius is applied correctly it's quite choppy. It's to the point where I might leave the images as squares as opposed to this. Is that due to the layer adjustment? I'll try with different image sizes to see if I can make it a little smoother but just curious.

Thanks again for your help in uncovering the cause to this and a potential work around.

**Comment by bradmartin** [comment] 2015-12-03 03:13
@vakrilov - feel free to close this if you want. Your solution for setting the layer works. Don't keep it open for me :) unless you guys are going to try and implement a fix. Thanks again for your help.

**Comment by PanayotCankov** [comment] 2016-02-08 15:40
We used clipping to achieve the rounding, but had to move to Canvas.drawRoundRect and the like to enable anti-aliasing. It would be nice if you could give it a try with the upcoming 1.6.0 release to check its status with the new implementation.

**Comment by bradmartin** [comment] 2016-02-08 17:10
I'll check it out and get some feedback to you.

**Comment by enchev** [comment] 2016-02-15 13:14
Hey @bradmartin,

Do you still have problems with this or we can close the issue?

**Comment by bradmartin** [comment] 2016-02-15 13:17
All good on my end. :+1:

**Closed** 2016-02-15 13:38 UTC
Labels: 1 - Backlog, T:Bug

**Comment by RyanSMurphy** [comment] 2016-12-08 15:59
This still isn't fixed out of the box on Android and requires a hacky fix as above. However, the above does work.
