### ISSUE TITLE
Some real android device can not read a file from content uri

### ISSUE THREAD

**Issue by miladfm** [NativeScript/NativeScript#10198] opened 2023-02-02 19:44 UTC
### Issue Description

If we try to get a file using nativescript file API (`File.fromPath(...)`) and the path is a `ContentUri`, then on some real Android devices like Samsung Galaxy S20 or S21, we will get the following error:

```
TypeError: Cannot read property 'getName' of null
    at FileSystemAccess29.getFile (file:///data/data/net.fourpanels.MedicalApp/files/app/vendor.js:2:273622)
    at Function.fr...
```

I tried to debug and find the problem, and it looks like the error is in the native package of nativescript
`org.nativescript.widgets.FileHelper.fromString(...)`

The file that causes the problem:‌ `node_modules/@nativescript/core/file-system/file-system-access.android.js`
<img width="967" alt="Screenshot 2023-02-01 at 20 44 25" src="https://user-images.githubusercontent.com/12626417/216430226-7d614d84-0302-40ab-a591-7df0d0c0cca0.png">

<img width="826" alt="Screenshot 2023-02-01 at 20 36 14" src="https://user-images.githubusercontent.com/12626417/216430335-265bdf8a-4b50-4294-b6f1-167138a0aa83.png">

### Please accept these terms

- [x] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by miladfm** [comment] 2023-02-16 23:58
@triniwiz hey Osei
Have you had a chance to look at this bug?
And If you need more information, please let me know

**Comment by triniwiz** [comment] 2023-02-17 00:02
@miladfm I'll be back on the OSS scene real soon to finish this

**Comment by Ederagp** [comment] 2023-03-29 20:21
@triniwiz Is there any news about this, I have the same problem.

**Comment by triniwiz** [comment] 2023-04-21 21:41
Hey @miladfm I'm curious on what did you use (plugin maybe ?) to get the path passed

**Comment by NathanWalker** [comment] 2023-04-21 21:43
If the file came from `imagepicker` plugin, just be sure using v2.0.0:
https://github.com/NativeScript/plugins/tree/main/packages/imagepicker#nativescriptimagepicker

**Comment by Xsmael** [comment] 2023-05-15 18:52
> If the file came from `imagepicker` plugin, just be sure using v2.0.0: https://github.com/NativeScript/plugins/tree/main/packages/imagepicker#nativescriptimagepicker

Hello I have the same issue! even using v2.0.0  i've tried both v2.0.1 and  v2.0.0 but get the same error and it doesn't work with android 10.

**Comment by jiswo** [comment] 2023-05-24 10:59
Hi, I have the same problem with the recently released imagepicker plugin v2.0.2.
Any advice/help would be appreciated as I've been struggling with this issue for hours.
Thanks in advance for looking into this.

**Comment by NathanWalker** [comment] 2023-06-12 19:33
Hi everyone @Xsmael @Ederagp @miladfm  @jiswo sounds like there is a single commit on core `main` branch related to this which hasn't been release in a patch yet however we are going to do that this week. What would help is if could confirm the following:

```
"@nativescript/android": "~8.5.0",  
"@nativescript/core": "8.5.4-alpha.2",    
"@nativescript/imagepicker": "^2.0.0",
```

Just keep in mind that imagepicker v2 has improved results with more detail. Was major version bump cause the result is a more detailed result set (eg, `result.asset` is the actual asset now but there's more data on the result now). In event you need to copy the file on latest Android devices you can use the result to do a `File.fromPath(path, true)` to copy the file.

Please let us know when possible if that works for you.

**Comment by jiswo** [comment] 2023-06-12 21:49
Hi, I tried the 8.5.4-alpha.2 package but an exception occured during application startup. 

Error received: An uncaught Exception occurred on "main" thread.
Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
ReferenceError: Cannot access 'platformNames' before initialization

**Comment by NathanWalker** [comment] 2023-06-13 05:25
Thanks for info @jiswo we have a few PRs going up to address this week - may post back when another is up to try - assume you’re using Angular?

**Comment by jiswo** [comment] 2023-06-13 07:07
> Thanks for info @jiswo we have a few PRs going up to address this week - may post back when another is up to try - assume you’re using Angular?

@NathanWalker, yes I'm using angular.

**Comment by NathanWalker** [comment] 2023-06-15 17:59
@jiswo if you get a chance, you could try one last time with this core version as we're looking to publish the 8.5.4 patch later today/tomorrow:
```ts
"@nativescript/android": "~8.5.0",  
"@nativescript/core": "8.5.4-next-06-15-2023-5281842431",    
"@nativescript/imagepicker": "^2.0.0",
```

**Comment by jiswo** [comment] 2023-06-15 22:28
@NathanWalker I tested the package and the application is running again but the main issue is not resolved.
TypeError: Cannot read properties of null (reading 'getName')
You receive this error after selecting an image with the imagepicker.
It also possible to reproduce this in an emulator running Pixel 2 API 30.

**Comment by NathanWalker** [comment] 2023-06-15 22:33
Thanks @jiswo possible to share your setup of picket maybe even drop in stackblitz? we can use that setup in the toolbox in the repo and likely setup automated test case around it.

**Comment by jiswo** [comment] 2023-06-15 23:18
@NathanWalker my picker setup is similar to the stackblitz demo found in the Nativescript docs. https://docs.nativescript.org/plugins/imagepicker.html#demo

Below is a stripped version of my setup. I'm able to reproduce the issue in a small test application.
I hope this helps.

```
public selectImage() {
  let context: imagepicker.ImagePicker = imagepicker.create({
    mode: 'single',
    mediaType: imagepicker.ImagePickerMediaType.Any,
    copyToAppFolder: 'media'
  });
  
  context
    .authorize()
    .then(() => {
      this.imageSrc = null;
      return context.present();
    })
    .then((selection: imagepicker.ImagePickerSelection[]) => {
      console.log('Selection done: ', selection);
      if(selection && selection.length > 0){
        this.imageSrc = selection[0].asset;
      }
      else{
        this.imageSrc = null;
      }
    }).catch(function (e) {
    console.log(e);
    });
}
```

**Comment by NathanWalker** [comment] 2023-06-16 00:05
Thanks @jiswo with that sample I get back a success with normal response here:
```ts
  Selection done:  [{
    "asset": {
      "_observers": {},
      "_options": {
        "keepAspectRatio": true,
        "autoScaleFactor": true
      },
      "_android": "/data/user/0/org.nativescript.ngsample/files/media/landscape-photography-tips-yosemite-valley-feature.jpg"
    },
    "filename": "landscape-photography-tips-yosemite-valley-feature.jpg",
    "originalFilename": "landscape-photography-tips-yosemite-valley-feature.jpg",
    "type": "image",
    "path": "/data/user/0/org.nativescript.ngsample/files/media/landscape-photography-tips-yosemite-valley-feature.jpg",
    "filesize": 131072
  }]
```

**Comment by NathanWalker** [comment] 2023-06-16 01:36
Successful result on API 33:
<img width="983" alt="Screenshot 2023-06-15 at 5 21 41 PM" src="https://github.com/NativeScript/NativeScript/assets/457187/a31109d0-9f5f-4f2d-8a5b-ae55e0c29a74">
And on API 31:

https://github.com/NativeScript/NativeScript/assets/457187/083ed183-eee8-4db1-b221-5bdcfd286ca9

And on a Pixel 3 physical device with Android 12:

https://github.com/NativeScript/NativeScript/assets/457187/f9541643-5909-4432-ac89-0c083c1bf882

All using AndroidManifest.xml that looks like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
	package="__PACKAGE__">

	<supports-screens
		android:smallScreens="true"
		android:normalScreens="true"
		android:largeScreens="true"
		android:xlargeScreens="true"/>

	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.INTERNET"/>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>

	<application
		android:name="com.tns.NativeScriptApplication"
		android:allowBackup="true"
		android:icon="@mipmap/ic_launcher"
		android:label="@string/app_name"
		android:theme="@style/AppTheme"
		android:hardwareAccelerated="true">

		<activity
			android:name="com.tns.NativeScriptActivity"
			android:label="@string/title_activity_kimera"
			android:configChanges="keyboard|keyboardHidden|orientation|screenSize|smallestScreenSize|screenLayout|locale|uiMode"
			android:theme="@style/LaunchScreenTheme"
			android:hardwareAccelerated="true"
      		android:launchMode="singleTask"
			android:exported="true">

			<meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />

			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<activity android:name="com.tns.ErrorReportActivity"/>
	</application>
</manifest>
```

Using these package.json dependencies:
```json
"@nativescript/android": "~8.5.0",  
"@nativescript/core": "8.5.4-next-06-15-2023-5281842431",    
"@nativescript/imagepicker": "^2.0.0",
```

Perhaps something else could be shared to help shed more light? This appears to be working properly.

**Comment by NathanWalker** [comment] 2023-06-16 01:45
Ok only with API level 30, the `TypeError: Cannot read properties of null (reading 'getName')` error occurs to conclude on this issue. With that clarity we can add a proper level check.

**Comment by jiswo** [comment] 2023-06-16 07:12
Thanks for the support, already targeting the new google play store requirement for our next release seems like a good idea.

**Comment by NathanWalker** [comment] 2023-06-17 17:39
Resolved with https://github.com/NativeScript/NativeScript/releases/tag/8.5.4-core published now.

When using with your projects and using `@nativescript/core: "~8.5.0"` in package.json, just be sure have run `ns clean` to reset lock file and ensure 8.5.4 reflects properly when lock is regenerated.

**Closed by NathanWalker** 2023-06-17 17:39 UTC
Labels: bug

**Comment by miladfm** [comment] 2023-06-28 06:47
Thank you, @NathanWalker 
I have finally managed to find some time to update the project and address this issue.
Fortunately, the latest versions of the packages have resolved the problem I was facing as well.
