### ISSUE TITLE
Inconsistency between Android and iOS in touch event getX()

### ISSUE THREAD

**Issue by Burgov** [NativeScript/NativeScript#5976] opened 2018-06-20 11:10 UTC
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
yes

### Tell us about the problem
The getX() method of the touch event on a scrollview yields different results in Android vs iOS if the scrollview is scrolled.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
See playground app

### Please tell us how to recreate the issue in as much detail as possible.
https://play.nativescript.org/?template=play-ng&id=74EbPd

- scroll the scrollview to have the number 3 in the center of the view
- tap on the 3
- a touch handler will register the output of `event.getX()` on a component property `x`

example:
in iOS the result is 602.5
in Android the result is 173.05

the difference between the two is exactly equal to `scrollView.horizontalOffset`.

**Comment by Burgov** [comment] 2018-06-20 11:44
i'm assuming the same holds true for getY(), but I didn't actually test this

**Comment by NickIliev** [comment] 2018-06-21 10:05
@Burgov I can confirm the inconsistency and mark this one as a bug. We will discuss the behaviour and post any related information at this issue.

Steps to reproduce the issue:
- use [this Playground](https://play.nativescript.org/?template=play-ng&id=74EbPd&v=2)
- scroll the `ScrollView` and tap on some point. On Android, the `getX` will return the point relative to the width of the screen while on iOS it will return the point relative to the width of the view that has triggered the gesture

**Comment by vakrilov** [comment] 2018-06-26 13:02
Indeed this is right. Looking at the code it seems that [IOS gets coordinates that are relative to the current view](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/gestures/gestures.ios.ts#L472-L478), while android g[ets coordinates from the android motion event](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/gestures/gestures.android.ts#L710-L716).

It is relatively easy to get window coordinates in IOS:
```
touch(event) {
  var point = event.getMainPointer().locationInView(event.getMainPointer().window);
  this.x = event.getX();
  this.y = event.getY();
}
```

According to the docs the `getX()/getY()` methods should return coordinates relative to the view that triggered the event. 

I'm not completely sure how should that be interpreted in the case of scroll-view. Probably, the right answer is - what API will be more useful in most of the cases. I'm curious to hear your opinion on it as it should be trivial to make the changes in one of the platforms to match the other.

**Comment by Burgov** [comment] 2018-06-26 13:08
I prefer the Android way. I want to know my position relative to the view, not the contents of it. I can add my touch event to the GridLayout if I want that behavior.

**Comment by vakrilov** [comment] 2018-08-03 09:16
Hey @Burgov - sounds reasonable :)
It looks like this issue is a good candidate for an external contribution. I you feel like it you can try opening a PR following our [contribution guideline](https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md).

**Comment by janoshrubos** [comment] 2021-09-16 08:45
Closing this issue since the implementation is merged to master. 
If this error is still relevant, feel free to open a new issue!

**Closed by janoshrubos** 2021-09-16 08:45 UTC
Labels: backlog, severity: medium, bug, os: android, good first issue, hacktoberfest
