### ISSUE TITLE
Issues when building Tabs component programatically

### ISSUE THREAD

**Issue by felixkrautschuk** [NativeScript/NativeScript#7903] opened 2019-10-03 15:50 UTC
**Environment**
 - CLI: 6.1.2
 - Cross-platform modules: 6.1.2
 - Android Runtime: 6.1.0
 - iOS Runtime: -
 - Plugin(s): -

**Describe the bug**
In our app we need to load data, that should be visualized in Tabs and we want to use the new Tabs component for that.

**Issue 1**: When trying to create the TabStripItems and the TabContentItems dynamically, the TabStrip is not visible afterwards. You are only able to swipe through the Tabs. When you navigate forwards to another page and then navigate back to the page, then suddenly you also see the TabStrip on the top.

**Issue 2** After navigating back you see the TabStrip, but it has not the complete style.
It has the correct backgroundColor, the selected Tab has the correct highlight-color, but all Tabs do not have the correct text-color and font-size and the selected Tab does not have the correct text-color (The styles have been successfully tested on a static Tabs-component).

CSS:
```
TabStrip {
    background-color: #f1f1eb;
    highlight-color: #d69a46;
}
TabStripItem Label {
    color: #3c3c3c;
    font-size: 18;
}
TabStripItem:active Label {
    color: #00718e;
}
TabStripItem Image {
    color: #3c3c3c;
}
TabStripItem:active Image {
    color: #00718e;
}
```

See the behaviour:
![TabsDynamicIssue](https://user-images.githubusercontent.com/6443021/66142258-64178a00-e605-11e9-815a-4b772f2ffb46.gif)

**To Reproduce**
Just follow the steps of the GIF:
- Navigate forwards to the Tabs-page by tapping the button.
- You can now swipe through the Tabs but you do not see the TabStrip
- Navigate forwards again by using the ActionItem
- navigate backwards by using the hardware back-button
- now you see the TabStrip, but it does not have the complete style

**Expected behavior**
The TabStrip should be visible without leaving and reloading the page.
The TabStrip should have all the styles applied, as defined in CSS (or in XML,...)

**Sample project**
[NSTabStripIssue.zip](https://github.com/NativeScript/NativeScript/files/3686847/NSTabStripIssue.zip)

**Additional context**
This is tested only on Android, maybe it does not occur on iOS.

**Comment by NickIliev** [comment] 2019-10-04 12:15
@felix-idf change the order in which the tab sub-components are created as follows:

```JavaScript
tabStrip.items = tabStripItems;
tabs.items = tabContentItems;
tabs.tabStrip = tabStrip;
```

With the above, the **first** issue is no longer reproducible on my side.

The second one seems like a legit but related[ to this issue](https://github.com/NativeScript/NativeScript/issues/7902)

**Comment by felix-idf** [comment] 2019-10-04 12:47
Hi @NickIliev

**Comment by felix-idf** [comment] 2019-10-04 12:52
Hi @NickIliev ,
I can confirm that the first issue was caused by a mistake from myself, sorry for that and thanks for that hint.

I re-tested the second issue by adding some valid FontAwesome icons to the TabStripItem, but it gives the same result.

**Comment by NickIliev** [comment] 2020-03-09 13:25
@felixkrautschuk the issue should be resolved via the latest version of the modules.

**Closed** 2020-05-23 12:42 UTC
Labels: backlog, bug, tabs
