### ISSUE TITLE
ConstraintLayout & AutoLayout implementation

### ISSUE THREAD

**Issue by DieOver** [NativeScript/NativeScript#9580] opened 2021-09-28 14:10 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when need to struct layout without the ConstraintLayout or AutoLayout,

**Describe the solution you'd like**
I'd like to use ConstraintLayout or AutoLayout, because it's more efficient way to struct layout

**Comment by rigor789** [comment] 2021-09-28 14:16
Duplicate of #5665

**Closed as completed by rigor789** 2021-09-28 14:16 UTC
Labels: feature
