### ISSUE TITLE
Execution failed for task ':processF0F1F2F3F4F5F6F7DebugResources'

### ISSUE THREAD

**Issue by ryc16** [NativeScript/NativeScript#2686] opened 2016-09-07 04:10 UTC
Hi, I got very strange behavior recently. I was able to build and run on different machine. However recently with the same source, one of my machine failed to build with below error. I try to google it for solution but can't find any. I even delete everything and checkout the source only, then do

```
> npm install
> tns platform add android
> tns run build
```

but still no luck. Anyone got this experience before and got solution? In additional, I wonder anyone have quick and detail instruction how to break down the build process or any flag that can turn on in tns to provide more detail. From message, I only know it failed on :processF0F1F2F3F4F5F6F7DebugResources FAILED. But what cause this error?

```
:preBuild UP-TO-DATE
:preF0F1F2F3F4F5F6F7DebugBuild UP-TO-DATE
:checkF0F1F2F3F4F5F6F7DebugManifest
:preF0F1F2F3F4F5F6F7ReleaseBuild UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2340Library
:prepareComAndroidSupportAppcompatV72340Library
:prepareComAndroidSupportDesign2340Library
:prepareComAndroidSupportRecyclerviewV72340Library
:prepareComAndroidSupportSupportV42340Library
:prepareComAndroidSupportSupportVectorDrawable2340Library
:prepareComGoogleAndroidGmsPlayServicesBase940Library
:prepareComGoogleAndroidGmsPlayServicesBasement940Library
:prepareComGoogleAndroidGmsPlayServicesMaps940Library
:prepareComGoogleAndroidGmsPlayServicesTasks940Library
:prepareCommon20162811DevReleaseLibrary
:prepareContactRuntimeUnspecifiedLibrary
:prepareData20162811DevReleaseLibrary
:prepareList20162811DevReleaseLibrary
:preparePrimitives20162811DevReleaseLibrary
:prepareWidgetsReleaseLibrary
:prepareF0F1F2F3F4F5F6F7DebugDependencies
:compileF0F1F2F3F4F5F6F7DebugAidl
:compileF0F1F2F3F4F5F6F7DebugRenderscript
:generateF0F1F2F3F4F5F6F7DebugBuildConfig
:cleanLocalAarFiles
:ensureMetadataOutDir
:collectAllJars
:setProperties
:asbg:generateInterfaceNamesList
:asbg:runAstParser UP-TO-DATE
:asbg:generateBindings UP-TO-DATE
:mergeF0F1F2F3F4F5F6F7DebugShaders
:compileF0F1F2F3F4F5F6F7DebugShaders
:generateF0F1F2F3F4F5F6F7DebugAssets
:mergeF0F1F2F3F4F5F6F7DebugAssets
:generateF0F1F2F3F4F5F6F7DebugResValues UP-TO-DATE
:generateF0F1F2F3F4F5F6F7DebugResources
:mergeF0F1F2F3F4F5F6F7DebugResources
:processF0F1F2F3F4F5F6F7DebugManifest
:processF0F1F2F3F4F5F6F7DebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processF0F1F2F3F4F5F6F7DebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\Android\android-sdk\build-tools\23.0.2\aapt.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```

```
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.2.1           │ 2.2.1          │ Up to date    │
│ tns-core-modules │ 2.2.1           │ 2.2.1          │ Up to date    │
│ tns-android      │ 2.2.0           │ 2.2.0          │ Up to date    │
│ tns-ios          │                 │ 2.2.1          │ Not installed │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
```

**Comment by enchev** [comment] 2016-09-07 06:28
Hey @ryc16,

Do you get this on Windows or Mac? Hey @Plamen5kov do you know what can cause this?

**Comment by Plamen5kov** [comment] 2016-09-07 06:52
Hi @ryc16,
try updating your build tools to 23.0.3 and platform tools and try building again.

**Comment by ryc16** [comment] 2016-09-07 12:53
@enchev, @Plamen5kov, thanks for your response. It is WIndows. Upgrade to 23.0.3 but and got the same. No lock (shown below) 

* What went wrong:
Execution failed for task ':processF0F1F2F3F4F5F6F7DebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\Android\android-sdk\build-tools\23.0.3\aapt.exe'' finished with non-zero exit value 1

**Comment by Plamen5kov** [comment] 2016-09-07 14:01
@ryc16 please provide steps to reproduce, and tell us what your version of CLI is.

**Comment by ryc16** [comment] 2016-09-07 14:12
@Plamen5kov, thanks for looking at it. The step is very straight forward shown below. However, I don't think it is easy to reproduce as I think it might be due to my environment problem. Since tns bundle certain process and calling other subprocess to make the build. I would like to find out if tns has any flag which I could pass to the build process so that it shows more details not just saying "Execution failed for task ':processF0F1F2F3F4F5F6F7DebugResources'.
 com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\Android\android-sdk\build-tools\23.0.3\aapt.exe'' finished with non-zero exit value 1" as it doesn't tell the problem.

> get the source form my local git.
> npm install
> tns platfrom add android
> tns build andriod

```
>tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.2.1           │ 2.2.1          │ Up to date    │
│ tns-core-modules │ 2.2.1           │ 2.2.1          │ Up to date    │
│ tns-android      │ 2.2.0           │ 2.2.0          │ Up to date    │
│ tns-ios          │                 │ 2.2.1          │ Not installed │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
```

**Comment by ryc16** [comment] 2016-09-07 18:03
I found the issue. 

`Unable to add 'C:\codeprojs\NameCard\src\ContactApp.NS\platforms\android\build\intermediates\assets\F0F1F2F3F4F5F6F7\debug\app\tns_modules\semver\semver.browser.js.gz': file already in archive (try '-u'?)`

It is exactly the same problem reported on https://github.com/NativeScript/nativescript-cli/issues/1802

Is this fixed? If not, is there any workaround at this point for us to keep working on the project rather totally dead here.

**Comment by NathanaelA** [comment] 2016-09-07 18:47
Yeah, I've seen this issue my self -- I commend you for finding out the issue!   

It is trivial to work around; what you do is:

1. tns platform remove android 
2. cd node_modules
3. Do a find *.gz *.zip *.tar   (whatever native command for you OS to find all .gz, .tar and zips)
4. DELETE them ALL, they aren't needed and as you can see aapt doesn't like them.
5. IF this module is NOT a already existing module that you have in your node_modules (i.e. something that is installed while building)
5a. npm install <modulename> --save-dev 
5b. Delete any .gz, .zip .tar files in the newly install module.
6. tns platform add android

And continue.

**Comment by sunny061** [comment] 2016-09-08 06:04
I was having similar build problems with the android platform. After finding this issue and examining my node_modules, I also found that one of my node dependencies had .gz and .tar files in them. I followed the steps provided by @NathanaelA and deleted those files. And I am able to build now.

**Comment by ryc16** [comment] 2016-09-08 12:13
Good to know it work. I didn't try @NathanaelA suggestion as I found some suggestion just to reinstall "semver". And it works to me. 

I wonder if all those no use *.gz and *.zip will be packaged into apk? Anyone know. I hope not because the apk is quite big already. But if it does, I think totally make sense to do @NathanaelA suggestion, and {N} should perform removal as build processing.

**Comment by enchev** [comment] 2016-09-10 13:29
Hey @rosen-vladimirov do you know if the CLI will remove any .gz and .zip in node_modules on build?

**Comment by enchev** [comment] 2016-09-17 11:03
Hey @Plamen5kov,

Can we handle this (work normally even if there is *.gz *.zip *.tar in the module) in our gradle?

**Comment by Plamen5kov** [comment] 2016-09-19 06:44
@enchev there was a discussion about the need on preparing the npm modules for use with NativeScript. One of the ideas was to do exactly what @NathanaelA suggested: carefuly traversing all folders inside the node_modules and find all `.gz` `.zip` `.tar` problematic files and delete them.

If there is a `.gz` file in a npm modue that contains the zipped library, we can't handle it normally, because the gradle build system uses the `aapt` tool from the Android Sdk. The `aapt` tool recognizes two files that are exactly the same: one in the npm module and one in the `.gz`.

**Comment by narender56** [comment] 2016-12-17 06:28
It's because dependencies incompatible,you can try to uninstall nativescript and install it again.
npm uninstall nativescript
npm install nativescript@2.2.0
tns platform clean android

ans there you go...

**Comment by gauravbabu74** [comment] 2017-03-09 07:15
I have got same issue during app development. Thanks for given right solutions.

"It's because dependencies incompatible,you can try to uninstall nativescript and install it again.
npm uninstall nativescript
npm install nativescript@2.2.0
tns platform clean android"

**Comment by tsonevn** [comment] 2018-02-19 13:32
This issue seems to not be reproducible anymore on our side. I am closing the issue.

**Closed by tsonevn** 2018-02-19 13:32 UTC
Labels: bug, os: android
