### ISSUE TITLE
Android run on device error: Error is: ENOENT: no such file or directory, open '/Users/nickdelahunt/<PATH>/platforms/android/build.gradle'.

### ISSUE THREAD

**Issue by delanick** [NativeScript/NativeScript#6661] opened 2018-12-04 21:12 UTC
Hi all, I see others have also had this issue but theirs seems isolated to iOS - mine is an Android build issue. It's saying my build.gradle file can't be found.

I'm using the side drawer template with CLI 5.0.1 and latest sidekick.

Here are my logs. Please help. This is painfully frustrating.

> [18-12-04 23:11:34.467] Build started.
[18-12-04 23:11:34.484] (CLI) Executing before-watchPatterns hook from /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/WeSignIt/WeSignIt/hooks/before-watchPatterns/nativescript-dev-sass.js
[18-12-04 23:11:34.484] (CLI) Executing before-watchPatterns hook from /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/WeSignIt/WeSignIt/hooks/before-watchPatterns/nativescript-dev-webpack.js
[18-12-04 23:11:34.508] (CLI) Executing before-watch hook from /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/WeSignIt/WeSignIt/hooks/before-watch/nativescript-dev-sass.js
[18-12-04 23:11:34.521] (CLI) Found peer node-sass
[18-12-04 23:11:35.493] (CLI) Executing before-watch hook from /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/WeSignIt/WeSignIt/hooks/before-watch/nativescript-dev-webpack.js
[18-12-04 23:11:35.510] (CLI) Executing before-shouldPrepare hook from /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/WeSignIt/WeSignIt/hooks/before-shouldPrepare/nativescript-dev-webpack.js
[18-12-04 23:11:35.512] (CLI) Executing before-prepare hook from /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/WeSignIt/WeSignIt/hooks/before-prepare/nativescript-dev-sass.js
[18-12-04 23:11:35.512] (CLI) Hook skipped because either bundling or livesync is in progress.
[18-12-04 23:11:35.512] (CLI) Preparing project...
[18-12-04 23:11:35.521] (CLI) Executing before-prepareJSApp hook from /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/WeSignIt/WeSignIt/hooks/before-prepareJSApp/nativescript-dev-webpack.js
[18-12-04 23:11:40.111] (CLI) Successfully prepared plugin nativescript-auto-fit-label for android.
[18-12-04 23:11:40.274] (CLI) Successfully prepared plugin nativescript-barcodescanner for android.
[18-12-04 23:11:40.384] (CLI) Successfully prepared plugin nativescript-iqkeyboardmanager for android.
[18-12-04 23:11:40.498] (CLI) Successfully prepared plugin nativescript-theme-core for android.
[18-12-04 23:11:40.623] (CLI) Successfully prepared plugin nativescript-ui-sidedrawer for android.
[18-12-04 23:11:40.732] (CLI) Successfully prepared plugin nativescript-videoplayer for android.
[18-12-04 23:11:40.845] (CLI) Successfully prepared plugin tns-core-modules for android.
[18-12-04 23:11:40.955] (CLI) Successfully prepared plugin nativescript-ui-core for android.
[18-12-04 23:11:41.066] (CLI) Successfully prepared plugin tns-core-modules-widgets for android.
[18-12-04 23:11:41.181] (CLI) Project successfully prepared (Android)
[18-12-04 23:11:41.183] (CLI) Executing after-prepare hook from /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/WeSignIt/WeSignIt/hooks/after-prepare/nativescript-dev-sass.js
[18-12-04 23:11:41.183] (CLI) Executing after-prepare hook from /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/WeSignIt/WeSignIt/hooks/after-prepare/nativescript-dev-webpack.js
[18-12-04 23:11:41.186] (CLI) Executing after-prepare hook from /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/WeSignIt/WeSignIt/hooks/after-prepare/nativescript-onesignal-gradle.js
[18-12-04 23:11:41.190] (CLI) Unable to apply changes on device: 52108bf447e0c3ad. Error is: ENOENT: no such file or directory, open '/Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/WeSignIt/WeSignIt/platforms/android/build.gradle'.
[18-12-04 23:11:41.190] (CLI) Executing after-watch hook from /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/WeSignIt/WeSignIt/hooks/after-watch/nativescript-dev-sass.js
[18-12-04 23:11:41.193] Error detected during LiveSync on 52108bf447e0c3ad for /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/WeSignIt/WeSignIt. Error: ENOENT: no such file or directory, open '/Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/WeSignIt/WeSignIt/platforms/android/build.gradle'
[18-12-04 23:11:41.198] Stopped LiveSync on 52108bf447e0c3ad for /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/WeSignIt/WeSignIt.
[18-12-04 23:11:41.201] (CLI) Executing after-watch hook from /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/WeSignIt/WeSignIt/hooks/after-watch/nativescript-dev-webpack.js
[18-12-04 23:11:41.201] (CLI) Stopping webpack watch
[18-12-04 23:11:41.203] Couldn't enable debugging for 52108bf447e0c3ad, Error: Couldn't enable debugging for 52108bf447e0c3ad
at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:125:28)
at Errors.failWithoutHelp (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:135:21)
at LiveSyncService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:263:30)
at Generator.next (<anonymous>)
at /usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:13:71
at new Promise (<anonymous>)
at __awaiter (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:9:12)
at LiveSyncService.enableDebuggingCoreWithoutWaitingCurrentAction (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:260:16)
at LiveSyncService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:301:25)
at Generator.next (<anonymous>)
at fulfilled (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:10:58)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)

>

**Comment by tsonevn** [comment] 2018-12-05 06:46
Hi @delanick,
Can you provide some more info about the way you are building the project(via cloud builds or while using your local environment)? Also, can you share with us your project `package.json` file?
Meanwhile, you can try to clear up the project while deleting `node_modules`, `platforms`, `hooks`, `package-lock.json` file and try to rebuild the project. If the issue persists build the project using the console via `tns run android --log trace > log.txt` command and if the error appears again send us the `log.txt` file.

**Comment by delanick** [comment] 2018-12-05 19:11
@tsonevn Hi, here you go :)

I'm using cloud builds and my `package.json `is as follow:

```
{
  "nativescript": {
    "id": "za.co.WeSignIt",
    "tns-android": {
      "version": "5.0.0"
    },
    "tns-ios": {
      "version": "5.0.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
    "lint": "eslint \"app/**/*.js\""
  },
  "dependencies": {
    "nativescript-auto-fit-label": "1.0.4",
    "nativescript-barcodescanner": "2.7.9",
    "nativescript-iqkeyboardmanager": "1.3.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-listview": "5.0.0",
    "nativescript-ui-sidedrawer": "5.0.0",
    "nativescript-videoplayer": "4.2.1",
    "rxjs": "~6.3.0",
    "tns-core-modules": "~5.0.2"
  },
  "devDependencies": {
    "eslint": "~5.8.0",
    "nativescript-dev-sass": "~1.6.0",
    "nativescript-dev-webpack": "~0.18.0"
  },
  "readme": "NativeScript Application",
  "author": "delanick"
}
```
Will try your other steps now and see what happens.

**Comment by delanick** [comment] 2018-12-05 20:48
@tsonevn those steps seem to have worked, but why would that sort out the issue? What would the issue be?

**Comment by tsonevn** [comment] 2018-12-06 06:38
Hi @delanick,
I am glad to hear that the issue is resolved on your side. 
The problem might be related to a corrupted file or an issue while the file is transferring(while using the cloud builds). It sounds like a temporary problem. However, without stable steps to recreate the issue on my side, I can not ensure what exactly has caused to the issue. I think that we can close the issue for now.

**Closed by tsonevn** 2018-12-06 06:38 UTC
Labels: needs more info, os: android

**Comment by delanick** [comment] 2018-12-06 10:21
@tsonevn Thanks so much!

**Comment by delanick** [comment] 2018-12-12 21:17
@tsonevn it's happening again, damn frsutrating. What do you need from me to get the right info to address this?

**Comment by tsonevn** [comment] 2018-12-13 08:21
Hi @delanick,
I would suggest opening a new issue in the sidekick repository [here](https://github.com/NativeScript/sidekick-feedback) by providing the info described in the [readme](https://github.com/NativeScript/sidekick-feedback/blob/master/README.md#access-the-nativescript-sidekick-logs)
