### ISSUE TITLE
hotspot problem in ios

### ISSUE THREAD

**Issue by alibahjat** [NativeScript/NativeScript#6126] opened 2018-07-27 11:33 UTC
hello
why hotspot alert is make my botton button down the problem shown in image 

![37837037_10212637071302523_6322992763738521600_n](https://user-images.githubusercontent.com/29424884/43318560-ef3140b0-91a9-11e8-9a7d-0ea256e40278.jpg)

**Comment by tsonevn** [comment] 2018-07-27 12:05
Duplicate of #4283 
@alibahjat, you can describe your case in the older issue

**Closed by tsonevn** 2018-07-27 12:05 UTC
Labels: os: ios
