### ISSUE TITLE
ActionBar.titleView out-of-position if re-rendered after delay - iOS 11

### ISSUE THREAD

**Issue by mingkho** [NativeScript/NativeScript#4745] opened 2017-08-24 03:35 UTC
### Which platform(s) does your issue occur on?
iOS 11

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: 3.1.1
- Runtime(s): tns-ios 3.1.0
- Plugin(s): no plugins

### Please tell us how to recreate the issue in as much detail as possible.
This only happened in iOS 11 (I build it using XCode 9 Beta 5 or XCode 9 Beta 6)
It happened on both simulator and device (iOS 11 Beta 7)
In page's loaded event handler:
1. Create a Label 
2. Create assign the label to the page's actionbar.titleView
4. If you navigate this to this page from another page, the title position will be okay at first but if something trigger the re-rendering, it will be messed up (moved to the bottom-right corner).

This issue seems to be triggered when the ActionBar is re-rendered after a small delay (e.g. add new ActionItem or even just call the requestLayout function).

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```javascript
    var page = args.object;
    var actionBarTitleLabel = new label.Label();
    var titleText = "DETAIL TITLE";
    actionBarTitleLabel.text = titleText;
    page.actionBar.titleView = actionBarTitleLabel;
    //Set a delay that will trigger re-render of the ActionBar
    setTimeout(function(){
        page.actionBar.requestLayout(); //add new ActionItem can also trigger the same issue
    },2000); //This issue can be triggered even if the delay is just 10ms
```
Attached is js files for the basic app that you can use to reproduce this issue
[app.zip](https://github.com/NativeScript/NativeScript/files/1247650/app.zip)

**Comment by tsonevn** [comment] 2017-08-24 11:17
Hi @mingkho,
Thank you for reporting this problem.

I reviewed this case on my side and indeed there is an issue with the ActionBar title and its position, This problem is reproducible only on iOS 11. I am attaching sample project, which could be used for debugging. For further info please keep track on the issue.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1248610/Archive.zip)

**Comment by terreb** [comment] 2017-10-26 11:03
Hey Guys, any workaround for this for now? Could be a piece of native code...

**Comment by terreb** [comment] 2017-10-26 11:04
I noticed that the title jumps even below the actionbar if I add flat=true.

**Comment by triniwiz** [comment] 2017-11-01 18:37
@terreb what i did was remove the flat prop then add the code that enables the flat prop in a timeout

**Comment by terreb** [comment] 2017-11-02 06:48
@triniwiz, ok thanks, will try your approach.

**Comment by terreb** [comment] 2017-11-15 13:04
@triniwiz, not the best solution for the issue, because when the screen loads I see the border for a moment. I will be waiting for an official solution from NativeScript guys.

**Comment by manijak** [comment] 2017-12-25 20:52
Yeah just noticed the same thing. If I use `flat="true"` or `navigationBar.translucent = true;` my custom ActionBar title initially loads to the right, overlapping the refresh button. 

When I navigate to another view, and back to the main, it gets properly centred.

**Comment by manijak** [comment] 2018-01-14 20:06
Any update on this? Kinda stuck and unable to push an app update because of this issue.

**Comment by rmathias86** [comment] 2018-01-15 20:12
For me, that happens only when using a 'Custom Title View'
https://docs.nativescript.org/ui/action-bar#how-to-create-custom-title-view-instead-of-the-actionbar-title. 

A temporary fix is to use 'Custom Title View' for Android :
`ngIf="isAndroid()"`
 and the 'title' property of ActionBar for iOS.
`[title]="isIOS() ? titleVar: '' "`

[BugActionbar.zip](https://github.com/NativeScript/NativeScript/files/1632893/BugActionbar.zip)

**Comment by manijak** [comment] 2018-01-15 20:16
Correct, using custom layouts as a title, makes it align to the right when navigating/loading. For me it is not a solution to use the `title` property, since it will default to default fonts, plus I it would not show the app-logo.

**Comment by rmathias86** [comment] 2018-01-15 20:31
@manijak, for me, that is not a final solution. I need to put a tap action on the label only. If I put a tap on the ActionBar, the ActionBarItems are tapped too 😢

**Comment by manijak** [comment] 2018-01-16 20:49
I found a temporary fix to this issue. Since my custom-title is a `StackLayout` containing an image and a label, I set the `width` of the StackLayout to `100%`. After that it aligned properly. 

In another view I had the Back button popping in on the left side, there I had to adjust the `width` percentage in order to fine tune the alignment.  Pluss add a dummy nav-button to the right (no icon).

**Comment by dhananjaykumar880** [comment] 2018-01-17 10:35
I have found perfect solution with custom title. it is working with `ios:horizontalAlignment="left"`

`<StackLayout *ngIf="config.title.isHomeTitle" orientation="horizontal" ios:horizontalAlignment="left" android:visibility="collapsed">
        <Image src="~/assets/icons/logo.png" class="action-image"></Image>
        <Label [text]="'application.title' | translate" class="action-bar-title"></Label>
    </StackLayout>`

**Comment by vchimev** [comment] 2018-01-25 08:56
Hey Guys,

This issue has been addressed in the *master* branch as part of implementing [more flexible composition and navigation with Frame, Page, and TabView](https://github.com/NativeScript/NativeScript/issues/48#issuecomment-360390513).

The solution is available in `tns-core-modules@next`, the forthcoming official release is going to be 4.0.0.

**Closed** 2018-01-25 08:56 UTC
Labels: backlog, bug, os: ios, severity: high

**Comment by prabudevarrajan** [comment] 2018-06-29 06:45
@vchimev i am able to reproduce this issue with ["nativescript-sdk-examples-ng"](https://github.com/NativeScript/nativescript-sdk-examples-ng) project. Attaching the iphone landscape view, and title is moved to left side(See image attached).

Is this fixed - if so, please point me to the solution, so that atleast i can patch my local file.

![image](https://user-images.githubusercontent.com/597694/42077187-debbdf80-7b2c-11e8-84c4-125d04d7fea7.png)
