### ISSUE TITLE
Changing applicationId in package.json doesnt affect the build

### ISSUE THREAD

**Issue by Legited** [NativeScript/NativeScript#2945] opened 2016-10-22 02:39 UTC
Hi,

Running NS 2.3.0 on Android, changed the "nativescript id" in package.json, but still get default Application ID. Final AndroidManifest.xml will still contain `package="org.nativescript.xxx"`

For now changed it manually in App_Resources/Android/app.gradle

**Comment by Pip3r4o** [comment] 2016-10-22 06:15
Duplicate of https://github.com/NativeScript/nativescript-cli/issues/2089. Follow the progress of the issue resolution there.

**Closed by Pip3r4o** 2016-10-22 06:15 UTC
