### ISSUE TITLE
When will be possible to compile for Android API < 17?

### ISSUE THREAD

**Issue by betosalvador** [NativeScript/NativeScript#3251] opened 2016-12-06 15:06 UTC
Hello.

I am analysing some tools to work with mobile app (ReactNative, ionic and NativeScript).

My choice at this moment is NativeScript, but I am a little afraid because in my country (Brasil) many users of Android are using version 4.0 and 4.1.

So, my question is: "When will be possible to compile for Android API < 17?".

Is there any possibility of this functionality being made available in the next release (2.5) ?

**Comment by NickIliev** [comment] 2016-12-07 07:36
Hey @betosalvador supporting of lower APIs is not top priority at this very moment and still, there is a great development on that matter which you can follow [here](https://github.com/NativeScript/NativeScript/issues/694#issuecomment-260539492).

Closing as duplicate of [vbresults ](vbresults )

**Closed** 2016-12-07 07:36 UTC
Labels: T:Question

**Comment by betosalvador** [comment] 2016-12-07 09:25
Hi.

Thanks for response, I will post my question there.

Thanks
