### ISSUE TITLE
Animated $navigateTo causes navigation bugs after suspended during the transition

### ISSUE THREAD

**Issue by tori1714** [NativeScript/NativeScript#7835] opened 2019-09-17 10:33 UTC
**Environment**
 - CLI: tns --version 5.4.0
 - Cross-platform modules: tns-core-modules@5.3.1
 - Android Runtime: "version": "5.4.0"
 - iOS Runtime: "version": "5.4.2"
(but it happens in the current version too)

**Describe the bug**
When the application is suspended during the transition animation, the following error occurs after resumed.
1) The screen before transition is displayed (though the actionbar displays the content which is after transition)
2) $navigateTo doesn't work

**To Reproduce**
1. On an app, move between pages using $navigateTo with animation  (using @tap etc.) 
2. Suspend app during the transition animation
3. Resume

**Expected behavior**
After the transition animation is interrupted / resumed, the screen display is in one of the following states, and navigating functions normally:
A: the state before transition
B: the state after transition

**Sample project**
https://play.nativescript.org/?template=play-vue&id=CUHPfN&v=7

**Comment by tsonevn** [comment] 2019-09-19 04:41
Duplicate of https://github.com/NativeScript/NativeScript/issues/7685

**Closed by tsonevn** 2019-09-19 04:41 UTC
