### ISSUE TITLE
Logs are not shown sometimes (erratic behavior)

### ISSUE THREAD

**Issue by endymion00** [NativeScript/NativeScript#6017] opened 2018-07-02 13:50 UTC
### Tell us about the problem
For some reason sometimes Nativescript does not show logs in console (console.log are not shown) after doing tns debug android or tns run android.

### Which platform(s) does your issue occur on?
Android (not tested in iOS)

### Please provide the following version numbers that your issue occurs with:
- CLI:  4.1.2
- Cross-platform modules: 3.4.1
- Runtime(s): 3.4.1
- Plugin(s): 
    "nativescript-bitmap-factory": "^1.7.1",
    "nativescript-cardview": "2.0.1",
    "nativescript-chatview": "^1.0.3",
    "nativescript-clipboard": "^1.1.7",
    "nativescript-facebook": "^2.1.0",
    "nativescript-geolocation": "^4.2.2",
    "nativescript-google-analytics": "^0.4.1",
    "nativescript-google-maps-sdk": "2.4.3",
    "nativescript-imagepicker": "4.0.1",
    "nativescript-iqkeyboardmanager": "^1.1.0",
    "nativescript-loading-indicator": "2.4.0",
    "nativescript-onesignal": "^1.0.7",
    "nativescript-orientation": "^2.2.0",
    "nativescript-phone": "1.3.1",
    "nativescript-pro-ui": "^3.4.1",
    "nativescript-toasty": "^1.1.5",
    "nativescript-ui-listview": "^3.5.5",
    "nativescript-web-image-cache": "^4.2.2"

### Please tell us how to recreate the issue in as much detail as possible.
I can not reproduce it because it happens randomly and for reasom every time is more frequent.
Sometimes I can fix-it by removing the platform but it does not work always.

**Comment by NickIliev** [comment] 2018-07-03 06:49
@endymion00 hard to investigate an issue that is not reproducible and does not have a related code involved. However, there is a possibility that sometimes the logs are not shown because the code is not live synced. When you are working in an Angular or TypeScript project and the newly placed `console.log` is now shown please examine the related transpiled JavaScript file to see if the changes are reflected in the JavaScript counterpart of your TS file.

The issue seems related to a CLI specific problem (live syncing or else) and I am closing it in favor of these. Still, I will reopen the issue If you have a stable way of reproducing the steps needed to hit this one.

**Closed by NickIliev** 2018-07-03 06:49 UTC
Labels: needs more info, os: android
