### ISSUE TITLE
IOS - Action bar title text problem.

### ISSUE THREAD

**Issue by bumbella** [NativeScript/NativeScript#4902] opened 2017-09-28 13:23 UTC
Hi,
I use Nativescript angular version
I have this problem in my app:
If I start app IOS action bar title centered and if I click icon on the left then action bar title jump right. Please help me what is the wrong code
https://youtu.be/7N0wGCwV0Vo

```
<ActionBar class="action-bar">
            <Label class="action-bar-title text-left" text="Ajánlatok"></Label>
            <ActionItem *ngIf="isDetailsView"
                        android:visibility="collapse"
                        (tap)="closeDetails()" ios.position="left">
                <Label [text]="drawerService.getMenuIcon('0xf3cf')"
                       class="font-ionic action-bar-icon"></Label>
            </ActionItem>
            <NavigationButton *ngIf="isDetailsView"
                              ios:visibility="collapse"
                              text="" android.systemIcon="ic_menu_back"
                              (tap)="closeDetails()"></NavigationButton>
            <ActionItem (tap)="userModify()"
                        *ngIf="drawerService.isModifyIconActive"
                        ios.position="right"
                        android.position="actionBar">
                <Label [text]="drawerService.getMenuIcon('0xf213')" class="font-ionic action-bar-icon"></Label>
            </ActionItem>
            <ActionItem [visibility]="!drawerService.isDrawerOpen ? 'visible' : 'collapsed'" (tap)="drawerService.toggleDrawer()"
                        *ngIf="drawerService.isToggleIconActive"
                        ios.position="right"
                        android.position="actionBar">
                <Label [text]="drawerService.getMenuIcon('0xf394')" class="font-ionic action-bar-icon"></Label>
            </ActionItem>
            <ActionItem [visibility]="drawerService.isDrawerOpen ? 'visible' : 'collapsed'" (tap)="drawerService.closeDrawer()"
                        *ngIf="drawerService.isToggleIconActive"
                        ios.position="right"
                        android.position="actionBar">
                <Label [text]="drawerService.getMenuIcon('0xf2d7')" class="font-ionic action-bar-icon"></Label>
            </ActionItem>
        </ActionBar>
```

Thanx

**Comment by tsonevn** [comment] 2017-09-28 14:29
Hi @bumbella,
Thank you for contacting us,
We reviewed your case and found that similar issue is already reported [here](https://github.com/NativeScript/NativeScript/issues/4745). The issue was reproducible only on iOS 11 and has been related to the fact that with the new iOS was introduced some changes to the layouts.

In case you think that this is a different issue, please provide some more info about your environment(NativeScript CLI, tns-core-modules and node versions), also some info about the iOS device or simulator, which is used for testing.

**Comment by vchimev** [comment] 2018-01-16 23:04
Duplicate of https://github.com/NativeScript/NativeScript/issues/4745.

**Closed** 2018-01-16 23:04 UTC
Labels: os: ios
