### ISSUE TITLE
[Angular] ListPicker throws an error when [page.color] css property is set

### ISSUE THREAD

**Issue by robertohuertasm** [NativeScript/NativeScript#3625] opened 2017-02-10 01:23 UTC
This is happening on:
- Android.
- CLI 2.50.
- Cross-platform modules 2.5.0
- tns-android 2.5.0

I create a new app by using the `cli`:
```
tns create app1 --ng
```

Then go to the `app.css` file and add this:

```css
.page {
  color: #222;
}
```

Next, add a `ListPicker` into the `item-detail.component.ts` (I'm using the default template the cli provides).

Execute `tns run android` and get the example's list. Finally, click over a row and you will get the error:

![image](https://cloud.githubusercontent.com/assets/696981/22810178/82ba929e-ef37-11e6-8837-75abb0ffb837.png)

**Comment by NickIliev** [comment] 2017-02-10 12:09
@robertohuertasm 
Thank you for reporting this one - I am confirming hat the issue is reproducible with an Angular application, NativeScript 2.5.0 on Android emulator and device.

Sample app to reproduce [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_3625_ng) (or use the steps provided by @robertohuertasm )

**Comment by PieterAelse** [comment] 2017-03-13 14:51
I have the same issue with an app not using Angular. Just adding a `<ListPicker .../>` to my XML will make the app crash when that screen is loaded. 
![image](https://cloud.githubusercontent.com/assets/6347879/23859715/e1e7706c-0804-11e7-918f-e79f85a41560.png)

![image](https://cloud.githubusercontent.com/assets/6347879/23859729/efc21f20-0804-11e7-944f-701da7c026e3.png)

**Comment by Taremeh** [comment] 2017-04-03 17:51
I experience the same bug, when upgrading to the newest Nativescript 2.5.2 (also: tns-core-modules 2.5.2).

I call the firebase service (https://github.com/EddyVerbruggen/nativescript-plugin-firebase) to fill the ListPicker-Array in the constructor of the component. No problem in the previous tns-core-modules 2.4.3 but now getting the same errors, as posted above.

But: I could fix the problem with *ngIf.
Instead of showing the ListPicker directly onInit, I interposed a button. After I click the button, `<ListPicker *ngIf` gets triggered, and everything works fine...

Maybe the ListPicker tries to initialize to early?

**Comment by PieterAelse** [comment] 2017-04-05 11:46
Downgrading to 2.4.3 seems to be the only solution for now... Waiting for 3.0 to be released!

**Comment by NickIliev** [comment] 2017-04-11 12:14
Fixed with versions 3.0.0. 
The fix is currently released with the release candidate 3.0.0-rc.1

**Closed by NickIliev** 2017-04-11 12:14 UTC
Labels: 4 - Ready For Test, 5 - Done, Android
