### ISSUE TITLE
Font awesome not working properly on IOS

### ISSUE THREAD

**Issue by markomiljkovic** [NativeScript/NativeScript#5497] opened 2018-03-06 14:10 UTC
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Tell us about the problem
Hello guys I have an Issue with font-awesome on IOS
when used in textfield or buttons it cuts my text 
Here is my code:

```
   <TextField  id="Email" width="200" hint="&#xf1fa;  "
                               text="gggyyyyy" keyboardType="email" autocorrect="false" autocapitalizationType="none" returnKeyType="next" />
```

and in app.css
```

TextField {
    border-color: #8F8F8F;
    border-width: 1;
    border-radius: 6;
    background-color: transparent;
    padding: 20;
    font-family: FontAwesome, fontawesome-webfont;
}
```

also here is a screenshot of the issue, letter g,y are cutted down inside textfields,labels, buttons.
[Screenshot](https://ibb.co/gA8K7n)

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.1

**Comment by tsonevn** [comment] 2018-03-07 09:33
Duplicate of #4689

**Closed by tsonevn** 2018-03-07 09:33 UTC
