### ISSUE TITLE
Navigating action from any UI widget (Except Button) or Layout takes time to start the action

### ISSUE THREAD

**Issue by KhalifaGad** [NativeScript/NativeScript#7599] opened 2019-07-27 14:02 UTC
**Environment**

- Nativescript version: 6.0.2
- tns-core-module: 6.0.1
- tns-android: 6.0.0
- tns-ios 6.0.1 

**Describe the bug**

When setting a tap event on Image or StackLayout that will be responsible for handling navigation it takes a while to start the function which will navigate, but when changing it to button it navigates immediately.
P.S: I have tested this on android only.

**Comment by tsonevn** [comment] 2019-07-29 04:31
Duplicate of https://github.com/NativeScript/NativeScript/issues/7559

**Closed by tsonevn** 2019-07-29 04:31 UTC
