### ISSUE TITLE
[iOS] Proper safe area support

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#5746] opened 2018-04-26 10:45 UTC
### Tell us about the problem

This aims to serve as an epic issue where to gather and discuss existing safe area problems with NativeScript 4.0, how to resolve them and store beneficial information on the topic.

### Related resources:

https://developer.apple.com/ios/human-interface-guidelines/overview/iphone-x/
https://developer.apple.com/videos/play/fall2017/201/
https://developer.apple.com/videos/play/fall2017/801/
https://medium.com/rosberryapps/ios-safe-area-ca10e919526f

### Proposed solution:

The iOS guidelines state that content should be constraint to the safe area. All the native iOS UIKit components handle these guidelines out of the box. However, {N} has its own layout system that differs from the iOS one and we should handle this ourselves. We can classify {N} components as two types - content components (those that are meaningful by themselves and show content) and container components (those that are used to contain other components and as layouts, are not meaningful just by themselves). The idea is to have all container components stretch outside the iOS safe area and have all content components lay out in the safe area. This basically means the backgrounds of the container components will be seen to the limits of the screen. Here is a list of the container components:

 - ListView (special case*)
 - ScrollView (special case*)
 - WebView (special case*)
 - Repeater
 - GridLayout
 - StackLayout
 - AbsoluteLayout
 - DockLayout
 - FlexboxLayout
 - WrapLayout

special case* - according to guidelines all scrollable containers should scroll their content beyond top/bottom constraint.

### Related issues:

- [x] https://github.com/NativeScript/NativeScript/issues/5765
- [x] https://github.com/NativeScript/NativeScript/issues/5774
- [x] https://github.com/NativeScript/NativeScript/issues/5782
- [x] https://github.com/NativeScript/NativeScript/issues/5672
- [x] https://github.com/NativeScript/NativeScript/issues/5855
- [x] https://github.com/NativeScript/nativescript-angular/issues/340
- [ ] https://github.com/NativeScript/NativeScript/issues/4283
- [ ] https://github.com/NativeScript/NativeScript/issues/6300

### Action Items:

- [x] @vchimev: Automate [templates](https://github.com/NativeScript?utf8=%E2%9C%93&q=template&type=&language=) verification against iPhone 7/8 and iPhone X.
Currently, there are builds only against iPhone 7. TODO: Add verifications for iPhone X.

**Comment by hettiger** [comment] 2018-04-27 13:09
__My Observations__

* The `LaunchScreen.storyboard` needs Safe Area support. Right now there's an ugly white bar underneath the home indicator.
* ScrollViews no longer respect Safe Areas but did pre {NS} 4.0
* [White bottom bar underneath iPhone X home indicator](https://discourse.nativescript.org/t/white-bottom-bar-underneath-iphone-x-home-indicator/5648)

**Comment by MartoYankov** [comment] 2018-04-27 13:51
@hettiger Regarding your first point - the `LaunchScreen.storyboard` has been updated in the templates. Take a look at this PR - https://github.com/NativeScript/template-master-detail-ng/pull/107

**Comment by hettiger** [comment] 2018-04-30 11:48
To make it more obvious what I was talking about in regards of the ScrollView:

I've created [a thread with a detailed explanation of the problem](https://discourse.nativescript.org/t/safe-area-issues-with-scrollview-ns-4/5714) on the forums.

Do you want me to open up a separate issue for this?

**Comment by hshristov** [comment] 2018-05-22 22:08
There is nothing epic here. I designed it to be compliant with Apple Design Guidelines out of the box.
Root element spans on the whole screen and its background spans on the whole screen as well. If the content of that root element is scrollable (which means ListView, ScrollView or any element with property [scrollableContent=true](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/core/view/view.ios.ts#L596)) then that element is given the whole screen size. If not the element is given the safe area. 
The property `scrollableContent` isn't public because there were cases where a developer would want to span at top but not at bottom so we need to make that property to support true (for top and bottom) as well as top only and bottom only.
Left and right are not an option when in landscape according to Apple docs.
So all the logged bugs are actually the expected behaviors that comply with Apple design guidelines...

**Comment by MartoYankov** [comment] 2018-05-23 12:01
Firstly, @hshristov, the current solution fulfills the guidelines if we agree that everything below the root of the app is content. However, inspecting Apple's own apps on the iPhone X quickly makes it clear that what the guidelines mean by "content" is undefined. In many cases it appears what is "content" should be determined by the app developer. For example, in the News app the news images stretch to full screen in landscape mode. Such scenarios need a different approach or new API to be handled

@davecoffin Thanks for the input. What, in your opinion, should be the default behavior of these spandUnder.. properties? My current plan is that all of these layout containers should stretch to full screen (under everything) and have a "padding" for their content with the same size as the insets. Basically, this means that by default the layout containers background (color or image) will be full screen, while their contents will lay out in the safe area. For example, this https://cl.ly/rjxy will be possible by default if the top element in the ScrollView is a layout container with background image. However, if the top element is an Image component it will be inset.

**Comment by hshristov** [comment] 2018-05-23 19:32
@MartoYankov everything inside Page is content. Again when content is scrollable it will stretch to full screen. By default scrollable content is ListView, RadListView, ScrollView if they are set as a content of the Page. If you want to force the content to be fullscreen - just set `scrollableContent=true` on the page content.
<br><br>
Messing with `Layout` paddings won't help at all because you will have to check the visual tree in order to determine when you have to set this paddings and when to remove them.

**Comment by davecoffin** [comment] 2018-06-16 18:44
@hshristov This property you describe:  scrollableContent=true doesnt appear to do anything. Take a look here:

https://cl.ly/sLGL

If scrollableContent="true" would take any root view and extend it to the bounds of the device, that would solve a problem where a dev would like their view to extend to the edges of both the bottom and top of the device. For example, in my login screen pictured above. That SHOULD look like this: https://cl.ly/sLUH

I accomplish that right now by appending a class to the element that sets its margins as 
```
margin-top: -44;
margin-bottom: -34;
```
This is not ideal for a number of reasons, the most obvious one being devices with notches and the concept of safe areas for content are becoming abundant on both platforms, I would bet money that Apple will release a new phone in September that has their safe areas defined slightly different, aka a smaller notch. Then the class structure will become unwieldy, as there is not even a reliable built in method to get a device type early enough in boot to append appropriate classes.

The properties I mention above would give a dev complete control over where their content spans. If a dev doesnt care about content scrolling under actionbar and tabview for example, they do nothing and their app looks fine. But I like the translucency that comes with those native elements, so I can span under it with `spansUnderActionBar`. If I have no action bar, for example in my login screen pictured above, I set the properties on that gridlayout to be `spansUnderStatusBar` and `spansUnderHomeIndicator` to true, and they would then extend to the edges of the device. 

Also, say for example I want a view to extend to the bottom, but its a scrollview and i dont want content to conflict with the status bar, I could JUST set `spansUnderHomeIndicator`, and then my view would look basically like this: https://cl.ly/sLjv
No reason to do that there, but imagine it was a ScrollView, I didnt have that background image (the whole view would be the Page background which shows under status bar) and I dont want text to scroll on top of the status bar. Then I can have my content scroll beautifully up from the bottom of the device like this: https://cl.ly/sLCp But clip at the top at the appropriate point set by the safe areas defined in UIKit. 

A LOT was done to improve iOS frame in 4.0, we have so much more flexibility now. And all this stuff is achievable using my method of applying negative margins to root views, but hardcoding margins will soon become unacceptable, and is already not intuitive for developers. I think my approach would cover everything, I'm excited to go into even more detail with the core team next week!

cc @NathanWalker @shiv19 @DickSmith

**Comment by davecoffin** [comment] 2018-06-16 19:05
One more thing worth mentioning: I use this approach for all iOS devices. According to Apple's design guidelines, the status bar should be incorporated into your application wherever possible, and that stands for iPhone X and any other iOS device. So my frame-content class is typically defined like so, in an ios specific scss file:

```
.frame-content {
  margin-top: -20;
  
  &.iphonex {
    margin-top: -44;
    margin-bottom: -34;
  }
}
```

Now obviously as a dev we need to design our apps to handle status bars in that case, but thats the name of the game. Here's how I do it in one my apps: https://cl.ly/sL4H

When content reaches a point where it may conflict with status bar, I display a blur view which the content scrolls under. And to complete my point, the approach is the same for other devices:

https://cl.ly/sLgK

 just the margins are different.

**Comment by hshristov** [comment] 2018-06-17 21:36
Hi @davecoffin,

The code that you are using is angular. Are you sure that this `GridLayout` is in fact a direct child of `Page` element? In any case I would suggest you try it on a non angular application and check the results.

Now I'm not against such properties. Exactly the opposite. In my previous post I said that `scrollableContent=true` isn't public because it is not flexible enough. It should be something like `scrollableContent="left, top, right, bottom"` or any of those. This is up to the application developer.
And but default we make sure that you don't have to do anything in order to get the best UX that comply with Apple guidelines. This means that if there is no action bar scrollable content should go under status bar. If this is the case a solution is to use a blur element (like you did in your app).

 There are more rules in the design guidelines but I won't discuss them here.

Most ViewControllers knows how to handle all these details so most of the time all should work out of the box. At least that was my idea. And if this is not good enough we should have the new `scrollableContent` I was talking about that lets you customize which direction you want to span.

Anyway I hope you could reach a consensus with the team on your next meeting...

**Comment by speigg** [comment] 2018-06-27 01:13
Yes, `scrollableContent=true` doesn't work. Looking at the code in view.ios.ts it's clear why:

```ts
        left = safeOrigin.x;
        width = safeAreaSize.width;

        if (hasChildControllers) {
            // If not inner most extend to fullscreen
            top = fullscreenOrigin.y;
            height = fullscreenSize.height;
        } else if (!scrollable) {
            // If not scrollable dock under safe area
            top = safeOrigin.y;
            height = safeAreaSize.height;
        } else if (navBarHidden) {
            // If scrollable but no navigation bar dock under safe area
            top = safeOrigin.y;
            height = navController ? (fullscreenSize.height - top) : safeAreaSize.height;
        } else {
            // If scrollable and navigation bar extend to fullscreen
            top = fullscreenOrigin.y;
            height = fullscreenSize.height;
        }
```

That last condition is the only condition in which top and bottom actually extend to the fullscreen (scrollableContent with visible navigation bar). If we have no navigation controller in our app, then Nativescript does not allow the app to go fullscreen. 

But it's also worse, because the width is constrained to the safe area width, so that when in landscape there are vertical bars on the left and right. I suppose this relates to what @hristoborisov said: "Left and right are not an option when in landscape according to Apple docs", but I see no evidence for this in my reading of the design guidelines (and even so, they are only design guidelines, not rules that should be strictly applied in every scenario).  

I want to have full control over how my content is played out with respect to safe areas in the (entire) full screen space, but the way that Nativescript currently constrains things is making it very difficult to do anything other than the most basic layout.

**Comment by davecoffin** [comment] 2018-06-27 13:29
I agree with all of that, there are very few scenarios where landscape should have margins on the side. The only one I can think of is a Page with no action bar, no tabview, nothing except scrollable textual content. To illustrate, create a simple app with a tabview, load it in iPhone X sim and turn it landscape. The tabview is padded, forcing the layout into stacked icon and text! In order to achieve this: https://cl.ly/sZID
You need to apply negative margins to left and right sides. This can be done by applying a class of "landscape" for example to the root view, and then adding negative margins on that class. BUT, even that comes with a pitfall which will require even more hackery, on `tnsApp.resumeEvent` that class is lost, and here is the result: https://cl.ly/sXuj

**Comment by hshristov** [comment] 2018-06-27 19:36
@speigg Here is the quote from the [guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/overview/iphone-x/):

> Inset essential content to prevent clipping. In general, content should be centered and symmetrically inset so it looks great in any orientation and **isn't clipped by corners or the device's sensor housing, or obscured by the indicator for accessing the Home screen**. 

In other words you are allowed to do whatever you want but you should keep in mind that people won't be able to interact easily with the content at the bottom/top of the screen.

In the case of @davecoffin we don't layout TabView. TabView and Frame are laid out by the system. We only layout the content inside Page or TabItem based on what space we are given.

As I said before `scrollableContent` is not powerful enough and it should support more options like `left, top, right, bottom` so that developer could override our implementation without any hacks. But I did run out of time for 4.0...

**Comment by speigg** [comment] 2018-06-27 20:18
> we don't layout TabView. TabView and Frame are laid out by the system. 

@hristoborisov I’m not so sure that this is the case (and it may be a bug) as {N} lays out the root View (whether Frame or TabView or any other kind of {N} View) to be constrained within the safe area. For example, the UIView located at `topFrame.nativeView` is constrained within the safe area defined by `topFame.viewController.view` (note that the former UIView is the subview of the latter). So, the system lays out the root UIViewController’s UIView, but the Frame and TabView nativeViews, which are a subview of the root UIView, are each layed out by NativeScript directly to be within the safe area (in “ui/core/view/view.ios.ts”, `layoutView()` method). If you were to layout the root View to the full screen size, and the Page/TabItem views within the safe area, I think that alone would solve a lot of the problems here (and I think this was the original intention anyways). 

Also, I don’t think “scrollableContent” (the name at least) makes sense at all, as full screen apps are not necessarily scrollable. I would prefer to see the concept of “safe areas” exposed directly as a first-class concept in {N}.

**Comment by davecoffin** [comment] 2018-06-28 14:10
Yea I was definitely wrong about the TabView layout, the reason my view looks like that is because I have TabView wrapped in a GridLayout. The reason for that is I like to display certain content (like videos, other overlays) on top of the TabView (fullscreen). 
Just want to give a shout out to all the smarties working on this specifically @vakrilov @MartoYankov who are working their butts off to address this issue!

**Comment by speigg** [comment] 2018-06-28 14:55
@MartoYankov ah okay I assumed that @davecoffin had his TabView at the root. 

Anyways, I’m not using TabView or Frame, just a GrIdLayout at the root (like @davecoffin), and yet it is contained within the safe area, which seems wrong.

**Comment by hshristov** [comment] 2018-06-29 19:51
@speigg I'm not hristoborisov but @hshristov. As I said we need to enhance scrollableContent (or whatever the property name is). But currently you have an easy workaround - just add a view controller to your view controller (your root view .`viewController` property should be populated by us with `UILayoutViewController`. I know it is not perfect but will allow you to bypass all check and go full screen immediately. 

@davecoffin I think you should not wrap Frame or TabView inside other elements. It may work but it is not a supported/tested scenario. A better approach would be to use [showModal](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/core/view-base/view-base.d.ts#L123) method which will display over the current page (not sure if this will solve all cases in your scenario but worth a try).

**Comment by speigg** [comment] 2018-06-30 01:22
> @speigg I'm not hristoborisov but @hshristov. 

Ah, thanks, I corrected it

> But currently you have an easy workaround - just add a view controller to your view controller (your root view .viewController property should be populated by us with UILayoutViewController

I did try this, but the problem is that the left and right safe area inset is still applied, so it does not in fact go fullscreen on landscape orientation (for iPhone X). The only workaround I found was to replace the root UILayoutViewController with my own implementation that lays out the rootView in fullscreen (without regard for safe areas).

**Comment by NathanaelA** [comment] 2018-07-12 16:51
I found another way to **fix** this issue in one of my app's.  NativeScript 4.0 adds a awesome `layoutChanged` event.  I tie this event on the root element and then change the root's frame if it has the wrong values.  :-)     Because the `layoutChanged` is fired on initial build layout and on each of the rotations; it allows me to fix the frame properly no matter when.  :-)

**Comment by hettiger** [comment] 2018-07-12 17:50
@NathanaelA

That’s awesome news! Do you mind sharing some code?

**Comment by NathanaelA** [comment] 2018-07-12 18:13
Well in my case I needed to eliminate the 20 pixel border; and doing the manual "-20" would break landscape mode.   But you can extend this to REDO any broken frame calculations.  :grinning:
 
```
<Page><SomeRoot layoutChanged="changed">...

function changed(arg) {
if (arg && arg.object && arg.object.nativeViewProtected) {
				var frame = arg.object.nativeViewProtected.frame;
				if (frame.origin.y !== 0) {
                                        // Origin.y would equal 20 here; so eliminate it and then add the missing 20 to the height
					var newFrame = CGRectMake(0, 0, frame.size.width, frame.size.height + 20); 
					arg.object.nativeViewProtected.frame = newFrame;
				}
			}
}
```

**Comment by hettiger** [comment] 2018-09-23 07:47
Will RadListView be supported as well? (It's not on the issue's proposed solution list)

**Comment by MartoYankov** [comment] 2018-09-25 14:14
@hettiger We are aiming for RadListView and RadSideDrawer to support expanding their non content parts outside the safe area. I will check out the large nav bar titles. I think they will work out of the box with the new implementation.

**Comment by hettiger** [comment] 2018-09-25 18:42
> @hettiger We are aiming for RadListView and RadSideDrawer to support expanding their non content parts outside the safe area. I will check out the large nav bar titles. I think they will work out of the box with the new implementation.

Amazing news. Thank you very much for the update. In the meanwhile I'm using following workaround for large navigation titles:

```ts
private subscriptions$ = new Subscription();
private scroll$: Subject<RadListView> = new Subject<RadListView>();

ngOnInit(): void {
    this.requestLayoutOnScroll();
}

ngOnDestroy(): void {
    this.subscriptions$.unsubscribe();
}

onScrolled(args: ListViewScrollEventData): void {
    const radListView = <RadListView>args.object;
    this.scroll$.next(radListView);
}

private requestLayoutOnScroll(): void {
    this.subscriptions$.add(
        this.scroll$.pipe(
            throttleTime(
                1000 / 24,
                undefined,
                { leading: false, trailing: true }
            )
        ).subscribe((radListView) => {
            radListView.requestLayout();
        })
    );
}
```

Performance is poor but it keeps the RadListView adapting to size changes that take place when scrolling with large navigation titles.

Maybe it helps some other people that want to workaround as well until this issue is fixed.

**Comment by davecoffin** [comment] 2018-09-25 20:14
In the mean time @MartoYankov, could you weigh in on this: https://cl.ly/567d4056092e
Notice, when in landscape when you navigate and go back, the *tabItem width changes. Switching to portrait and back fixes the layout issue. This is new to iOS 12.

**Comment by MartoYankov** [comment] 2018-09-26 09:59
@hettiger @davecoffin Thanks for reporting this. I think this might be fixed with the new implementation. We're planning to merge a version of it in `master` this week, so that it can be tested with the `next` tag.

**Comment by davecoffin** [comment] 2018-09-26 12:38
You mean all the safe area stuff? That would be awesome...

**Comment by hettiger** [comment] 2018-09-29 12:42
<img width="1032" alt="extendedlistviewcell" src="https://user-images.githubusercontent.com/4583871/46245847-49f50b80-c3f5-11e8-915e-c0bc65b152d2.png">
<img width="1121" alt="tkcollectionview" src="https://user-images.githubusercontent.com/4583871/46245848-49f50b80-c3f5-11e8-89d2-9c5f696cbe3e.png">
<img width="1124" alt="tklistview" src="https://user-images.githubusercontent.com/4583871/46245849-49f50b80-c3f5-11e8-85ea-7a6e65487aee.png">

Here are some Screenshots from the View Hierarchy. It's interesting that the ExtendedListViewCell's suppresses the TKListView. (I've tried adding more cells to verify this.)

The root element in this app is a TabView with 4 page router outlets. It's an angular app.

I hope this helps a little @MartoYankov

**Comment by hettiger** [comment] 2018-09-29 13:17
Just made a little repo so you can reproduce the issue:

https://github.com/hettiger/RadListView-safe-area-issues/commits/master

(See commit messages for more information)

**Comment by MartoYankov** [comment] 2018-10-01 07:29
@hettiger The ui plugins should behave like before. There is no breaking change for them. `RadListView` should layout in the safe area. I tested this on iOS 10, and 12 both on device and emulator and can't reproduce the issue with the repo. Is there something else I can try? Also, does it happen if you change `RadListView` to a simple `ListView`?

Further, let me clarify that the safe area support that is now in `next` doesn't automatically affect ui plugins. Each ui component should decide for itself how to handle the safe area constraints. Part of the idea to merge this in `next` is to start testing and implementing the ui plugins.

**Comment by hettiger** [comment] 2018-10-01 08:00
Thanks for looking into this @MartoYankov 

> ... can't reproduce the issue with the repo.

I'm not sure why you would not be able to reproduce.
I've just tried reproducing with a fresh clone and I immediately get the white page.

```bash
tns --version
# Output: 4.2.4
git clone git@github.com:hettiger/RadListView-safe-area-issues.git
cd RadListView-safe-area-issues
npm i
tns run ios
# ActionBar is visible but content area is empty / white page
git reset HEAD --hard
git checkout 7663114fe1936b72eea0cd5409ecb86a9d4f250d
rm -rf platforms
rm -rf node_modules
npm i
tns run ios
# ActionBar and RadListView both are visible. RadListView content is showing up correctly.
```

I'm running Xcode Version 10.0 (10A255) on macOS Mojave Version 10.14 (18A391).

Tested with:

- iPhone 6s (Real device)
- iPhone XS Max (Simulator)

> Also, does it happen if you change RadListView to a simple ListView?

I've tried ListView on the master branch of my repo. It's showing up correctly. 👍 

> Further, let me clarify that the safe area support that is now in next doesn't automatically affect ui plugins. Each ui component should decide for itself how to handle the safe area constraints. Part of the idea to merge this in next is to start testing and implementing the ui plugins.

I understand this and it's perfectly fine. I'm glad about the way how you takle this and am really thankful for all the effort you've put into this. This is just some feedback to help improve the next iteration.

**Comment by MartoYankov** [comment] 2018-10-01 08:51
@hettiger The only difference to what I tried is the Mojave version. I tested it on Mojave and I still see the `RadListView` items. Can you try setting a `backgroundColor` to the `RadListView`? In this way we can differentiate between the control not being laid out and the cells not being shown.

**Comment by hettiger** [comment] 2018-10-01 11:16
@MartoYankov Wow, that's super weird. However: 

- [I've added background colors](https://github.com/hettiger/RadListView-safe-area-issues/commit/0437f32e7e92a03ac5e0cd8507401deb8e624bc2)
- [I've added a »working« branch](https://github.com/hettiger/RadListView-safe-area-issues/branches/all) (»master« is still the failing branch)
- I've made some screenshots

![radlistview-tests](https://user-images.githubusercontent.com/4583871/46285506-fc56db00-c57b-11e8-84dc-2d44ab8c4502.png)

I hope this helps.

**Closed** 2019-04-03 11:46 UTC
Labels: os: ios
