### ISSUE TITLE
Feature request: PagerView Control

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#765] opened 2015-09-17 13:57 UTC
I feel that we need a "PagerView"-control or a "ScrollView" with paging. This is not the "Caoursel" component that iOS uses, nor the "ListView with horizontal scroll". But more of a flat-style view\content switcher, the famous "white-dot-pager". So that we can easily switch between parts of the view\screen (For instance images, or results of a football game).

It could behave similary to the TabView component, just without the TabBar-buttons and with swipe gestures (to swipe between pages). 

I would create one of theese on my own, but have no idea where to start. 

Something like this:
```xml
<PagerView orientation="horizontal" height="300">
   <PagerView.items>
   
     <PageViewItem title="Item 1">
       <PageViewItem.view>
          <StackLayout>
			<Label text="Some text here..." />
			// Other content
		  </StackLayout>
       </PageViewItem.view>
     </PageViewItem>
	 
     <PageViewItem title="Item 2">
       <PageViewItem.view>
          <StackLayout>
			<Label text="Some text here..." />
			// Other content
		  </StackLayout>
       </PageViewItem.view>
     </PageViewItem>
	 
   </PagerView.items>
</PagerView>
```
Features:
- Orientation
- Height or the posibility that it can be stacked with other components (not allways fullscreen).
- Bindable? (If you have a list of images e.g.)

![GitHub Logo](http://www.apeth.com/iOSBook/figs/pios_2003.png)

**Comment by jlooper** [comment] 2015-09-17 14:27
I was thinking about this yesterday. Good idea, especially when you need a tutorial to onboard app users. +1

**Comment by dbbk** [comment] 2015-09-18 20:00
This is a duplicate of #173. Been waiting four months :(

**Comment by valentinstoychev** [comment] 2015-10-08 13:28
Hey all - good news!! We are working on this and it will be available soon as part of Telerik UI for NativeScript - hopefully as part of our 1.5 release (coming mid-November).

**Closed** 2015-10-08 13:37 UTC
