### ISSUE TITLE
problem with scrolling and swiping nested elements inside <ScrollView>

### ISSUE THREAD

**Issue by ghbakhtiari** [NativeScript/NativeScript#3286] opened 2016-12-12 19:06 UTC
I'm developing a naiveScript app with angular. 
so the problem is, inside a `scrollview` when i put another `scrollview` or even a google map plugin, the scrolling gets blown up...

the problem with nested `scrollview`s happens only when the orientation of the parent `scrollview` and the child `scrollview` are the same. for example when they're both vertical, the swipe/scroll event mostly works for the parent `scrollview` and doesn't get passed through to the child.
for example:

```
<ScrollView orientation="vertical" height="100%" width="100%">
      <StackLayout orientation="vertical" height="200%" width="100%">
            <ScrollView orientation="vertical" height="100"  width="100%">
                   <StackLayout orientation="vertical" height="200"  width="100%">
                          //scrolling here, wont work at all
                   </StackLayout>
             </ScrollView>
      </StackLayout>
</ScrollView>
```

but when i use a map plugin inside another vertical `scrollview`, aside from map's vertical scrolling which doesn't work at all, the horizontal scroll also doesn't work properly.
for example:

```
<ScrollView orientation="vertical" height="100%"  width="100%">
      <StackLayout orientation="vertical" height="200%"  width="100%">
                <MapView (mapReady)="onMapReady($event)"></MapView>
      </StackLayout>
</ScrollView>
```

the map plugin is from [here](https://www.npmjs.com/package/nativescript-google-maps-sdk)

aside from these, other `(swipe)` events also don't work properly and constantly get mixed up with the parent's scrolling event. (even horizontal swipes inside a vertical `scrollview`)

I've only tested this on android.
my tns version is 2.3.0

**Comment by tsonevn** [comment] 2016-12-13 07:49
Hi @ghbakhtiari, 
Thank you for your interest in NativeScript.
I reviewed your case and was able to reproduce this problem. Unfortunately this is something related with the Android platform and the fact that the parent ScrollView will handle the event before the child component. On that matter, the best practice is to not use nested ScrollViews.  Regarding the problem with the `nativescript-google-maps-sdk`, perhaps you should specify the height of the `MapView` component.

To be able to use similar functionality, like swipe between different views, you could use `nativescript-slides` plugin and its `SlideContainer` For further help, you could also  review the demo app in the plugins [repo](https://github.com/TheOriginalJosh/nativescript-slides).

I also would like to notify you that you could upgrade your `NativeScript` to latest version `2.4.2`. Instructions, how to do that, could be found [here](http://docs.nativescript.org/releases/upgrade-instructions).

To be able to provide more straightforward suggestion for your case, could you provide some more info about your project and the need of using nested `ScrollView`.

Regards,
@tsonevn

**Comment by ghbakhtiari** [comment] 2016-12-13 09:13
hi, thanks for your answer

> Unfortunately this is something related with the Android platform and the fact that the parent ScrollView will handle the event before the child component

this is exactly my problem. all the swipe and scroll events go to the parent ScrollView instead of any child element. whether it be a nested Scrollview, or the map, or even just assigning a method to an element's `(swipe)` event like this:

```
<ScrollView orientation="vertical" height="100%"  width="100%">
    <StackLayout orientation="vertical" height="200%"  width="100%">
          <Label text="some text" (swipe)="someMethod($event.direction)" height="100" width="100%"></Label>
    </StackLayout>
</ScrollView>
```
here, inside the `<Label>` , a vertical swipe (to up or down) wouldn't even call the method and would just scroll. and moreover, unless the swipe is **exactly** towards right or left, the gesture would again be considered as scrolling ScrollView up and down. even with less than a 30 degree deflection from the horizontal direction. I men shouldn't it be considered as a bug?

> Regarding the problem with the nativescript-google-maps-sdk, perhaps you should specify the height of the MapView component

i've done that, but the problem stays.

> To be able to provide more straightforward suggestion for your case, could you provide some more info about your project and the need of using nested ScrollView.

my main problem was with the case of using a map and a `(swipe)` event on some other element both inside the ScrollView. i just checked the nested ScrollViews to see if the problem occurs with that too.


you think upgrading the nativescript would solve it?

**Comment by ghbakhtiari** [comment] 2016-12-15 20:19
any suggestions?

**Comment by tsonevn** [comment] 2016-12-16 12:48
Hi @ghbakhtiari.
Thank you for writing us back.
I reviewed your problem again and was able to reproduce this behavior, while using `ScrollView` and attaching swipe gesture to some of its child component for `Android`. I have tested this scenario with `swipe` and `pan` gestures. We will research further, what is causing this problem. In the meantime  you could create your UI without using ScrollView. For example:

```
<GridLayout rows="100 *" >
      <Label text="some text" (swipe)="someMethod($event)" ></Label>
      <MapView row="1" (mapReady)="onMapReady($event)"></MapView>
</GridLayout>
```

Regards,
@tsonevn

**Comment by ghbakhtiari** [comment] 2016-12-17 10:32
hi @tsonevn
thanks again,

> We will research further, what is causing this problem.

I would really appreciate it if there was a solution found. because in this current project I have no choice but to use the ScrollView and that's because of the page design that's been given to me by our graphist...

**Comment by ghbakhtiari** [comment] 2017-01-04 15:24
any progress?

**Comment by tbsf** [comment] 2017-10-26 18:36
Is it possible to support NestedScrollView on Android to solve this? 

https://developer.android.com/reference/android/support/v4/widget/NestedScrollView.html

**Comment by TheOnlyMatt** [comment] 2017-12-12 14:10
This problem is very awkward ! :s
Did someone find a fix ?

**Comment by maruffci** [comment] 2018-01-13 03:57
In android, ScrollView and Nested ScrollView are different, nativescript implements only ScrollView. This cause the problem.

You can extend scrollview class something like below, then add desired content to it.

```
var scrollView = require('tns-core-modules/ui/scroll-view');

function NestedScroll() {};
NestedScroll.prototype = new scrollView.ScrollView();
NestedScroll.prototype.createNativeView = function(){
    const nativeView = new android.support.v4.widget.NestedScrollView(this._context);
        if (this._androidViewId < 0) {
            this._androidViewId = android.view.View.generateViewId();
        }

        nativeView.setId(this._androidViewId);
    return nativeView;
};
```

Creating Nested Scrollview:
`var nested_scroll = new NestedScroll();`

Adding content to it:
`nested_scroll.content = example_content; //example_content: Any layout or View`

Then add `nested_scroll` to your parent layout.


This is a quick fix.

Have fun...

**Comment by Nevaan** [comment] 2019-12-04 13:28
Hi,

I have a similar problem when using ListView.
Playground here: https://play.nativescript.org/?template=play-ng&id=asaWrV

Swipe event is not fired every time, you have to perfectly, horizontally move your finger. Of course, if you move finger to other element, event which should be considered as element swipe is interpreted as scrolling the listview. 

Are there any chances for workaround or fix of this issue? Unfortunately, I dont have enough native mobile development knowledge to tinker with this by myself and provide fix proposition.

**Comment by NickIliev** [comment] 2019-12-11 13:59
Closing the issue as multiple ScrollView components are not supported scenario in NativeScript.

**Closed by NickIliev** 2019-12-11 13:59 UTC
Labels: bug, os: android

**Comment by juniorschen** [comment] 2020-11-12 12:38
@tsonevn  
2020 do we have any solution?
It still sucks to use swipe inside a scroll :/

**Comment by toverux** [comment] 2021-02-07 23:04
Thanks to @marufi-billah I've been able to use `NestedScrollView` and also use it to implement OnScrollChangeListener, since I had problem with the `scroll` event from ScrollView (there was some strange momentum effect added on the scrollY, it did not always represent the actual value rendered on screen).

Adding my solution here to help people using the right keywords on Google ;)

```ts
import { ScrollView } from '@nativescript/core';
import { layout } from '@nativescript/core/utils';
import NestedScrollView = androidx.core.widget.NestedScrollView;

// noinspection JSUnusedGlobalSymbols
export class IrScrollView extends ScrollView {
    public nativeView!: NestedScrollView;

    private scrollChangeHandler?: NestedScrollView.OnScrollChangeListener;

    public createNativeView(): NestedScrollView {
        return new NestedScrollView(this._context);
    }

    protected attachNative(): void {
        const thisRef = new WeakRef(this);

        this.scrollChangeHandler = new NestedScrollView.OnScrollChangeListener({
            onScrollChange(view, scrollX, scrollY) {
                const owner = thisRef.get();
                if (!owner) return;

                owner.notify({
                    object: owner,
                    eventName: ScrollView.scrollEvent,
                    scrollX: layout.toDeviceIndependentPixels(scrollX),
                    scrollY: layout.toDeviceIndependentPixels(scrollY)
                });
            }
        });

        this.nativeView.setOnScrollChangeListener(this.scrollChangeHandler);
    }

    // noinspection SpellCheckingInspection It's a typo from {N}
    protected dettachNative(): void {
        // @ts-expect-error - {N} definition files aren't null-strict
        this.nativeView.setOnScrollChangeListener(null);
        this.scrollChangeHandler = undefined;
    }
}
```

It would be cool if NativeScript implemented NestedScrollView by default, it seems much better! Android documentation say:

![image](https://user-images.githubusercontent.com/1343250/107162066-05081900-69a1-11eb-9036-ca976aaf90a8.png)

**Comment by farfromrefug** [comment] 2021-02-08 09:06
@toverux  https://github.com/NativeScript/NativeScript/pull/9199
