### ISSUE TITLE
iOS Action Dialog does not show Cancel button

### ISSUE THREAD

**Issue by jubinpolackal** [NativeScript/NativeScript#5894] opened 2018-05-31 13:56 UTC
Hi,
  I created a sample application with a page and a button. On tapping the button, an action dialog is presented. I copy pasted the sample code from the native script tutorial site.
  The issue is that the dialog does not show Cancel button on iOS. But the same works fine on Android and I am able to see the cancel button. Is this a bug or am I doing something wrong?

I tried the code with Angular and Typescript

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.2
- Cross-platform [modules:](url) 4.0.1
- Runtime(s):    "tns-ios": {
      "version": "4.0.1"
    },
    "tns-android": {
      "version": "4.0.1"
    }
- Plugin(s): "dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "nativescript-angular": "~5.3.0",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.5.2",
    "tns-core-modules": "~4.0.0",
    "typescript": "^2.8.4",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.7.0",
    "typescript": "~2.7.2"
  }

### Please tell us how to recreate the issue in as much detail as possible.
Create a new Native script angular project, create new component called main, add a button and on the button action add the below given code.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

 showDialog() {
    console.log('Show Dialog Button Tapped ...');
    dialogs.action({
        message: "Action Title",
        cancelButtonText: "Cancel",
        actions: ["Option1", "Option2", "Option3"]
    }).then(result => {
        console.log("Dialog result: " + result);
        if(result == "Options1"){
            //Do action1
        } else if(result == "Option2"){
            //Do action2
        } else if(result == "Option3"){
            //Do action2
        }
    });
  }
Please find the source code attached here.

[DialogTest.zip](https://github.com/NativeScript/NativeScript/files/2058485/DialogTest.zip)

**Comment by NickIliev** [comment] 2018-05-31 14:28
@jubinpolackal can you share more details regarding the used device/emulator and version of iOS. I've tested with iOS 11.3, and iPhone X simulator and the cancel button is appearing as expected on my side.

![screen shot 2018-05-31 at 5 26 58 pm](https://user-images.githubusercontent.com/18008302/40788072-d9dde9e0-64f7-11e8-9f2a-2e3f81861702.png)

**Comment by jubinpolackal** [comment] 2018-05-31 14:40
@NickIliev Thank you for the response.
The simulator used is iPad Pro(9.7 inch) and iOS version is 11.3.
I am still not getting the clear button. Any help would be much appreciated.
Thank You.

**Comment by jubinpolackal** [comment] 2018-05-31 14:44
@NickIliev I am getting cancel button on iPhone simulator, but not on iPad. I noticed it just now.

**Comment by NickIliev** [comment] 2018-06-01 07:00
@jubinpolackal thanks for the update - I can confirm that indeed there seems to be an issue with the action dialog on iPad.

**Comment by jubinpolackal** [comment] 2018-06-01 13:48
I think it is the intended iPad behaviour. The alert is internally using UIActionSheet. If that is the case, cancel button should not be present on iPad, user must tap anywhere outside to dismiss it. But it would be present on iPhone. I hope it is not a bug after all.

**Comment by manoldonev** [comment] 2018-06-07 14:19
@jubinpolackal on further investigation it seems your observation is correct and this is not a bug after all but the behavior by design for UIActionSheet rendered on iPad: "because taps outside the popover dismiss the action sheet without selecting an item, this results in a default way to cancel the sheet. Including a cancel button would therefore only cause confusion".

Closing this issue.

**Closed by manoldonev** 2018-06-07 14:19 UTC
Labels: backlog, bug, os: ios, severity: high
