### ISSUE TITLE
Frame crashes on app restore occasionally 

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#715] opened 2015-09-11 09:37 UTC
If I leave my app open, then come back to it later it crashes with this?? 

https://goo.gl/photos/Z8pJyrY8w8nNM9Uf6

... It's always done this

**Comment by Kamilius** [comment] 2015-09-12 09:17
I have exactly the same issue on Android. 
- App is running
- I'm pressing "home" button to suspend it
- Opening Chrome and navigating to any page
- Opening app manager
- Choosing running NS application
- Getting error screen with a stack trace:
![quickmemo _2015-09-12-11-00-12](https://cloud.githubusercontent.com/assets/3115794/9830866/5fb858b0-593f-11e5-86ee-6e9b419af9fa.png)

Sadly I don't know how to copy a full stack trace in this situation.
@sitefinitysteve gave only screenshot of first lines of a stacktrace.

Funny thing, that it is hard to reproduce if you simply suspending app, without running different ones. For example, If I'm locking/unlocking phone or simply navigating it, mostly - everything's great. But when it comes to launching different apps - it crashes with error above.

Any clues on how to copy a full stack trace?

I'm using nativescript-cli on Ubuntu 14.04 with real device.

**Comment by sitefinitysteve** [comment] 2015-09-14 17:21
I am unable to replicate via those steps 100% of the time, however I did try to get a full stack trace by using the app analytics module of the telerik platform...app crashed twice on a demo, nothing logged.

application.on(application.uncaughtErrorEvent, function (args) {
    var exception;
     
    if (args.android)
        exception = args.android;
    else if (args.ios)
        exception = args.ios;
  
    monitor.trackException(exception, "Uncaught exception");
});

**Comment by x4080** [comment] 2015-09-30 11:58
I think I have a way to relocate ,in the developers option , set background process limit to 2 or 1, open ns app , go to another app or two then go to the ns app. If the ns app is restarted it will crash as the above picture ( using real device here )

**Comment by Kamilius** [comment] 2015-10-01 07:48
@x4080  :+1: awesome. It really was crashing upon app restart. Didn't knew that on android dev options is such option, like limiting processes.

And that actually works 100% of time

**Comment by Kamilius** [comment] 2015-10-01 07:51
Also, I think that this situation should've been able to be handled by at least - "lowMemory" or "uncaughtError" application events, but it's not.

**Comment by x4080** [comment] 2015-10-01 12:19
Glad it can help a bit..the Google search and stackoverflow talked about manifest app name setting but i still cannot resolve it. Maybe other people csn help

**Comment by AntonioCuevaUrraco** [comment] 2015-10-09 05:53
+1 I would love to figure out a way to solve this issue as it is happening quite often.

**Comment by x4080** [comment] 2015-10-09 06:38
I think it needs high priority also

**Comment by blagoev** [comment] 2015-10-09 07:13
raised the priority. We will investigate this further as part of 1.5 work.

**Comment by x4080** [comment] 2015-10-09 21:55
Thanks man

**Comment by x4080** [comment] 2015-10-11 08:07
I think the problem is in frame.android.ts (PageFragmentBody), android complains about the constructor is not public and have no empty constructor, I tried to change the constructor without parameters and calling new PageFragmentBody with :
    
        var newFragment = new PageFragmentBody();
        newFragment.frame = this;
        newFragment.entry = backstackEntry;

(the constructor) :

    class PageFragmentBody extends android.app.Fragment {
    public frame: Frame;
    public entry: definition.BackstackEntry;

    public  constructor() {
        super();
        return global.__native(this);
    }

It still the same result, maybe because class generated is not public ? How can we make inherited class in nativescript public ?

**Comment by hamorphis** [comment] 2015-10-21 09:24
Starting work on it...

**Comment by hamorphis** [comment] 2015-10-21 14:22
I managed to reproduce it. Go to the App Manager (the thing that has the RAM tab), go to "RAM" and hit the "Clear Memory" button to run the Low Memory Killer (LMK). Then go back to the app. I changed the code so that the PageFragmentBody now has a default empty constructor and is created via a static method called **newInstance** (as described [here](https://github.com/codepath/android_guides/wiki/Creating-and-Using-Fragments)), but the Android runtime still can't find the default constructor of PageFragmentBody and crashes with the same exception. [Here](https://github.com/NativeScript/NativeScript/blob/fragment-ctor/ui/frame/frame.android.ts) is the new source code. Maybe the Android runtime guys will be able to help here.

**Comment by hamorphis** [comment] 2015-10-22 10:55
Just pasting the Java code that leads to this exception. Fragment.java:
```Java
    public static Fragment instantiate(Context context, String fname, @Nullable Bundle args) {
        try {
            Class<?> clazz = sClassMap.get(fname);
            if (clazz == null) {
                // Class not found in the cache, see if it's real, and try to add it
                clazz = context.getClassLoader().loadClass(fname);
                if (!Fragment.class.isAssignableFrom(clazz)) {
                    throw new InstantiationException("Trying to instantiate a class " + fname
                            + " that is not a Fragment", new ClassCastException());
                }
                sClassMap.put(fname, clazz);
            }
            Fragment f = (Fragment)clazz.newInstance();
            if (args != null) {
                args.setClassLoader(f.getClass().getClassLoader());
                f.mArguments = args;
            }
            return f;
        } catch (ClassNotFoundException e) {
            throw new InstantiationException("Unable to instantiate fragment " + fname
                    + ": make sure class name exists, is public, and has an"
                    + " empty constructor that is public", e);
        } catch (java.lang.InstantiationException e) {
            throw new InstantiationException("Unable to instantiate fragment " + fname
                    + ": make sure class name exists, is public, and has an"
                    + " empty constructor that is public", e);
        } catch (IllegalAccessException e) {
            throw new InstantiationException("Unable to instantiate fragment " + fname
                    + ": make sure class name exists, is public, and has an"
                    + " empty constructor that is public", e);
        }
    }
```

**Comment by blagoev** [comment] 2015-10-22 15:46
Ok managed to reproduce this. Will be back with more info what is the issue.

**Comment by lscown** [comment] 2015-11-05 21:20
Any update on this?

**Comment by hshristov** [comment] 2015-11-06 07:57
Hi guys,

We have fixed this issue and it will be included in 1.6 release.

**Comment by x4080** [comment] 2015-11-06 10:57
Thumbs up..1.5 already finished?

**Comment by sitefinitysteve** [comment] 2015-11-06 15:48
@hshristov Yeah is this a typo?  Did you mean 1.5?  I see the version has been incrimented to 1.5, but this is a pretty critical bug to push back to December or later.

**Comment by hshristov** [comment] 2015-11-09 11:36
@sitefinitysteve Yeah typo on my side. Sorry. I meant 1.5

**Closed** 2015-11-13 13:21 UTC
Labels: 5 - Done, S:High, T:Bug
